/*
 * New file for SGE — no LibGDX equivalent (replaces GWT's Preloader concept).
 * Licensed under the Apache License, Version 2.0
 *
 * Migration notes:
 *   Renames: GWT Preloader -> BrowserAssetLoader
 *   Convention: Scala.js only; backed by multiarch.resources.PlatformResources
 *     (build-time-embedded resource map generated by MultiArchResourcesPlugin,
 *     with a Node fs fallback for in-repo dev/test). No fetch/manifest/preload:
 *     assets are embedded at compile time and served synchronously.
 *   Convention: directory listing derived from the embedded resource key set.
 *   Audited: 2026-03-08
 *
 * Scala port copyright 2025-2026 Mateusz Kubuszok
 */
package sge
package files

import multiarch.resources.{ EmbeddedResources, PlatformResources }

/** Browser asset loader backed by [[multiarch.resources.PlatformResources]].
  *
  * Assets are embedded into the JS bundle at build time (base64) by `MultiArchResourcesPlugin.embeddedResourcesSettings` and served synchronously — there is no HTTP fetch, manifest, or async preload
  * phase. A Node `fs` fallback (provided by `PlatformResources` itself) keeps in-repo development and test resources working from the repository tree.
  *
  * Paths are forward-slash separated and resolved as classpath-absolute (a leading `/` is added when absent) before being handed to `PlatformResources`.
  */
class BrowserAssetLoader {

  import BrowserAssetLoader.*

  /** Synchronously check if an asset exists. */
  def contains(path: String): Boolean = {
    val p = fixSlashes(path)
    PlatformResources.resourceExists(classOf[BrowserAssetLoader], absolute(p)) || isDirectory(p)
  }

  /** Check if the path denotes a directory (i.e. a non-empty prefix of some embedded key, but not itself an embedded resource). */
  def isDirectory(path: String): Boolean = {
    val p = fixSlashes(path)
    if (PlatformResources.resourceExists(classOf[BrowserAssetLoader], absolute(p))) false
    else {
      val prefix = if (p.isEmpty) "" else if (p.endsWith("/")) p else p + "/"
      relativeKeys.exists(_.startsWith(prefix)) && (p.isEmpty || prefix.length > 1)
    }
  }

  /** Read an asset as text (UTF-8), or `None` if it cannot be found. */
  def readText(path: String): Option[String] =
    PlatformResources.getResourceAsString(classOf[BrowserAssetLoader], absolute(fixSlashes(path)))

  /** Read an asset as raw bytes, or `None` if it cannot be found. */
  def readBytes(path: String): Option[Array[Byte]] =
    PlatformResources.getResourceBytes(classOf[BrowserAssetLoader], absolute(fixSlashes(path)))

  /** Get the size of an asset in bytes, or 0 if it cannot be read. */
  def length(path: String): Long =
    PlatformResources.getResourceBytes(classOf[BrowserAssetLoader], absolute(fixSlashes(path))).fold(0L)(_.length.toLong)

  /** List direct children of a directory, derived from the embedded resource key set. */
  def list(directory: String): Array[String] = {
    val dir    = fixSlashes(directory)
    val prefix = if (dir.isEmpty) "" else if (dir.endsWith("/")) dir else dir + "/"
    val result = scala.collection.mutable.LinkedHashSet[String]()

    relativeKeys.foreach { key =>
      if (key.startsWith(prefix)) {
        val rest = key.substring(prefix.length)
        if (rest.nonEmpty) {
          val slash = rest.indexOf('/')
          if (slash < 0) result += key // direct file child
          else result += prefix + rest.substring(0, slash) // direct sub-directory
        }
      }
    }
    result.toArray
  }
}

object BrowserAssetLoader {

  /** Embedded keys are stored classpath-absolute (leading `/`); expose them relative for SGE's forward-slash path model. */
  private def relativeKeys: Iterable[String] =
    EmbeddedResources.keys.map(k => if (k.startsWith("/")) k.substring(1) else k)

  /** Resolve a forward-slash SGE path to a classpath-absolute resource path. */
  private def absolute(path: String): String =
    if (path.startsWith("/")) path else "/" + path

  private def fixSlashes(path: String): String =
    path.replace('\\', '/')
}
