/*
 * Ported from colorful-gdx - https://github.com/tommyettinger/colorful-gdx
 * Original authors: Tommy Ettinger
 * Licensed under the Apache License, Version 2.0
 *
 * Scala port copyright 2025-2026 Mateusz Kubuszok
 *
 * Covenant: full-port
 * Covenant-baseline-spec-pass: 0
 * Covenant-baseline-loc: 811
 * Covenant-baseline-methods: ABSINTHE,AIR_FORCE_BLUE,AMAZONITE,ANGEL_WING,APPLE_GREEN,APRICOT,AQUAMARINE,ARMY_GREEN,ARTICHOKE,ASPARAGUS,AVOCADO,BANANA_PUDDING,BEIGE,BLACK,BLACKLIGHT_GLOW,BLUE,BLUEBERRY,BLUE_EYE,BLUE_SMOKE,BLUE_STEEL,BOLOGNA,BOYSENBERRY,BRICK,BRIGHT_RED,BRONZE_SKIN_1,BRONZE_SKIN_2,BRONZE_SKIN_3,BRONZE_SKIN_4,BROWN_VELVET,BUBBLE,BUBBLEGUM_PINK,BUBBLE_GUM,BURNT_YELLOW,CALM_SKY,CARMINE,CEDAR_WOOD,CELADON,CELERY,CHARTREUSE,CHERRY_SYRUP,CHINCHILLA,CHIPPED_GRANITE,CLOUD,COAL_BLACK,COLD_IRON,CORNFLOWER_BLUE,CORN_SILK,COTTON_CANDY,CREAM,CRICKET,CYAN,DARK_GRAY,DARK_PINE,DARK_SKIN_1,DARK_SKIN_2,DARK_SKIN_3,DARK_TEAL,DEEP_JUNGLE,DEEP_PURPLE,DEEP_TEAL,DENIM_BLUE,DESERT_RAIN,DRAB_GREEN,DREARY_BLUE,DRIED_SAGE,DRIFTWOOD,DRY_BRUSH,DRY_PEPPER,DULL_AZURE,DULL_GREEN,DULL_VIOLET,DUN,DUSTY_GRAPE,DUSTY_GREEN,DUSTY_PINK,DUST_BUNNY,EARWAX,EGGPLANT,ELECTRIC_BLUE,EMBERS,EMERALD,EMINENCE,EUCALYPTUS,FADED_BLUE,FAWN,FEATHER_DOWN,FERN_GREEN,FLAMINGO,FLORAL_FOAM,FOREST_GLEN,FROG_GREEN,FRUIT_PUNCH,GARTER_SNAKE,GRAPE_LOLLIPOP,GRAPE_SODA,GRAPHITE,GRAY,GRAY_GREEN,GREEN,GREYHOUND,HAM,HELIOTROPE,HIDDEN_BLUE,HONEYDEW,HOSPITAL_GREEN,HOT_SAUCE,HUNTER_GREEN,INDIGO,INFECTION,IOLITE,IRIS,IRON,IVY_GREEN,JADE,JUICY_GRAPE,KELLY_GREEN,KOA,KYANITE,LAVENDER,LEAD,LIGHT_GRAY,LIGHT_SKIN_1,LIGHT_SKIN_2,LIGHT_SKIN_3,LIGHT_SKIN_4,LIGHT_SKIN_5,LIGHT_SKIN_6,LIGHT_SKIN_7,LIGHT_SKIN_8,LIGHT_SKIN_9,LILAC,LIST,LIZARD_SCALES,LURID_RED,MAGENTA,MAIDENHAIR_FERN,MALACHITE,MARSH,MAUVE,MEDIUM_PLUM,MEDIUM_TEAL,MILD_VIOLET,MINT_GREEN,MOSS_GREEN,MULBERRY,MUMMY_BROWN,MURK,MUSH,NAMED,NAVY_BLUE,NIGHTSHADE,NINJA,OCEAN_BLUE,OCHRE,OLD_ROSE,OLIVE_GREEN,OLIVE_OIL,ORANGE,ORCHID,PASTEL_SKY,PATINA,PEACH,PEAT_BOG,PEA_SOUP,PENCIL_YELLOW,PERIWINKLE,PINE_GREEN,PINK_LEMONADE,PINK_SKIN_1,PINK_SKIN_2,PINK_SKIN_3,PINK_SKIN_4,PINK_TUTU,PINK_VIOLET,PISTACHIO,PLATINUM,PLUM_JUICE,POLISHED_SAPPHIRE,PORK_CHOP,POWDER_BLUE,PRASE,PRUNE,PRUSSIAN_BLUE,PUCE,PURPLE,PURPLE_FREESIA,PUTTY,Palette,RASPBERRY,RAW_MEAT,RED,REDWOOD,REFRESHING_MIST,RIPE_PLUM,RIPPED_DENIM,ROBIN_EGG_BLUE,ROSE,ROSEATE_SPOONBILL,ROUGH_SAPPHIRE,ROYAL_BLUE,ROYAL_VIOLET,SAFFRON,SAGE_GREEN,SALMON,SCRIBE_INK,SEAFOAM,SEAL_BROWN,SEAWATER,SHADOW,SHARP_AZURE,SHINING_SKY,SHRIMP,SIENNA,SILVER,SILVER_GREEN,SILVER_PINK,SLATE_GRAY,SLOW_CREEK,SMOG,SOAP,SOFT_TEAL,SPACE_BLUE,SPEARMINT,SPRING_GREEN,STEAM,STRAW,STRONG_CYAN,STYGIAN_BLUE,SUBTLETY,SUDS,TAN,TARNISH,TAUPE,TAXICAB_YELLOW,TEA_ROSE,THICK_AMETHYST,THIN_AMETHYST,THISTLE,THULIAN_PINK,TRANSPARENT,TROPIC_MIST,TURQUOISE,TWILIGHT_CLOUD,TYRIAN_PURPLE,UMBER,VAPOR,VARISCITE,VARNISH,VIOLET,VIOLET_CUSHIONS,VIRIDIAN,WATERCOLOR_BLACK,WATERCOLOR_GRAY,WET_STONE,WHITE,WISTERIA,WOODLANDS,YELLOW,ZUCCHINI,appendToKnownColors,editKnownColors
 * Covenant-source-reference: com/github/tommyettinger/colorful/cielab/Palette.java
 * Covenant-verified: 2026-04-19
 *
 * upstream-commit: e4a5fd960eef746ca5aa826063432fb79666d74f
 */
package sge
package colorful
package cielab

import scala.collection.mutable

/** A palette of predefined colors as packed CIELAB floats, the kind [[ColorTools]] works with. You can access colors by their constant name, such as `OCEAN_BLUE`, by the [[NAMED]] map using
  * `NAMED.getOrElse("Ocean Blue", 0f)`, or by index in the list called [[LIST]].
  */
object Palette {

  /** Maps color names to packed float colors. */
  val NAMED: mutable.HashMap[String, Float] = mutable.HashMap.empty[String, Float]

  /** Lists packed float color values, in declaration order. */
  val LIST: mutable.ArrayBuffer[Float] = mutable.ArrayBuffer.empty[Float]

  val TRANSPARENT:       Float = java.lang.Float.intBitsToFloat(0x7f7f00)
  val BLACK:             Float = java.lang.Float.intBitsToFloat(0xfe7f7f00)
  val COAL_BLACK:        Float = java.lang.Float.intBitsToFloat(0xfe7e7d0f)
  val SHADOW:            Float = java.lang.Float.intBitsToFloat(0xfe7d7c25)
  val GRAPHITE:          Float = java.lang.Float.intBitsToFloat(0xfe7d7b3b)
  val DARK_GRAY:         Float = java.lang.Float.intBitsToFloat(0xfe7c7b4f)
  val LEAD:              Float = java.lang.Float.intBitsToFloat(0xfe7c7a62)
  val IRON:              Float = java.lang.Float.intBitsToFloat(0xfe7b7976)
  val GRAY:              Float = java.lang.Float.intBitsToFloat(0xfe7b7989)
  val CHINCHILLA:        Float = java.lang.Float.intBitsToFloat(0xfe7a789b)
  val GREYHOUND:         Float = java.lang.Float.intBitsToFloat(0xfe7a77ac)
  val SILVER:            Float = java.lang.Float.intBitsToFloat(0xfe7977bd)
  val LIGHT_GRAY:        Float = java.lang.Float.intBitsToFloat(0xfe7976cf)
  val PLATINUM:          Float = java.lang.Float.intBitsToFloat(0xfe7875df)
  val CLOUD:             Float = java.lang.Float.intBitsToFloat(0xfe7875ef)
  val WHITE:             Float = java.lang.Float.intBitsToFloat(0xfe7874ff)
  val SEAWATER:          Float = java.lang.Float.intBitsToFloat(0xfe70557a)
  val HOSPITAL_GREEN:    Float = java.lang.Float.intBitsToFloat(0xfe6c4cb5)
  val CYAN:              Float = java.lang.Float.intBitsToFloat(0xfe6639e9)
  val BUBBLE:            Float = java.lang.Float.intBitsToFloat(0xfe6f5cf5)
  val PERIWINKLE:        Float = java.lang.Float.intBitsToFloat(0xfe27a198)
  val BLUE:              Float = java.lang.Float.intBitsToFloat(0xfe00de52)
  val FADED_BLUE:        Float = java.lang.Float.intBitsToFloat(0xfe24ad58)
  val OCEAN_BLUE:        Float = java.lang.Float.intBitsToFloat(0xfe28b820)
  val STYGIAN_BLUE:      Float = java.lang.Float.intBitsToFloat(0xfe4a9c17)
  val DEEP_PURPLE:       Float = java.lang.Float.intBitsToFloat(0xfe4cc54b)
  val TYRIAN_PURPLE:     Float = java.lang.Float.intBitsToFloat(0xfe44cc7f)
  val MAGENTA:           Float = java.lang.Float.intBitsToFloat(0xfe2df094)
  val BUBBLEGUM_PINK:    Float = java.lang.Float.intBitsToFloat(0xfe42c7b8)
  val PORK_CHOP:         Float = java.lang.Float.intBitsToFloat(0xfe7d94d5)
  val RAW_MEAT:          Float = java.lang.Float.intBitsToFloat(0xfe97b3af)
  val RED:               Float = java.lang.Float.intBitsToFloat(0xfed3dd88)
  val PUTTY:             Float = java.lang.Float.intBitsToFloat(0xfea1ba74)
  val SIENNA:            Float = java.lang.Float.intBitsToFloat(0xfeaeb740)
  val SEAL_BROWN:        Float = java.lang.Float.intBitsToFloat(0xfe94a12d)
  val MUMMY_BROWN:       Float = java.lang.Float.intBitsToFloat(0xfeb69957)
  val FAWN:              Float = java.lang.Float.intBitsToFloat(0xfeb49096)
  val ORANGE:            Float = java.lang.Float.intBitsToFloat(0xfedbaeab)
  val PEACH:             Float = java.lang.Float.intBitsToFloat(0xfeae8ad1)
  val CREAM:             Float = java.lang.Float.intBitsToFloat(0xfea068fc)
  val YELLOW:            Float = java.lang.Float.intBitsToFloat(0xfef459f8)
  val EARWAX:            Float = java.lang.Float.intBitsToFloat(0xfeca63c0)
  val UMBER:             Float = java.lang.Float.intBitsToFloat(0xfec56983)
  val IVY_GREEN:         Float = java.lang.Float.intBitsToFloat(0xfebc3975)
  val JADE:              Float = java.lang.Float.intBitsToFloat(0xfebf2daf)
  val GREEN:             Float = java.lang.Float.intBitsToFloat(0xfee609e0)
  val CELADON:           Float = java.lang.Float.intBitsToFloat(0xfea043ee)
  val PUCE:              Float = java.lang.Float.intBitsToFloat(0xfe7081ba)
  val BEIGE:             Float = java.lang.Float.intBitsToFloat(0xfe9680b7)
  val WET_STONE:         Float = java.lang.Float.intBitsToFloat(0xfe8677a8)
  val SLOW_CREEK:        Float = java.lang.Float.intBitsToFloat(0xfe776e98)
  val SLATE_GRAY:        Float = java.lang.Float.intBitsToFloat(0xfe747187)
  val LIGHT_SKIN_1:      Float = java.lang.Float.intBitsToFloat(0xfe887e79)
  val LIGHT_SKIN_2:      Float = java.lang.Float.intBitsToFloat(0xfe8e937f)
  val LIGHT_SKIN_3:      Float = java.lang.Float.intBitsToFloat(0xfe8e9b94)
  val LIGHT_SKIN_4:      Float = java.lang.Float.intBitsToFloat(0xfe9896a3)
  val LIGHT_SKIN_5:      Float = java.lang.Float.intBitsToFloat(0xfe9c94b3)
  val LIGHT_SKIN_6:      Float = java.lang.Float.intBitsToFloat(0xfe9a90c0)
  val LIGHT_SKIN_7:      Float = java.lang.Float.intBitsToFloat(0xfe988dcc)
  val LIGHT_SKIN_8:      Float = java.lang.Float.intBitsToFloat(0xfe9186d6)
  val LIGHT_SKIN_9:      Float = java.lang.Float.intBitsToFloat(0xfe857be8)
  val DARK_SKIN_1:       Float = java.lang.Float.intBitsToFloat(0xfe838a47)
  val DARK_SKIN_2:       Float = java.lang.Float.intBitsToFloat(0xfe8c9555)
  val DARK_SKIN_3:       Float = java.lang.Float.intBitsToFloat(0xfe89976d)
  val PINK_SKIN_1:       Float = java.lang.Float.intBitsToFloat(0xfe86948a)
  val PINK_SKIN_2:       Float = java.lang.Float.intBitsToFloat(0xfe8592a5)
  val PINK_SKIN_3:       Float = java.lang.Float.intBitsToFloat(0xfe8490c0)
  val PINK_SKIN_4:       Float = java.lang.Float.intBitsToFloat(0xfe7a88e0)
  val BRONZE_SKIN_4:     Float = java.lang.Float.intBitsToFloat(0xfe907dd1)
  val BRONZE_SKIN_3:     Float = java.lang.Float.intBitsToFloat(0xfe9e82ad)
  val BRONZE_SKIN_2:     Float = java.lang.Float.intBitsToFloat(0xfe958281)
  val BRONZE_SKIN_1:     Float = java.lang.Float.intBitsToFloat(0xfe978464)
  val TAUPE:             Float = java.lang.Float.intBitsToFloat(0xfe8c8132)
  val DRAB_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe947444)
  val LIZARD_SCALES:     Float = java.lang.Float.intBitsToFloat(0xfea46e78)
  val CRICKET:           Float = java.lang.Float.intBitsToFloat(0xfea26d94)
  val OLIVE_OIL:         Float = java.lang.Float.intBitsToFloat(0xfeae69a6)
  val DUN:               Float = java.lang.Float.intBitsToFloat(0xfea66ab9)
  val CORN_SILK:         Float = java.lang.Float.intBitsToFloat(0xfe9e6bca)
  val TAN:               Float = java.lang.Float.intBitsToFloat(0xfe976cdc)
  val STRAW:             Float = java.lang.Float.intBitsToFloat(0xfe906ded)
  val HONEYDEW:          Float = java.lang.Float.intBitsToFloat(0xfe995ede)
  val TARNISH:           Float = java.lang.Float.intBitsToFloat(0xfe9a5ec5)
  val PEA_SOUP:          Float = java.lang.Float.intBitsToFloat(0xfeb84db7)
  val MARSH:             Float = java.lang.Float.intBitsToFloat(0xfe9d5f8f)
  val ASPARAGUS:         Float = java.lang.Float.intBitsToFloat(0xfea3597b)
  val PEAT_BOG:          Float = java.lang.Float.intBitsToFloat(0xfe926e52)
  val DEEP_JUNGLE:       Float = java.lang.Float.intBitsToFloat(0xfe89751a)
  val PINE_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe895f4d)
  val OLIVE_GREEN:       Float = java.lang.Float.intBitsToFloat(0xfe8d6557)
  val GRAY_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe876b67)
  val MAIDENHAIR_FERN:   Float = java.lang.Float.intBitsToFloat(0xfe935670)
  val KELLY_GREEN:       Float = java.lang.Float.intBitsToFloat(0xfe9a528b)
  val DUSTY_GREEN:       Float = java.lang.Float.intBitsToFloat(0xfe9852a6)
  val GARTER_SNAKE:      Float = java.lang.Float.intBitsToFloat(0xfe9843b5)
  val SILVER_GREEN:      Float = java.lang.Float.intBitsToFloat(0xfe9752c0)
  val PISTACHIO:         Float = java.lang.Float.intBitsToFloat(0xfe9553d0)
  val ANGEL_WING:        Float = java.lang.Float.intBitsToFloat(0xfe736cf5)
  val SAGE_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe8755e4)
  val DRIED_SAGE:        Float = java.lang.Float.intBitsToFloat(0xfe8457db)
  val ARTICHOKE:         Float = java.lang.Float.intBitsToFloat(0xfe8d5ab1)
  val VIRIDIAN:          Float = java.lang.Float.intBitsToFloat(0xfe8a5d7c)
  val FLORAL_FOAM:       Float = java.lang.Float.intBitsToFloat(0xfe8c4f63)
  val HUNTER_GREEN:      Float = java.lang.Float.intBitsToFloat(0xfe83712b)
  val DARK_TEAL:         Float = java.lang.Float.intBitsToFloat(0xfe746f41)
  val KYANITE:           Float = java.lang.Float.intBitsToFloat(0xfe746272)
  val SPEARMINT:         Float = java.lang.Float.intBitsToFloat(0xfe715ba7)
  val AMAZONITE:         Float = java.lang.Float.intBitsToFloat(0xfe7160c3)
  val PASTEL_SKY:        Float = java.lang.Float.intBitsToFloat(0xfe715fdd)
  val AQUAMARINE:        Float = java.lang.Float.intBitsToFloat(0xfe7264ec)
  val DUST_BUNNY:        Float = java.lang.Float.intBitsToFloat(0xfe6275d6)
  val PATINA:            Float = java.lang.Float.intBitsToFloat(0xfe6372ca)
  val CHIPPED_GRANITE:   Float = java.lang.Float.intBitsToFloat(0xfe6079bf)
  val BLUE_SMOKE:        Float = java.lang.Float.intBitsToFloat(0xfe6373b0)
  val AIR_FORCE_BLUE:    Float = java.lang.Float.intBitsToFloat(0xfe4d7694)
  val COLD_IRON:         Float = java.lang.Float.intBitsToFloat(0xfe637679)
  val DREARY_BLUE:       Float = java.lang.Float.intBitsToFloat(0xfe62785c)
  val MURK:              Float = java.lang.Float.intBitsToFloat(0xfe6a8016)
  val NINJA:             Float = java.lang.Float.intBitsToFloat(0xfe658721)
  val WATERCOLOR_BLACK:  Float = java.lang.Float.intBitsToFloat(0xfe668442)
  val IOLITE:            Float = java.lang.Float.intBitsToFloat(0xfe5c8853)
  val BOYSENBERRY:       Float = java.lang.Float.intBitsToFloat(0xfe538c64)
  val WATERCOLOR_GRAY:   Float = java.lang.Float.intBitsToFloat(0xfe518d7d)
  val BLUE_STEEL:        Float = java.lang.Float.intBitsToFloat(0xfe419387)
  val TWILIGHT_CLOUD:    Float = java.lang.Float.intBitsToFloat(0xfe54889c)
  val SMOG:              Float = java.lang.Float.intBitsToFloat(0xfe5486b7)
  val TROPIC_MIST:       Float = java.lang.Float.intBitsToFloat(0xfe6479df)
  val FEATHER_DOWN:      Float = java.lang.Float.intBitsToFloat(0xfe667ce8)
  val MILD_VIOLET:       Float = java.lang.Float.intBitsToFloat(0xfe5992a3)
  val VIOLET_CUSHIONS:   Float = java.lang.Float.intBitsToFloat(0xfe39b17a)
  val DULL_VIOLET:       Float = java.lang.Float.intBitsToFloat(0xfe58976b)
  val ROYAL_VIOLET:      Float = java.lang.Float.intBitsToFloat(0xfe58994d)
  val EMINENCE:          Float = java.lang.Float.intBitsToFloat(0xfe6e912d)
  val PRUNE:             Float = java.lang.Float.intBitsToFloat(0xfe718c3c)
  val DUSTY_GRAPE:       Float = java.lang.Float.intBitsToFloat(0xfe62a059)
  val PINK_VIOLET:       Float = java.lang.Float.intBitsToFloat(0xfe5fa273)
  val RIPE_PLUM:         Float = java.lang.Float.intBitsToFloat(0xfe53b37f)
  val MAUVE:             Float = java.lang.Float.intBitsToFloat(0xfe5fa08f)
  val HAM:               Float = java.lang.Float.intBitsToFloat(0xfe629ec6)
  val COTTON_CANDY:      Float = java.lang.Float.intBitsToFloat(0xfe6e89e9)
  val SILVER_PINK:       Float = java.lang.Float.intBitsToFloat(0xfe6b88d5)
  val TEA_ROSE:          Float = java.lang.Float.intBitsToFloat(0xfe708dca)
  val OLD_ROSE:          Float = java.lang.Float.intBitsToFloat(0xfe7096b7)
  val DUSTY_PINK:        Float = java.lang.Float.intBitsToFloat(0xfe689ba8)
  val ROSEATE_SPOONBILL: Float = java.lang.Float.intBitsToFloat(0xfe72a39c)
  val THULIAN_PINK:      Float = java.lang.Float.intBitsToFloat(0xfe6db587)
  val BROWN_VELVET:      Float = java.lang.Float.intBitsToFloat(0xfe799336)
  val NIGHTSHADE:        Float = java.lang.Float.intBitsToFloat(0xfe7a911e)
  val SCRIBE_INK:        Float = java.lang.Float.intBitsToFloat(0xfe769312)
  val VARNISH:           Float = java.lang.Float.intBitsToFloat(0xfe8f9424)
  val CEDAR_WOOD:        Float = java.lang.Float.intBitsToFloat(0xfea6a435)
  val HOT_SAUCE:         Float = java.lang.Float.intBitsToFloat(0xfeb7c059)
  val LURID_RED:         Float = java.lang.Float.intBitsToFloat(0xfec4ce78)
  val BRICK:             Float = java.lang.Float.intBitsToFloat(0xfea5b986)
  val BRIGHT_RED:        Float = java.lang.Float.intBitsToFloat(0xfed2d190)
  val EMBERS:            Float = java.lang.Float.intBitsToFloat(0xfec0c096)
  val SALMON:            Float = java.lang.Float.intBitsToFloat(0xfea4c39f)
  val TAXICAB_YELLOW:    Float = java.lang.Float.intBitsToFloat(0xfed881cc)
  val APRICOT:           Float = java.lang.Float.intBitsToFloat(0xfecf96c0)
  val BURNT_YELLOW:      Float = java.lang.Float.intBitsToFloat(0xfed687ad)
  val DRY_PEPPER:        Float = java.lang.Float.intBitsToFloat(0xfecfa794)
  val REDWOOD:           Float = java.lang.Float.intBitsToFloat(0xfec6a17b)
  val KOA:               Float = java.lang.Float.intBitsToFloat(0xfebea26b)
  val OCHRE:             Float = java.lang.Float.intBitsToFloat(0xfea09142)
  val DULL_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfeae7154)
  val ARMY_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfeb96c66)
  val DRIFTWOOD:         Float = java.lang.Float.intBitsToFloat(0xfe987789)
  val DRY_BRUSH:         Float = java.lang.Float.intBitsToFloat(0xfed0749d)
  val MUSH:              Float = java.lang.Float.intBitsToFloat(0xfed763b3)
  val BANANA_PUDDING:    Float = java.lang.Float.intBitsToFloat(0xfec96bd8)
  val SAFFRON:           Float = java.lang.Float.intBitsToFloat(0xfee975dd)
  val PENCIL_YELLOW:     Float = java.lang.Float.intBitsToFloat(0xfedc69eb)
  val CHARTREUSE:        Float = java.lang.Float.intBitsToFloat(0xfee040ef)
  val ABSINTHE:          Float = java.lang.Float.intBitsToFloat(0xfed535de)
  val INFECTION:         Float = java.lang.Float.intBitsToFloat(0xfedd3bce)
  val FROG_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfed836ba)
  val AVOCADO:           Float = java.lang.Float.intBitsToFloat(0xfece44a0)
  val WOODLANDS:         Float = java.lang.Float.intBitsToFloat(0xfeb2516a)
  val DARK_PINE:         Float = java.lang.Float.intBitsToFloat(0xfe9e6b32)
  val MOSS_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfea45b42)
  val FERN_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfeab4a55)
  val FOREST_GLEN:       Float = java.lang.Float.intBitsToFloat(0xfec3328a)
  val MALACHITE:         Float = java.lang.Float.intBitsToFloat(0xfed818c0)
  val APPLE_GREEN:       Float = java.lang.Float.intBitsToFloat(0xfedd13cc)
  val CELERY:            Float = java.lang.Float.intBitsToFloat(0xfec127e7)
  val MINT_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfec61dd7)
  val EMERALD:           Float = java.lang.Float.intBitsToFloat(0xfed11eb1)
  val PRASE:             Float = java.lang.Float.intBitsToFloat(0xfeae2ca4)
  val EUCALYPTUS:        Float = java.lang.Float.intBitsToFloat(0xfe9b4083)
  val ZUCCHINI:          Float = java.lang.Float.intBitsToFloat(0xfe7c6835)
  val SOFT_TEAL:         Float = java.lang.Float.intBitsToFloat(0xfe7f478f)
  val MEDIUM_TEAL:       Float = java.lang.Float.intBitsToFloat(0xfe8c34b4)
  val SPRING_GREEN:      Float = java.lang.Float.intBitsToFloat(0xfeb31ec7)
  val TURQUOISE:         Float = java.lang.Float.intBitsToFloat(0xfe932ad5)
  val SEAFOAM:           Float = java.lang.Float.intBitsToFloat(0xfe9f22e4)
  val VARISCITE:         Float = java.lang.Float.intBitsToFloat(0xfe8834e9)
  val REFRESHING_MIST:   Float = java.lang.Float.intBitsToFloat(0xfe615ae1)
  val SHINING_SKY:       Float = java.lang.Float.intBitsToFloat(0xfe5a4fd9)
  val STEAM:             Float = java.lang.Float.intBitsToFloat(0xfe5e5cd0)
  val ROBIN_EGG_BLUE:    Float = java.lang.Float.intBitsToFloat(0xfe6e3dcd)
  val DENIM_BLUE:        Float = java.lang.Float.intBitsToFloat(0xfe426b9b)
  val DEEP_TEAL:         Float = java.lang.Float.intBitsToFloat(0xfe725f57)
  val NAVY_BLUE:         Float = java.lang.Float.intBitsToFloat(0xfe5b832e)
  val BLUEBERRY:         Float = java.lang.Float.intBitsToFloat(0xfe438e3f)
  val PRUSSIAN_BLUE:     Float = java.lang.Float.intBitsToFloat(0xfe3a8c53)
  val DESERT_RAIN:       Float = java.lang.Float.intBitsToFloat(0xfe517969)
  val ELECTRIC_BLUE:     Float = java.lang.Float.intBitsToFloat(0xfe0ab16c)
  val HIDDEN_BLUE:       Float = java.lang.Float.intBitsToFloat(0xfe398371)
  val DULL_AZURE:        Float = java.lang.Float.intBitsToFloat(0xfe2e8881)
  val RIPPED_DENIM:      Float = java.lang.Float.intBitsToFloat(0xfe596fa0)
  val CALM_SKY:          Float = java.lang.Float.intBitsToFloat(0xfe347aa8)
  val VAPOR:             Float = java.lang.Float.intBitsToFloat(0xfe4182b9)
  val POWDER_BLUE:       Float = java.lang.Float.intBitsToFloat(0xfe4865c1)
  val SUDS:              Float = java.lang.Float.intBitsToFloat(0xfe508ac6)
  val STRONG_CYAN:       Float = java.lang.Float.intBitsToFloat(0xfe4161b9)
  val SHARP_AZURE:       Float = java.lang.Float.intBitsToFloat(0xfe1d918b)
  val BLUE_EYE:          Float = java.lang.Float.intBitsToFloat(0xfe418185)
  val SUBTLETY:          Float = java.lang.Float.intBitsToFloat(0xfe26a888)
  val ROUGH_SAPPHIRE:    Float = java.lang.Float.intBitsToFloat(0xfe0db478)
  val IRIS:              Float = java.lang.Float.intBitsToFloat(0xfe0bc66d)
  val CORNFLOWER_BLUE:   Float = java.lang.Float.intBitsToFloat(0xfe04c464)
  val POLISHED_SAPPHIRE: Float = java.lang.Float.intBitsToFloat(0xfe03cb4b)
  val ROYAL_BLUE:        Float = java.lang.Float.intBitsToFloat(0xfe0ec63c)
  val INDIGO:            Float = java.lang.Float.intBitsToFloat(0xfe25b931)
  val SPACE_BLUE:        Float = java.lang.Float.intBitsToFloat(0xfe5a8622)
  val THICK_AMETHYST:    Float = java.lang.Float.intBitsToFloat(0xfe20c645)
  val JUICY_GRAPE:       Float = java.lang.Float.intBitsToFloat(0xfe12d053)
  val BLACKLIGHT_GLOW:   Float = java.lang.Float.intBitsToFloat(0xfe23c969)
  val PURPLE_FREESIA:    Float = java.lang.Float.intBitsToFloat(0xfe13d27e)
  val THIN_AMETHYST:     Float = java.lang.Float.intBitsToFloat(0xfe00e268)
  val ORCHID:            Float = java.lang.Float.intBitsToFloat(0xfe26c796)
  val LAVENDER:          Float = java.lang.Float.intBitsToFloat(0xfe39a6ad)
  val LILAC:             Float = java.lang.Float.intBitsToFloat(0xfe48a2c0)
  val SOAP:              Float = java.lang.Float.intBitsToFloat(0xfe598cd2)
  val PINK_TUTU:         Float = java.lang.Float.intBitsToFloat(0xfe5f97db)
  val THISTLE:           Float = java.lang.Float.intBitsToFloat(0xfe37c8aa)
  val HELIOTROPE:        Float = java.lang.Float.intBitsToFloat(0xfe34e1a7)
  val PURPLE:            Float = java.lang.Float.intBitsToFloat(0xfe32e388)
  val WISTERIA:          Float = java.lang.Float.intBitsToFloat(0xfe17e283)
  val MEDIUM_PLUM:       Float = java.lang.Float.intBitsToFloat(0xfe37dc75)
  val VIOLET:            Float = java.lang.Float.intBitsToFloat(0xfe2ad05f)
  val GRAPE_LOLLIPOP:    Float = java.lang.Float.intBitsToFloat(0xfe45b53e)
  val MULBERRY:          Float = java.lang.Float.intBitsToFloat(0xfe58b33d)
  val GRAPE_SODA:        Float = java.lang.Float.intBitsToFloat(0xfe47b327)
  val EGGPLANT:          Float = java.lang.Float.intBitsToFloat(0xfe58a31d)
  val CHERRY_SYRUP:      Float = java.lang.Float.intBitsToFloat(0xfe77a332)
  val PLUM_JUICE:        Float = java.lang.Float.intBitsToFloat(0xfe5ac75f)
  val FRUIT_PUNCH:       Float = java.lang.Float.intBitsToFloat(0xfe70d46f)
  val BUBBLE_GUM:        Float = java.lang.Float.intBitsToFloat(0xfe5dd79f)
  val PINK_LEMONADE:     Float = java.lang.Float.intBitsToFloat(0xfe61caa9)
  val SHRIMP:            Float = java.lang.Float.intBitsToFloat(0xfe7ba5c1)
  val FLAMINGO:          Float = java.lang.Float.intBitsToFloat(0xfe7cd893)
  val ROSE:              Float = java.lang.Float.intBitsToFloat(0xfe7ed882)
  val CARMINE:           Float = java.lang.Float.intBitsToFloat(0xfe9eca67)
  val BOLOGNA:           Float = java.lang.Float.intBitsToFloat(0xfe86b15f)
  val RASPBERRY:         Float = java.lang.Float.intBitsToFloat(0xfe8ebb50)

  // Register all colors
  locally {
    NAMED.put("Transparent", java.lang.Float.intBitsToFloat(0x7f7f00))
    LIST += java.lang.Float.intBitsToFloat(0x7f7f00)
    NAMED.put("Black", java.lang.Float.intBitsToFloat(0xfe7f7f00))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7f00)
    NAMED.put("Coal Black", java.lang.Float.intBitsToFloat(0xfe7e7d0f))
    LIST += java.lang.Float.intBitsToFloat(0xfe7e7d0f)
    NAMED.put("Shadow", java.lang.Float.intBitsToFloat(0xfe7d7c25))
    LIST += java.lang.Float.intBitsToFloat(0xfe7d7c25)
    NAMED.put("Graphite", java.lang.Float.intBitsToFloat(0xfe7d7b3b))
    LIST += java.lang.Float.intBitsToFloat(0xfe7d7b3b)
    NAMED.put("Dark Gray", java.lang.Float.intBitsToFloat(0xfe7c7b4f))
    LIST += java.lang.Float.intBitsToFloat(0xfe7c7b4f)
    NAMED.put("Lead", java.lang.Float.intBitsToFloat(0xfe7c7a62))
    LIST += java.lang.Float.intBitsToFloat(0xfe7c7a62)
    NAMED.put("Iron", java.lang.Float.intBitsToFloat(0xfe7b7976))
    LIST += java.lang.Float.intBitsToFloat(0xfe7b7976)
    NAMED.put("Gray", java.lang.Float.intBitsToFloat(0xfe7b7989))
    LIST += java.lang.Float.intBitsToFloat(0xfe7b7989)
    NAMED.put("Chinchilla", java.lang.Float.intBitsToFloat(0xfe7a789b))
    LIST += java.lang.Float.intBitsToFloat(0xfe7a789b)
    NAMED.put("Greyhound", java.lang.Float.intBitsToFloat(0xfe7a77ac))
    LIST += java.lang.Float.intBitsToFloat(0xfe7a77ac)
    NAMED.put("Silver", java.lang.Float.intBitsToFloat(0xfe7977bd))
    LIST += java.lang.Float.intBitsToFloat(0xfe7977bd)
    NAMED.put("Light Gray", java.lang.Float.intBitsToFloat(0xfe7976cf))
    LIST += java.lang.Float.intBitsToFloat(0xfe7976cf)
    NAMED.put("Platinum", java.lang.Float.intBitsToFloat(0xfe7875df))
    LIST += java.lang.Float.intBitsToFloat(0xfe7875df)
    NAMED.put("Cloud", java.lang.Float.intBitsToFloat(0xfe7875ef))
    LIST += java.lang.Float.intBitsToFloat(0xfe7875ef)
    NAMED.put("White", java.lang.Float.intBitsToFloat(0xfe7874ff))
    LIST += java.lang.Float.intBitsToFloat(0xfe7874ff)
    NAMED.put("Seawater", java.lang.Float.intBitsToFloat(0xfe70557a))
    LIST += java.lang.Float.intBitsToFloat(0xfe70557a)
    NAMED.put("Hospital Green", java.lang.Float.intBitsToFloat(0xfe6c4cb5))
    LIST += java.lang.Float.intBitsToFloat(0xfe6c4cb5)
    NAMED.put("Cyan", java.lang.Float.intBitsToFloat(0xfe6639e9))
    LIST += java.lang.Float.intBitsToFloat(0xfe6639e9)
    NAMED.put("Bubble", java.lang.Float.intBitsToFloat(0xfe6f5cf5))
    LIST += java.lang.Float.intBitsToFloat(0xfe6f5cf5)
    NAMED.put("Periwinkle", java.lang.Float.intBitsToFloat(0xfe27a198))
    LIST += java.lang.Float.intBitsToFloat(0xfe27a198)
    NAMED.put("Blue", java.lang.Float.intBitsToFloat(0xfe00de52))
    LIST += java.lang.Float.intBitsToFloat(0xfe00de52)
    NAMED.put("Faded Blue", java.lang.Float.intBitsToFloat(0xfe24ad58))
    LIST += java.lang.Float.intBitsToFloat(0xfe24ad58)
    NAMED.put("Ocean Blue", java.lang.Float.intBitsToFloat(0xfe28b820))
    LIST += java.lang.Float.intBitsToFloat(0xfe28b820)
    NAMED.put("Stygian Blue", java.lang.Float.intBitsToFloat(0xfe4a9c17))
    LIST += java.lang.Float.intBitsToFloat(0xfe4a9c17)
    NAMED.put("Deep Purple", java.lang.Float.intBitsToFloat(0xfe4cc54b))
    LIST += java.lang.Float.intBitsToFloat(0xfe4cc54b)
    NAMED.put("Tyrian Purple", java.lang.Float.intBitsToFloat(0xfe44cc7f))
    LIST += java.lang.Float.intBitsToFloat(0xfe44cc7f)
    NAMED.put("Magenta", java.lang.Float.intBitsToFloat(0xfe2df094))
    LIST += java.lang.Float.intBitsToFloat(0xfe2df094)
    NAMED.put("Bubblegum Pink", java.lang.Float.intBitsToFloat(0xfe42c7b8))
    LIST += java.lang.Float.intBitsToFloat(0xfe42c7b8)
    NAMED.put("Pork Chop", java.lang.Float.intBitsToFloat(0xfe7d94d5))
    LIST += java.lang.Float.intBitsToFloat(0xfe7d94d5)
    NAMED.put("Raw Meat", java.lang.Float.intBitsToFloat(0xfe97b3af))
    LIST += java.lang.Float.intBitsToFloat(0xfe97b3af)
    NAMED.put("Red", java.lang.Float.intBitsToFloat(0xfed3dd88))
    LIST += java.lang.Float.intBitsToFloat(0xfed3dd88)
    NAMED.put("Putty", java.lang.Float.intBitsToFloat(0xfea1ba74))
    LIST += java.lang.Float.intBitsToFloat(0xfea1ba74)
    NAMED.put("Sienna", java.lang.Float.intBitsToFloat(0xfeaeb740))
    LIST += java.lang.Float.intBitsToFloat(0xfeaeb740)
    NAMED.put("Seal Brown", java.lang.Float.intBitsToFloat(0xfe94a12d))
    LIST += java.lang.Float.intBitsToFloat(0xfe94a12d)
    NAMED.put("Mummy Brown", java.lang.Float.intBitsToFloat(0xfeb69957))
    LIST += java.lang.Float.intBitsToFloat(0xfeb69957)
    NAMED.put("Fawn", java.lang.Float.intBitsToFloat(0xfeb49096))
    LIST += java.lang.Float.intBitsToFloat(0xfeb49096)
    NAMED.put("Orange", java.lang.Float.intBitsToFloat(0xfedbaeab))
    LIST += java.lang.Float.intBitsToFloat(0xfedbaeab)
    NAMED.put("Peach", java.lang.Float.intBitsToFloat(0xfeae8ad1))
    LIST += java.lang.Float.intBitsToFloat(0xfeae8ad1)
    NAMED.put("Cream", java.lang.Float.intBitsToFloat(0xfea068fc))
    LIST += java.lang.Float.intBitsToFloat(0xfea068fc)
    NAMED.put("Yellow", java.lang.Float.intBitsToFloat(0xfef459f8))
    LIST += java.lang.Float.intBitsToFloat(0xfef459f8)
    NAMED.put("Earwax", java.lang.Float.intBitsToFloat(0xfeca63c0))
    LIST += java.lang.Float.intBitsToFloat(0xfeca63c0)
    NAMED.put("Umber", java.lang.Float.intBitsToFloat(0xfec56983))
    LIST += java.lang.Float.intBitsToFloat(0xfec56983)
    NAMED.put("Ivy Green", java.lang.Float.intBitsToFloat(0xfebc3975))
    LIST += java.lang.Float.intBitsToFloat(0xfebc3975)
    NAMED.put("Jade", java.lang.Float.intBitsToFloat(0xfebf2daf))
    LIST += java.lang.Float.intBitsToFloat(0xfebf2daf)
    NAMED.put("Green", java.lang.Float.intBitsToFloat(0xfee609e0))
    LIST += java.lang.Float.intBitsToFloat(0xfee609e0)
    NAMED.put("Celadon", java.lang.Float.intBitsToFloat(0xfea043ee))
    LIST += java.lang.Float.intBitsToFloat(0xfea043ee)
    NAMED.put("Puce", java.lang.Float.intBitsToFloat(0xfe7081ba))
    LIST += java.lang.Float.intBitsToFloat(0xfe7081ba)
    NAMED.put("Beige", java.lang.Float.intBitsToFloat(0xfe9680b7))
    LIST += java.lang.Float.intBitsToFloat(0xfe9680b7)
    NAMED.put("Wet Stone", java.lang.Float.intBitsToFloat(0xfe8677a8))
    LIST += java.lang.Float.intBitsToFloat(0xfe8677a8)
    NAMED.put("Slow Creek", java.lang.Float.intBitsToFloat(0xfe776e98))
    LIST += java.lang.Float.intBitsToFloat(0xfe776e98)
    NAMED.put("Slate Gray", java.lang.Float.intBitsToFloat(0xfe747187))
    LIST += java.lang.Float.intBitsToFloat(0xfe747187)
    NAMED.put("Light Skin 1", java.lang.Float.intBitsToFloat(0xfe887e79))
    LIST += java.lang.Float.intBitsToFloat(0xfe887e79)
    NAMED.put("Light Skin 2", java.lang.Float.intBitsToFloat(0xfe8e937f))
    LIST += java.lang.Float.intBitsToFloat(0xfe8e937f)
    NAMED.put("Light Skin 3", java.lang.Float.intBitsToFloat(0xfe8e9b94))
    LIST += java.lang.Float.intBitsToFloat(0xfe8e9b94)
    NAMED.put("Light Skin 4", java.lang.Float.intBitsToFloat(0xfe9896a3))
    LIST += java.lang.Float.intBitsToFloat(0xfe9896a3)
    NAMED.put("Light Skin 5", java.lang.Float.intBitsToFloat(0xfe9c94b3))
    LIST += java.lang.Float.intBitsToFloat(0xfe9c94b3)
    NAMED.put("Light Skin 6", java.lang.Float.intBitsToFloat(0xfe9a90c0))
    LIST += java.lang.Float.intBitsToFloat(0xfe9a90c0)
    NAMED.put("Light Skin 7", java.lang.Float.intBitsToFloat(0xfe988dcc))
    LIST += java.lang.Float.intBitsToFloat(0xfe988dcc)
    NAMED.put("Light Skin 8", java.lang.Float.intBitsToFloat(0xfe9186d6))
    LIST += java.lang.Float.intBitsToFloat(0xfe9186d6)
    NAMED.put("Light Skin 9", java.lang.Float.intBitsToFloat(0xfe857be8))
    LIST += java.lang.Float.intBitsToFloat(0xfe857be8)
    NAMED.put("Dark Skin 1", java.lang.Float.intBitsToFloat(0xfe838a47))
    LIST += java.lang.Float.intBitsToFloat(0xfe838a47)
    NAMED.put("Dark Skin 2", java.lang.Float.intBitsToFloat(0xfe8c9555))
    LIST += java.lang.Float.intBitsToFloat(0xfe8c9555)
    NAMED.put("Dark Skin 3", java.lang.Float.intBitsToFloat(0xfe89976d))
    LIST += java.lang.Float.intBitsToFloat(0xfe89976d)
    NAMED.put("Pink Skin 1", java.lang.Float.intBitsToFloat(0xfe86948a))
    LIST += java.lang.Float.intBitsToFloat(0xfe86948a)
    NAMED.put("Pink Skin 2", java.lang.Float.intBitsToFloat(0xfe8592a5))
    LIST += java.lang.Float.intBitsToFloat(0xfe8592a5)
    NAMED.put("Pink Skin 3", java.lang.Float.intBitsToFloat(0xfe8490c0))
    LIST += java.lang.Float.intBitsToFloat(0xfe8490c0)
    NAMED.put("Pink Skin 4", java.lang.Float.intBitsToFloat(0xfe7a88e0))
    LIST += java.lang.Float.intBitsToFloat(0xfe7a88e0)
    NAMED.put("Bronze Skin 4", java.lang.Float.intBitsToFloat(0xfe907dd1))
    LIST += java.lang.Float.intBitsToFloat(0xfe907dd1)
    NAMED.put("Bronze Skin 3", java.lang.Float.intBitsToFloat(0xfe9e82ad))
    LIST += java.lang.Float.intBitsToFloat(0xfe9e82ad)
    NAMED.put("Bronze Skin 2", java.lang.Float.intBitsToFloat(0xfe958281))
    LIST += java.lang.Float.intBitsToFloat(0xfe958281)
    NAMED.put("Bronze Skin 1", java.lang.Float.intBitsToFloat(0xfe978464))
    LIST += java.lang.Float.intBitsToFloat(0xfe978464)
    NAMED.put("Taupe", java.lang.Float.intBitsToFloat(0xfe8c8132))
    LIST += java.lang.Float.intBitsToFloat(0xfe8c8132)
    NAMED.put("Drab Green", java.lang.Float.intBitsToFloat(0xfe947444))
    LIST += java.lang.Float.intBitsToFloat(0xfe947444)
    NAMED.put("Lizard Scales", java.lang.Float.intBitsToFloat(0xfea46e78))
    LIST += java.lang.Float.intBitsToFloat(0xfea46e78)
    NAMED.put("Cricket", java.lang.Float.intBitsToFloat(0xfea26d94))
    LIST += java.lang.Float.intBitsToFloat(0xfea26d94)
    NAMED.put("Olive Oil", java.lang.Float.intBitsToFloat(0xfeae69a6))
    LIST += java.lang.Float.intBitsToFloat(0xfeae69a6)
    NAMED.put("Dun", java.lang.Float.intBitsToFloat(0xfea66ab9))
    LIST += java.lang.Float.intBitsToFloat(0xfea66ab9)
    NAMED.put("Corn Silk", java.lang.Float.intBitsToFloat(0xfe9e6bca))
    LIST += java.lang.Float.intBitsToFloat(0xfe9e6bca)
    NAMED.put("Tan", java.lang.Float.intBitsToFloat(0xfe976cdc))
    LIST += java.lang.Float.intBitsToFloat(0xfe976cdc)
    NAMED.put("Straw", java.lang.Float.intBitsToFloat(0xfe906ded))
    LIST += java.lang.Float.intBitsToFloat(0xfe906ded)
    NAMED.put("Honeydew", java.lang.Float.intBitsToFloat(0xfe995ede))
    LIST += java.lang.Float.intBitsToFloat(0xfe995ede)
    NAMED.put("Tarnish", java.lang.Float.intBitsToFloat(0xfe9a5ec5))
    LIST += java.lang.Float.intBitsToFloat(0xfe9a5ec5)
    NAMED.put("Pea Soup", java.lang.Float.intBitsToFloat(0xfeb84db7))
    LIST += java.lang.Float.intBitsToFloat(0xfeb84db7)
    NAMED.put("Marsh", java.lang.Float.intBitsToFloat(0xfe9d5f8f))
    LIST += java.lang.Float.intBitsToFloat(0xfe9d5f8f)
    NAMED.put("Asparagus", java.lang.Float.intBitsToFloat(0xfea3597b))
    LIST += java.lang.Float.intBitsToFloat(0xfea3597b)
    NAMED.put("Peat Bog", java.lang.Float.intBitsToFloat(0xfe926e52))
    LIST += java.lang.Float.intBitsToFloat(0xfe926e52)
    NAMED.put("Deep Jungle", java.lang.Float.intBitsToFloat(0xfe89751a))
    LIST += java.lang.Float.intBitsToFloat(0xfe89751a)
    NAMED.put("Pine Green", java.lang.Float.intBitsToFloat(0xfe895f4d))
    LIST += java.lang.Float.intBitsToFloat(0xfe895f4d)
    NAMED.put("Olive Green", java.lang.Float.intBitsToFloat(0xfe8d6557))
    LIST += java.lang.Float.intBitsToFloat(0xfe8d6557)
    NAMED.put("Gray Green", java.lang.Float.intBitsToFloat(0xfe876b67))
    LIST += java.lang.Float.intBitsToFloat(0xfe876b67)
    NAMED.put("Maidenhair Fern", java.lang.Float.intBitsToFloat(0xfe935670))
    LIST += java.lang.Float.intBitsToFloat(0xfe935670)
    NAMED.put("Kelly Green", java.lang.Float.intBitsToFloat(0xfe9a528b))
    LIST += java.lang.Float.intBitsToFloat(0xfe9a528b)
    NAMED.put("Dusty Green", java.lang.Float.intBitsToFloat(0xfe9852a6))
    LIST += java.lang.Float.intBitsToFloat(0xfe9852a6)
    NAMED.put("Garter Snake", java.lang.Float.intBitsToFloat(0xfe9843b5))
    LIST += java.lang.Float.intBitsToFloat(0xfe9843b5)
    NAMED.put("Silver Green", java.lang.Float.intBitsToFloat(0xfe9752c0))
    LIST += java.lang.Float.intBitsToFloat(0xfe9752c0)
    NAMED.put("Pistachio", java.lang.Float.intBitsToFloat(0xfe9553d0))
    LIST += java.lang.Float.intBitsToFloat(0xfe9553d0)
    NAMED.put("Angel Wing", java.lang.Float.intBitsToFloat(0xfe736cf5))
    LIST += java.lang.Float.intBitsToFloat(0xfe736cf5)
    NAMED.put("Sage Green", java.lang.Float.intBitsToFloat(0xfe8755e4))
    LIST += java.lang.Float.intBitsToFloat(0xfe8755e4)
    NAMED.put("Dried Sage", java.lang.Float.intBitsToFloat(0xfe8457db))
    LIST += java.lang.Float.intBitsToFloat(0xfe8457db)
    NAMED.put("Artichoke", java.lang.Float.intBitsToFloat(0xfe8d5ab1))
    LIST += java.lang.Float.intBitsToFloat(0xfe8d5ab1)
    NAMED.put("Viridian", java.lang.Float.intBitsToFloat(0xfe8a5d7c))
    LIST += java.lang.Float.intBitsToFloat(0xfe8a5d7c)
    NAMED.put("Floral Foam", java.lang.Float.intBitsToFloat(0xfe8c4f63))
    LIST += java.lang.Float.intBitsToFloat(0xfe8c4f63)
    NAMED.put("Hunter Green", java.lang.Float.intBitsToFloat(0xfe83712b))
    LIST += java.lang.Float.intBitsToFloat(0xfe83712b)
    NAMED.put("Dark Teal", java.lang.Float.intBitsToFloat(0xfe746f41))
    LIST += java.lang.Float.intBitsToFloat(0xfe746f41)
    NAMED.put("Kyanite", java.lang.Float.intBitsToFloat(0xfe746272))
    LIST += java.lang.Float.intBitsToFloat(0xfe746272)
    NAMED.put("Spearmint", java.lang.Float.intBitsToFloat(0xfe715ba7))
    LIST += java.lang.Float.intBitsToFloat(0xfe715ba7)
    NAMED.put("Amazonite", java.lang.Float.intBitsToFloat(0xfe7160c3))
    LIST += java.lang.Float.intBitsToFloat(0xfe7160c3)
    NAMED.put("Pastel Sky", java.lang.Float.intBitsToFloat(0xfe715fdd))
    LIST += java.lang.Float.intBitsToFloat(0xfe715fdd)
    NAMED.put("Aquamarine", java.lang.Float.intBitsToFloat(0xfe7264ec))
    LIST += java.lang.Float.intBitsToFloat(0xfe7264ec)
    NAMED.put("Dust Bunny", java.lang.Float.intBitsToFloat(0xfe6275d6))
    LIST += java.lang.Float.intBitsToFloat(0xfe6275d6)
    NAMED.put("Patina", java.lang.Float.intBitsToFloat(0xfe6372ca))
    LIST += java.lang.Float.intBitsToFloat(0xfe6372ca)
    NAMED.put("Chipped Granite", java.lang.Float.intBitsToFloat(0xfe6079bf))
    LIST += java.lang.Float.intBitsToFloat(0xfe6079bf)
    NAMED.put("Blue Smoke", java.lang.Float.intBitsToFloat(0xfe6373b0))
    LIST += java.lang.Float.intBitsToFloat(0xfe6373b0)
    NAMED.put("Air Force Blue", java.lang.Float.intBitsToFloat(0xfe4d7694))
    LIST += java.lang.Float.intBitsToFloat(0xfe4d7694)
    NAMED.put("Cold Iron", java.lang.Float.intBitsToFloat(0xfe637679))
    LIST += java.lang.Float.intBitsToFloat(0xfe637679)
    NAMED.put("Dreary Blue", java.lang.Float.intBitsToFloat(0xfe62785c))
    LIST += java.lang.Float.intBitsToFloat(0xfe62785c)
    NAMED.put("Murk", java.lang.Float.intBitsToFloat(0xfe6a8016))
    LIST += java.lang.Float.intBitsToFloat(0xfe6a8016)
    NAMED.put("Ninja", java.lang.Float.intBitsToFloat(0xfe658721))
    LIST += java.lang.Float.intBitsToFloat(0xfe658721)
    NAMED.put("Watercolor Black", java.lang.Float.intBitsToFloat(0xfe668442))
    LIST += java.lang.Float.intBitsToFloat(0xfe668442)
    NAMED.put("Iolite", java.lang.Float.intBitsToFloat(0xfe5c8853))
    LIST += java.lang.Float.intBitsToFloat(0xfe5c8853)
    NAMED.put("Boysenberry", java.lang.Float.intBitsToFloat(0xfe538c64))
    LIST += java.lang.Float.intBitsToFloat(0xfe538c64)
    NAMED.put("Watercolor Gray", java.lang.Float.intBitsToFloat(0xfe518d7d))
    LIST += java.lang.Float.intBitsToFloat(0xfe518d7d)
    NAMED.put("Blue Steel", java.lang.Float.intBitsToFloat(0xfe419387))
    LIST += java.lang.Float.intBitsToFloat(0xfe419387)
    NAMED.put("Twilight Cloud", java.lang.Float.intBitsToFloat(0xfe54889c))
    LIST += java.lang.Float.intBitsToFloat(0xfe54889c)
    NAMED.put("Smog", java.lang.Float.intBitsToFloat(0xfe5486b7))
    LIST += java.lang.Float.intBitsToFloat(0xfe5486b7)
    NAMED.put("Tropic Mist", java.lang.Float.intBitsToFloat(0xfe6479df))
    LIST += java.lang.Float.intBitsToFloat(0xfe6479df)
    NAMED.put("Feather Down", java.lang.Float.intBitsToFloat(0xfe667ce8))
    LIST += java.lang.Float.intBitsToFloat(0xfe667ce8)
    NAMED.put("Mild Violet", java.lang.Float.intBitsToFloat(0xfe5992a3))
    LIST += java.lang.Float.intBitsToFloat(0xfe5992a3)
    NAMED.put("Violet Cushions", java.lang.Float.intBitsToFloat(0xfe39b17a))
    LIST += java.lang.Float.intBitsToFloat(0xfe39b17a)
    NAMED.put("Dull Violet", java.lang.Float.intBitsToFloat(0xfe58976b))
    LIST += java.lang.Float.intBitsToFloat(0xfe58976b)
    NAMED.put("Royal Violet", java.lang.Float.intBitsToFloat(0xfe58994d))
    LIST += java.lang.Float.intBitsToFloat(0xfe58994d)
    NAMED.put("Eminence", java.lang.Float.intBitsToFloat(0xfe6e912d))
    LIST += java.lang.Float.intBitsToFloat(0xfe6e912d)
    NAMED.put("Prune", java.lang.Float.intBitsToFloat(0xfe718c3c))
    LIST += java.lang.Float.intBitsToFloat(0xfe718c3c)
    NAMED.put("Dusty Grape", java.lang.Float.intBitsToFloat(0xfe62a059))
    LIST += java.lang.Float.intBitsToFloat(0xfe62a059)
    NAMED.put("Pink Violet", java.lang.Float.intBitsToFloat(0xfe5fa273))
    LIST += java.lang.Float.intBitsToFloat(0xfe5fa273)
    NAMED.put("Ripe Plum", java.lang.Float.intBitsToFloat(0xfe53b37f))
    LIST += java.lang.Float.intBitsToFloat(0xfe53b37f)
    NAMED.put("Mauve", java.lang.Float.intBitsToFloat(0xfe5fa08f))
    LIST += java.lang.Float.intBitsToFloat(0xfe5fa08f)
    NAMED.put("Ham", java.lang.Float.intBitsToFloat(0xfe629ec6))
    LIST += java.lang.Float.intBitsToFloat(0xfe629ec6)
    NAMED.put("Cotton Candy", java.lang.Float.intBitsToFloat(0xfe6e89e9))
    LIST += java.lang.Float.intBitsToFloat(0xfe6e89e9)
    NAMED.put("Silver Pink", java.lang.Float.intBitsToFloat(0xfe6b88d5))
    LIST += java.lang.Float.intBitsToFloat(0xfe6b88d5)
    NAMED.put("Tea Rose", java.lang.Float.intBitsToFloat(0xfe708dca))
    LIST += java.lang.Float.intBitsToFloat(0xfe708dca)
    NAMED.put("Old Rose", java.lang.Float.intBitsToFloat(0xfe7096b7))
    LIST += java.lang.Float.intBitsToFloat(0xfe7096b7)
    NAMED.put("Dusty Pink", java.lang.Float.intBitsToFloat(0xfe689ba8))
    LIST += java.lang.Float.intBitsToFloat(0xfe689ba8)
    NAMED.put("Roseate Spoonbill", java.lang.Float.intBitsToFloat(0xfe72a39c))
    LIST += java.lang.Float.intBitsToFloat(0xfe72a39c)
    NAMED.put("Thulian Pink", java.lang.Float.intBitsToFloat(0xfe6db587))
    LIST += java.lang.Float.intBitsToFloat(0xfe6db587)
    NAMED.put("Brown Velvet", java.lang.Float.intBitsToFloat(0xfe799336))
    LIST += java.lang.Float.intBitsToFloat(0xfe799336)
    NAMED.put("Nightshade", java.lang.Float.intBitsToFloat(0xfe7a911e))
    LIST += java.lang.Float.intBitsToFloat(0xfe7a911e)
    NAMED.put("Scribe Ink", java.lang.Float.intBitsToFloat(0xfe769312))
    LIST += java.lang.Float.intBitsToFloat(0xfe769312)
    NAMED.put("Varnish", java.lang.Float.intBitsToFloat(0xfe8f9424))
    LIST += java.lang.Float.intBitsToFloat(0xfe8f9424)
    NAMED.put("Cedar Wood", java.lang.Float.intBitsToFloat(0xfea6a435))
    LIST += java.lang.Float.intBitsToFloat(0xfea6a435)
    NAMED.put("Hot Sauce", java.lang.Float.intBitsToFloat(0xfeb7c059))
    LIST += java.lang.Float.intBitsToFloat(0xfeb7c059)
    NAMED.put("Lurid Red", java.lang.Float.intBitsToFloat(0xfec4ce78))
    LIST += java.lang.Float.intBitsToFloat(0xfec4ce78)
    NAMED.put("Brick", java.lang.Float.intBitsToFloat(0xfea5b986))
    LIST += java.lang.Float.intBitsToFloat(0xfea5b986)
    NAMED.put("Bright Red", java.lang.Float.intBitsToFloat(0xfed2d190))
    LIST += java.lang.Float.intBitsToFloat(0xfed2d190)
    NAMED.put("Embers", java.lang.Float.intBitsToFloat(0xfec0c096))
    LIST += java.lang.Float.intBitsToFloat(0xfec0c096)
    NAMED.put("Salmon", java.lang.Float.intBitsToFloat(0xfea4c39f))
    LIST += java.lang.Float.intBitsToFloat(0xfea4c39f)
    NAMED.put("Taxicab Yellow", java.lang.Float.intBitsToFloat(0xfed881cc))
    LIST += java.lang.Float.intBitsToFloat(0xfed881cc)
    NAMED.put("Apricot", java.lang.Float.intBitsToFloat(0xfecf96c0))
    LIST += java.lang.Float.intBitsToFloat(0xfecf96c0)
    NAMED.put("Burnt Yellow", java.lang.Float.intBitsToFloat(0xfed687ad))
    LIST += java.lang.Float.intBitsToFloat(0xfed687ad)
    NAMED.put("Dry Pepper", java.lang.Float.intBitsToFloat(0xfecfa794))
    LIST += java.lang.Float.intBitsToFloat(0xfecfa794)
    NAMED.put("Redwood", java.lang.Float.intBitsToFloat(0xfec6a17b))
    LIST += java.lang.Float.intBitsToFloat(0xfec6a17b)
    NAMED.put("Koa", java.lang.Float.intBitsToFloat(0xfebea26b))
    LIST += java.lang.Float.intBitsToFloat(0xfebea26b)
    NAMED.put("Ochre", java.lang.Float.intBitsToFloat(0xfea09142))
    LIST += java.lang.Float.intBitsToFloat(0xfea09142)
    NAMED.put("Dull Green", java.lang.Float.intBitsToFloat(0xfeae7154))
    LIST += java.lang.Float.intBitsToFloat(0xfeae7154)
    NAMED.put("Army Green", java.lang.Float.intBitsToFloat(0xfeb96c66))
    LIST += java.lang.Float.intBitsToFloat(0xfeb96c66)
    NAMED.put("Driftwood", java.lang.Float.intBitsToFloat(0xfe987789))
    LIST += java.lang.Float.intBitsToFloat(0xfe987789)
    NAMED.put("Dry Brush", java.lang.Float.intBitsToFloat(0xfed0749d))
    LIST += java.lang.Float.intBitsToFloat(0xfed0749d)
    NAMED.put("Mush", java.lang.Float.intBitsToFloat(0xfed763b3))
    LIST += java.lang.Float.intBitsToFloat(0xfed763b3)
    NAMED.put("Banana Pudding", java.lang.Float.intBitsToFloat(0xfec96bd8))
    LIST += java.lang.Float.intBitsToFloat(0xfec96bd8)
    NAMED.put("Saffron", java.lang.Float.intBitsToFloat(0xfee975dd))
    LIST += java.lang.Float.intBitsToFloat(0xfee975dd)
    NAMED.put("Pencil Yellow", java.lang.Float.intBitsToFloat(0xfedc69eb))
    LIST += java.lang.Float.intBitsToFloat(0xfedc69eb)
    NAMED.put("Chartreuse", java.lang.Float.intBitsToFloat(0xfee040ef))
    LIST += java.lang.Float.intBitsToFloat(0xfee040ef)
    NAMED.put("Absinthe", java.lang.Float.intBitsToFloat(0xfed535de))
    LIST += java.lang.Float.intBitsToFloat(0xfed535de)
    NAMED.put("Infection", java.lang.Float.intBitsToFloat(0xfedd3bce))
    LIST += java.lang.Float.intBitsToFloat(0xfedd3bce)
    NAMED.put("Frog Green", java.lang.Float.intBitsToFloat(0xfed836ba))
    LIST += java.lang.Float.intBitsToFloat(0xfed836ba)
    NAMED.put("Avocado", java.lang.Float.intBitsToFloat(0xfece44a0))
    LIST += java.lang.Float.intBitsToFloat(0xfece44a0)
    NAMED.put("Woodlands", java.lang.Float.intBitsToFloat(0xfeb2516a))
    LIST += java.lang.Float.intBitsToFloat(0xfeb2516a)
    NAMED.put("Dark Pine", java.lang.Float.intBitsToFloat(0xfe9e6b32))
    LIST += java.lang.Float.intBitsToFloat(0xfe9e6b32)
    NAMED.put("Moss Green", java.lang.Float.intBitsToFloat(0xfea45b42))
    LIST += java.lang.Float.intBitsToFloat(0xfea45b42)
    NAMED.put("Fern Green", java.lang.Float.intBitsToFloat(0xfeab4a55))
    LIST += java.lang.Float.intBitsToFloat(0xfeab4a55)
    NAMED.put("Forest Glen", java.lang.Float.intBitsToFloat(0xfec3328a))
    LIST += java.lang.Float.intBitsToFloat(0xfec3328a)
    NAMED.put("Malachite", java.lang.Float.intBitsToFloat(0xfed818c0))
    LIST += java.lang.Float.intBitsToFloat(0xfed818c0)
    NAMED.put("Apple Green", java.lang.Float.intBitsToFloat(0xfedd13cc))
    LIST += java.lang.Float.intBitsToFloat(0xfedd13cc)
    NAMED.put("Celery", java.lang.Float.intBitsToFloat(0xfec127e7))
    LIST += java.lang.Float.intBitsToFloat(0xfec127e7)
    NAMED.put("Mint Green", java.lang.Float.intBitsToFloat(0xfec61dd7))
    LIST += java.lang.Float.intBitsToFloat(0xfec61dd7)
    NAMED.put("Emerald", java.lang.Float.intBitsToFloat(0xfed11eb1))
    LIST += java.lang.Float.intBitsToFloat(0xfed11eb1)
    NAMED.put("Prase", java.lang.Float.intBitsToFloat(0xfeae2ca4))
    LIST += java.lang.Float.intBitsToFloat(0xfeae2ca4)
    NAMED.put("Eucalyptus", java.lang.Float.intBitsToFloat(0xfe9b4083))
    LIST += java.lang.Float.intBitsToFloat(0xfe9b4083)
    NAMED.put("Zucchini", java.lang.Float.intBitsToFloat(0xfe7c6835))
    LIST += java.lang.Float.intBitsToFloat(0xfe7c6835)
    NAMED.put("Soft Teal", java.lang.Float.intBitsToFloat(0xfe7f478f))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f478f)
    NAMED.put("Medium Teal", java.lang.Float.intBitsToFloat(0xfe8c34b4))
    LIST += java.lang.Float.intBitsToFloat(0xfe8c34b4)
    NAMED.put("Spring Green", java.lang.Float.intBitsToFloat(0xfeb31ec7))
    LIST += java.lang.Float.intBitsToFloat(0xfeb31ec7)
    NAMED.put("Turquoise", java.lang.Float.intBitsToFloat(0xfe932ad5))
    LIST += java.lang.Float.intBitsToFloat(0xfe932ad5)
    NAMED.put("Seafoam", java.lang.Float.intBitsToFloat(0xfe9f22e4))
    LIST += java.lang.Float.intBitsToFloat(0xfe9f22e4)
    NAMED.put("Variscite", java.lang.Float.intBitsToFloat(0xfe8834e9))
    LIST += java.lang.Float.intBitsToFloat(0xfe8834e9)
    NAMED.put("Refreshing Mist", java.lang.Float.intBitsToFloat(0xfe615ae1))
    LIST += java.lang.Float.intBitsToFloat(0xfe615ae1)
    NAMED.put("Shining Sky", java.lang.Float.intBitsToFloat(0xfe5a4fd9))
    LIST += java.lang.Float.intBitsToFloat(0xfe5a4fd9)
    NAMED.put("Steam", java.lang.Float.intBitsToFloat(0xfe5e5cd0))
    LIST += java.lang.Float.intBitsToFloat(0xfe5e5cd0)
    NAMED.put("Robin Egg Blue", java.lang.Float.intBitsToFloat(0xfe6e3dcd))
    LIST += java.lang.Float.intBitsToFloat(0xfe6e3dcd)
    NAMED.put("Denim Blue", java.lang.Float.intBitsToFloat(0xfe426b9b))
    LIST += java.lang.Float.intBitsToFloat(0xfe426b9b)
    NAMED.put("Deep Teal", java.lang.Float.intBitsToFloat(0xfe725f57))
    LIST += java.lang.Float.intBitsToFloat(0xfe725f57)
    NAMED.put("Navy Blue", java.lang.Float.intBitsToFloat(0xfe5b832e))
    LIST += java.lang.Float.intBitsToFloat(0xfe5b832e)
    NAMED.put("Blueberry", java.lang.Float.intBitsToFloat(0xfe438e3f))
    LIST += java.lang.Float.intBitsToFloat(0xfe438e3f)
    NAMED.put("Prussian Blue", java.lang.Float.intBitsToFloat(0xfe3a8c53))
    LIST += java.lang.Float.intBitsToFloat(0xfe3a8c53)
    NAMED.put("Desert Rain", java.lang.Float.intBitsToFloat(0xfe517969))
    LIST += java.lang.Float.intBitsToFloat(0xfe517969)
    NAMED.put("Electric Blue", java.lang.Float.intBitsToFloat(0xfe0ab16c))
    LIST += java.lang.Float.intBitsToFloat(0xfe0ab16c)
    NAMED.put("Hidden Blue", java.lang.Float.intBitsToFloat(0xfe398371))
    LIST += java.lang.Float.intBitsToFloat(0xfe398371)
    NAMED.put("Dull Azure", java.lang.Float.intBitsToFloat(0xfe2e8881))
    LIST += java.lang.Float.intBitsToFloat(0xfe2e8881)
    NAMED.put("Ripped Denim", java.lang.Float.intBitsToFloat(0xfe596fa0))
    LIST += java.lang.Float.intBitsToFloat(0xfe596fa0)
    NAMED.put("Calm Sky", java.lang.Float.intBitsToFloat(0xfe347aa8))
    LIST += java.lang.Float.intBitsToFloat(0xfe347aa8)
    NAMED.put("Vapor", java.lang.Float.intBitsToFloat(0xfe4182b9))
    LIST += java.lang.Float.intBitsToFloat(0xfe4182b9)
    NAMED.put("Powder Blue", java.lang.Float.intBitsToFloat(0xfe4865c1))
    LIST += java.lang.Float.intBitsToFloat(0xfe4865c1)
    NAMED.put("Suds", java.lang.Float.intBitsToFloat(0xfe508ac6))
    LIST += java.lang.Float.intBitsToFloat(0xfe508ac6)
    NAMED.put("Strong Cyan", java.lang.Float.intBitsToFloat(0xfe4161b9))
    LIST += java.lang.Float.intBitsToFloat(0xfe4161b9)
    NAMED.put("Sharp Azure", java.lang.Float.intBitsToFloat(0xfe1d918b))
    LIST += java.lang.Float.intBitsToFloat(0xfe1d918b)
    NAMED.put("Blue Eye", java.lang.Float.intBitsToFloat(0xfe418185))
    LIST += java.lang.Float.intBitsToFloat(0xfe418185)
    NAMED.put("Subtlety", java.lang.Float.intBitsToFloat(0xfe26a888))
    LIST += java.lang.Float.intBitsToFloat(0xfe26a888)
    NAMED.put("Rough Sapphire", java.lang.Float.intBitsToFloat(0xfe0db478))
    LIST += java.lang.Float.intBitsToFloat(0xfe0db478)
    NAMED.put("Iris", java.lang.Float.intBitsToFloat(0xfe0bc66d))
    LIST += java.lang.Float.intBitsToFloat(0xfe0bc66d)
    NAMED.put("Cornflower Blue", java.lang.Float.intBitsToFloat(0xfe04c464))
    LIST += java.lang.Float.intBitsToFloat(0xfe04c464)
    NAMED.put("Polished Sapphire", java.lang.Float.intBitsToFloat(0xfe03cb4b))
    LIST += java.lang.Float.intBitsToFloat(0xfe03cb4b)
    NAMED.put("Royal Blue", java.lang.Float.intBitsToFloat(0xfe0ec63c))
    LIST += java.lang.Float.intBitsToFloat(0xfe0ec63c)
    NAMED.put("Indigo", java.lang.Float.intBitsToFloat(0xfe25b931))
    LIST += java.lang.Float.intBitsToFloat(0xfe25b931)
    NAMED.put("Space Blue", java.lang.Float.intBitsToFloat(0xfe5a8622))
    LIST += java.lang.Float.intBitsToFloat(0xfe5a8622)
    NAMED.put("Thick Amethyst", java.lang.Float.intBitsToFloat(0xfe20c645))
    LIST += java.lang.Float.intBitsToFloat(0xfe20c645)
    NAMED.put("Juicy Grape", java.lang.Float.intBitsToFloat(0xfe12d053))
    LIST += java.lang.Float.intBitsToFloat(0xfe12d053)
    NAMED.put("Blacklight Glow", java.lang.Float.intBitsToFloat(0xfe23c969))
    LIST += java.lang.Float.intBitsToFloat(0xfe23c969)
    NAMED.put("Purple Freesia", java.lang.Float.intBitsToFloat(0xfe13d27e))
    LIST += java.lang.Float.intBitsToFloat(0xfe13d27e)
    NAMED.put("Thin Amethyst", java.lang.Float.intBitsToFloat(0xfe00e268))
    LIST += java.lang.Float.intBitsToFloat(0xfe00e268)
    NAMED.put("Orchid", java.lang.Float.intBitsToFloat(0xfe26c796))
    LIST += java.lang.Float.intBitsToFloat(0xfe26c796)
    NAMED.put("Lavender", java.lang.Float.intBitsToFloat(0xfe39a6ad))
    LIST += java.lang.Float.intBitsToFloat(0xfe39a6ad)
    NAMED.put("Lilac", java.lang.Float.intBitsToFloat(0xfe48a2c0))
    LIST += java.lang.Float.intBitsToFloat(0xfe48a2c0)
    NAMED.put("Soap", java.lang.Float.intBitsToFloat(0xfe598cd2))
    LIST += java.lang.Float.intBitsToFloat(0xfe598cd2)
    NAMED.put("Pink Tutu", java.lang.Float.intBitsToFloat(0xfe5f97db))
    LIST += java.lang.Float.intBitsToFloat(0xfe5f97db)
    NAMED.put("Thistle", java.lang.Float.intBitsToFloat(0xfe37c8aa))
    LIST += java.lang.Float.intBitsToFloat(0xfe37c8aa)
    NAMED.put("Heliotrope", java.lang.Float.intBitsToFloat(0xfe34e1a7))
    LIST += java.lang.Float.intBitsToFloat(0xfe34e1a7)
    NAMED.put("Purple", java.lang.Float.intBitsToFloat(0xfe32e388))
    LIST += java.lang.Float.intBitsToFloat(0xfe32e388)
    NAMED.put("Wisteria", java.lang.Float.intBitsToFloat(0xfe17e283))
    LIST += java.lang.Float.intBitsToFloat(0xfe17e283)
    NAMED.put("Medium Plum", java.lang.Float.intBitsToFloat(0xfe37dc75))
    LIST += java.lang.Float.intBitsToFloat(0xfe37dc75)
    NAMED.put("Violet", java.lang.Float.intBitsToFloat(0xfe2ad05f))
    LIST += java.lang.Float.intBitsToFloat(0xfe2ad05f)
    NAMED.put("Grape Lollipop", java.lang.Float.intBitsToFloat(0xfe45b53e))
    LIST += java.lang.Float.intBitsToFloat(0xfe45b53e)
    NAMED.put("Mulberry", java.lang.Float.intBitsToFloat(0xfe58b33d))
    LIST += java.lang.Float.intBitsToFloat(0xfe58b33d)
    NAMED.put("Grape Soda", java.lang.Float.intBitsToFloat(0xfe47b327))
    LIST += java.lang.Float.intBitsToFloat(0xfe47b327)
    NAMED.put("Eggplant", java.lang.Float.intBitsToFloat(0xfe58a31d))
    LIST += java.lang.Float.intBitsToFloat(0xfe58a31d)
    NAMED.put("Cherry Syrup", java.lang.Float.intBitsToFloat(0xfe77a332))
    LIST += java.lang.Float.intBitsToFloat(0xfe77a332)
    NAMED.put("Plum Juice", java.lang.Float.intBitsToFloat(0xfe5ac75f))
    LIST += java.lang.Float.intBitsToFloat(0xfe5ac75f)
    NAMED.put("Fruit Punch", java.lang.Float.intBitsToFloat(0xfe70d46f))
    LIST += java.lang.Float.intBitsToFloat(0xfe70d46f)
    NAMED.put("Bubble Gum", java.lang.Float.intBitsToFloat(0xfe5dd79f))
    LIST += java.lang.Float.intBitsToFloat(0xfe5dd79f)
    NAMED.put("Pink Lemonade", java.lang.Float.intBitsToFloat(0xfe61caa9))
    LIST += java.lang.Float.intBitsToFloat(0xfe61caa9)
    NAMED.put("Shrimp", java.lang.Float.intBitsToFloat(0xfe7ba5c1))
    LIST += java.lang.Float.intBitsToFloat(0xfe7ba5c1)
    NAMED.put("Flamingo", java.lang.Float.intBitsToFloat(0xfe7cd893))
    LIST += java.lang.Float.intBitsToFloat(0xfe7cd893)
    NAMED.put("Rose", java.lang.Float.intBitsToFloat(0xfe7ed882))
    LIST += java.lang.Float.intBitsToFloat(0xfe7ed882)
    NAMED.put("Carmine", java.lang.Float.intBitsToFloat(0xfe9eca67))
    LIST += java.lang.Float.intBitsToFloat(0xfe9eca67)
    NAMED.put("Bologna", java.lang.Float.intBitsToFloat(0xfe86b15f))
    LIST += java.lang.Float.intBitsToFloat(0xfe86b15f)
    NAMED.put("Raspberry", java.lang.Float.intBitsToFloat(0xfe8ebb50))
    LIST += java.lang.Float.intBitsToFloat(0xfe8ebb50)
  }

  /** Converts existing Color entries in [[sge.graphics.Colors]] from RGBA to CIELAB format. */
  def editKnownColors(): Unit =
    for (c <- sge.graphics.Colors.colors.values) {
      val f = ColorTools.fromColor(c)
      c.set(ColorTools.channelL(f), ColorTools.channelA(f), ColorTools.channelB(f), c.a)
    }

  /** Appends CIELAB-compatible Color instances to the map in [[sge.graphics.Colors]]. */
  def appendToKnownColors(): Unit =
    for ((key, value) <- NAMED) {
      val f = value
      sge.graphics.Colors.put(key, new sge.graphics.Color(ColorTools.channelL(f), ColorTools.channelA(f), ColorTools.channelB(f), ColorTools.alpha(f)))
    }
}
