# Override dialect for -no-indent (braces required) codebase
dialectOverride.allowSignificantIndentation = false

# Default rules (empty — invoke specific rules via sbt command line)
rules = []

RemoveUnused {
  imports = true
  privates = true
  locals = true
  patvars = true
}
