/*
 * Ported from colorful-gdx - https://github.com/tommyettinger/colorful-gdx
 * Original authors: Tommy Ettinger
 * Licensed under the Apache License, Version 2.0
 *
 * Scala port copyright 2025-2026 Mateusz Kubuszok
 *
 * Covenant: full-port
 * Covenant-baseline-spec-pass: 0
 * Covenant-baseline-loc: 811
 * Covenant-baseline-methods: ABSINTHE,AIR_FORCE_BLUE,AMAZONITE,ANGEL_WING,APPLE_GREEN,APRICOT,AQUAMARINE,ARMY_GREEN,ARTICHOKE,ASPARAGUS,AVOCADO,BANANA_PUDDING,BEIGE,BLACK,BLACKLIGHT_GLOW,BLUE,BLUEBERRY,BLUE_EYE,BLUE_SMOKE,BLUE_STEEL,BOLOGNA,BOYSENBERRY,BRICK,BRIGHT_RED,BRONZE_SKIN_1,BRONZE_SKIN_2,BRONZE_SKIN_3,BRONZE_SKIN_4,BROWN_VELVET,BUBBLE,BUBBLEGUM_PINK,BUBBLE_GUM,BURNT_YELLOW,CALM_SKY,CARMINE,CEDAR_WOOD,CELADON,CELERY,CHARTREUSE,CHERRY_SYRUP,CHINCHILLA,CHIPPED_GRANITE,CLOUD,COAL_BLACK,COLD_IRON,CORNFLOWER_BLUE,CORN_SILK,COTTON_CANDY,CREAM,CRICKET,CYAN,DARK_GRAY,DARK_PINE,DARK_SKIN_1,DARK_SKIN_2,DARK_SKIN_3,DARK_TEAL,DEEP_JUNGLE,DEEP_PURPLE,DEEP_TEAL,DENIM_BLUE,DESERT_RAIN,DRAB_GREEN,DREARY_BLUE,DRIED_SAGE,DRIFTWOOD,DRY_BRUSH,DRY_PEPPER,DULL_AZURE,DULL_GREEN,DULL_VIOLET,DUN,DUSTY_GRAPE,DUSTY_GREEN,DUSTY_PINK,DUST_BUNNY,EARWAX,EGGPLANT,ELECTRIC_BLUE,EMBERS,EMERALD,EMINENCE,EUCALYPTUS,FADED_BLUE,FAWN,FEATHER_DOWN,FERN_GREEN,FLAMINGO,FLORAL_FOAM,FOREST_GLEN,FROG_GREEN,FRUIT_PUNCH,GARTER_SNAKE,GRAPE_LOLLIPOP,GRAPE_SODA,GRAPHITE,GRAY,GRAY_GREEN,GREEN,GREYHOUND,HAM,HELIOTROPE,HIDDEN_BLUE,HONEYDEW,HOSPITAL_GREEN,HOT_SAUCE,HUNTER_GREEN,INDIGO,INFECTION,IOLITE,IRIS,IRON,IVY_GREEN,JADE,JUICY_GRAPE,KELLY_GREEN,KOA,KYANITE,LAVENDER,LEAD,LIGHT_GRAY,LIGHT_SKIN_1,LIGHT_SKIN_2,LIGHT_SKIN_3,LIGHT_SKIN_4,LIGHT_SKIN_5,LIGHT_SKIN_6,LIGHT_SKIN_7,LIGHT_SKIN_8,LIGHT_SKIN_9,LILAC,LIST,LIZARD_SCALES,LURID_RED,MAGENTA,MAIDENHAIR_FERN,MALACHITE,MARSH,MAUVE,MEDIUM_PLUM,MEDIUM_TEAL,MILD_VIOLET,MINT_GREEN,MOSS_GREEN,MULBERRY,MUMMY_BROWN,MURK,MUSH,NAMED,NAVY_BLUE,NIGHTSHADE,NINJA,OCEAN_BLUE,OCHRE,OLD_ROSE,OLIVE_GREEN,OLIVE_OIL,ORANGE,ORCHID,PASTEL_SKY,PATINA,PEACH,PEAT_BOG,PEA_SOUP,PENCIL_YELLOW,PERIWINKLE,PINE_GREEN,PINK_LEMONADE,PINK_SKIN_1,PINK_SKIN_2,PINK_SKIN_3,PINK_SKIN_4,PINK_TUTU,PINK_VIOLET,PISTACHIO,PLATINUM,PLUM_JUICE,POLISHED_SAPPHIRE,PORK_CHOP,POWDER_BLUE,PRASE,PRUNE,PRUSSIAN_BLUE,PUCE,PURPLE,PURPLE_FREESIA,PUTTY,Palette,RASPBERRY,RAW_MEAT,RED,REDWOOD,REFRESHING_MIST,RIPE_PLUM,RIPPED_DENIM,ROBIN_EGG_BLUE,ROSE,ROSEATE_SPOONBILL,ROUGH_SAPPHIRE,ROYAL_BLUE,ROYAL_VIOLET,SAFFRON,SAGE_GREEN,SALMON,SCRIBE_INK,SEAFOAM,SEAL_BROWN,SEAWATER,SHADOW,SHARP_AZURE,SHINING_SKY,SHRIMP,SIENNA,SILVER,SILVER_GREEN,SILVER_PINK,SLATE_GRAY,SLOW_CREEK,SMOG,SOAP,SOFT_TEAL,SPACE_BLUE,SPEARMINT,SPRING_GREEN,STEAM,STRAW,STRONG_CYAN,STYGIAN_BLUE,SUBTLETY,SUDS,TAN,TARNISH,TAUPE,TAXICAB_YELLOW,TEA_ROSE,THICK_AMETHYST,THIN_AMETHYST,THISTLE,THULIAN_PINK,TRANSPARENT,TROPIC_MIST,TURQUOISE,TWILIGHT_CLOUD,TYRIAN_PURPLE,UMBER,VAPOR,VARISCITE,VARNISH,VIOLET,VIOLET_CUSHIONS,VIRIDIAN,WATERCOLOR_BLACK,WATERCOLOR_GRAY,WET_STONE,WHITE,WISTERIA,WOODLANDS,YELLOW,ZUCCHINI,appendToKnownColors,editKnownColors
 * Covenant-source-reference: com/github/tommyettinger/colorful/ipt/Palette.java
 * Covenant-verified: 2026-04-19
 *
 * upstream-commit: e4a5fd960eef746ca5aa826063432fb79666d74f
 */
package sge
package colorful
package ipt

import scala.collection.mutable

/** A palette of predefined colors as packed IPT floats, the kind [[ColorTools]] works with. You can access colors by their constant name, such as `OCEAN_BLUE`, by the [[NAMED]] map using
  * `NAMED.getOrElse("Ocean Blue", 0f)`, or by index in the list called [[LIST]].
  */
object Palette {

  /** Maps color names to packed float colors. */
  val NAMED: mutable.HashMap[String, Float] = mutable.HashMap.empty[String, Float]

  /** Lists packed float color values, in declaration order. */
  val LIST: mutable.ArrayBuffer[Float] = mutable.ArrayBuffer.empty[Float]

  val TRANSPARENT:       Float = java.lang.Float.intBitsToFloat(0x7f7f00)
  val BLACK:             Float = java.lang.Float.intBitsToFloat(0xfe7f7f00)
  val COAL_BLACK:        Float = java.lang.Float.intBitsToFloat(0xfe7f7f13)
  val SHADOW:            Float = java.lang.Float.intBitsToFloat(0xfe7f7f25)
  val GRAPHITE:          Float = java.lang.Float.intBitsToFloat(0xfe7f7f37)
  val DARK_GRAY:         Float = java.lang.Float.intBitsToFloat(0xfe7f7f49)
  val LEAD:              Float = java.lang.Float.intBitsToFloat(0xfe7f7f5b)
  val IRON:              Float = java.lang.Float.intBitsToFloat(0xfe7f7f6e)
  val GRAY:              Float = java.lang.Float.intBitsToFloat(0xfe7f7f80)
  val CHINCHILLA:        Float = java.lang.Float.intBitsToFloat(0xfe7f7f92)
  val GREYHOUND:         Float = java.lang.Float.intBitsToFloat(0xfe7f7fa4)
  val SILVER:            Float = java.lang.Float.intBitsToFloat(0xfe7f7fb6)
  val LIGHT_GRAY:        Float = java.lang.Float.intBitsToFloat(0xfe7f7fc9)
  val PLATINUM:          Float = java.lang.Float.intBitsToFloat(0xfe7f7fdb)
  val CLOUD:             Float = java.lang.Float.intBitsToFloat(0xfe7f7fed)
  val WHITE:             Float = java.lang.Float.intBitsToFloat(0xfe7f7fff)
  val SEAWATER:          Float = java.lang.Float.intBitsToFloat(0xfe6d5567)
  val HOSPITAL_GREEN:    Float = java.lang.Float.intBitsToFloat(0xfe6d54a7)
  val CYAN:              Float = java.lang.Float.intBitsToFloat(0xfe5a2acf)
  val BUBBLE:            Float = java.lang.Float.intBitsToFloat(0xfe766af3)
  val PERIWINKLE:        Float = java.lang.Float.intBitsToFloat(0xfe44839e)
  val BLUE:              Float = java.lang.Float.intBitsToFloat(0xfe07883b)
  val FADED_BLUE:        Float = java.lang.Float.intBitsToFloat(0xfe43835d)
  val OCEAN_BLUE:        Float = java.lang.Float.intBitsToFloat(0xfe43831e)
  val STYGIAN_BLUE:      Float = java.lang.Float.intBitsToFloat(0xfe60811e)
  val DEEP_PURPLE:       Float = java.lang.Float.intBitsToFloat(0xfe55ae36)
  val TYRIAN_PURPLE:     Float = java.lang.Float.intBitsToFloat(0xfe55ae75)
  val MAGENTA:           Float = java.lang.Float.intBitsToFloat(0xfe2fd968)
  val BUBBLEGUM_PINK:    Float = java.lang.Float.intBitsToFloat(0xfe55adb6)
  val PORK_CHOP:         Float = java.lang.Float.intBitsToFloat(0xfe8395cf)
  val RAW_MEAT:          Float = java.lang.Float.intBitsToFloat(0xfe91a999)
  val RED:               Float = java.lang.Float.intBitsToFloat(0xfea4d430)
  val PUTTY:             Float = java.lang.Float.intBitsToFloat(0xfe91aa57)
  val SIENNA:            Float = java.lang.Float.intBitsToFloat(0xfe91aa18)
  val SEAL_BROWN:        Float = java.lang.Float.intBitsToFloat(0xfe889520)
  val MUMMY_BROWN:       Float = java.lang.Float.intBitsToFloat(0xfea6923c)
  val FAWN:              Float = java.lang.Float.intBitsToFloat(0xfea6927c)
  val ORANGE:            Float = java.lang.Float.intBitsToFloat(0xfecda67a)
  val PEACH:             Float = java.lang.Float.intBitsToFloat(0xfea592bd)
  val CREAM:             Float = java.lang.Float.intBitsToFloat(0xfe9d7df0)
  val YELLOW:            Float = java.lang.Float.intBitsToFloat(0xfef776c4)
  val EARWAX:            Float = java.lang.Float.intBitsToFloat(0xfebb7ba1)
  val UMBER:             Float = java.lang.Float.intBitsToFloat(0xfebb7b61)
  val IVY_GREEN:         Float = java.lang.Float.intBitsToFloat(0xfea95049)
  val JADE:              Float = java.lang.Float.intBitsToFloat(0xfea95089)
  val GREEN:             Float = java.lang.Float.intBitsToFloat(0xfed32193)
  val CELADON:           Float = java.lang.Float.intBitsToFloat(0xfe9962dd)
  val PUCE:              Float = java.lang.Float.intBitsToFloat(0xfe7984b5)
  val BEIGE:             Float = java.lang.Float.intBitsToFloat(0xfe9389a9)
  val WET_STONE:         Float = java.lang.Float.intBitsToFloat(0xfe87809d)
  val SLOW_CREEK:        Float = java.lang.Float.intBitsToFloat(0xfe7c7890)
  val SLATE_GRAY:        Float = java.lang.Float.intBitsToFloat(0xfe7a787f)
  val LIGHT_SKIN_1:      Float = java.lang.Float.intBitsToFloat(0xfe88846e)
  val LIGHT_SKIN_2:      Float = java.lang.Float.intBitsToFloat(0xfe8c9171)
  val LIGHT_SKIN_3:      Float = java.lang.Float.intBitsToFloat(0xfe8c9784)
  val LIGHT_SKIN_4:      Float = java.lang.Float.intBitsToFloat(0xfe939692)
  val LIGHT_SKIN_5:      Float = java.lang.Float.intBitsToFloat(0xfe9795a1)
  val LIGHT_SKIN_6:      Float = java.lang.Float.intBitsToFloat(0xfe9694af)
  val LIGHT_SKIN_7:      Float = java.lang.Float.intBitsToFloat(0xfe9692bd)
  val LIGHT_SKIN_8:      Float = java.lang.Float.intBitsToFloat(0xfe918ecb)
  val LIGHT_SKIN_9:      Float = java.lang.Float.intBitsToFloat(0xfe8985e1)
  val DARK_SKIN_1:       Float = java.lang.Float.intBitsToFloat(0xfe838840)
  val DARK_SKIN_2:       Float = java.lang.Float.intBitsToFloat(0xfe899049)
  val DARK_SKIN_3:       Float = java.lang.Float.intBitsToFloat(0xfe879260)
  val PINK_SKIN_1:       Float = java.lang.Float.intBitsToFloat(0xfe87927e)
  val PINK_SKIN_2:       Float = java.lang.Float.intBitsToFloat(0xfe87929a)
  val PINK_SKIN_3:       Float = java.lang.Float.intBitsToFloat(0xfe8792b6)
  val PINK_SKIN_4:       Float = java.lang.Float.intBitsToFloat(0xfe818cdb)
  val BRONZE_SKIN_4:     Float = java.lang.Float.intBitsToFloat(0xfe9087c6)
  val BRONZE_SKIN_3:     Float = java.lang.Float.intBitsToFloat(0xfe998a9b)
  val BRONZE_SKIN_2:     Float = java.lang.Float.intBitsToFloat(0xfe908772)
  val BRONZE_SKIN_1:     Float = java.lang.Float.intBitsToFloat(0xfe908756)
  val TAUPE:             Float = java.lang.Float.intBitsToFloat(0xfe88832c)
  val DRAB_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe8d7e3a)
  val LIZARD_SCALES:     Float = java.lang.Float.intBitsToFloat(0xfe997d66)
  val CRICKET:           Float = java.lang.Float.intBitsToFloat(0xfe997d82)
  val OLIVE_OIL:         Float = java.lang.Float.intBitsToFloat(0xfea37c90)
  val DUN:               Float = java.lang.Float.intBitsToFloat(0xfe9f7da5)
  val CORN_SILK:         Float = java.lang.Float.intBitsToFloat(0xfe997dba)
  val TAN:               Float = java.lang.Float.intBitsToFloat(0xfe957dcf)
  val STRAW:             Float = java.lang.Float.intBitsToFloat(0xfe917ee4)
  val HONEYDEW:          Float = java.lang.Float.intBitsToFloat(0xfe9574d1)
  val TARNISH:           Float = java.lang.Float.intBitsToFloat(0xfe9574b5)
  val PEA_SOUP:          Float = java.lang.Float.intBitsToFloat(0xfeaa6b9c)
  val MARSH:             Float = java.lang.Float.intBitsToFloat(0xfe95747d)
  val ASPARAGUS:         Float = java.lang.Float.intBitsToFloat(0xfe977067)
  val PEAT_BOG:          Float = java.lang.Float.intBitsToFloat(0xfe8c7b47)
  val DEEP_JUNGLE:       Float = java.lang.Float.intBitsToFloat(0xfe857d1a)
  val PINE_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe846f42)
  val OLIVE_GREEN:       Float = java.lang.Float.intBitsToFloat(0xfe88754b)
  val GRAY_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe86785c)
  val MAIDENHAIR_FERN:   Float = java.lang.Float.intBitsToFloat(0xfe8b6b5f)
  val KELLY_GREEN:       Float = java.lang.Float.intBitsToFloat(0xfe916a77)
  val DUSTY_GREEN:       Float = java.lang.Float.intBitsToFloat(0xfe916a93)
  val GARTER_SNAKE:      Float = java.lang.Float.intBitsToFloat(0xfe8f5ea0)
  val SILVER_GREEN:      Float = java.lang.Float.intBitsToFloat(0xfe916aaf)
  val PISTACHIO:         Float = java.lang.Float.intBitsToFloat(0xfe916bc1)
  val ANGEL_WING:        Float = java.lang.Float.intBitsToFloat(0xfe7b77f4)
  val SAGE_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe886adb)
  val DRIED_SAGE:        Float = java.lang.Float.intBitsToFloat(0xfe856bd1)
  val ARTICHOKE:         Float = java.lang.Float.intBitsToFloat(0xfe8a6fa3)
  val VIRIDIAN:          Float = java.lang.Float.intBitsToFloat(0xfe876f6d)
  val FLORAL_FOAM:       Float = java.lang.Float.intBitsToFloat(0xfe836050)
  val HUNTER_GREEN:      Float = java.lang.Float.intBitsToFloat(0xfe827a28)
  val DARK_TEAL:         Float = java.lang.Float.intBitsToFloat(0xfe78753c)
  val KYANITE:           Float = java.lang.Float.intBitsToFloat(0xfe776c68)
  val SPEARMINT:         Float = java.lang.Float.intBitsToFloat(0xfe75679e)
  val AMAZONITE:         Float = java.lang.Float.intBitsToFloat(0xfe776cbc)
  val PASTEL_SKY:        Float = java.lang.Float.intBitsToFloat(0xfe776cd8)
  val AQUAMARINE:        Float = java.lang.Float.intBitsToFloat(0xfe7971e9)
  val DUST_BUNNY:        Float = java.lang.Float.intBitsToFloat(0xfe6e79d5)
  val PATINA:            Float = java.lang.Float.intBitsToFloat(0xfe6e77c8)
  val CHIPPED_GRANITE:   Float = java.lang.Float.intBitsToFloat(0xfe6c7bbe)
  val BLUE_SMOKE:        Float = java.lang.Float.intBitsToFloat(0xfe6e77ac)
  val AIR_FORCE_BLUE:    Float = java.lang.Float.intBitsToFloat(0xfe5d6e91)
  val COLD_IRON:         Float = java.lang.Float.intBitsToFloat(0xfe6e7774)
  val DREARY_BLUE:       Float = java.lang.Float.intBitsToFloat(0xfe6e7758)
  val MURK:              Float = java.lang.Float.intBitsToFloat(0xfe747c1c)
  val NINJA:             Float = java.lang.Float.intBitsToFloat(0xfe728026)
  val WATERCOLOR_BLACK:  Float = java.lang.Float.intBitsToFloat(0xfe728042)
  val IOLITE:            Float = java.lang.Float.intBitsToFloat(0xfe6b8053)
  val BOYSENBERRY:       Float = java.lang.Float.intBitsToFloat(0xfe658164)
  val WATERCOLOR_GRAY:   Float = java.lang.Float.intBitsToFloat(0xfe63837d)
  val BLUE_STEEL:        Float = java.lang.Float.intBitsToFloat(0xfe57828a)
  val TWILIGHT_CLOUD:    Float = java.lang.Float.intBitsToFloat(0xfe65819c)
  val SMOG:              Float = java.lang.Float.intBitsToFloat(0xfe6581b8)
  val TROPIC_MIST:       Float = java.lang.Float.intBitsToFloat(0xfe6f7ddf)
  val FEATHER_DOWN:      Float = java.lang.Float.intBitsToFloat(0xfe7280ea)
  val MILD_VIOLET:       Float = java.lang.Float.intBitsToFloat(0xfe698aa1)
  val VIOLET_CUSHIONS:   Float = java.lang.Float.intBitsToFloat(0xfe52967c)
  val DULL_VIOLET:       Float = java.lang.Float.intBitsToFloat(0xfe698a69)
  val ROYAL_VIOLET:      Float = java.lang.Float.intBitsToFloat(0xfe698a4d)
  val EMINENCE:          Float = java.lang.Float.intBitsToFloat(0xfe77882e)
  val PRUNE:             Float = java.lang.Float.intBitsToFloat(0xfe78863a)
  val DUSTY_GRAPE:       Float = java.lang.Float.intBitsToFloat(0xfe6f9155)
  val PINK_VIOLET:       Float = java.lang.Float.intBitsToFloat(0xfe6d946f)
  val RIPE_PLUM:         Float = java.lang.Float.intBitsToFloat(0xfe639e7b)
  val MAUVE:             Float = java.lang.Float.intBitsToFloat(0xfe6d948b)
  val HAM:               Float = java.lang.Float.intBitsToFloat(0xfe6f96c4)
  val COTTON_CANDY:      Float = java.lang.Float.intBitsToFloat(0xfe788ce8)
  val SILVER_PINK:       Float = java.lang.Float.intBitsToFloat(0xfe7689d3)
  val TEA_ROSE:          Float = java.lang.Float.intBitsToFloat(0xfe798dc6)
  val OLD_ROSE:          Float = java.lang.Float.intBitsToFloat(0xfe7992b1)
  val DUSTY_PINK:        Float = java.lang.Float.intBitsToFloat(0xfe7393a3)
  val ROSEATE_SPOONBILL: Float = java.lang.Float.intBitsToFloat(0xfe799993)
  val THULIAN_PINK:      Float = java.lang.Float.intBitsToFloat(0xfe74a47b)
  val BROWN_VELVET:      Float = java.lang.Float.intBitsToFloat(0xfe7d8b32)
  val NIGHTSHADE:        Float = java.lang.Float.intBitsToFloat(0xfe7d891e)
  val SCRIBE_INK:        Float = java.lang.Float.intBitsToFloat(0xfe7a8a14)
  val VARNISH:           Float = java.lang.Float.intBitsToFloat(0xfe888c1e)
  val CEDAR_WOOD:        Float = java.lang.Float.intBitsToFloat(0xfe959720)
  val HOT_SAUCE:         Float = java.lang.Float.intBitsToFloat(0xfe98af2d)
  val LURID_RED:         Float = java.lang.Float.intBitsToFloat(0xfea1bd40)
  val BRICK:             Float = java.lang.Float.intBitsToFloat(0xfe96ab69)
  val BRIGHT_RED:        Float = java.lang.Float.intBitsToFloat(0xfeb2bf55)
  val EMBERS:            Float = java.lang.Float.intBitsToFloat(0xfea8b26e)
  val SALMON:            Float = java.lang.Float.intBitsToFloat(0xfe95b480)
  val TAXICAB_YELLOW:    Float = java.lang.Float.intBitsToFloat(0xfec98da7)
  val APRICOT:           Float = java.lang.Float.intBitsToFloat(0xfebd9a9e)
  val BURNT_YELLOW:      Float = java.lang.Float.intBitsToFloat(0xfeca8e86)
  val DRY_PEPPER:        Float = java.lang.Float.intBitsToFloat(0xfebea06b)
  val REDWOOD:           Float = java.lang.Float.intBitsToFloat(0xfeb69a56)
  val KOA:               Float = java.lang.Float.intBitsToFloat(0xfeac994b)
  val OCHRE:             Float = java.lang.Float.intBitsToFloat(0xfe948d34)
  val DULL_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfea07e40)
  val ARMY_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfead7c4b)
  val DRIFTWOOD:         Float = java.lang.Float.intBitsToFloat(0xfe938279)
  val DRY_BRUSH:         Float = java.lang.Float.intBitsToFloat(0xfec88276)
  val MUSH:              Float = java.lang.Float.intBitsToFloat(0xfece798a)
  val BANANA_PUDDING:    Float = java.lang.Float.intBitsToFloat(0xfebb81bc)
  val SAFFRON:           Float = java.lang.Float.intBitsToFloat(0xfee286af)
  val PENCIL_YELLOW:     Float = java.lang.Float.intBitsToFloat(0xfecd81c9)
  val CHARTREUSE:        Float = java.lang.Float.intBitsToFloat(0xfed166c8)
  val ABSINTHE:          Float = java.lang.Float.intBitsToFloat(0xfec35db8)
  val INFECTION:         Float = java.lang.Float.intBitsToFloat(0xfed161a1)
  val FROG_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfecf5c8a)
  val AVOCADO:           Float = java.lang.Float.intBitsToFloat(0xfec36576)
  val WOODLANDS:         Float = java.lang.Float.intBitsToFloat(0xfea26b50)
  val DARK_PINE:         Float = java.lang.Float.intBitsToFloat(0xfe937927)
  val MOSS_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe977030)
  val FERN_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe99623a)
  val FOREST_GLEN:       Float = java.lang.Float.intBitsToFloat(0xfeb14f5c)
  val MALACHITE:         Float = java.lang.Float.intBitsToFloat(0xfec23380)
  val APPLE_GREEN:       Float = java.lang.Float.intBitsToFloat(0xfec9318b)
  val CELERY:            Float = java.lang.Float.intBitsToFloat(0xfeae4fc6)
  val MINT_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfeae43ae)
  val EMERALD:           Float = java.lang.Float.intBitsToFloat(0xfeb63776)
  val PRASE:             Float = java.lang.Float.intBitsToFloat(0xfe95417b)
  val EUCALYPTUS:        Float = java.lang.Float.intBitsToFloat(0xfe8c5768)
  val ZUCCHINI:          Float = java.lang.Float.intBitsToFloat(0xfe7c722f)
  val SOFT_TEAL:         Float = java.lang.Float.intBitsToFloat(0xfe775179)
  val MEDIUM_TEAL:       Float = java.lang.Float.intBitsToFloat(0xfe7c3e94)
  val SPRING_GREEN:      Float = java.lang.Float.intBitsToFloat(0xfe963199)
  val TURQUOISE:         Float = java.lang.Float.intBitsToFloat(0xfe833db7)
  val SEAFOAM:           Float = java.lang.Float.intBitsToFloat(0xfe8d3bc4)
  val VARISCITE:         Float = java.lang.Float.intBitsToFloat(0xfe814bd7)
  val REFRESHING_MIST:   Float = java.lang.Float.intBitsToFloat(0xfe6962df)
  val SHINING_SKY:       Float = java.lang.Float.intBitsToFloat(0xfe5e4fd0)
  val STEAM:             Float = java.lang.Float.intBitsToFloat(0xfe6662cc)
  val ROBIN_EGG_BLUE:    Float = java.lang.Float.intBitsToFloat(0xfe6537b3)
  val DENIM_BLUE:        Float = java.lang.Float.intBitsToFloat(0xfe4c5291)
  val DEEP_TEAL:         Float = java.lang.Float.intBitsToFloat(0xfe72634a)
  val NAVY_BLUE:         Float = java.lang.Float.intBitsToFloat(0xfe6a7931)
  val BLUEBERRY:         Float = java.lang.Float.intBitsToFloat(0xfe587440)
  val PRUSSIAN_BLUE:     Float = java.lang.Float.intBitsToFloat(0xfe4e694f)
  val DESERT_RAIN:       Float = java.lang.Float.intBitsToFloat(0xfe607066)
  val ELECTRIC_BLUE:     Float = java.lang.Float.intBitsToFloat(0xfe266969)
  val HIDDEN_BLUE:       Float = java.lang.Float.intBitsToFloat(0xfe4c666e)
  val DULL_AZURE:        Float = java.lang.Float.intBitsToFloat(0xfe44667f)
  val RIPPED_DENIM:      Float = java.lang.Float.intBitsToFloat(0xfe666f9c)
  val CALM_SKY:          Float = java.lang.Float.intBitsToFloat(0xfe4764a8)
  val VAPOR:             Float = java.lang.Float.intBitsToFloat(0xfe5577bc)
  val POWDER_BLUE:       Float = java.lang.Float.intBitsToFloat(0xfe545dbe)
  val SUDS:              Float = java.lang.Float.intBitsToFloat(0xfe6183c9)
  val STRONG_CYAN:       Float = java.lang.Float.intBitsToFloat(0xfe4541aa)
  val SHARP_AZURE:       Float = java.lang.Float.intBitsToFloat(0xfe315985)
  val BLUE_EYE:          Float = java.lang.Float.intBitsToFloat(0xfe557185)
  val SUBTLETY:          Float = java.lang.Float.intBitsToFloat(0xfe43878e)
  val ROUGH_SAPPHIRE:    Float = java.lang.Float.intBitsToFloat(0xfe2f7f7d)
  val IRIS:              Float = java.lang.Float.intBitsToFloat(0xfe2e9071)
  val CORNFLOWER_BLUE:   Float = java.lang.Float.intBitsToFloat(0xfe288567)
  val POLISHED_SAPPHIRE: Float = java.lang.Float.intBitsToFloat(0xfe248146)
  val ROYAL_BLUE:        Float = java.lang.Float.intBitsToFloat(0xfe2b8035)
  val INDIGO:            Float = java.lang.Float.intBitsToFloat(0xfe448a32)
  val SPACE_BLUE:        Float = java.lang.Float.intBitsToFloat(0xfe6a7926)
  val THICK_AMETHYST:    Float = java.lang.Float.intBitsToFloat(0xfe3d9a41)
  val JUICY_GRAPE:       Float = java.lang.Float.intBitsToFloat(0xfe30a04c)
  val BLACKLIGHT_GLOW:   Float = java.lang.Float.intBitsToFloat(0xfe40a167)
  val PURPLE_FREESIA:    Float = java.lang.Float.intBitsToFloat(0xfe33a47f)
  val THIN_AMETHYST:     Float = java.lang.Float.intBitsToFloat(0xfe19b254)
  val ORCHID:            Float = java.lang.Float.intBitsToFloat(0xfe42a398)
  val LAVENDER:          Float = java.lang.Float.intBitsToFloat(0xfe5190b2)
  val LILAC:             Float = java.lang.Float.intBitsToFloat(0xfe5c93c3)
  val SOAP:              Float = java.lang.Float.intBitsToFloat(0xfe6888d4)
  val PINK_TUTU:         Float = java.lang.Float.intBitsToFloat(0xfe6d92dc)
  val THISTLE:           Float = java.lang.Float.intBitsToFloat(0xfe4eaaa9)
  val HELIOTROPE:        Float = java.lang.Float.intBitsToFloat(0xfe46bf9b)
  val PURPLE:            Float = java.lang.Float.intBitsToFloat(0xfe3fc470)
  val WISTERIA:          Float = java.lang.Float.intBitsToFloat(0xfe2fb877)
  val MEDIUM_PLUM:       Float = java.lang.Float.intBitsToFloat(0xfe43bf5b)
  val VIOLET:            Float = java.lang.Float.intBitsToFloat(0xfe40ad52)
  val GRAPE_LOLLIPOP:    Float = java.lang.Float.intBitsToFloat(0xfe5a983c)
  val MULBERRY:          Float = java.lang.Float.intBitsToFloat(0xfe659d36)
  val GRAPE_SODA:        Float = java.lang.Float.intBitsToFloat(0xfe5a9823)
  val EGGPLANT:          Float = java.lang.Float.intBitsToFloat(0xfe688e20)
  val CHERRY_SYRUP:      Float = java.lang.Float.intBitsToFloat(0xfe79942b)
  val PLUM_JUICE:        Float = java.lang.Float.intBitsToFloat(0xfe61b04b)
  val FRUIT_PUNCH:       Float = java.lang.Float.intBitsToFloat(0xfe63c642)
  val BUBBLE_GUM:        Float = java.lang.Float.intBitsToFloat(0xfe64bd8b)
  val PINK_LEMONADE:     Float = java.lang.Float.intBitsToFloat(0xfe69b49b)
  val SHRIMP:            Float = java.lang.Float.intBitsToFloat(0xfe809eb7)
  val FLAMINGO:          Float = java.lang.Float.intBitsToFloat(0xfe74c372)
  val ROSE:              Float = java.lang.Float.intBitsToFloat(0xfe71c559)
  val CARMINE:           Float = java.lang.Float.intBitsToFloat(0xfe84ba3a)
  val BOLOGNA:           Float = java.lang.Float.intBitsToFloat(0xfe82a14d)
  val RASPBERRY:         Float = java.lang.Float.intBitsToFloat(0xfe80aa34)

  // Register all colors
  locally {
    NAMED.put("Transparent", java.lang.Float.intBitsToFloat(0x7f7f00))
    LIST += java.lang.Float.intBitsToFloat(0x7f7f00)
    NAMED.put("Black", java.lang.Float.intBitsToFloat(0xfe7f7f00))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7f00)
    NAMED.put("Coal Black", java.lang.Float.intBitsToFloat(0xfe7f7f13))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7f13)
    NAMED.put("Shadow", java.lang.Float.intBitsToFloat(0xfe7f7f25))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7f25)
    NAMED.put("Graphite", java.lang.Float.intBitsToFloat(0xfe7f7f37))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7f37)
    NAMED.put("Dark Gray", java.lang.Float.intBitsToFloat(0xfe7f7f49))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7f49)
    NAMED.put("Lead", java.lang.Float.intBitsToFloat(0xfe7f7f5b))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7f5b)
    NAMED.put("Iron", java.lang.Float.intBitsToFloat(0xfe7f7f6e))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7f6e)
    NAMED.put("Gray", java.lang.Float.intBitsToFloat(0xfe7f7f80))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7f80)
    NAMED.put("Chinchilla", java.lang.Float.intBitsToFloat(0xfe7f7f92))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7f92)
    NAMED.put("Greyhound", java.lang.Float.intBitsToFloat(0xfe7f7fa4))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7fa4)
    NAMED.put("Silver", java.lang.Float.intBitsToFloat(0xfe7f7fb6))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7fb6)
    NAMED.put("Light Gray", java.lang.Float.intBitsToFloat(0xfe7f7fc9))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7fc9)
    NAMED.put("Platinum", java.lang.Float.intBitsToFloat(0xfe7f7fdb))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7fdb)
    NAMED.put("Cloud", java.lang.Float.intBitsToFloat(0xfe7f7fed))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7fed)
    NAMED.put("White", java.lang.Float.intBitsToFloat(0xfe7f7fff))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7fff)
    NAMED.put("Seawater", java.lang.Float.intBitsToFloat(0xfe6d5567))
    LIST += java.lang.Float.intBitsToFloat(0xfe6d5567)
    NAMED.put("Hospital Green", java.lang.Float.intBitsToFloat(0xfe6d54a7))
    LIST += java.lang.Float.intBitsToFloat(0xfe6d54a7)
    NAMED.put("Cyan", java.lang.Float.intBitsToFloat(0xfe5a2acf))
    LIST += java.lang.Float.intBitsToFloat(0xfe5a2acf)
    NAMED.put("Bubble", java.lang.Float.intBitsToFloat(0xfe766af3))
    LIST += java.lang.Float.intBitsToFloat(0xfe766af3)
    NAMED.put("Periwinkle", java.lang.Float.intBitsToFloat(0xfe44839e))
    LIST += java.lang.Float.intBitsToFloat(0xfe44839e)
    NAMED.put("Blue", java.lang.Float.intBitsToFloat(0xfe07883b))
    LIST += java.lang.Float.intBitsToFloat(0xfe07883b)
    NAMED.put("Faded Blue", java.lang.Float.intBitsToFloat(0xfe43835d))
    LIST += java.lang.Float.intBitsToFloat(0xfe43835d)
    NAMED.put("Ocean Blue", java.lang.Float.intBitsToFloat(0xfe43831e))
    LIST += java.lang.Float.intBitsToFloat(0xfe43831e)
    NAMED.put("Stygian Blue", java.lang.Float.intBitsToFloat(0xfe60811e))
    LIST += java.lang.Float.intBitsToFloat(0xfe60811e)
    NAMED.put("Deep Purple", java.lang.Float.intBitsToFloat(0xfe55ae36))
    LIST += java.lang.Float.intBitsToFloat(0xfe55ae36)
    NAMED.put("Tyrian Purple", java.lang.Float.intBitsToFloat(0xfe55ae75))
    LIST += java.lang.Float.intBitsToFloat(0xfe55ae75)
    NAMED.put("Magenta", java.lang.Float.intBitsToFloat(0xfe2fd968))
    LIST += java.lang.Float.intBitsToFloat(0xfe2fd968)
    NAMED.put("Bubblegum Pink", java.lang.Float.intBitsToFloat(0xfe55adb6))
    LIST += java.lang.Float.intBitsToFloat(0xfe55adb6)
    NAMED.put("Pork Chop", java.lang.Float.intBitsToFloat(0xfe8395cf))
    LIST += java.lang.Float.intBitsToFloat(0xfe8395cf)
    NAMED.put("Raw Meat", java.lang.Float.intBitsToFloat(0xfe91a999))
    LIST += java.lang.Float.intBitsToFloat(0xfe91a999)
    NAMED.put("Red", java.lang.Float.intBitsToFloat(0xfea4d430))
    LIST += java.lang.Float.intBitsToFloat(0xfea4d430)
    NAMED.put("Putty", java.lang.Float.intBitsToFloat(0xfe91aa57))
    LIST += java.lang.Float.intBitsToFloat(0xfe91aa57)
    NAMED.put("Sienna", java.lang.Float.intBitsToFloat(0xfe91aa18))
    LIST += java.lang.Float.intBitsToFloat(0xfe91aa18)
    NAMED.put("Seal Brown", java.lang.Float.intBitsToFloat(0xfe889520))
    LIST += java.lang.Float.intBitsToFloat(0xfe889520)
    NAMED.put("Mummy Brown", java.lang.Float.intBitsToFloat(0xfea6923c))
    LIST += java.lang.Float.intBitsToFloat(0xfea6923c)
    NAMED.put("Fawn", java.lang.Float.intBitsToFloat(0xfea6927c))
    LIST += java.lang.Float.intBitsToFloat(0xfea6927c)
    NAMED.put("Orange", java.lang.Float.intBitsToFloat(0xfecda67a))
    LIST += java.lang.Float.intBitsToFloat(0xfecda67a)
    NAMED.put("Peach", java.lang.Float.intBitsToFloat(0xfea592bd))
    LIST += java.lang.Float.intBitsToFloat(0xfea592bd)
    NAMED.put("Cream", java.lang.Float.intBitsToFloat(0xfe9d7df0))
    LIST += java.lang.Float.intBitsToFloat(0xfe9d7df0)
    NAMED.put("Yellow", java.lang.Float.intBitsToFloat(0xfef776c4))
    LIST += java.lang.Float.intBitsToFloat(0xfef776c4)
    NAMED.put("Earwax", java.lang.Float.intBitsToFloat(0xfebb7ba1))
    LIST += java.lang.Float.intBitsToFloat(0xfebb7ba1)
    NAMED.put("Umber", java.lang.Float.intBitsToFloat(0xfebb7b61))
    LIST += java.lang.Float.intBitsToFloat(0xfebb7b61)
    NAMED.put("Ivy Green", java.lang.Float.intBitsToFloat(0xfea95049))
    LIST += java.lang.Float.intBitsToFloat(0xfea95049)
    NAMED.put("Jade", java.lang.Float.intBitsToFloat(0xfea95089))
    LIST += java.lang.Float.intBitsToFloat(0xfea95089)
    NAMED.put("Green", java.lang.Float.intBitsToFloat(0xfed32193))
    LIST += java.lang.Float.intBitsToFloat(0xfed32193)
    NAMED.put("Celadon", java.lang.Float.intBitsToFloat(0xfe9962dd))
    LIST += java.lang.Float.intBitsToFloat(0xfe9962dd)
    NAMED.put("Puce", java.lang.Float.intBitsToFloat(0xfe7984b5))
    LIST += java.lang.Float.intBitsToFloat(0xfe7984b5)
    NAMED.put("Beige", java.lang.Float.intBitsToFloat(0xfe9389a9))
    LIST += java.lang.Float.intBitsToFloat(0xfe9389a9)
    NAMED.put("Wet Stone", java.lang.Float.intBitsToFloat(0xfe87809d))
    LIST += java.lang.Float.intBitsToFloat(0xfe87809d)
    NAMED.put("Slow Creek", java.lang.Float.intBitsToFloat(0xfe7c7890))
    LIST += java.lang.Float.intBitsToFloat(0xfe7c7890)
    NAMED.put("Slate Gray", java.lang.Float.intBitsToFloat(0xfe7a787f))
    LIST += java.lang.Float.intBitsToFloat(0xfe7a787f)
    NAMED.put("Light Skin 1", java.lang.Float.intBitsToFloat(0xfe88846e))
    LIST += java.lang.Float.intBitsToFloat(0xfe88846e)
    NAMED.put("Light Skin 2", java.lang.Float.intBitsToFloat(0xfe8c9171))
    LIST += java.lang.Float.intBitsToFloat(0xfe8c9171)
    NAMED.put("Light Skin 3", java.lang.Float.intBitsToFloat(0xfe8c9784))
    LIST += java.lang.Float.intBitsToFloat(0xfe8c9784)
    NAMED.put("Light Skin 4", java.lang.Float.intBitsToFloat(0xfe939692))
    LIST += java.lang.Float.intBitsToFloat(0xfe939692)
    NAMED.put("Light Skin 5", java.lang.Float.intBitsToFloat(0xfe9795a1))
    LIST += java.lang.Float.intBitsToFloat(0xfe9795a1)
    NAMED.put("Light Skin 6", java.lang.Float.intBitsToFloat(0xfe9694af))
    LIST += java.lang.Float.intBitsToFloat(0xfe9694af)
    NAMED.put("Light Skin 7", java.lang.Float.intBitsToFloat(0xfe9692bd))
    LIST += java.lang.Float.intBitsToFloat(0xfe9692bd)
    NAMED.put("Light Skin 8", java.lang.Float.intBitsToFloat(0xfe918ecb))
    LIST += java.lang.Float.intBitsToFloat(0xfe918ecb)
    NAMED.put("Light Skin 9", java.lang.Float.intBitsToFloat(0xfe8985e1))
    LIST += java.lang.Float.intBitsToFloat(0xfe8985e1)
    NAMED.put("Dark Skin 1", java.lang.Float.intBitsToFloat(0xfe838840))
    LIST += java.lang.Float.intBitsToFloat(0xfe838840)
    NAMED.put("Dark Skin 2", java.lang.Float.intBitsToFloat(0xfe899049))
    LIST += java.lang.Float.intBitsToFloat(0xfe899049)
    NAMED.put("Dark Skin 3", java.lang.Float.intBitsToFloat(0xfe879260))
    LIST += java.lang.Float.intBitsToFloat(0xfe879260)
    NAMED.put("Pink Skin 1", java.lang.Float.intBitsToFloat(0xfe87927e))
    LIST += java.lang.Float.intBitsToFloat(0xfe87927e)
    NAMED.put("Pink Skin 2", java.lang.Float.intBitsToFloat(0xfe87929a))
    LIST += java.lang.Float.intBitsToFloat(0xfe87929a)
    NAMED.put("Pink Skin 3", java.lang.Float.intBitsToFloat(0xfe8792b6))
    LIST += java.lang.Float.intBitsToFloat(0xfe8792b6)
    NAMED.put("Pink Skin 4", java.lang.Float.intBitsToFloat(0xfe818cdb))
    LIST += java.lang.Float.intBitsToFloat(0xfe818cdb)
    NAMED.put("Bronze Skin 4", java.lang.Float.intBitsToFloat(0xfe9087c6))
    LIST += java.lang.Float.intBitsToFloat(0xfe9087c6)
    NAMED.put("Bronze Skin 3", java.lang.Float.intBitsToFloat(0xfe998a9b))
    LIST += java.lang.Float.intBitsToFloat(0xfe998a9b)
    NAMED.put("Bronze Skin 2", java.lang.Float.intBitsToFloat(0xfe908772))
    LIST += java.lang.Float.intBitsToFloat(0xfe908772)
    NAMED.put("Bronze Skin 1", java.lang.Float.intBitsToFloat(0xfe908756))
    LIST += java.lang.Float.intBitsToFloat(0xfe908756)
    NAMED.put("Taupe", java.lang.Float.intBitsToFloat(0xfe88832c))
    LIST += java.lang.Float.intBitsToFloat(0xfe88832c)
    NAMED.put("Drab Green", java.lang.Float.intBitsToFloat(0xfe8d7e3a))
    LIST += java.lang.Float.intBitsToFloat(0xfe8d7e3a)
    NAMED.put("Lizard Scales", java.lang.Float.intBitsToFloat(0xfe997d66))
    LIST += java.lang.Float.intBitsToFloat(0xfe997d66)
    NAMED.put("Cricket", java.lang.Float.intBitsToFloat(0xfe997d82))
    LIST += java.lang.Float.intBitsToFloat(0xfe997d82)
    NAMED.put("Olive Oil", java.lang.Float.intBitsToFloat(0xfea37c90))
    LIST += java.lang.Float.intBitsToFloat(0xfea37c90)
    NAMED.put("Dun", java.lang.Float.intBitsToFloat(0xfe9f7da5))
    LIST += java.lang.Float.intBitsToFloat(0xfe9f7da5)
    NAMED.put("Corn Silk", java.lang.Float.intBitsToFloat(0xfe997dba))
    LIST += java.lang.Float.intBitsToFloat(0xfe997dba)
    NAMED.put("Tan", java.lang.Float.intBitsToFloat(0xfe957dcf))
    LIST += java.lang.Float.intBitsToFloat(0xfe957dcf)
    NAMED.put("Straw", java.lang.Float.intBitsToFloat(0xfe917ee4))
    LIST += java.lang.Float.intBitsToFloat(0xfe917ee4)
    NAMED.put("Honeydew", java.lang.Float.intBitsToFloat(0xfe9574d1))
    LIST += java.lang.Float.intBitsToFloat(0xfe9574d1)
    NAMED.put("Tarnish", java.lang.Float.intBitsToFloat(0xfe9574b5))
    LIST += java.lang.Float.intBitsToFloat(0xfe9574b5)
    NAMED.put("Pea Soup", java.lang.Float.intBitsToFloat(0xfeaa6b9c))
    LIST += java.lang.Float.intBitsToFloat(0xfeaa6b9c)
    NAMED.put("Marsh", java.lang.Float.intBitsToFloat(0xfe95747d))
    LIST += java.lang.Float.intBitsToFloat(0xfe95747d)
    NAMED.put("Asparagus", java.lang.Float.intBitsToFloat(0xfe977067))
    LIST += java.lang.Float.intBitsToFloat(0xfe977067)
    NAMED.put("Peat Bog", java.lang.Float.intBitsToFloat(0xfe8c7b47))
    LIST += java.lang.Float.intBitsToFloat(0xfe8c7b47)
    NAMED.put("Deep Jungle", java.lang.Float.intBitsToFloat(0xfe857d1a))
    LIST += java.lang.Float.intBitsToFloat(0xfe857d1a)
    NAMED.put("Pine Green", java.lang.Float.intBitsToFloat(0xfe846f42))
    LIST += java.lang.Float.intBitsToFloat(0xfe846f42)
    NAMED.put("Olive Green", java.lang.Float.intBitsToFloat(0xfe88754b))
    LIST += java.lang.Float.intBitsToFloat(0xfe88754b)
    NAMED.put("Gray Green", java.lang.Float.intBitsToFloat(0xfe86785c))
    LIST += java.lang.Float.intBitsToFloat(0xfe86785c)
    NAMED.put("Maidenhair Fern", java.lang.Float.intBitsToFloat(0xfe8b6b5f))
    LIST += java.lang.Float.intBitsToFloat(0xfe8b6b5f)
    NAMED.put("Kelly Green", java.lang.Float.intBitsToFloat(0xfe916a77))
    LIST += java.lang.Float.intBitsToFloat(0xfe916a77)
    NAMED.put("Dusty Green", java.lang.Float.intBitsToFloat(0xfe916a93))
    LIST += java.lang.Float.intBitsToFloat(0xfe916a93)
    NAMED.put("Garter Snake", java.lang.Float.intBitsToFloat(0xfe8f5ea0))
    LIST += java.lang.Float.intBitsToFloat(0xfe8f5ea0)
    NAMED.put("Silver Green", java.lang.Float.intBitsToFloat(0xfe916aaf))
    LIST += java.lang.Float.intBitsToFloat(0xfe916aaf)
    NAMED.put("Pistachio", java.lang.Float.intBitsToFloat(0xfe916bc1))
    LIST += java.lang.Float.intBitsToFloat(0xfe916bc1)
    NAMED.put("Angel Wing", java.lang.Float.intBitsToFloat(0xfe7b77f4))
    LIST += java.lang.Float.intBitsToFloat(0xfe7b77f4)
    NAMED.put("Sage Green", java.lang.Float.intBitsToFloat(0xfe886adb))
    LIST += java.lang.Float.intBitsToFloat(0xfe886adb)
    NAMED.put("Dried Sage", java.lang.Float.intBitsToFloat(0xfe856bd1))
    LIST += java.lang.Float.intBitsToFloat(0xfe856bd1)
    NAMED.put("Artichoke", java.lang.Float.intBitsToFloat(0xfe8a6fa3))
    LIST += java.lang.Float.intBitsToFloat(0xfe8a6fa3)
    NAMED.put("Viridian", java.lang.Float.intBitsToFloat(0xfe876f6d))
    LIST += java.lang.Float.intBitsToFloat(0xfe876f6d)
    NAMED.put("Floral Foam", java.lang.Float.intBitsToFloat(0xfe836050))
    LIST += java.lang.Float.intBitsToFloat(0xfe836050)
    NAMED.put("Hunter Green", java.lang.Float.intBitsToFloat(0xfe827a28))
    LIST += java.lang.Float.intBitsToFloat(0xfe827a28)
    NAMED.put("Dark Teal", java.lang.Float.intBitsToFloat(0xfe78753c))
    LIST += java.lang.Float.intBitsToFloat(0xfe78753c)
    NAMED.put("Kyanite", java.lang.Float.intBitsToFloat(0xfe776c68))
    LIST += java.lang.Float.intBitsToFloat(0xfe776c68)
    NAMED.put("Spearmint", java.lang.Float.intBitsToFloat(0xfe75679e))
    LIST += java.lang.Float.intBitsToFloat(0xfe75679e)
    NAMED.put("Amazonite", java.lang.Float.intBitsToFloat(0xfe776cbc))
    LIST += java.lang.Float.intBitsToFloat(0xfe776cbc)
    NAMED.put("Pastel Sky", java.lang.Float.intBitsToFloat(0xfe776cd8))
    LIST += java.lang.Float.intBitsToFloat(0xfe776cd8)
    NAMED.put("Aquamarine", java.lang.Float.intBitsToFloat(0xfe7971e9))
    LIST += java.lang.Float.intBitsToFloat(0xfe7971e9)
    NAMED.put("Dust Bunny", java.lang.Float.intBitsToFloat(0xfe6e79d5))
    LIST += java.lang.Float.intBitsToFloat(0xfe6e79d5)
    NAMED.put("Patina", java.lang.Float.intBitsToFloat(0xfe6e77c8))
    LIST += java.lang.Float.intBitsToFloat(0xfe6e77c8)
    NAMED.put("Chipped Granite", java.lang.Float.intBitsToFloat(0xfe6c7bbe))
    LIST += java.lang.Float.intBitsToFloat(0xfe6c7bbe)
    NAMED.put("Blue Smoke", java.lang.Float.intBitsToFloat(0xfe6e77ac))
    LIST += java.lang.Float.intBitsToFloat(0xfe6e77ac)
    NAMED.put("Air Force Blue", java.lang.Float.intBitsToFloat(0xfe5d6e91))
    LIST += java.lang.Float.intBitsToFloat(0xfe5d6e91)
    NAMED.put("Cold Iron", java.lang.Float.intBitsToFloat(0xfe6e7774))
    LIST += java.lang.Float.intBitsToFloat(0xfe6e7774)
    NAMED.put("Dreary Blue", java.lang.Float.intBitsToFloat(0xfe6e7758))
    LIST += java.lang.Float.intBitsToFloat(0xfe6e7758)
    NAMED.put("Murk", java.lang.Float.intBitsToFloat(0xfe747c1c))
    LIST += java.lang.Float.intBitsToFloat(0xfe747c1c)
    NAMED.put("Ninja", java.lang.Float.intBitsToFloat(0xfe728026))
    LIST += java.lang.Float.intBitsToFloat(0xfe728026)
    NAMED.put("Watercolor Black", java.lang.Float.intBitsToFloat(0xfe728042))
    LIST += java.lang.Float.intBitsToFloat(0xfe728042)
    NAMED.put("Iolite", java.lang.Float.intBitsToFloat(0xfe6b8053))
    LIST += java.lang.Float.intBitsToFloat(0xfe6b8053)
    NAMED.put("Boysenberry", java.lang.Float.intBitsToFloat(0xfe658164))
    LIST += java.lang.Float.intBitsToFloat(0xfe658164)
    NAMED.put("Watercolor Gray", java.lang.Float.intBitsToFloat(0xfe63837d))
    LIST += java.lang.Float.intBitsToFloat(0xfe63837d)
    NAMED.put("Blue Steel", java.lang.Float.intBitsToFloat(0xfe57828a))
    LIST += java.lang.Float.intBitsToFloat(0xfe57828a)
    NAMED.put("Twilight Cloud", java.lang.Float.intBitsToFloat(0xfe65819c))
    LIST += java.lang.Float.intBitsToFloat(0xfe65819c)
    NAMED.put("Smog", java.lang.Float.intBitsToFloat(0xfe6581b8))
    LIST += java.lang.Float.intBitsToFloat(0xfe6581b8)
    NAMED.put("Tropic Mist", java.lang.Float.intBitsToFloat(0xfe6f7ddf))
    LIST += java.lang.Float.intBitsToFloat(0xfe6f7ddf)
    NAMED.put("Feather Down", java.lang.Float.intBitsToFloat(0xfe7280ea))
    LIST += java.lang.Float.intBitsToFloat(0xfe7280ea)
    NAMED.put("Mild Violet", java.lang.Float.intBitsToFloat(0xfe698aa1))
    LIST += java.lang.Float.intBitsToFloat(0xfe698aa1)
    NAMED.put("Violet Cushions", java.lang.Float.intBitsToFloat(0xfe52967c))
    LIST += java.lang.Float.intBitsToFloat(0xfe52967c)
    NAMED.put("Dull Violet", java.lang.Float.intBitsToFloat(0xfe698a69))
    LIST += java.lang.Float.intBitsToFloat(0xfe698a69)
    NAMED.put("Royal Violet", java.lang.Float.intBitsToFloat(0xfe698a4d))
    LIST += java.lang.Float.intBitsToFloat(0xfe698a4d)
    NAMED.put("Eminence", java.lang.Float.intBitsToFloat(0xfe77882e))
    LIST += java.lang.Float.intBitsToFloat(0xfe77882e)
    NAMED.put("Prune", java.lang.Float.intBitsToFloat(0xfe78863a))
    LIST += java.lang.Float.intBitsToFloat(0xfe78863a)
    NAMED.put("Dusty Grape", java.lang.Float.intBitsToFloat(0xfe6f9155))
    LIST += java.lang.Float.intBitsToFloat(0xfe6f9155)
    NAMED.put("Pink Violet", java.lang.Float.intBitsToFloat(0xfe6d946f))
    LIST += java.lang.Float.intBitsToFloat(0xfe6d946f)
    NAMED.put("Ripe Plum", java.lang.Float.intBitsToFloat(0xfe639e7b))
    LIST += java.lang.Float.intBitsToFloat(0xfe639e7b)
    NAMED.put("Mauve", java.lang.Float.intBitsToFloat(0xfe6d948b))
    LIST += java.lang.Float.intBitsToFloat(0xfe6d948b)
    NAMED.put("Ham", java.lang.Float.intBitsToFloat(0xfe6f96c4))
    LIST += java.lang.Float.intBitsToFloat(0xfe6f96c4)
    NAMED.put("Cotton Candy", java.lang.Float.intBitsToFloat(0xfe788ce8))
    LIST += java.lang.Float.intBitsToFloat(0xfe788ce8)
    NAMED.put("Silver Pink", java.lang.Float.intBitsToFloat(0xfe7689d3))
    LIST += java.lang.Float.intBitsToFloat(0xfe7689d3)
    NAMED.put("Tea Rose", java.lang.Float.intBitsToFloat(0xfe798dc6))
    LIST += java.lang.Float.intBitsToFloat(0xfe798dc6)
    NAMED.put("Old Rose", java.lang.Float.intBitsToFloat(0xfe7992b1))
    LIST += java.lang.Float.intBitsToFloat(0xfe7992b1)
    NAMED.put("Dusty Pink", java.lang.Float.intBitsToFloat(0xfe7393a3))
    LIST += java.lang.Float.intBitsToFloat(0xfe7393a3)
    NAMED.put("Roseate Spoonbill", java.lang.Float.intBitsToFloat(0xfe799993))
    LIST += java.lang.Float.intBitsToFloat(0xfe799993)
    NAMED.put("Thulian Pink", java.lang.Float.intBitsToFloat(0xfe74a47b))
    LIST += java.lang.Float.intBitsToFloat(0xfe74a47b)
    NAMED.put("Brown Velvet", java.lang.Float.intBitsToFloat(0xfe7d8b32))
    LIST += java.lang.Float.intBitsToFloat(0xfe7d8b32)
    NAMED.put("Nightshade", java.lang.Float.intBitsToFloat(0xfe7d891e))
    LIST += java.lang.Float.intBitsToFloat(0xfe7d891e)
    NAMED.put("Scribe Ink", java.lang.Float.intBitsToFloat(0xfe7a8a14))
    LIST += java.lang.Float.intBitsToFloat(0xfe7a8a14)
    NAMED.put("Varnish", java.lang.Float.intBitsToFloat(0xfe888c1e))
    LIST += java.lang.Float.intBitsToFloat(0xfe888c1e)
    NAMED.put("Cedar Wood", java.lang.Float.intBitsToFloat(0xfe959720))
    LIST += java.lang.Float.intBitsToFloat(0xfe959720)
    NAMED.put("Hot Sauce", java.lang.Float.intBitsToFloat(0xfe98af2d))
    LIST += java.lang.Float.intBitsToFloat(0xfe98af2d)
    NAMED.put("Lurid Red", java.lang.Float.intBitsToFloat(0xfea1bd40))
    LIST += java.lang.Float.intBitsToFloat(0xfea1bd40)
    NAMED.put("Brick", java.lang.Float.intBitsToFloat(0xfe96ab69))
    LIST += java.lang.Float.intBitsToFloat(0xfe96ab69)
    NAMED.put("Bright Red", java.lang.Float.intBitsToFloat(0xfeb2bf55))
    LIST += java.lang.Float.intBitsToFloat(0xfeb2bf55)
    NAMED.put("Embers", java.lang.Float.intBitsToFloat(0xfea8b26e))
    LIST += java.lang.Float.intBitsToFloat(0xfea8b26e)
    NAMED.put("Salmon", java.lang.Float.intBitsToFloat(0xfe95b480))
    LIST += java.lang.Float.intBitsToFloat(0xfe95b480)
    NAMED.put("Taxicab Yellow", java.lang.Float.intBitsToFloat(0xfec98da7))
    LIST += java.lang.Float.intBitsToFloat(0xfec98da7)
    NAMED.put("Apricot", java.lang.Float.intBitsToFloat(0xfebd9a9e))
    LIST += java.lang.Float.intBitsToFloat(0xfebd9a9e)
    NAMED.put("Burnt Yellow", java.lang.Float.intBitsToFloat(0xfeca8e86))
    LIST += java.lang.Float.intBitsToFloat(0xfeca8e86)
    NAMED.put("Dry Pepper", java.lang.Float.intBitsToFloat(0xfebea06b))
    LIST += java.lang.Float.intBitsToFloat(0xfebea06b)
    NAMED.put("Redwood", java.lang.Float.intBitsToFloat(0xfeb69a56))
    LIST += java.lang.Float.intBitsToFloat(0xfeb69a56)
    NAMED.put("Koa", java.lang.Float.intBitsToFloat(0xfeac994b))
    LIST += java.lang.Float.intBitsToFloat(0xfeac994b)
    NAMED.put("Ochre", java.lang.Float.intBitsToFloat(0xfe948d34))
    LIST += java.lang.Float.intBitsToFloat(0xfe948d34)
    NAMED.put("Dull Green", java.lang.Float.intBitsToFloat(0xfea07e40))
    LIST += java.lang.Float.intBitsToFloat(0xfea07e40)
    NAMED.put("Army Green", java.lang.Float.intBitsToFloat(0xfead7c4b))
    LIST += java.lang.Float.intBitsToFloat(0xfead7c4b)
    NAMED.put("Driftwood", java.lang.Float.intBitsToFloat(0xfe938279))
    LIST += java.lang.Float.intBitsToFloat(0xfe938279)
    NAMED.put("Dry Brush", java.lang.Float.intBitsToFloat(0xfec88276))
    LIST += java.lang.Float.intBitsToFloat(0xfec88276)
    NAMED.put("Mush", java.lang.Float.intBitsToFloat(0xfece798a))
    LIST += java.lang.Float.intBitsToFloat(0xfece798a)
    NAMED.put("Banana Pudding", java.lang.Float.intBitsToFloat(0xfebb81bc))
    LIST += java.lang.Float.intBitsToFloat(0xfebb81bc)
    NAMED.put("Saffron", java.lang.Float.intBitsToFloat(0xfee286af))
    LIST += java.lang.Float.intBitsToFloat(0xfee286af)
    NAMED.put("Pencil Yellow", java.lang.Float.intBitsToFloat(0xfecd81c9))
    LIST += java.lang.Float.intBitsToFloat(0xfecd81c9)
    NAMED.put("Chartreuse", java.lang.Float.intBitsToFloat(0xfed166c8))
    LIST += java.lang.Float.intBitsToFloat(0xfed166c8)
    NAMED.put("Absinthe", java.lang.Float.intBitsToFloat(0xfec35db8))
    LIST += java.lang.Float.intBitsToFloat(0xfec35db8)
    NAMED.put("Infection", java.lang.Float.intBitsToFloat(0xfed161a1))
    LIST += java.lang.Float.intBitsToFloat(0xfed161a1)
    NAMED.put("Frog Green", java.lang.Float.intBitsToFloat(0xfecf5c8a))
    LIST += java.lang.Float.intBitsToFloat(0xfecf5c8a)
    NAMED.put("Avocado", java.lang.Float.intBitsToFloat(0xfec36576))
    LIST += java.lang.Float.intBitsToFloat(0xfec36576)
    NAMED.put("Woodlands", java.lang.Float.intBitsToFloat(0xfea26b50))
    LIST += java.lang.Float.intBitsToFloat(0xfea26b50)
    NAMED.put("Dark Pine", java.lang.Float.intBitsToFloat(0xfe937927))
    LIST += java.lang.Float.intBitsToFloat(0xfe937927)
    NAMED.put("Moss Green", java.lang.Float.intBitsToFloat(0xfe977030))
    LIST += java.lang.Float.intBitsToFloat(0xfe977030)
    NAMED.put("Fern Green", java.lang.Float.intBitsToFloat(0xfe99623a))
    LIST += java.lang.Float.intBitsToFloat(0xfe99623a)
    NAMED.put("Forest Glen", java.lang.Float.intBitsToFloat(0xfeb14f5c))
    LIST += java.lang.Float.intBitsToFloat(0xfeb14f5c)
    NAMED.put("Malachite", java.lang.Float.intBitsToFloat(0xfec23380))
    LIST += java.lang.Float.intBitsToFloat(0xfec23380)
    NAMED.put("Apple Green", java.lang.Float.intBitsToFloat(0xfec9318b))
    LIST += java.lang.Float.intBitsToFloat(0xfec9318b)
    NAMED.put("Celery", java.lang.Float.intBitsToFloat(0xfeae4fc6))
    LIST += java.lang.Float.intBitsToFloat(0xfeae4fc6)
    NAMED.put("Mint Green", java.lang.Float.intBitsToFloat(0xfeae43ae))
    LIST += java.lang.Float.intBitsToFloat(0xfeae43ae)
    NAMED.put("Emerald", java.lang.Float.intBitsToFloat(0xfeb63776))
    LIST += java.lang.Float.intBitsToFloat(0xfeb63776)
    NAMED.put("Prase", java.lang.Float.intBitsToFloat(0xfe95417b))
    LIST += java.lang.Float.intBitsToFloat(0xfe95417b)
    NAMED.put("Eucalyptus", java.lang.Float.intBitsToFloat(0xfe8c5768))
    LIST += java.lang.Float.intBitsToFloat(0xfe8c5768)
    NAMED.put("Zucchini", java.lang.Float.intBitsToFloat(0xfe7c722f))
    LIST += java.lang.Float.intBitsToFloat(0xfe7c722f)
    NAMED.put("Soft Teal", java.lang.Float.intBitsToFloat(0xfe775179))
    LIST += java.lang.Float.intBitsToFloat(0xfe775179)
    NAMED.put("Medium Teal", java.lang.Float.intBitsToFloat(0xfe7c3e94))
    LIST += java.lang.Float.intBitsToFloat(0xfe7c3e94)
    NAMED.put("Spring Green", java.lang.Float.intBitsToFloat(0xfe963199))
    LIST += java.lang.Float.intBitsToFloat(0xfe963199)
    NAMED.put("Turquoise", java.lang.Float.intBitsToFloat(0xfe833db7))
    LIST += java.lang.Float.intBitsToFloat(0xfe833db7)
    NAMED.put("Seafoam", java.lang.Float.intBitsToFloat(0xfe8d3bc4))
    LIST += java.lang.Float.intBitsToFloat(0xfe8d3bc4)
    NAMED.put("Variscite", java.lang.Float.intBitsToFloat(0xfe814bd7))
    LIST += java.lang.Float.intBitsToFloat(0xfe814bd7)
    NAMED.put("Refreshing Mist", java.lang.Float.intBitsToFloat(0xfe6962df))
    LIST += java.lang.Float.intBitsToFloat(0xfe6962df)
    NAMED.put("Shining Sky", java.lang.Float.intBitsToFloat(0xfe5e4fd0))
    LIST += java.lang.Float.intBitsToFloat(0xfe5e4fd0)
    NAMED.put("Steam", java.lang.Float.intBitsToFloat(0xfe6662cc))
    LIST += java.lang.Float.intBitsToFloat(0xfe6662cc)
    NAMED.put("Robin Egg Blue", java.lang.Float.intBitsToFloat(0xfe6537b3))
    LIST += java.lang.Float.intBitsToFloat(0xfe6537b3)
    NAMED.put("Denim Blue", java.lang.Float.intBitsToFloat(0xfe4c5291))
    LIST += java.lang.Float.intBitsToFloat(0xfe4c5291)
    NAMED.put("Deep Teal", java.lang.Float.intBitsToFloat(0xfe72634a))
    LIST += java.lang.Float.intBitsToFloat(0xfe72634a)
    NAMED.put("Navy Blue", java.lang.Float.intBitsToFloat(0xfe6a7931))
    LIST += java.lang.Float.intBitsToFloat(0xfe6a7931)
    NAMED.put("Blueberry", java.lang.Float.intBitsToFloat(0xfe587440))
    LIST += java.lang.Float.intBitsToFloat(0xfe587440)
    NAMED.put("Prussian Blue", java.lang.Float.intBitsToFloat(0xfe4e694f))
    LIST += java.lang.Float.intBitsToFloat(0xfe4e694f)
    NAMED.put("Desert Rain", java.lang.Float.intBitsToFloat(0xfe607066))
    LIST += java.lang.Float.intBitsToFloat(0xfe607066)
    NAMED.put("Electric Blue", java.lang.Float.intBitsToFloat(0xfe266969))
    LIST += java.lang.Float.intBitsToFloat(0xfe266969)
    NAMED.put("Hidden Blue", java.lang.Float.intBitsToFloat(0xfe4c666e))
    LIST += java.lang.Float.intBitsToFloat(0xfe4c666e)
    NAMED.put("Dull Azure", java.lang.Float.intBitsToFloat(0xfe44667f))
    LIST += java.lang.Float.intBitsToFloat(0xfe44667f)
    NAMED.put("Ripped Denim", java.lang.Float.intBitsToFloat(0xfe666f9c))
    LIST += java.lang.Float.intBitsToFloat(0xfe666f9c)
    NAMED.put("Calm Sky", java.lang.Float.intBitsToFloat(0xfe4764a8))
    LIST += java.lang.Float.intBitsToFloat(0xfe4764a8)
    NAMED.put("Vapor", java.lang.Float.intBitsToFloat(0xfe5577bc))
    LIST += java.lang.Float.intBitsToFloat(0xfe5577bc)
    NAMED.put("Powder Blue", java.lang.Float.intBitsToFloat(0xfe545dbe))
    LIST += java.lang.Float.intBitsToFloat(0xfe545dbe)
    NAMED.put("Suds", java.lang.Float.intBitsToFloat(0xfe6183c9))
    LIST += java.lang.Float.intBitsToFloat(0xfe6183c9)
    NAMED.put("Strong Cyan", java.lang.Float.intBitsToFloat(0xfe4541aa))
    LIST += java.lang.Float.intBitsToFloat(0xfe4541aa)
    NAMED.put("Sharp Azure", java.lang.Float.intBitsToFloat(0xfe315985))
    LIST += java.lang.Float.intBitsToFloat(0xfe315985)
    NAMED.put("Blue Eye", java.lang.Float.intBitsToFloat(0xfe557185))
    LIST += java.lang.Float.intBitsToFloat(0xfe557185)
    NAMED.put("Subtlety", java.lang.Float.intBitsToFloat(0xfe43878e))
    LIST += java.lang.Float.intBitsToFloat(0xfe43878e)
    NAMED.put("Rough Sapphire", java.lang.Float.intBitsToFloat(0xfe2f7f7d))
    LIST += java.lang.Float.intBitsToFloat(0xfe2f7f7d)
    NAMED.put("Iris", java.lang.Float.intBitsToFloat(0xfe2e9071))
    LIST += java.lang.Float.intBitsToFloat(0xfe2e9071)
    NAMED.put("Cornflower Blue", java.lang.Float.intBitsToFloat(0xfe288567))
    LIST += java.lang.Float.intBitsToFloat(0xfe288567)
    NAMED.put("Polished Sapphire", java.lang.Float.intBitsToFloat(0xfe248146))
    LIST += java.lang.Float.intBitsToFloat(0xfe248146)
    NAMED.put("Royal Blue", java.lang.Float.intBitsToFloat(0xfe2b8035))
    LIST += java.lang.Float.intBitsToFloat(0xfe2b8035)
    NAMED.put("Indigo", java.lang.Float.intBitsToFloat(0xfe448a32))
    LIST += java.lang.Float.intBitsToFloat(0xfe448a32)
    NAMED.put("Space Blue", java.lang.Float.intBitsToFloat(0xfe6a7926))
    LIST += java.lang.Float.intBitsToFloat(0xfe6a7926)
    NAMED.put("Thick Amethyst", java.lang.Float.intBitsToFloat(0xfe3d9a41))
    LIST += java.lang.Float.intBitsToFloat(0xfe3d9a41)
    NAMED.put("Juicy Grape", java.lang.Float.intBitsToFloat(0xfe30a04c))
    LIST += java.lang.Float.intBitsToFloat(0xfe30a04c)
    NAMED.put("Blacklight Glow", java.lang.Float.intBitsToFloat(0xfe40a167))
    LIST += java.lang.Float.intBitsToFloat(0xfe40a167)
    NAMED.put("Purple Freesia", java.lang.Float.intBitsToFloat(0xfe33a47f))
    LIST += java.lang.Float.intBitsToFloat(0xfe33a47f)
    NAMED.put("Thin Amethyst", java.lang.Float.intBitsToFloat(0xfe19b254))
    LIST += java.lang.Float.intBitsToFloat(0xfe19b254)
    NAMED.put("Orchid", java.lang.Float.intBitsToFloat(0xfe42a398))
    LIST += java.lang.Float.intBitsToFloat(0xfe42a398)
    NAMED.put("Lavender", java.lang.Float.intBitsToFloat(0xfe5190b2))
    LIST += java.lang.Float.intBitsToFloat(0xfe5190b2)
    NAMED.put("Lilac", java.lang.Float.intBitsToFloat(0xfe5c93c3))
    LIST += java.lang.Float.intBitsToFloat(0xfe5c93c3)
    NAMED.put("Soap", java.lang.Float.intBitsToFloat(0xfe6888d4))
    LIST += java.lang.Float.intBitsToFloat(0xfe6888d4)
    NAMED.put("Pink Tutu", java.lang.Float.intBitsToFloat(0xfe6d92dc))
    LIST += java.lang.Float.intBitsToFloat(0xfe6d92dc)
    NAMED.put("Thistle", java.lang.Float.intBitsToFloat(0xfe4eaaa9))
    LIST += java.lang.Float.intBitsToFloat(0xfe4eaaa9)
    NAMED.put("Heliotrope", java.lang.Float.intBitsToFloat(0xfe46bf9b))
    LIST += java.lang.Float.intBitsToFloat(0xfe46bf9b)
    NAMED.put("Purple", java.lang.Float.intBitsToFloat(0xfe3fc470))
    LIST += java.lang.Float.intBitsToFloat(0xfe3fc470)
    NAMED.put("Wisteria", java.lang.Float.intBitsToFloat(0xfe2fb877))
    LIST += java.lang.Float.intBitsToFloat(0xfe2fb877)
    NAMED.put("Medium Plum", java.lang.Float.intBitsToFloat(0xfe43bf5b))
    LIST += java.lang.Float.intBitsToFloat(0xfe43bf5b)
    NAMED.put("Violet", java.lang.Float.intBitsToFloat(0xfe40ad52))
    LIST += java.lang.Float.intBitsToFloat(0xfe40ad52)
    NAMED.put("Grape Lollipop", java.lang.Float.intBitsToFloat(0xfe5a983c))
    LIST += java.lang.Float.intBitsToFloat(0xfe5a983c)
    NAMED.put("Mulberry", java.lang.Float.intBitsToFloat(0xfe659d36))
    LIST += java.lang.Float.intBitsToFloat(0xfe659d36)
    NAMED.put("Grape Soda", java.lang.Float.intBitsToFloat(0xfe5a9823))
    LIST += java.lang.Float.intBitsToFloat(0xfe5a9823)
    NAMED.put("Eggplant", java.lang.Float.intBitsToFloat(0xfe688e20))
    LIST += java.lang.Float.intBitsToFloat(0xfe688e20)
    NAMED.put("Cherry Syrup", java.lang.Float.intBitsToFloat(0xfe79942b))
    LIST += java.lang.Float.intBitsToFloat(0xfe79942b)
    NAMED.put("Plum Juice", java.lang.Float.intBitsToFloat(0xfe61b04b))
    LIST += java.lang.Float.intBitsToFloat(0xfe61b04b)
    NAMED.put("Fruit Punch", java.lang.Float.intBitsToFloat(0xfe63c642))
    LIST += java.lang.Float.intBitsToFloat(0xfe63c642)
    NAMED.put("Bubble Gum", java.lang.Float.intBitsToFloat(0xfe64bd8b))
    LIST += java.lang.Float.intBitsToFloat(0xfe64bd8b)
    NAMED.put("Pink Lemonade", java.lang.Float.intBitsToFloat(0xfe69b49b))
    LIST += java.lang.Float.intBitsToFloat(0xfe69b49b)
    NAMED.put("Shrimp", java.lang.Float.intBitsToFloat(0xfe809eb7))
    LIST += java.lang.Float.intBitsToFloat(0xfe809eb7)
    NAMED.put("Flamingo", java.lang.Float.intBitsToFloat(0xfe74c372))
    LIST += java.lang.Float.intBitsToFloat(0xfe74c372)
    NAMED.put("Rose", java.lang.Float.intBitsToFloat(0xfe71c559))
    LIST += java.lang.Float.intBitsToFloat(0xfe71c559)
    NAMED.put("Carmine", java.lang.Float.intBitsToFloat(0xfe84ba3a))
    LIST += java.lang.Float.intBitsToFloat(0xfe84ba3a)
    NAMED.put("Bologna", java.lang.Float.intBitsToFloat(0xfe82a14d))
    LIST += java.lang.Float.intBitsToFloat(0xfe82a14d)
    NAMED.put("Raspberry", java.lang.Float.intBitsToFloat(0xfe80aa34))
    LIST += java.lang.Float.intBitsToFloat(0xfe80aa34)
  }

  /** Converts existing Color entries in [[sge.graphics.Colors]] from RGBA to IPT format. */
  def editKnownColors(): Unit =
    for (c <- sge.graphics.Colors.colors.values) {
      val f = ColorTools.fromColor(c)
      c.set(ColorTools.intensity(f), ColorTools.protan(f), ColorTools.tritan(f), c.a)
    }

  /** Appends IPT-compatible Color instances to the map in [[sge.graphics.Colors]]. */
  def appendToKnownColors(): Unit =
    for ((key, value) <- NAMED) {
      val f = value
      sge.graphics.Colors.put(key, new sge.graphics.Color(ColorTools.intensity(f), ColorTools.protan(f), ColorTools.tritan(f), ColorTools.alpha(f)))
    }
}
