/*
 * Ported from colorful-gdx - https://github.com/tommyettinger/colorful-gdx
 * Original authors: Tommy Ettinger
 * Licensed under the Apache License, Version 2.0
 *
 * Scala port copyright 2025-2026 Mateusz Kubuszok
 *
 * Covenant: full-port
 * Covenant-baseline-spec-pass: 0
 * Covenant-baseline-loc: 811
 * Covenant-baseline-methods: ABSINTHE,AIR_FORCE_BLUE,AMAZONITE,ANGEL_WING,APPLE_GREEN,APRICOT,AQUAMARINE,ARMY_GREEN,ARTICHOKE,ASPARAGUS,AVOCADO,BANANA_PUDDING,BEIGE,BLACK,BLACKLIGHT_GLOW,BLUE,BLUEBERRY,BLUE_EYE,BLUE_SMOKE,BLUE_STEEL,BOLOGNA,BOYSENBERRY,BRICK,BRIGHT_RED,BRONZE_SKIN_1,BRONZE_SKIN_2,BRONZE_SKIN_3,BRONZE_SKIN_4,BROWN_VELVET,BUBBLE,BUBBLEGUM_PINK,BUBBLE_GUM,BURNT_YELLOW,CALM_SKY,CARMINE,CEDAR_WOOD,CELADON,CELERY,CHARTREUSE,CHERRY_SYRUP,CHINCHILLA,CHIPPED_GRANITE,CLOUD,COAL_BLACK,COLD_IRON,CORNFLOWER_BLUE,CORN_SILK,COTTON_CANDY,CREAM,CRICKET,CYAN,DARK_GRAY,DARK_PINE,DARK_SKIN_1,DARK_SKIN_2,DARK_SKIN_3,DARK_TEAL,DEEP_JUNGLE,DEEP_PURPLE,DEEP_TEAL,DENIM_BLUE,DESERT_RAIN,DRAB_GREEN,DREARY_BLUE,DRIED_SAGE,DRIFTWOOD,DRY_BRUSH,DRY_PEPPER,DULL_AZURE,DULL_GREEN,DULL_VIOLET,DUN,DUSTY_GRAPE,DUSTY_GREEN,DUSTY_PINK,DUST_BUNNY,EARWAX,EGGPLANT,ELECTRIC_BLUE,EMBERS,EMERALD,EMINENCE,EUCALYPTUS,FADED_BLUE,FAWN,FEATHER_DOWN,FERN_GREEN,FLAMINGO,FLORAL_FOAM,FOREST_GLEN,FROG_GREEN,FRUIT_PUNCH,GARTER_SNAKE,GRAPE_LOLLIPOP,GRAPE_SODA,GRAPHITE,GRAY,GRAY_GREEN,GREEN,GREYHOUND,HAM,HELIOTROPE,HIDDEN_BLUE,HONEYDEW,HOSPITAL_GREEN,HOT_SAUCE,HUNTER_GREEN,INDIGO,INFECTION,IOLITE,IRIS,IRON,IVY_GREEN,JADE,JUICY_GRAPE,KELLY_GREEN,KOA,KYANITE,LAVENDER,LEAD,LIGHT_GRAY,LIGHT_SKIN_1,LIGHT_SKIN_2,LIGHT_SKIN_3,LIGHT_SKIN_4,LIGHT_SKIN_5,LIGHT_SKIN_6,LIGHT_SKIN_7,LIGHT_SKIN_8,LIGHT_SKIN_9,LILAC,LIST,LIZARD_SCALES,LURID_RED,MAGENTA,MAIDENHAIR_FERN,MALACHITE,MARSH,MAUVE,MEDIUM_PLUM,MEDIUM_TEAL,MILD_VIOLET,MINT_GREEN,MOSS_GREEN,MULBERRY,MUMMY_BROWN,MURK,MUSH,NAMED,NAVY_BLUE,NIGHTSHADE,NINJA,OCEAN_BLUE,OCHRE,OLD_ROSE,OLIVE_GREEN,OLIVE_OIL,ORANGE,ORCHID,PASTEL_SKY,PATINA,PEACH,PEAT_BOG,PEA_SOUP,PENCIL_YELLOW,PERIWINKLE,PINE_GREEN,PINK_LEMONADE,PINK_SKIN_1,PINK_SKIN_2,PINK_SKIN_3,PINK_SKIN_4,PINK_TUTU,PINK_VIOLET,PISTACHIO,PLATINUM,PLUM_JUICE,POLISHED_SAPPHIRE,PORK_CHOP,POWDER_BLUE,PRASE,PRUNE,PRUSSIAN_BLUE,PUCE,PURPLE,PURPLE_FREESIA,PUTTY,Palette,RASPBERRY,RAW_MEAT,RED,REDWOOD,REFRESHING_MIST,RIPE_PLUM,RIPPED_DENIM,ROBIN_EGG_BLUE,ROSE,ROSEATE_SPOONBILL,ROUGH_SAPPHIRE,ROYAL_BLUE,ROYAL_VIOLET,SAFFRON,SAGE_GREEN,SALMON,SCRIBE_INK,SEAFOAM,SEAL_BROWN,SEAWATER,SHADOW,SHARP_AZURE,SHINING_SKY,SHRIMP,SIENNA,SILVER,SILVER_GREEN,SILVER_PINK,SLATE_GRAY,SLOW_CREEK,SMOG,SOAP,SOFT_TEAL,SPACE_BLUE,SPEARMINT,SPRING_GREEN,STEAM,STRAW,STRONG_CYAN,STYGIAN_BLUE,SUBTLETY,SUDS,TAN,TARNISH,TAUPE,TAXICAB_YELLOW,TEA_ROSE,THICK_AMETHYST,THIN_AMETHYST,THISTLE,THULIAN_PINK,TRANSPARENT,TROPIC_MIST,TURQUOISE,TWILIGHT_CLOUD,TYRIAN_PURPLE,UMBER,VAPOR,VARISCITE,VARNISH,VIOLET,VIOLET_CUSHIONS,VIRIDIAN,WATERCOLOR_BLACK,WATERCOLOR_GRAY,WET_STONE,WHITE,WISTERIA,WOODLANDS,YELLOW,ZUCCHINI,appendToKnownColors,editKnownColors
 * Covenant-source-reference: com/github/tommyettinger/colorful/hsluv/Palette.java
 * Covenant-verified: 2026-04-19
 */
package sge
package colorful
package hsluv

import scala.collection.mutable

/** A palette of predefined colors as packed HSLUV floats, the kind [[ColorTools]] works with. You can access colors by their constant name, such as `OCEAN_BLUE`, by the [[NAMED]] map using
  * `NAMED.getOrElse("Ocean Blue", 0f)`, or by index in the list called [[LIST]].
  */
object Palette {

  /** Maps color names to packed float colors. */
  val NAMED: mutable.HashMap[String, Float] = mutable.HashMap.empty[String, Float]

  /** Lists packed float color values, in declaration order. */
  val LIST: mutable.ArrayBuffer[Float] = mutable.ArrayBuffer.empty[Float]

  val TRANSPARENT:       Float = java.lang.Float.intBitsToFloat(0x0)
  val BLACK:             Float = java.lang.Float.intBitsToFloat(0xfe000000)
  val COAL_BLACK:        Float = java.lang.Float.intBitsToFloat(0xfe0f0029)
  val SHADOW:            Float = java.lang.Float.intBitsToFloat(0xfe230029)
  val GRAPHITE:          Float = java.lang.Float.intBitsToFloat(0xfe360029)
  val DARK_GRAY:         Float = java.lang.Float.intBitsToFloat(0xfe490029)
  val LEAD:              Float = java.lang.Float.intBitsToFloat(0xfe5b0029)
  val IRON:              Float = java.lang.Float.intBitsToFloat(0xfe6e0029)
  val GRAY:              Float = java.lang.Float.intBitsToFloat(0xfe800029)
  val CHINCHILLA:        Float = java.lang.Float.intBitsToFloat(0xfe910029)
  val GREYHOUND:         Float = java.lang.Float.intBitsToFloat(0xfea30029)
  val SILVER:            Float = java.lang.Float.intBitsToFloat(0xfeb50029)
  val LIGHT_GRAY:        Float = java.lang.Float.intBitsToFloat(0xfec80029)
  val PLATINUM:          Float = java.lang.Float.intBitsToFloat(0xfedb0029)
  val CLOUD:             Float = java.lang.Float.intBitsToFloat(0xfeed0029)
  val WHITE:             Float = java.lang.Float.intBitsToFloat(0xfeff0029)
  val SEAWATER:          Float = java.lang.Float.intBitsToFloat(0xfe71ff88)
  val HOSPITAL_GREEN:    Float = java.lang.Float.intBitsToFloat(0xfeaded88)
  val CYAN:              Float = java.lang.Float.intBitsToFloat(0xfee5ff88)
  val BUBBLE:            Float = java.lang.Float.intBitsToFloat(0xfef3db88)
  val PERIWINKLE:        Float = java.lang.Float.intBitsToFloat(0xfe8fedbd)
  val BLUE:              Float = java.lang.Float.intBitsToFloat(0xfe4cffbd)
  val FADED_BLUE:        Float = java.lang.Float.intBitsToFloat(0xfe51babd)
  val OCEAN_BLUE:        Float = java.lang.Float.intBitsToFloat(0xfe1fffbd)
  val STYGIAN_BLUE:      Float = java.lang.Float.intBitsToFloat(0xfe17c3bd)
  val DEEP_PURPLE:       Float = java.lang.Float.intBitsToFloat(0xfe45ffda)
  val TYRIAN_PURPLE:     Float = java.lang.Float.intBitsToFloat(0xfe76dada)
  val MAGENTA:           Float = java.lang.Float.intBitsToFloat(0xfe8bffda)
  val BUBBLEGUM_PINK:    Float = java.lang.Float.intBitsToFloat(0xfeb0e6da)
  val PORK_CHOP:         Float = java.lang.Float.intBitsToFloat(0xfed0dc00)
  val RAW_MEAT:          Float = java.lang.Float.intBitsToFloat(0xfea6dc08)
  val RED:               Float = java.lang.Float.intBitsToFloat(0xfe7fff08)
  val PUTTY:             Float = java.lang.Float.intBitsToFloat(0xfe6cb208)
  val SIENNA:            Float = java.lang.Float.intBitsToFloat(0xfe3bff08)
  val SEAL_BROWN:        Float = java.lang.Float.intBitsToFloat(0xfe2abd08)
  val MUMMY_BROWN:       Float = java.lang.Float.intBitsToFloat(0xfe50ff16)
  val FAWN:              Float = java.lang.Float.intBitsToFloat(0xfe8cd71d)
  val ORANGE:            Float = java.lang.Float.intBitsToFloat(0xfea2ff15)
  val PEACH:             Float = java.lang.Float.intBitsToFloat(0xfecbd820)
  val CREAM:             Float = java.lang.Float.intBitsToFloat(0xfefbd83d)
  val YELLOW:            Float = java.lang.Float.intBitsToFloat(0xfef7ff3d)
  val EARWAX:            Float = java.lang.Float.intBitsToFloat(0xfeb9ea3d)
  val UMBER:             Float = java.lang.Float.intBitsToFloat(0xfe7aff3d)
  val IVY_GREEN:         Float = java.lang.Float.intBitsToFloat(0xfe6cff5a)
  val JADE:              Float = java.lang.Float.intBitsToFloat(0xfea6e45a)
  val GREEN:             Float = java.lang.Float.intBitsToFloat(0xfedcff5a)
  val CELADON:           Float = java.lang.Float.intBitsToFloat(0xfeecd75a)
  val PUCE:              Float = java.lang.Float.intBitsToFloat(0xfeb224d4)
  val BEIGE:             Float = java.lang.Float.intBitsToFloat(0xfeaf6723)
  val WET_STONE:         Float = java.lang.Float.intBitsToFloat(0xfea03132)
  val SLOW_CREEK:        Float = java.lang.Float.intBitsToFloat(0xfe8f4488)
  val SLATE_GRAY:        Float = java.lang.Float.intBitsToFloat(0xfe7e4a95)
  val LIGHT_SKIN_1:      Float = java.lang.Float.intBitsToFloat(0xfe704722)
  val LIGHT_SKIN_2:      Float = java.lang.Float.intBitsToFloat(0xfe765f0f)
  val LIGHT_SKIN_3:      Float = java.lang.Float.intBitsToFloat(0xfe8b570b)
  val LIGHT_SKIN_4:      Float = java.lang.Float.intBitsToFloat(0xfe9b7512)
  val LIGHT_SKIN_5:      Float = java.lang.Float.intBitsToFloat(0xfeab7c15)
  val LIGHT_SKIN_6:      Float = java.lang.Float.intBitsToFloat(0xfeb88d17)
  val LIGHT_SKIN_7:      Float = java.lang.Float.intBitsToFloat(0xfec5ab18)
  val LIGHT_SKIN_8:      Float = java.lang.Float.intBitsToFloat(0xfed1a81a)
  val LIGHT_SKIN_9:      Float = java.lang.Float.intBitsToFloat(0xfee48221)
  val DARK_SKIN_1:       Float = java.lang.Float.intBitsToFloat(0xfe423208)
  val DARK_SKIN_2:       Float = java.lang.Float.intBitsToFloat(0xfe4e6b0b)
  val DARK_SKIN_3:       Float = java.lang.Float.intBitsToFloat(0xfe644b08)
  val PINK_SKIN_1:       Float = java.lang.Float.intBitsToFloat(0xfe813808)
  val PINK_SKIN_2:       Float = java.lang.Float.intBitsToFloat(0xfe9c4a08)
  val PINK_SKIN_3:       Float = java.lang.Float.intBitsToFloat(0xfeb87708)
  val PINK_SKIN_4:       Float = java.lang.Float.intBitsToFloat(0xfedbadfd)
  val BRONZE_SKIN_4:     Float = java.lang.Float.intBitsToFloat(0xfecb5424)
  val BRONZE_SKIN_3:     Float = java.lang.Float.intBitsToFloat(0xfea48724)
  val BRONZE_SKIN_2:     Float = java.lang.Float.intBitsToFloat(0xfe787d22)
  val BRONZE_SKIN_1:     Float = java.lang.Float.intBitsToFloat(0xfe5c9a21)
  val TAUPE:             Float = java.lang.Float.intBitsToFloat(0xfe2f8622)
  val DRAB_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe3fae3d)
  val LIZARD_SCALES:     Float = java.lang.Float.intBitsToFloat(0xfe70c03d)
  val CRICKET:           Float = java.lang.Float.intBitsToFloat(0xfe8ba23d)
  val OLIVE_OIL:         Float = java.lang.Float.intBitsToFloat(0xfe9dbd3d)
  val DUN:               Float = java.lang.Float.intBitsToFloat(0xfeb19a3d)
  val CORN_SILK:         Float = java.lang.Float.intBitsToFloat(0xfec3793d)
  val TAN:               Float = java.lang.Float.intBitsToFloat(0xfed75e3d)
  val STRAW:             Float = java.lang.Float.intBitsToFloat(0xfeea473d)
  val HONEYDEW:          Float = java.lang.Float.intBitsToFloat(0xfed9624d)
  val TARNISH:           Float = java.lang.Float.intBitsToFloat(0xfebd704e)
  val PEA_SOUP:          Float = java.lang.Float.intBitsToFloat(0xfeafcb4e)
  val MARSH:             Float = java.lang.Float.intBitsToFloat(0xfe86994e)
  val ASPARAGUS:         Float = java.lang.Float.intBitsToFloat(0xfe72bb52)
  val PEAT_BOG:          Float = java.lang.Float.intBitsToFloat(0xfe4c9049)
  val DEEP_JUNGLE:       Float = java.lang.Float.intBitsToFloat(0xfe1a8d49)
  val PINE_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe47c765)
  val OLIVE_GREEN:       Float = java.lang.Float.intBitsToFloat(0xfe50725a)
  val GRAY_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe5f485a)
  val MAIDENHAIR_FERN:   Float = java.lang.Float.intBitsToFloat(0xfe67b360)
  val KELLY_GREEN:       Float = java.lang.Float.intBitsToFloat(0xfe82905a)
  val DUSTY_GREEN:       Float = java.lang.Float.intBitsToFloat(0xfe9d795a)
  val GARTER_SNAKE:      Float = java.lang.Float.intBitsToFloat(0xfeadb362)
  val SILVER_GREEN:      Float = java.lang.Float.intBitsToFloat(0xfeb9685a)
  val PISTACHIO:         Float = java.lang.Float.intBitsToFloat(0xfeca5c5a)
  val ANGEL_WING:        Float = java.lang.Float.intBitsToFloat(0xfef47a8d)
  val SAGE_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfee06065)
  val DRIED_SAGE:        Float = java.lang.Float.intBitsToFloat(0xfed66369)
  val ARTICHOKE:         Float = java.lang.Float.intBitsToFloat(0xfea85f5e)
  val VIRIDIAN:          Float = java.lang.Float.intBitsToFloat(0xfe738b63)
  val FLORAL_FOAM:       Float = java.lang.Float.intBitsToFloat(0xfe5cff69)
  val HUNTER_GREEN:      Float = java.lang.Float.intBitsToFloat(0xfe286c63)
  val DARK_TEAL:         Float = java.lang.Float.intBitsToFloat(0xfe3cb393)
  val KYANITE:           Float = java.lang.Float.intBitsToFloat(0xfe6ac288)
  val SPEARMINT:         Float = java.lang.Float.intBitsToFloat(0xfe9fac88)
  val AMAZONITE:         Float = java.lang.Float.intBitsToFloat(0xfebc7b88)
  val PASTEL_SKY:        Float = java.lang.Float.intBitsToFloat(0xfed86d88)
  val AQUAMARINE:        Float = java.lang.Float.intBitsToFloat(0xfee94e88)
  val DUST_BUNNY:        Float = java.lang.Float.intBitsToFloat(0xfed095ae)
  val PATINA:            Float = java.lang.Float.intBitsToFloat(0xfec373aa)
  val CHIPPED_GRANITE:   Float = java.lang.Float.intBitsToFloat(0xfeb86fb2)
  val BLUE_SMOKE:        Float = java.lang.Float.intBitsToFloat(0xfea75baa)
  val AIR_FORCE_BLUE:    Float = java.lang.Float.intBitsToFloat(0xfe8abbae)
  val COLD_IRON:         Float = java.lang.Float.intBitsToFloat(0xfe7081ab)
  val DREARY_BLUE:       Float = java.lang.Float.intBitsToFloat(0xfe549eac)
  val MURK:              Float = java.lang.Float.intBitsToFloat(0xfe1799b5)
  val NINJA:             Float = java.lang.Float.intBitsToFloat(0xfe2054bd)
  val WATERCOLOR_BLACK:  Float = java.lang.Float.intBitsToFloat(0xfe3d37bd)
  val IOLITE:            Float = java.lang.Float.intBitsToFloat(0xfe4d46bd)
  val BOYSENBERRY:       Float = java.lang.Float.intBitsToFloat(0xfe5c57bd)
  val WATERCOLOR_GRAY:   Float = java.lang.Float.intBitsToFloat(0xfe7460be)
  val BLUE_STEEL:        Float = java.lang.Float.intBitsToFloat(0xfe7e90bd)
  val TWILIGHT_CLOUD:    Float = java.lang.Float.intBitsToFloat(0xfe936ebd)
  val SMOG:              Float = java.lang.Float.intBitsToFloat(0xfeaf91bd)
  val TROPIC_MIST:       Float = java.lang.Float.intBitsToFloat(0xfedab2b5)
  val FEATHER_DOWN:      Float = java.lang.Float.intBitsToFloat(0xfee5ddbd)
  val MILD_VIOLET:       Float = java.lang.Float.intBitsToFloat(0xfe9a65ca)
  val VIOLET_CUSHIONS:   Float = java.lang.Float.intBitsToFloat(0xfe72a2c8)
  val DULL_VIOLET:       Float = java.lang.Float.intBitsToFloat(0xfe6362ca)
  val ROYAL_VIOLET:      Float = java.lang.Float.intBitsToFloat(0xfe477fc9)
  val EMINENCE:          Float = java.lang.Float.intBitsToFloat(0xfe2b6eda)
  val PRUNE:             Float = java.lang.Float.intBitsToFloat(0xfe384bda)
  val DUSTY_GRAPE:       Float = java.lang.Float.intBitsToFloat(0xfe5285da)
  val PINK_VIOLET:       Float = java.lang.Float.intBitsToFloat(0xfe6a77da)
  val RIPE_PLUM:         Float = java.lang.Float.intBitsToFloat(0xfe779cda)
  val MAUVE:             Float = java.lang.Float.intBitsToFloat(0xfe8661da)
  val HAM:               Float = java.lang.Float.intBitsToFloat(0xfebf96e0)
  val COTTON_CANDY:      Float = java.lang.Float.intBitsToFloat(0xfee6dce4)
  val SILVER_PINK:       Float = java.lang.Float.intBitsToFloat(0xfecf5ada)
  val TEA_ROSE:          Float = java.lang.Float.intBitsToFloat(0xfec467e8)
  val OLD_ROSE:          Float = java.lang.Float.intBitsToFloat(0xfeaf66ed)
  val DUSTY_PINK:        Float = java.lang.Float.intBitsToFloat(0xfea057e3)
  val ROSEATE_SPOONBILL: Float = java.lang.Float.intBitsToFloat(0xfe9361f2)
  val THULIAN_PINK:      Float = java.lang.Float.intBitsToFloat(0xfe7e95f1)
  val BROWN_VELVET:      Float = java.lang.Float.intBitsToFloat(0xfe3268f5)
  val NIGHTSHADE:        Float = java.lang.Float.intBitsToFloat(0xfe1d74f4)
  val SCRIBE_INK:        Float = java.lang.Float.intBitsToFloat(0xfe129eea)
  val VARNISH:           Float = java.lang.Float.intBitsToFloat(0xfe23af0c)
  val CEDAR_WOOD:        Float = java.lang.Float.intBitsToFloat(0xfe32ff0c)
  val HOT_SAUCE:         Float = java.lang.Float.intBitsToFloat(0xfe52ff09)
  val LURID_RED:         Float = java.lang.Float.intBitsToFloat(0xfe6fff09)
  val BRICK:             Float = java.lang.Float.intBitsToFloat(0xfe7daf0a)
  val BRIGHT_RED:        Float = java.lang.Float.intBitsToFloat(0xfe87ff0a)
  val EMBERS:            Float = java.lang.Float.intBitsToFloat(0xfe8dec0d)
  val SALMON:            Float = java.lang.Float.intBitsToFloat(0xfe96dc08)
  val TAXICAB_YELLOW:    Float = java.lang.Float.intBitsToFloat(0xfec5f829)
  val APRICOT:           Float = java.lang.Float.intBitsToFloat(0xfeb8ee1d)
  val BURNT_YELLOW:      Float = java.lang.Float.intBitsToFloat(0xfea5ff26)
  val DRY_PEPPER:        Float = java.lang.Float.intBitsToFloat(0xfe8bff15)
  val REDWOOD:           Float = java.lang.Float.intBitsToFloat(0xfe72ff15)
  val KOA:               Float = java.lang.Float.intBitsToFloat(0xfe63ff14)
  val OCHRE:             Float = java.lang.Float.intBitsToFloat(0xfe3de716)
  val DULL_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe4eff3a)
  val ARMY_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe5eff3d)
  val DRIFTWOOD:         Float = java.lang.Float.intBitsToFloat(0xfe808632)
  val DRY_BRUSH:         Float = java.lang.Float.intBitsToFloat(0xfe94ff32)
  val MUSH:              Float = java.lang.Float.intBitsToFloat(0xfeaaff3d)
  val BANANA_PUDDING:    Float = java.lang.Float.intBitsToFloat(0xfed2d736)
  val SAFFRON:           Float = java.lang.Float.intBitsToFloat(0xfed8ff30)
  val PENCIL_YELLOW:     Float = java.lang.Float.intBitsToFloat(0xfee8e936)
  val CHARTREUSE:        Float = java.lang.Float.intBitsToFloat(0xfeecef4a)
  val ABSINTHE:          Float = java.lang.Float.intBitsToFloat(0xfed9ea51)
  val INFECTION:         Float = java.lang.Float.intBitsToFloat(0xfec7ff4e)
  val FROG_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfeb2ff52)
  val AVOCADO:           Float = java.lang.Float.intBitsToFloat(0xfe97ff50)
  val WOODLANDS:         Float = java.lang.Float.intBitsToFloat(0xfe62ff53)
  val DARK_PINE:         Float = java.lang.Float.intBitsToFloat(0xfe2fff49)
  val MOSS_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe3dff55)
  val FERN_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe4eff5a)
  val FOREST_GLEN:       Float = java.lang.Float.intBitsToFloat(0xfe81ff5a)
  val MALACHITE:         Float = java.lang.Float.intBitsToFloat(0xfeb9ff5a)
  val APPLE_GREEN:       Float = java.lang.Float.intBitsToFloat(0xfec6ff5a)
  val CELERY:            Float = java.lang.Float.intBitsToFloat(0xfee3d559)
  val MINT_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfed2e55b)
  val EMERALD:           Float = java.lang.Float.intBitsToFloat(0xfea9ff5b)
  val PRASE:             Float = java.lang.Float.intBitsToFloat(0xfe9bff5f)
  val EUCALYPTUS:        Float = java.lang.Float.intBitsToFloat(0xfe7aff62)
  val ZUCCHINI:          Float = java.lang.Float.intBitsToFloat(0xfe31de7b)
  val SOFT_TEAL:         Float = java.lang.Float.intBitsToFloat(0xfe86ff76)
  val MEDIUM_TEAL:       Float = java.lang.Float.intBitsToFloat(0xfeacff6d)
  val SPRING_GREEN:      Float = java.lang.Float.intBitsToFloat(0xfec0ff60)
  val TURQUOISE:         Float = java.lang.Float.intBitsToFloat(0xfecffb6a)
  val SEAFOAM:           Float = java.lang.Float.intBitsToFloat(0xfee0f366)
  val VARISCITE:         Float = java.lang.Float.intBitsToFloat(0xfee6d96f)
  val REFRESHING_MIST:   Float = java.lang.Float.intBitsToFloat(0xfedddd96)
  val SHINING_SKY:       Float = java.lang.Float.intBitsToFloat(0xfed3e496)
  val STEAM:             Float = java.lang.Float.intBitsToFloat(0xfecab29a)
  val ROBIN_EGG_BLUE:    Float = java.lang.Float.intBitsToFloat(0xfec6ff83)
  val DENIM_BLUE:        Float = java.lang.Float.intBitsToFloat(0xfe92ffaa)
  val DEEP_TEAL:         Float = java.lang.Float.intBitsToFloat(0xfe50ff8b)
  val NAVY_BLUE:         Float = java.lang.Float.intBitsToFloat(0xfe2bd0b5)
  val BLUEBERRY:         Float = java.lang.Float.intBitsToFloat(0xfe3affb7)
  val PRUSSIAN_BLUE:     Float = java.lang.Float.intBitsToFloat(0xfe4cffb6)
  val DESERT_RAIN:       Float = java.lang.Float.intBitsToFloat(0xfe61d8af)
  val ELECTRIC_BLUE:     Float = java.lang.Float.intBitsToFloat(0xfe64ffba)
  val HIDDEN_BLUE:       Float = java.lang.Float.intBitsToFloat(0xfe69ffb3)
  val DULL_AZURE:        Float = java.lang.Float.intBitsToFloat(0xfe78ffb4)
  val RIPPED_DENIM:      Float = java.lang.Float.intBitsToFloat(0xfe97a0a8)
  val CALM_SKY:          Float = java.lang.Float.intBitsToFloat(0xfe9fe9b0)
  val VAPOR:             Float = java.lang.Float.intBitsToFloat(0xfeb1e5b5)
  val POWDER_BLUE:       Float = java.lang.Float.intBitsToFloat(0xfebae3a6)
  val SUDS:              Float = java.lang.Float.intBitsToFloat(0xfebfcfbe)
  val STRONG_CYAN:       Float = java.lang.Float.intBitsToFloat(0xfeb1ffa6)
  val SHARP_AZURE:       Float = java.lang.Float.intBitsToFloat(0xfe82ffb5)
  val BLUE_EYE:          Float = java.lang.Float.intBitsToFloat(0xfe7cc7b3)
  val SUBTLETY:          Float = java.lang.Float.intBitsToFloat(0xfe7fd7be)
  val ROUGH_SAPPHIRE:    Float = java.lang.Float.intBitsToFloat(0xfe6ff8bb)
  val IRIS:              Float = java.lang.Float.intBitsToFloat(0xfe65f1bf)
  val CORNFLOWER_BLUE:   Float = java.lang.Float.intBitsToFloat(0xfe5cf4bd)
  val POLISHED_SAPPHIRE: Float = java.lang.Float.intBitsToFloat(0xfe45ffbc)
  val ROYAL_BLUE:        Float = java.lang.Float.intBitsToFloat(0xfe38ffbc)
  val INDIGO:            Float = java.lang.Float.intBitsToFloat(0xfe2efdbe)
  val SPACE_BLUE:        Float = java.lang.Float.intBitsToFloat(0xfe21dfb6)
  val THICK_AMETHYST:    Float = java.lang.Float.intBitsToFloat(0xfe40ffc2)
  val JUICY_GRAPE:       Float = java.lang.Float.intBitsToFloat(0xfe4dffc2)
  val BLACKLIGHT_GLOW:   Float = java.lang.Float.intBitsToFloat(0xfe61e9c7)
  val PURPLE_FREESIA:    Float = java.lang.Float.intBitsToFloat(0xfe75f6c6)
  val THIN_AMETHYST:     Float = java.lang.Float.intBitsToFloat(0xfe60ffc3)
  val ORCHID:            Float = java.lang.Float.intBitsToFloat(0xfe8deeca)
  val LAVENDER:          Float = java.lang.Float.intBitsToFloat(0xfea5e8c5)
  val LILAC:             Float = java.lang.Float.intBitsToFloat(0xfeb8e4cc)
  val SOAP:              Float = java.lang.Float.intBitsToFloat(0xfecbc9c6)
  val PINK_TUTU:         Float = java.lang.Float.intBitsToFloat(0xfed6ced8)
  val THISTLE:           Float = java.lang.Float.intBitsToFloat(0xfea2e9d3)
  val HELIOTROPE:        Float = java.lang.Float.intBitsToFloat(0xfe9eeada)
  val PURPLE:            Float = java.lang.Float.intBitsToFloat(0xfe7fffd9)
  val WISTERIA:          Float = java.lang.Float.intBitsToFloat(0xfe7affcc)
  val MEDIUM_PLUM:       Float = java.lang.Float.intBitsToFloat(0xfe6cffd8)
  val VIOLET:            Float = java.lang.Float.intBitsToFloat(0xfe58ffcc)
  val GRAPE_LOLLIPOP:    Float = java.lang.Float.intBitsToFloat(0xfe3aeecc)
  val MULBERRY:          Float = java.lang.Float.intBitsToFloat(0xfe39f2da)
  val GRAPE_SODA:        Float = java.lang.Float.intBitsToFloat(0xfe25ffca)
  val EGGPLANT:          Float = java.lang.Float.intBitsToFloat(0xfe1cdfcc)
  val CHERRY_SYRUP:      Float = java.lang.Float.intBitsToFloat(0xfe2fbcf4)
  val PLUM_JUICE:        Float = java.lang.Float.intBitsToFloat(0xfe58ffe7)
  val FRUIT_PUNCH:       Float = java.lang.Float.intBitsToFloat(0xfe67fff6)
  val BUBBLE_GUM:        Float = java.lang.Float.intBitsToFloat(0xfe96e5ee)
  val PINK_LEMONADE:     Float = java.lang.Float.intBitsToFloat(0xfea0e3ed)
  val SHRIMP:            Float = java.lang.Float.intBitsToFloat(0xfeb9cbfc)
  val FLAMINGO:          Float = java.lang.Float.intBitsToFloat(0xfe8ae5fb)
  val ROSE:              Float = java.lang.Float.intBitsToFloat(0xfe79fffc)
  val CARMINE:           Float = java.lang.Float.intBitsToFloat(0xfe5fff04)
  val BOLOGNA:           Float = java.lang.Float.intBitsToFloat(0xfe57b200)
  val RASPBERRY:         Float = java.lang.Float.intBitsToFloat(0xfe49f802)

  // Register all colors
  locally {
    NAMED.put("Transparent", java.lang.Float.intBitsToFloat(0x0))
    LIST += java.lang.Float.intBitsToFloat(0x0)
    NAMED.put("Black", java.lang.Float.intBitsToFloat(0xfe000000))
    LIST += java.lang.Float.intBitsToFloat(0xfe000000)
    NAMED.put("Coal Black", java.lang.Float.intBitsToFloat(0xfe0f0029))
    LIST += java.lang.Float.intBitsToFloat(0xfe0f0029)
    NAMED.put("Shadow", java.lang.Float.intBitsToFloat(0xfe230029))
    LIST += java.lang.Float.intBitsToFloat(0xfe230029)
    NAMED.put("Graphite", java.lang.Float.intBitsToFloat(0xfe360029))
    LIST += java.lang.Float.intBitsToFloat(0xfe360029)
    NAMED.put("Dark Gray", java.lang.Float.intBitsToFloat(0xfe490029))
    LIST += java.lang.Float.intBitsToFloat(0xfe490029)
    NAMED.put("Lead", java.lang.Float.intBitsToFloat(0xfe5b0029))
    LIST += java.lang.Float.intBitsToFloat(0xfe5b0029)
    NAMED.put("Iron", java.lang.Float.intBitsToFloat(0xfe6e0029))
    LIST += java.lang.Float.intBitsToFloat(0xfe6e0029)
    NAMED.put("Gray", java.lang.Float.intBitsToFloat(0xfe800029))
    LIST += java.lang.Float.intBitsToFloat(0xfe800029)
    NAMED.put("Chinchilla", java.lang.Float.intBitsToFloat(0xfe910029))
    LIST += java.lang.Float.intBitsToFloat(0xfe910029)
    NAMED.put("Greyhound", java.lang.Float.intBitsToFloat(0xfea30029))
    LIST += java.lang.Float.intBitsToFloat(0xfea30029)
    NAMED.put("Silver", java.lang.Float.intBitsToFloat(0xfeb50029))
    LIST += java.lang.Float.intBitsToFloat(0xfeb50029)
    NAMED.put("Light Gray", java.lang.Float.intBitsToFloat(0xfec80029))
    LIST += java.lang.Float.intBitsToFloat(0xfec80029)
    NAMED.put("Platinum", java.lang.Float.intBitsToFloat(0xfedb0029))
    LIST += java.lang.Float.intBitsToFloat(0xfedb0029)
    NAMED.put("Cloud", java.lang.Float.intBitsToFloat(0xfeed0029))
    LIST += java.lang.Float.intBitsToFloat(0xfeed0029)
    NAMED.put("White", java.lang.Float.intBitsToFloat(0xfeff0029))
    LIST += java.lang.Float.intBitsToFloat(0xfeff0029)
    NAMED.put("Seawater", java.lang.Float.intBitsToFloat(0xfe71ff88))
    LIST += java.lang.Float.intBitsToFloat(0xfe71ff88)
    NAMED.put("Hospital Green", java.lang.Float.intBitsToFloat(0xfeaded88))
    LIST += java.lang.Float.intBitsToFloat(0xfeaded88)
    NAMED.put("Cyan", java.lang.Float.intBitsToFloat(0xfee5ff88))
    LIST += java.lang.Float.intBitsToFloat(0xfee5ff88)
    NAMED.put("Bubble", java.lang.Float.intBitsToFloat(0xfef3db88))
    LIST += java.lang.Float.intBitsToFloat(0xfef3db88)
    NAMED.put("Periwinkle", java.lang.Float.intBitsToFloat(0xfe8fedbd))
    LIST += java.lang.Float.intBitsToFloat(0xfe8fedbd)
    NAMED.put("Blue", java.lang.Float.intBitsToFloat(0xfe4cffbd))
    LIST += java.lang.Float.intBitsToFloat(0xfe4cffbd)
    NAMED.put("Faded Blue", java.lang.Float.intBitsToFloat(0xfe51babd))
    LIST += java.lang.Float.intBitsToFloat(0xfe51babd)
    NAMED.put("Ocean Blue", java.lang.Float.intBitsToFloat(0xfe1fffbd))
    LIST += java.lang.Float.intBitsToFloat(0xfe1fffbd)
    NAMED.put("Stygian Blue", java.lang.Float.intBitsToFloat(0xfe17c3bd))
    LIST += java.lang.Float.intBitsToFloat(0xfe17c3bd)
    NAMED.put("Deep Purple", java.lang.Float.intBitsToFloat(0xfe45ffda))
    LIST += java.lang.Float.intBitsToFloat(0xfe45ffda)
    NAMED.put("Tyrian Purple", java.lang.Float.intBitsToFloat(0xfe76dada))
    LIST += java.lang.Float.intBitsToFloat(0xfe76dada)
    NAMED.put("Magenta", java.lang.Float.intBitsToFloat(0xfe8bffda))
    LIST += java.lang.Float.intBitsToFloat(0xfe8bffda)
    NAMED.put("Bubblegum Pink", java.lang.Float.intBitsToFloat(0xfeb0e6da))
    LIST += java.lang.Float.intBitsToFloat(0xfeb0e6da)
    NAMED.put("Pork Chop", java.lang.Float.intBitsToFloat(0xfed0dc00))
    LIST += java.lang.Float.intBitsToFloat(0xfed0dc00)
    NAMED.put("Raw Meat", java.lang.Float.intBitsToFloat(0xfea6dc08))
    LIST += java.lang.Float.intBitsToFloat(0xfea6dc08)
    NAMED.put("Red", java.lang.Float.intBitsToFloat(0xfe7fff08))
    LIST += java.lang.Float.intBitsToFloat(0xfe7fff08)
    NAMED.put("Putty", java.lang.Float.intBitsToFloat(0xfe6cb208))
    LIST += java.lang.Float.intBitsToFloat(0xfe6cb208)
    NAMED.put("Sienna", java.lang.Float.intBitsToFloat(0xfe3bff08))
    LIST += java.lang.Float.intBitsToFloat(0xfe3bff08)
    NAMED.put("Seal Brown", java.lang.Float.intBitsToFloat(0xfe2abd08))
    LIST += java.lang.Float.intBitsToFloat(0xfe2abd08)
    NAMED.put("Mummy Brown", java.lang.Float.intBitsToFloat(0xfe50ff16))
    LIST += java.lang.Float.intBitsToFloat(0xfe50ff16)
    NAMED.put("Fawn", java.lang.Float.intBitsToFloat(0xfe8cd71d))
    LIST += java.lang.Float.intBitsToFloat(0xfe8cd71d)
    NAMED.put("Orange", java.lang.Float.intBitsToFloat(0xfea2ff15))
    LIST += java.lang.Float.intBitsToFloat(0xfea2ff15)
    NAMED.put("Peach", java.lang.Float.intBitsToFloat(0xfecbd820))
    LIST += java.lang.Float.intBitsToFloat(0xfecbd820)
    NAMED.put("Cream", java.lang.Float.intBitsToFloat(0xfefbd83d))
    LIST += java.lang.Float.intBitsToFloat(0xfefbd83d)
    NAMED.put("Yellow", java.lang.Float.intBitsToFloat(0xfef7ff3d))
    LIST += java.lang.Float.intBitsToFloat(0xfef7ff3d)
    NAMED.put("Earwax", java.lang.Float.intBitsToFloat(0xfeb9ea3d))
    LIST += java.lang.Float.intBitsToFloat(0xfeb9ea3d)
    NAMED.put("Umber", java.lang.Float.intBitsToFloat(0xfe7aff3d))
    LIST += java.lang.Float.intBitsToFloat(0xfe7aff3d)
    NAMED.put("Ivy Green", java.lang.Float.intBitsToFloat(0xfe6cff5a))
    LIST += java.lang.Float.intBitsToFloat(0xfe6cff5a)
    NAMED.put("Jade", java.lang.Float.intBitsToFloat(0xfea6e45a))
    LIST += java.lang.Float.intBitsToFloat(0xfea6e45a)
    NAMED.put("Green", java.lang.Float.intBitsToFloat(0xfedcff5a))
    LIST += java.lang.Float.intBitsToFloat(0xfedcff5a)
    NAMED.put("Celadon", java.lang.Float.intBitsToFloat(0xfeecd75a))
    LIST += java.lang.Float.intBitsToFloat(0xfeecd75a)
    NAMED.put("Puce", java.lang.Float.intBitsToFloat(0xfeb224d4))
    LIST += java.lang.Float.intBitsToFloat(0xfeb224d4)
    NAMED.put("Beige", java.lang.Float.intBitsToFloat(0xfeaf6723))
    LIST += java.lang.Float.intBitsToFloat(0xfeaf6723)
    NAMED.put("Wet Stone", java.lang.Float.intBitsToFloat(0xfea03132))
    LIST += java.lang.Float.intBitsToFloat(0xfea03132)
    NAMED.put("Slow Creek", java.lang.Float.intBitsToFloat(0xfe8f4488))
    LIST += java.lang.Float.intBitsToFloat(0xfe8f4488)
    NAMED.put("Slate Gray", java.lang.Float.intBitsToFloat(0xfe7e4a95))
    LIST += java.lang.Float.intBitsToFloat(0xfe7e4a95)
    NAMED.put("Light Skin 1", java.lang.Float.intBitsToFloat(0xfe704722))
    LIST += java.lang.Float.intBitsToFloat(0xfe704722)
    NAMED.put("Light Skin 2", java.lang.Float.intBitsToFloat(0xfe765f0f))
    LIST += java.lang.Float.intBitsToFloat(0xfe765f0f)
    NAMED.put("Light Skin 3", java.lang.Float.intBitsToFloat(0xfe8b570b))
    LIST += java.lang.Float.intBitsToFloat(0xfe8b570b)
    NAMED.put("Light Skin 4", java.lang.Float.intBitsToFloat(0xfe9b7512))
    LIST += java.lang.Float.intBitsToFloat(0xfe9b7512)
    NAMED.put("Light Skin 5", java.lang.Float.intBitsToFloat(0xfeab7c15))
    LIST += java.lang.Float.intBitsToFloat(0xfeab7c15)
    NAMED.put("Light Skin 6", java.lang.Float.intBitsToFloat(0xfeb88d17))
    LIST += java.lang.Float.intBitsToFloat(0xfeb88d17)
    NAMED.put("Light Skin 7", java.lang.Float.intBitsToFloat(0xfec5ab18))
    LIST += java.lang.Float.intBitsToFloat(0xfec5ab18)
    NAMED.put("Light Skin 8", java.lang.Float.intBitsToFloat(0xfed1a81a))
    LIST += java.lang.Float.intBitsToFloat(0xfed1a81a)
    NAMED.put("Light Skin 9", java.lang.Float.intBitsToFloat(0xfee48221))
    LIST += java.lang.Float.intBitsToFloat(0xfee48221)
    NAMED.put("Dark Skin 1", java.lang.Float.intBitsToFloat(0xfe423208))
    LIST += java.lang.Float.intBitsToFloat(0xfe423208)
    NAMED.put("Dark Skin 2", java.lang.Float.intBitsToFloat(0xfe4e6b0b))
    LIST += java.lang.Float.intBitsToFloat(0xfe4e6b0b)
    NAMED.put("Dark Skin 3", java.lang.Float.intBitsToFloat(0xfe644b08))
    LIST += java.lang.Float.intBitsToFloat(0xfe644b08)
    NAMED.put("Pink Skin 1", java.lang.Float.intBitsToFloat(0xfe813808))
    LIST += java.lang.Float.intBitsToFloat(0xfe813808)
    NAMED.put("Pink Skin 2", java.lang.Float.intBitsToFloat(0xfe9c4a08))
    LIST += java.lang.Float.intBitsToFloat(0xfe9c4a08)
    NAMED.put("Pink Skin 3", java.lang.Float.intBitsToFloat(0xfeb87708))
    LIST += java.lang.Float.intBitsToFloat(0xfeb87708)
    NAMED.put("Pink Skin 4", java.lang.Float.intBitsToFloat(0xfedbadfd))
    LIST += java.lang.Float.intBitsToFloat(0xfedbadfd)
    NAMED.put("Bronze Skin 4", java.lang.Float.intBitsToFloat(0xfecb5424))
    LIST += java.lang.Float.intBitsToFloat(0xfecb5424)
    NAMED.put("Bronze Skin 3", java.lang.Float.intBitsToFloat(0xfea48724))
    LIST += java.lang.Float.intBitsToFloat(0xfea48724)
    NAMED.put("Bronze Skin 2", java.lang.Float.intBitsToFloat(0xfe787d22))
    LIST += java.lang.Float.intBitsToFloat(0xfe787d22)
    NAMED.put("Bronze Skin 1", java.lang.Float.intBitsToFloat(0xfe5c9a21))
    LIST += java.lang.Float.intBitsToFloat(0xfe5c9a21)
    NAMED.put("Taupe", java.lang.Float.intBitsToFloat(0xfe2f8622))
    LIST += java.lang.Float.intBitsToFloat(0xfe2f8622)
    NAMED.put("Drab Green", java.lang.Float.intBitsToFloat(0xfe3fae3d))
    LIST += java.lang.Float.intBitsToFloat(0xfe3fae3d)
    NAMED.put("Lizard Scales", java.lang.Float.intBitsToFloat(0xfe70c03d))
    LIST += java.lang.Float.intBitsToFloat(0xfe70c03d)
    NAMED.put("Cricket", java.lang.Float.intBitsToFloat(0xfe8ba23d))
    LIST += java.lang.Float.intBitsToFloat(0xfe8ba23d)
    NAMED.put("Olive Oil", java.lang.Float.intBitsToFloat(0xfe9dbd3d))
    LIST += java.lang.Float.intBitsToFloat(0xfe9dbd3d)
    NAMED.put("Dun", java.lang.Float.intBitsToFloat(0xfeb19a3d))
    LIST += java.lang.Float.intBitsToFloat(0xfeb19a3d)
    NAMED.put("Corn Silk", java.lang.Float.intBitsToFloat(0xfec3793d))
    LIST += java.lang.Float.intBitsToFloat(0xfec3793d)
    NAMED.put("Tan", java.lang.Float.intBitsToFloat(0xfed75e3d))
    LIST += java.lang.Float.intBitsToFloat(0xfed75e3d)
    NAMED.put("Straw", java.lang.Float.intBitsToFloat(0xfeea473d))
    LIST += java.lang.Float.intBitsToFloat(0xfeea473d)
    NAMED.put("Honeydew", java.lang.Float.intBitsToFloat(0xfed9624d))
    LIST += java.lang.Float.intBitsToFloat(0xfed9624d)
    NAMED.put("Tarnish", java.lang.Float.intBitsToFloat(0xfebd704e))
    LIST += java.lang.Float.intBitsToFloat(0xfebd704e)
    NAMED.put("Pea Soup", java.lang.Float.intBitsToFloat(0xfeafcb4e))
    LIST += java.lang.Float.intBitsToFloat(0xfeafcb4e)
    NAMED.put("Marsh", java.lang.Float.intBitsToFloat(0xfe86994e))
    LIST += java.lang.Float.intBitsToFloat(0xfe86994e)
    NAMED.put("Asparagus", java.lang.Float.intBitsToFloat(0xfe72bb52))
    LIST += java.lang.Float.intBitsToFloat(0xfe72bb52)
    NAMED.put("Peat Bog", java.lang.Float.intBitsToFloat(0xfe4c9049))
    LIST += java.lang.Float.intBitsToFloat(0xfe4c9049)
    NAMED.put("Deep Jungle", java.lang.Float.intBitsToFloat(0xfe1a8d49))
    LIST += java.lang.Float.intBitsToFloat(0xfe1a8d49)
    NAMED.put("Pine Green", java.lang.Float.intBitsToFloat(0xfe47c765))
    LIST += java.lang.Float.intBitsToFloat(0xfe47c765)
    NAMED.put("Olive Green", java.lang.Float.intBitsToFloat(0xfe50725a))
    LIST += java.lang.Float.intBitsToFloat(0xfe50725a)
    NAMED.put("Gray Green", java.lang.Float.intBitsToFloat(0xfe5f485a))
    LIST += java.lang.Float.intBitsToFloat(0xfe5f485a)
    NAMED.put("Maidenhair Fern", java.lang.Float.intBitsToFloat(0xfe67b360))
    LIST += java.lang.Float.intBitsToFloat(0xfe67b360)
    NAMED.put("Kelly Green", java.lang.Float.intBitsToFloat(0xfe82905a))
    LIST += java.lang.Float.intBitsToFloat(0xfe82905a)
    NAMED.put("Dusty Green", java.lang.Float.intBitsToFloat(0xfe9d795a))
    LIST += java.lang.Float.intBitsToFloat(0xfe9d795a)
    NAMED.put("Garter Snake", java.lang.Float.intBitsToFloat(0xfeadb362))
    LIST += java.lang.Float.intBitsToFloat(0xfeadb362)
    NAMED.put("Silver Green", java.lang.Float.intBitsToFloat(0xfeb9685a))
    LIST += java.lang.Float.intBitsToFloat(0xfeb9685a)
    NAMED.put("Pistachio", java.lang.Float.intBitsToFloat(0xfeca5c5a))
    LIST += java.lang.Float.intBitsToFloat(0xfeca5c5a)
    NAMED.put("Angel Wing", java.lang.Float.intBitsToFloat(0xfef47a8d))
    LIST += java.lang.Float.intBitsToFloat(0xfef47a8d)
    NAMED.put("Sage Green", java.lang.Float.intBitsToFloat(0xfee06065))
    LIST += java.lang.Float.intBitsToFloat(0xfee06065)
    NAMED.put("Dried Sage", java.lang.Float.intBitsToFloat(0xfed66369))
    LIST += java.lang.Float.intBitsToFloat(0xfed66369)
    NAMED.put("Artichoke", java.lang.Float.intBitsToFloat(0xfea85f5e))
    LIST += java.lang.Float.intBitsToFloat(0xfea85f5e)
    NAMED.put("Viridian", java.lang.Float.intBitsToFloat(0xfe738b63))
    LIST += java.lang.Float.intBitsToFloat(0xfe738b63)
    NAMED.put("Floral Foam", java.lang.Float.intBitsToFloat(0xfe5cff69))
    LIST += java.lang.Float.intBitsToFloat(0xfe5cff69)
    NAMED.put("Hunter Green", java.lang.Float.intBitsToFloat(0xfe286c63))
    LIST += java.lang.Float.intBitsToFloat(0xfe286c63)
    NAMED.put("Dark Teal", java.lang.Float.intBitsToFloat(0xfe3cb393))
    LIST += java.lang.Float.intBitsToFloat(0xfe3cb393)
    NAMED.put("Kyanite", java.lang.Float.intBitsToFloat(0xfe6ac288))
    LIST += java.lang.Float.intBitsToFloat(0xfe6ac288)
    NAMED.put("Spearmint", java.lang.Float.intBitsToFloat(0xfe9fac88))
    LIST += java.lang.Float.intBitsToFloat(0xfe9fac88)
    NAMED.put("Amazonite", java.lang.Float.intBitsToFloat(0xfebc7b88))
    LIST += java.lang.Float.intBitsToFloat(0xfebc7b88)
    NAMED.put("Pastel Sky", java.lang.Float.intBitsToFloat(0xfed86d88))
    LIST += java.lang.Float.intBitsToFloat(0xfed86d88)
    NAMED.put("Aquamarine", java.lang.Float.intBitsToFloat(0xfee94e88))
    LIST += java.lang.Float.intBitsToFloat(0xfee94e88)
    NAMED.put("Dust Bunny", java.lang.Float.intBitsToFloat(0xfed095ae))
    LIST += java.lang.Float.intBitsToFloat(0xfed095ae)
    NAMED.put("Patina", java.lang.Float.intBitsToFloat(0xfec373aa))
    LIST += java.lang.Float.intBitsToFloat(0xfec373aa)
    NAMED.put("Chipped Granite", java.lang.Float.intBitsToFloat(0xfeb86fb2))
    LIST += java.lang.Float.intBitsToFloat(0xfeb86fb2)
    NAMED.put("Blue Smoke", java.lang.Float.intBitsToFloat(0xfea75baa))
    LIST += java.lang.Float.intBitsToFloat(0xfea75baa)
    NAMED.put("Air Force Blue", java.lang.Float.intBitsToFloat(0xfe8abbae))
    LIST += java.lang.Float.intBitsToFloat(0xfe8abbae)
    NAMED.put("Cold Iron", java.lang.Float.intBitsToFloat(0xfe7081ab))
    LIST += java.lang.Float.intBitsToFloat(0xfe7081ab)
    NAMED.put("Dreary Blue", java.lang.Float.intBitsToFloat(0xfe549eac))
    LIST += java.lang.Float.intBitsToFloat(0xfe549eac)
    NAMED.put("Murk", java.lang.Float.intBitsToFloat(0xfe1799b5))
    LIST += java.lang.Float.intBitsToFloat(0xfe1799b5)
    NAMED.put("Ninja", java.lang.Float.intBitsToFloat(0xfe2054bd))
    LIST += java.lang.Float.intBitsToFloat(0xfe2054bd)
    NAMED.put("Watercolor Black", java.lang.Float.intBitsToFloat(0xfe3d37bd))
    LIST += java.lang.Float.intBitsToFloat(0xfe3d37bd)
    NAMED.put("Iolite", java.lang.Float.intBitsToFloat(0xfe4d46bd))
    LIST += java.lang.Float.intBitsToFloat(0xfe4d46bd)
    NAMED.put("Boysenberry", java.lang.Float.intBitsToFloat(0xfe5c57bd))
    LIST += java.lang.Float.intBitsToFloat(0xfe5c57bd)
    NAMED.put("Watercolor Gray", java.lang.Float.intBitsToFloat(0xfe7460be))
    LIST += java.lang.Float.intBitsToFloat(0xfe7460be)
    NAMED.put("Blue Steel", java.lang.Float.intBitsToFloat(0xfe7e90bd))
    LIST += java.lang.Float.intBitsToFloat(0xfe7e90bd)
    NAMED.put("Twilight Cloud", java.lang.Float.intBitsToFloat(0xfe936ebd))
    LIST += java.lang.Float.intBitsToFloat(0xfe936ebd)
    NAMED.put("Smog", java.lang.Float.intBitsToFloat(0xfeaf91bd))
    LIST += java.lang.Float.intBitsToFloat(0xfeaf91bd)
    NAMED.put("Tropic Mist", java.lang.Float.intBitsToFloat(0xfedab2b5))
    LIST += java.lang.Float.intBitsToFloat(0xfedab2b5)
    NAMED.put("Feather Down", java.lang.Float.intBitsToFloat(0xfee5ddbd))
    LIST += java.lang.Float.intBitsToFloat(0xfee5ddbd)
    NAMED.put("Mild Violet", java.lang.Float.intBitsToFloat(0xfe9a65ca))
    LIST += java.lang.Float.intBitsToFloat(0xfe9a65ca)
    NAMED.put("Violet Cushions", java.lang.Float.intBitsToFloat(0xfe72a2c8))
    LIST += java.lang.Float.intBitsToFloat(0xfe72a2c8)
    NAMED.put("Dull Violet", java.lang.Float.intBitsToFloat(0xfe6362ca))
    LIST += java.lang.Float.intBitsToFloat(0xfe6362ca)
    NAMED.put("Royal Violet", java.lang.Float.intBitsToFloat(0xfe477fc9))
    LIST += java.lang.Float.intBitsToFloat(0xfe477fc9)
    NAMED.put("Eminence", java.lang.Float.intBitsToFloat(0xfe2b6eda))
    LIST += java.lang.Float.intBitsToFloat(0xfe2b6eda)
    NAMED.put("Prune", java.lang.Float.intBitsToFloat(0xfe384bda))
    LIST += java.lang.Float.intBitsToFloat(0xfe384bda)
    NAMED.put("Dusty Grape", java.lang.Float.intBitsToFloat(0xfe5285da))
    LIST += java.lang.Float.intBitsToFloat(0xfe5285da)
    NAMED.put("Pink Violet", java.lang.Float.intBitsToFloat(0xfe6a77da))
    LIST += java.lang.Float.intBitsToFloat(0xfe6a77da)
    NAMED.put("Ripe Plum", java.lang.Float.intBitsToFloat(0xfe779cda))
    LIST += java.lang.Float.intBitsToFloat(0xfe779cda)
    NAMED.put("Mauve", java.lang.Float.intBitsToFloat(0xfe8661da))
    LIST += java.lang.Float.intBitsToFloat(0xfe8661da)
    NAMED.put("Ham", java.lang.Float.intBitsToFloat(0xfebf96e0))
    LIST += java.lang.Float.intBitsToFloat(0xfebf96e0)
    NAMED.put("Cotton Candy", java.lang.Float.intBitsToFloat(0xfee6dce4))
    LIST += java.lang.Float.intBitsToFloat(0xfee6dce4)
    NAMED.put("Silver Pink", java.lang.Float.intBitsToFloat(0xfecf5ada))
    LIST += java.lang.Float.intBitsToFloat(0xfecf5ada)
    NAMED.put("Tea Rose", java.lang.Float.intBitsToFloat(0xfec467e8))
    LIST += java.lang.Float.intBitsToFloat(0xfec467e8)
    NAMED.put("Old Rose", java.lang.Float.intBitsToFloat(0xfeaf66ed))
    LIST += java.lang.Float.intBitsToFloat(0xfeaf66ed)
    NAMED.put("Dusty Pink", java.lang.Float.intBitsToFloat(0xfea057e3))
    LIST += java.lang.Float.intBitsToFloat(0xfea057e3)
    NAMED.put("Roseate Spoonbill", java.lang.Float.intBitsToFloat(0xfe9361f2))
    LIST += java.lang.Float.intBitsToFloat(0xfe9361f2)
    NAMED.put("Thulian Pink", java.lang.Float.intBitsToFloat(0xfe7e95f1))
    LIST += java.lang.Float.intBitsToFloat(0xfe7e95f1)
    NAMED.put("Brown Velvet", java.lang.Float.intBitsToFloat(0xfe3268f5))
    LIST += java.lang.Float.intBitsToFloat(0xfe3268f5)
    NAMED.put("Nightshade", java.lang.Float.intBitsToFloat(0xfe1d74f4))
    LIST += java.lang.Float.intBitsToFloat(0xfe1d74f4)
    NAMED.put("Scribe Ink", java.lang.Float.intBitsToFloat(0xfe129eea))
    LIST += java.lang.Float.intBitsToFloat(0xfe129eea)
    NAMED.put("Varnish", java.lang.Float.intBitsToFloat(0xfe23af0c))
    LIST += java.lang.Float.intBitsToFloat(0xfe23af0c)
    NAMED.put("Cedar Wood", java.lang.Float.intBitsToFloat(0xfe32ff0c))
    LIST += java.lang.Float.intBitsToFloat(0xfe32ff0c)
    NAMED.put("Hot Sauce", java.lang.Float.intBitsToFloat(0xfe52ff09))
    LIST += java.lang.Float.intBitsToFloat(0xfe52ff09)
    NAMED.put("Lurid Red", java.lang.Float.intBitsToFloat(0xfe6fff09))
    LIST += java.lang.Float.intBitsToFloat(0xfe6fff09)
    NAMED.put("Brick", java.lang.Float.intBitsToFloat(0xfe7daf0a))
    LIST += java.lang.Float.intBitsToFloat(0xfe7daf0a)
    NAMED.put("Bright Red", java.lang.Float.intBitsToFloat(0xfe87ff0a))
    LIST += java.lang.Float.intBitsToFloat(0xfe87ff0a)
    NAMED.put("Embers", java.lang.Float.intBitsToFloat(0xfe8dec0d))
    LIST += java.lang.Float.intBitsToFloat(0xfe8dec0d)
    NAMED.put("Salmon", java.lang.Float.intBitsToFloat(0xfe96dc08))
    LIST += java.lang.Float.intBitsToFloat(0xfe96dc08)
    NAMED.put("Taxicab Yellow", java.lang.Float.intBitsToFloat(0xfec5f829))
    LIST += java.lang.Float.intBitsToFloat(0xfec5f829)
    NAMED.put("Apricot", java.lang.Float.intBitsToFloat(0xfeb8ee1d))
    LIST += java.lang.Float.intBitsToFloat(0xfeb8ee1d)
    NAMED.put("Burnt Yellow", java.lang.Float.intBitsToFloat(0xfea5ff26))
    LIST += java.lang.Float.intBitsToFloat(0xfea5ff26)
    NAMED.put("Dry Pepper", java.lang.Float.intBitsToFloat(0xfe8bff15))
    LIST += java.lang.Float.intBitsToFloat(0xfe8bff15)
    NAMED.put("Redwood", java.lang.Float.intBitsToFloat(0xfe72ff15))
    LIST += java.lang.Float.intBitsToFloat(0xfe72ff15)
    NAMED.put("Koa", java.lang.Float.intBitsToFloat(0xfe63ff14))
    LIST += java.lang.Float.intBitsToFloat(0xfe63ff14)
    NAMED.put("Ochre", java.lang.Float.intBitsToFloat(0xfe3de716))
    LIST += java.lang.Float.intBitsToFloat(0xfe3de716)
    NAMED.put("Dull Green", java.lang.Float.intBitsToFloat(0xfe4eff3a))
    LIST += java.lang.Float.intBitsToFloat(0xfe4eff3a)
    NAMED.put("Army Green", java.lang.Float.intBitsToFloat(0xfe5eff3d))
    LIST += java.lang.Float.intBitsToFloat(0xfe5eff3d)
    NAMED.put("Driftwood", java.lang.Float.intBitsToFloat(0xfe808632))
    LIST += java.lang.Float.intBitsToFloat(0xfe808632)
    NAMED.put("Dry Brush", java.lang.Float.intBitsToFloat(0xfe94ff32))
    LIST += java.lang.Float.intBitsToFloat(0xfe94ff32)
    NAMED.put("Mush", java.lang.Float.intBitsToFloat(0xfeaaff3d))
    LIST += java.lang.Float.intBitsToFloat(0xfeaaff3d)
    NAMED.put("Banana Pudding", java.lang.Float.intBitsToFloat(0xfed2d736))
    LIST += java.lang.Float.intBitsToFloat(0xfed2d736)
    NAMED.put("Saffron", java.lang.Float.intBitsToFloat(0xfed8ff30))
    LIST += java.lang.Float.intBitsToFloat(0xfed8ff30)
    NAMED.put("Pencil Yellow", java.lang.Float.intBitsToFloat(0xfee8e936))
    LIST += java.lang.Float.intBitsToFloat(0xfee8e936)
    NAMED.put("Chartreuse", java.lang.Float.intBitsToFloat(0xfeecef4a))
    LIST += java.lang.Float.intBitsToFloat(0xfeecef4a)
    NAMED.put("Absinthe", java.lang.Float.intBitsToFloat(0xfed9ea51))
    LIST += java.lang.Float.intBitsToFloat(0xfed9ea51)
    NAMED.put("Infection", java.lang.Float.intBitsToFloat(0xfec7ff4e))
    LIST += java.lang.Float.intBitsToFloat(0xfec7ff4e)
    NAMED.put("Frog Green", java.lang.Float.intBitsToFloat(0xfeb2ff52))
    LIST += java.lang.Float.intBitsToFloat(0xfeb2ff52)
    NAMED.put("Avocado", java.lang.Float.intBitsToFloat(0xfe97ff50))
    LIST += java.lang.Float.intBitsToFloat(0xfe97ff50)
    NAMED.put("Woodlands", java.lang.Float.intBitsToFloat(0xfe62ff53))
    LIST += java.lang.Float.intBitsToFloat(0xfe62ff53)
    NAMED.put("Dark Pine", java.lang.Float.intBitsToFloat(0xfe2fff49))
    LIST += java.lang.Float.intBitsToFloat(0xfe2fff49)
    NAMED.put("Moss Green", java.lang.Float.intBitsToFloat(0xfe3dff55))
    LIST += java.lang.Float.intBitsToFloat(0xfe3dff55)
    NAMED.put("Fern Green", java.lang.Float.intBitsToFloat(0xfe4eff5a))
    LIST += java.lang.Float.intBitsToFloat(0xfe4eff5a)
    NAMED.put("Forest Glen", java.lang.Float.intBitsToFloat(0xfe81ff5a))
    LIST += java.lang.Float.intBitsToFloat(0xfe81ff5a)
    NAMED.put("Malachite", java.lang.Float.intBitsToFloat(0xfeb9ff5a))
    LIST += java.lang.Float.intBitsToFloat(0xfeb9ff5a)
    NAMED.put("Apple Green", java.lang.Float.intBitsToFloat(0xfec6ff5a))
    LIST += java.lang.Float.intBitsToFloat(0xfec6ff5a)
    NAMED.put("Celery", java.lang.Float.intBitsToFloat(0xfee3d559))
    LIST += java.lang.Float.intBitsToFloat(0xfee3d559)
    NAMED.put("Mint Green", java.lang.Float.intBitsToFloat(0xfed2e55b))
    LIST += java.lang.Float.intBitsToFloat(0xfed2e55b)
    NAMED.put("Emerald", java.lang.Float.intBitsToFloat(0xfea9ff5b))
    LIST += java.lang.Float.intBitsToFloat(0xfea9ff5b)
    NAMED.put("Prase", java.lang.Float.intBitsToFloat(0xfe9bff5f))
    LIST += java.lang.Float.intBitsToFloat(0xfe9bff5f)
    NAMED.put("Eucalyptus", java.lang.Float.intBitsToFloat(0xfe7aff62))
    LIST += java.lang.Float.intBitsToFloat(0xfe7aff62)
    NAMED.put("Zucchini", java.lang.Float.intBitsToFloat(0xfe31de7b))
    LIST += java.lang.Float.intBitsToFloat(0xfe31de7b)
    NAMED.put("Soft Teal", java.lang.Float.intBitsToFloat(0xfe86ff76))
    LIST += java.lang.Float.intBitsToFloat(0xfe86ff76)
    NAMED.put("Medium Teal", java.lang.Float.intBitsToFloat(0xfeacff6d))
    LIST += java.lang.Float.intBitsToFloat(0xfeacff6d)
    NAMED.put("Spring Green", java.lang.Float.intBitsToFloat(0xfec0ff60))
    LIST += java.lang.Float.intBitsToFloat(0xfec0ff60)
    NAMED.put("Turquoise", java.lang.Float.intBitsToFloat(0xfecffb6a))
    LIST += java.lang.Float.intBitsToFloat(0xfecffb6a)
    NAMED.put("Seafoam", java.lang.Float.intBitsToFloat(0xfee0f366))
    LIST += java.lang.Float.intBitsToFloat(0xfee0f366)
    NAMED.put("Variscite", java.lang.Float.intBitsToFloat(0xfee6d96f))
    LIST += java.lang.Float.intBitsToFloat(0xfee6d96f)
    NAMED.put("Refreshing Mist", java.lang.Float.intBitsToFloat(0xfedddd96))
    LIST += java.lang.Float.intBitsToFloat(0xfedddd96)
    NAMED.put("Shining Sky", java.lang.Float.intBitsToFloat(0xfed3e496))
    LIST += java.lang.Float.intBitsToFloat(0xfed3e496)
    NAMED.put("Steam", java.lang.Float.intBitsToFloat(0xfecab29a))
    LIST += java.lang.Float.intBitsToFloat(0xfecab29a)
    NAMED.put("Robin Egg Blue", java.lang.Float.intBitsToFloat(0xfec6ff83))
    LIST += java.lang.Float.intBitsToFloat(0xfec6ff83)
    NAMED.put("Denim Blue", java.lang.Float.intBitsToFloat(0xfe92ffaa))
    LIST += java.lang.Float.intBitsToFloat(0xfe92ffaa)
    NAMED.put("Deep Teal", java.lang.Float.intBitsToFloat(0xfe50ff8b))
    LIST += java.lang.Float.intBitsToFloat(0xfe50ff8b)
    NAMED.put("Navy Blue", java.lang.Float.intBitsToFloat(0xfe2bd0b5))
    LIST += java.lang.Float.intBitsToFloat(0xfe2bd0b5)
    NAMED.put("Blueberry", java.lang.Float.intBitsToFloat(0xfe3affb7))
    LIST += java.lang.Float.intBitsToFloat(0xfe3affb7)
    NAMED.put("Prussian Blue", java.lang.Float.intBitsToFloat(0xfe4cffb6))
    LIST += java.lang.Float.intBitsToFloat(0xfe4cffb6)
    NAMED.put("Desert Rain", java.lang.Float.intBitsToFloat(0xfe61d8af))
    LIST += java.lang.Float.intBitsToFloat(0xfe61d8af)
    NAMED.put("Electric Blue", java.lang.Float.intBitsToFloat(0xfe64ffba))
    LIST += java.lang.Float.intBitsToFloat(0xfe64ffba)
    NAMED.put("Hidden Blue", java.lang.Float.intBitsToFloat(0xfe69ffb3))
    LIST += java.lang.Float.intBitsToFloat(0xfe69ffb3)
    NAMED.put("Dull Azure", java.lang.Float.intBitsToFloat(0xfe78ffb4))
    LIST += java.lang.Float.intBitsToFloat(0xfe78ffb4)
    NAMED.put("Ripped Denim", java.lang.Float.intBitsToFloat(0xfe97a0a8))
    LIST += java.lang.Float.intBitsToFloat(0xfe97a0a8)
    NAMED.put("Calm Sky", java.lang.Float.intBitsToFloat(0xfe9fe9b0))
    LIST += java.lang.Float.intBitsToFloat(0xfe9fe9b0)
    NAMED.put("Vapor", java.lang.Float.intBitsToFloat(0xfeb1e5b5))
    LIST += java.lang.Float.intBitsToFloat(0xfeb1e5b5)
    NAMED.put("Powder Blue", java.lang.Float.intBitsToFloat(0xfebae3a6))
    LIST += java.lang.Float.intBitsToFloat(0xfebae3a6)
    NAMED.put("Suds", java.lang.Float.intBitsToFloat(0xfebfcfbe))
    LIST += java.lang.Float.intBitsToFloat(0xfebfcfbe)
    NAMED.put("Strong Cyan", java.lang.Float.intBitsToFloat(0xfeb1ffa6))
    LIST += java.lang.Float.intBitsToFloat(0xfeb1ffa6)
    NAMED.put("Sharp Azure", java.lang.Float.intBitsToFloat(0xfe82ffb5))
    LIST += java.lang.Float.intBitsToFloat(0xfe82ffb5)
    NAMED.put("Blue Eye", java.lang.Float.intBitsToFloat(0xfe7cc7b3))
    LIST += java.lang.Float.intBitsToFloat(0xfe7cc7b3)
    NAMED.put("Subtlety", java.lang.Float.intBitsToFloat(0xfe7fd7be))
    LIST += java.lang.Float.intBitsToFloat(0xfe7fd7be)
    NAMED.put("Rough Sapphire", java.lang.Float.intBitsToFloat(0xfe6ff8bb))
    LIST += java.lang.Float.intBitsToFloat(0xfe6ff8bb)
    NAMED.put("Iris", java.lang.Float.intBitsToFloat(0xfe65f1bf))
    LIST += java.lang.Float.intBitsToFloat(0xfe65f1bf)
    NAMED.put("Cornflower Blue", java.lang.Float.intBitsToFloat(0xfe5cf4bd))
    LIST += java.lang.Float.intBitsToFloat(0xfe5cf4bd)
    NAMED.put("Polished Sapphire", java.lang.Float.intBitsToFloat(0xfe45ffbc))
    LIST += java.lang.Float.intBitsToFloat(0xfe45ffbc)
    NAMED.put("Royal Blue", java.lang.Float.intBitsToFloat(0xfe38ffbc))
    LIST += java.lang.Float.intBitsToFloat(0xfe38ffbc)
    NAMED.put("Indigo", java.lang.Float.intBitsToFloat(0xfe2efdbe))
    LIST += java.lang.Float.intBitsToFloat(0xfe2efdbe)
    NAMED.put("Space Blue", java.lang.Float.intBitsToFloat(0xfe21dfb6))
    LIST += java.lang.Float.intBitsToFloat(0xfe21dfb6)
    NAMED.put("Thick Amethyst", java.lang.Float.intBitsToFloat(0xfe40ffc2))
    LIST += java.lang.Float.intBitsToFloat(0xfe40ffc2)
    NAMED.put("Juicy Grape", java.lang.Float.intBitsToFloat(0xfe4dffc2))
    LIST += java.lang.Float.intBitsToFloat(0xfe4dffc2)
    NAMED.put("Blacklight Glow", java.lang.Float.intBitsToFloat(0xfe61e9c7))
    LIST += java.lang.Float.intBitsToFloat(0xfe61e9c7)
    NAMED.put("Purple Freesia", java.lang.Float.intBitsToFloat(0xfe75f6c6))
    LIST += java.lang.Float.intBitsToFloat(0xfe75f6c6)
    NAMED.put("Thin Amethyst", java.lang.Float.intBitsToFloat(0xfe60ffc3))
    LIST += java.lang.Float.intBitsToFloat(0xfe60ffc3)
    NAMED.put("Orchid", java.lang.Float.intBitsToFloat(0xfe8deeca))
    LIST += java.lang.Float.intBitsToFloat(0xfe8deeca)
    NAMED.put("Lavender", java.lang.Float.intBitsToFloat(0xfea5e8c5))
    LIST += java.lang.Float.intBitsToFloat(0xfea5e8c5)
    NAMED.put("Lilac", java.lang.Float.intBitsToFloat(0xfeb8e4cc))
    LIST += java.lang.Float.intBitsToFloat(0xfeb8e4cc)
    NAMED.put("Soap", java.lang.Float.intBitsToFloat(0xfecbc9c6))
    LIST += java.lang.Float.intBitsToFloat(0xfecbc9c6)
    NAMED.put("Pink Tutu", java.lang.Float.intBitsToFloat(0xfed6ced8))
    LIST += java.lang.Float.intBitsToFloat(0xfed6ced8)
    NAMED.put("Thistle", java.lang.Float.intBitsToFloat(0xfea2e9d3))
    LIST += java.lang.Float.intBitsToFloat(0xfea2e9d3)
    NAMED.put("Heliotrope", java.lang.Float.intBitsToFloat(0xfe9eeada))
    LIST += java.lang.Float.intBitsToFloat(0xfe9eeada)
    NAMED.put("Purple", java.lang.Float.intBitsToFloat(0xfe7fffd9))
    LIST += java.lang.Float.intBitsToFloat(0xfe7fffd9)
    NAMED.put("Wisteria", java.lang.Float.intBitsToFloat(0xfe7affcc))
    LIST += java.lang.Float.intBitsToFloat(0xfe7affcc)
    NAMED.put("Medium Plum", java.lang.Float.intBitsToFloat(0xfe6cffd8))
    LIST += java.lang.Float.intBitsToFloat(0xfe6cffd8)
    NAMED.put("Violet", java.lang.Float.intBitsToFloat(0xfe58ffcc))
    LIST += java.lang.Float.intBitsToFloat(0xfe58ffcc)
    NAMED.put("Grape Lollipop", java.lang.Float.intBitsToFloat(0xfe3aeecc))
    LIST += java.lang.Float.intBitsToFloat(0xfe3aeecc)
    NAMED.put("Mulberry", java.lang.Float.intBitsToFloat(0xfe39f2da))
    LIST += java.lang.Float.intBitsToFloat(0xfe39f2da)
    NAMED.put("Grape Soda", java.lang.Float.intBitsToFloat(0xfe25ffca))
    LIST += java.lang.Float.intBitsToFloat(0xfe25ffca)
    NAMED.put("Eggplant", java.lang.Float.intBitsToFloat(0xfe1cdfcc))
    LIST += java.lang.Float.intBitsToFloat(0xfe1cdfcc)
    NAMED.put("Cherry Syrup", java.lang.Float.intBitsToFloat(0xfe2fbcf4))
    LIST += java.lang.Float.intBitsToFloat(0xfe2fbcf4)
    NAMED.put("Plum Juice", java.lang.Float.intBitsToFloat(0xfe58ffe7))
    LIST += java.lang.Float.intBitsToFloat(0xfe58ffe7)
    NAMED.put("Fruit Punch", java.lang.Float.intBitsToFloat(0xfe67fff6))
    LIST += java.lang.Float.intBitsToFloat(0xfe67fff6)
    NAMED.put("Bubble Gum", java.lang.Float.intBitsToFloat(0xfe96e5ee))
    LIST += java.lang.Float.intBitsToFloat(0xfe96e5ee)
    NAMED.put("Pink Lemonade", java.lang.Float.intBitsToFloat(0xfea0e3ed))
    LIST += java.lang.Float.intBitsToFloat(0xfea0e3ed)
    NAMED.put("Shrimp", java.lang.Float.intBitsToFloat(0xfeb9cbfc))
    LIST += java.lang.Float.intBitsToFloat(0xfeb9cbfc)
    NAMED.put("Flamingo", java.lang.Float.intBitsToFloat(0xfe8ae5fb))
    LIST += java.lang.Float.intBitsToFloat(0xfe8ae5fb)
    NAMED.put("Rose", java.lang.Float.intBitsToFloat(0xfe79fffc))
    LIST += java.lang.Float.intBitsToFloat(0xfe79fffc)
    NAMED.put("Carmine", java.lang.Float.intBitsToFloat(0xfe5fff04))
    LIST += java.lang.Float.intBitsToFloat(0xfe5fff04)
    NAMED.put("Bologna", java.lang.Float.intBitsToFloat(0xfe57b200))
    LIST += java.lang.Float.intBitsToFloat(0xfe57b200)
    NAMED.put("Raspberry", java.lang.Float.intBitsToFloat(0xfe49f802))
    LIST += java.lang.Float.intBitsToFloat(0xfe49f802)
  }

  /** Converts existing Color entries in [[sge.graphics.Colors]] from RGBA to HSLuv format. */
  def editKnownColors(): Unit =
    for (c <- sge.graphics.Colors.colors.values) {
      val f = ColorTools.fromColor(c)
      c.set(ColorTools.channelH(f), ColorTools.channelS(f), ColorTools.channelL(f), c.a)
    }

  /** Appends HSLuv-compatible Color instances to the map in [[sge.graphics.Colors]]. */
  def appendToKnownColors(): Unit =
    for ((key, value) <- NAMED) {
      val f = value
      sge.graphics.Colors.put(key, new sge.graphics.Color(ColorTools.channelH(f), ColorTools.channelS(f), ColorTools.channelL(f), ColorTools.alpha(f)))
    }
}
