/*
 * Ported from libGDX - https://github.com/libgdx/libgdx
 * Original source: com/badlogic/gdx/scenes/scene2d/ui/TextField.java
 * Original authors: mzechner, Nathan Sweet
 * Licensed under the Apache License, Version 2.0
 *
 * Migration notes:
 *   Convention: null -> Nullable; (using Sge) context; boundary/break; Clipboard from sge; Skin constructors present
 *   Idiom: split packages
 *   Note: Java-style getters/setters retained — many methods have validation/events logic, getText conflicts with constructor param name; converting would be a large refactor
 *   Convention: opaque Button/Key types for type-safe button/key code params
 *   Audited: 2026-03-03
 *
 * Scala port copyright 2025-2026 Mateusz Kubuszok
 */
package sge
package scenes
package scene2d
package ui

import scala.language.implicitConversions
import scala.util.boundary

import sge.Input.{ Button, Key }
import sge.graphics.Color
import sge.graphics.g2d.{ Batch, BitmapFont, GlyphLayout }
import sge.math.{ MathUtils, Vector2 }
import sge.scenes.scene2d.{ Actor, Group, InputEvent, InputListener }
import sge.scenes.scene2d.utils.{ ChangeListener, ClickListener, Disableable, Drawable, UIUtils }
import sge.utils.{ Align, Clipboard, DynamicArray, Nullable, Seconds, Timer }

/** A single-line text input field. <p> The preferred height of a text field is the height of the {@link TextFieldStyle#font} and {@link TextFieldStyle#background}. The preferred width of a text field
  * is 150, a relatively arbitrary size. <p> The text field will copy the currently selected text when ctrl+c is pressed, and paste any text in the clipboard when ctrl+v is pressed. Clipboard
  * functionality is provided via the {@link Clipboard} interface. Currently there are two standard implementations, one for the desktop and one for Android. The Android clipboard is a stub, as copy &
  * pasting on Android is not supported yet. <p> The text field allows you to specify an {@link OnscreenKeyboard} for displaying a softkeyboard and piping all key events generated by the keyboard to
  * the text field. There are two standard implementations, one for the desktop and one for Android. The desktop keyboard is a stub, as a softkeyboard is not needed on the desktop. The Android
  * {@link OnscreenKeyboard} implementation will bring up the default IME.
  * @author
  *   mzechner
  * @author
  *   Nathan Sweet
  */
class TextField(text: Nullable[String], style: TextField.TextFieldStyle)(using Sge) extends Widget with Disableable with Styleable[TextField.TextFieldStyle] {

  import TextField._

  protected var _text:          String              = ""
  protected var cursor:         Int                 = 0
  protected var selectionStart: Int                 = 0
  protected var hasSelection:   Boolean             = false
  protected var writeEnters:    Boolean             = false
  protected val glyphLayout:    GlyphLayout         = GlyphLayout()
  protected val glyphPositions: DynamicArray[Float] = DynamicArray[Float]()

  protected var _style:       TextField.TextFieldStyle    = scala.compiletime.uninitialized
  private var messageText:    Nullable[String]            = Nullable.empty
  protected var displayText:  CharSequence                = ""
  var clipboard:              Clipboard                   = Sge().application.getClipboard()
  var inputListener:          InputListener               = scala.compiletime.uninitialized
  var listener:               Nullable[TextFieldListener] = Nullable.empty
  var filter:                 Nullable[TextFieldFilter]   = Nullable.empty
  var keyboard:               OnscreenKeyboard            = DEFAULT_ONSCREEN_KEYBOARD
  var focusTraversal:         Boolean                     = true
  var onlyFontChars:          Boolean                     = true
  var disabled:               Boolean                     = false
  private var textHAlign:     Align                       = Align.left
  private var selectionX:     Float                       = 0
  private var selectionWidth: Float                       = 0

  var undoText:       String = ""
  var lastChangeTime: Long   = 0

  var passwordMode:              Boolean                           = false
  private var passwordBuffer:    Nullable[java.lang.StringBuilder] = Nullable.empty
  private var passwordCharacter: Char                              = BULLET

  protected var fontOffset:          Float                      = 0
  protected var textHeight:          Float                      = 0
  protected var textOffset:          Float                      = 0
  var renderOffset:                  Float                      = 0
  protected var visibleTextStart:    Int                        = 0
  protected var visibleTextEnd:      Int                        = 0
  private var maxLength:             Int                        = 0
  private var autocompleteOptions:   Nullable[Array[String]]    = Nullable.empty
  private var keyboardType:          Input.OnscreenKeyboardType = Input.OnscreenKeyboardType.Default
  private var preventAutoCorrection: Boolean                    = false

  var focused:   Boolean    = false
  var cursorOn:  Boolean    = false
  var blinkTime: Seconds    = Seconds(0.32f)
  val blinkTask: Timer.Task = new Timer.Task {
    def run(): Unit =
      if (stage.isEmpty) {
        cancel()
      } else {
        cursorOn = !cursorOn
        Sge().graphics.requestRendering()
      }
  }

  val keyRepeatTask:            KeyRepeatTask = KeyRepeatTask()
  var programmaticChangeEvents: Boolean       = false

  setStyle(style)
  initialize()
  setText(text.getOrElse(""))
  setSize(getPrefWidth, getPrefHeight)

  /** Creates a new TextField. */
  def this(text: Nullable[String], skin: Skin)(using Sge) = this(text, skin.get[TextField.TextFieldStyle])

  /** Creates a new TextField. */
  def this(text: Nullable[String], skin: Skin, styleName: String)(using Sge) = this(text, skin.get[TextField.TextFieldStyle](styleName))

  protected def initialize(): Unit = {
    inputListener = createInputListener()
    addListener(inputListener)
  }

  protected def createInputListener(): InputListener =
    TextFieldClickListener()

  protected def letterUnderCursor(x: Float): Int = boundary {
    var adjustedX  = x - textOffset - fontOffset + _style.font.data.cursorX + glyphPositions(visibleTextStart)
    val background = getBackgroundDrawable()
    background.foreach { bg =>
      adjustedX -= bg.leftWidth
    }
    val n = this.glyphPositions.size
    var i = 1
    while (i < n) {
      if (glyphPositions(i) > adjustedX) {
        if (glyphPositions(i) - adjustedX <= adjustedX - glyphPositions(i - 1)) boundary.break(i)
        else boundary.break(i - 1)
      }
      i += 1
    }
    n - 1
  }

  protected def isWordCharacter(c: Char): Boolean =
    Character.isLetterOrDigit(c)

  protected def wordUnderCursor(at: Int): Array[Int] = {
    val text  = this._text
    var right = text.length()
    var left  = 0
    var index = at
    if (at >= text.length()) {
      left = text.length()
      right = 0
    } else {
      while (index < right)
        if (!isWordCharacter(text.charAt(index))) {
          right = index
          index = right // break
        } else {
          index += 1
        }
      index = at - 1
      while (index > -1)
        if (!isWordCharacter(text.charAt(index))) {
          left = index + 1
          index = -1 // break
        } else {
          index -= 1
        }
    }
    Array(left, right)
  }

  private[ui] def wordUnderCursor(x: Float): Array[Int] =
    wordUnderCursor(letterUnderCursor(x))

  private[ui] def withinMaxLength(size: Int): Boolean =
    maxLength <= 0 || size < maxLength

  def setMaxLength(maxLength: Int): Unit =
    this.maxLength = maxLength

  def getMaxLength: Int = this.maxLength

  /** A list of possible strings that are valid to autocomplete. Currently only has an effect on mobile with NativeOnscreenKeyboard
    */
  def setAutocompleteOptions(autocompleteOptions: Nullable[Array[String]]): Unit =
    this.autocompleteOptions = autocompleteOptions

  /** Which {@link Input.OnscreenKeyboardType} to use. Mainly used for mobile, will also be referenced for password masking */
  def setKeyboardType(keyboardType: Input.OnscreenKeyboardType): Unit =
    this.keyboardType = keyboardType

  /** Whether if auto correction is provided by the system, it should be suppressed. Will be considered true, if {@link Input.OnscreenKeyboardType} is `Password`
    */
  def setPreventAutoCorrection(preventAutoCorrection: Boolean): Unit =
    this.preventAutoCorrection = preventAutoCorrection

  /** When false, text set by {@link #setText(String)} may contain characters not in the font, a space will be displayed instead. When true (the default), characters not in the font are stripped by
    * setText. Characters not in the font are always stripped when typed or pasted.
    */
  def setOnlyFontChars(onlyFontChars: Boolean): Unit =
    this.onlyFontChars = onlyFontChars

  def setStyle(style: TextField.TextFieldStyle): Unit = {
    this._style = style

    textHeight = style.font.capHeight - style.font.descent * 2
    updateDisplayText()
    invalidateHierarchy()
  }

  /** Returns the text field's style. Modifying the returned style may not have an effect until {@link #setStyle(TextFieldStyle)} is called.
    */
  def getStyle: TextField.TextFieldStyle = _style

  protected def calculateOffsets(): Unit = {
    var visibleWidth = this.width
    val background   = getBackgroundDrawable()
    background.foreach { bg =>
      visibleWidth -= bg.leftWidth + bg.rightWidth
    }

    val glyphCount = glyphPositions.size

    // Check if the cursor has gone out the left or right side of the visible area and adjust renderOffset.
    cursor = MathUtils.clamp(cursor, 0, glyphCount - 1)
    val distance = glyphPositions(Math.max(0, cursor - 1)) + renderOffset
    if (distance <= 0)
      renderOffset -= distance
    else {
      val index = Math.min(glyphCount - 1, cursor + 1)
      val minX  = glyphPositions(index) - visibleWidth
      if (-renderOffset < minX) renderOffset = -minX
    }

    // Prevent renderOffset from starting too close to the end, eg after text was deleted.
    var maxOffset = 0f
    val width     = glyphPositions(glyphCount - 1)
    var i         = glyphCount - 2
    boundary {
      while (i >= 0) {
        val x = glyphPositions(i)
        if (width - x > visibleWidth) boundary.break(())
        maxOffset = x
        i -= 1
      }
    }
    if (-renderOffset > maxOffset) renderOffset = -maxOffset

    // calculate first visible char based on render offset
    visibleTextStart = 0
    var startX = 0f
    i = 0
    boundary {
      while (i < glyphCount) {
        if (glyphPositions(i) >= -renderOffset) {
          visibleTextStart = i
          startX = glyphPositions(i)
          boundary.break(())
        }
        i += 1
      }
    }

    // calculate last visible char based on visible width and render offset
    var end  = visibleTextStart + 1
    val endX = visibleWidth - renderOffset
    val n    = Math.min(displayText.length(), glyphCount)
    boundary {
      while (end <= n) {
        if (glyphPositions(end) > endX) boundary.break(())
        end += 1
      }
    }
    visibleTextEnd = Math.max(0, end - 1)

    if ((textHAlign & Align.left).toInt == 0) {
      textOffset = visibleWidth - glyphPositions(visibleTextEnd) - fontOffset + startX
      if ((textHAlign & Align.center).toInt != 0) textOffset = Math.round(textOffset * 0.5f).toFloat
    } else {
      textOffset = startX + renderOffset
    }

    // calculate selection x position and width
    if (hasSelection) {
      val minIndex = Math.min(cursor, selectionStart)
      val maxIndex = Math.max(cursor, selectionStart)
      val minX     = Math.max(glyphPositions(minIndex) - glyphPositions(visibleTextStart), -textOffset)
      val maxX     = Math.min(glyphPositions(maxIndex) - glyphPositions(visibleTextStart), visibleWidth - textOffset)
      selectionX = minX
      selectionWidth = maxX - minX - _style.font.data.cursorX
    }
  }

  protected def getBackgroundDrawable(): Nullable[Drawable] =
    if (disabled && _style.disabledBackground.isDefined) _style.disabledBackground
    else if (_style.focusedBackground.isDefined && hasKeyboardFocus) _style.focusedBackground
    else _style.background

  override def draw(batch: Batch, parentAlpha: Float): Unit = {
    val focused = hasKeyboardFocus
    if (focused != this.focused || (focused && !blinkTask.isScheduled)) {
      this.focused = focused
      blinkTask.cancel()
      cursorOn = focused
      if (focused)
        Timer.schedule(blinkTask, blinkTime, blinkTime)
      else
        keyRepeatTask.cancel()
    } else if (!focused) {
      cursorOn = false
    }

    val font = _style.font
    val fontColor: Color =
      if (disabled && _style.disabledFontColor.isDefined) _style.disabledFontColor.getOrElse(_style.fontColor)
      else if (focused && _style.focusedFontColor.isDefined) _style.focusedFontColor.getOrElse(_style.fontColor)
      else _style.fontColor
    val selection   = _style.selection
    val cursorPatch = _style.cursor
    val background  = getBackgroundDrawable()

    val color = this.color
    val tx    = this.x
    val ty    = this.y
    val tw    = this.width
    val th    = this.height

    batch.setColor(color.r, color.g, color.b, color.a * parentAlpha)
    var bgLeftWidth  = 0f
    var bgRightWidth = 0f
    background.foreach { bg =>
      drawBackground(bg, batch, tx, ty, tw, th)
      bgLeftWidth = bg.leftWidth
      bgRightWidth = bg.rightWidth
    }

    val textY = getTextY(font, background)
    calculateOffsets()

    if (focused && hasSelection) {
      selection.foreach { sel =>
        drawSelection(sel, batch, font, tx + bgLeftWidth, ty + textY)
      }
    }

    val yOffset = if (font.flipped) -textHeight else 0
    if (displayText.length() == 0) {
      if ((!focused || disabled) && messageText.isDefined) {
        val messageFont = _style.messageFont.getOrElse(font)
        _style.messageFontColor.fold {
          messageFont.setColor(0.7f, 0.7f, 0.7f, color.a * parentAlpha)
        } { mfc =>
          messageFont.setColor(mfc.r, mfc.g, mfc.b, mfc.a * color.a * parentAlpha)
        }
        drawMessageText(batch, messageFont, tx + bgLeftWidth, ty + textY + yOffset, tw - bgLeftWidth - bgRightWidth)
      }
    } else {
      val data          = font.data
      val markupEnabled = data.markupEnabled
      data.markupEnabled = false
      font.setColor(fontColor.r, fontColor.g, fontColor.b, fontColor.a * color.a * parentAlpha)
      drawText(batch, font, tx + bgLeftWidth, ty + textY + yOffset)
      data.markupEnabled = markupEnabled
    }
    if (!disabled && cursorOn) {
      cursorPatch.foreach { cp =>
        drawCursor(cp, batch, font, tx + bgLeftWidth, ty + textY)
      }
    }
  }

  protected def getTextY(font: BitmapFont, background: Nullable[Drawable]): Float = {
    val height = this.height
    var textY  = textHeight / 2 + font.descent
    background.fold {
      textY = textY + height / 2
    } { bg =>
      val bottom = bg.bottomHeight
      textY = textY + (height - bg.topHeight - bottom) / 2 + bottom
    }
    if (font.integerPositions) textY = textY.toInt.toFloat
    textY
  }

  protected def drawBackground(background: Drawable, batch: Batch, x: Float, y: Float, width: Float, height: Float): Unit =
    background.draw(batch, x, y, width, height)

  /** Draws selection rectangle * */
  protected def drawSelection(selection: Drawable, batch: Batch, font: BitmapFont, x: Float, y: Float): Unit =
    selection.draw(batch, x + textOffset + selectionX + fontOffset, y - textHeight - font.descent, selectionWidth, textHeight)

  protected def drawText(batch: Batch, font: BitmapFont, x: Float, y: Float): Unit =
    font.draw(batch, displayText, x + textOffset, y, visibleTextStart, visibleTextEnd, 0, Align.left.toInt, false)

  protected def drawMessageText(batch: Batch, font: BitmapFont, x: Float, y: Float, maxWidth: Float): Unit =
    messageText.foreach { msg =>
      font.draw(batch, msg, x, y, 0, msg.length(), maxWidth, textHAlign.toInt, false, Nullable("..."))
    }

  protected def drawCursor(cursorPatch: Drawable, batch: Batch, font: BitmapFont, x: Float, y: Float): Unit =
    cursorPatch.draw(
      batch,
      x + textOffset + glyphPositions(cursor) - glyphPositions(visibleTextStart) + fontOffset + font.data.cursorX,
      y - textHeight - font.descent,
      cursorPatch.minWidth,
      textHeight
    )

  protected def updateDisplayText(): Unit = {
    val font       = _style.font
    val data       = font.data
    val text       = this._text
    val textLength = text.length()

    val buffer = new java.lang.StringBuilder()
    var i      = 0
    while (i < textLength) {
      val c = text.charAt(i)
      buffer.append(if (data.hasGlyph(c)) c else ' ')
      i += 1
    }
    val newDisplayText = buffer.toString

    if (passwordMode && data.hasGlyph(passwordCharacter)) {
      val pwBuf = passwordBuffer.getOrElse {
        val sb = new java.lang.StringBuilder(newDisplayText.length())
        passwordBuffer = Nullable(sb)
        sb
      }
      if (pwBuf.length() > textLength)
        pwBuf.setLength(textLength)
      else {
        var j = pwBuf.length()
        while (j < textLength) {
          pwBuf.append(passwordCharacter)
          j += 1
        }
      }
      displayText = pwBuf
    } else {
      displayText = newDisplayText
    }

    val markupEnabled = data.markupEnabled
    data.markupEnabled = false
    glyphLayout.setText(font, displayText.toString.replace('\r', ' ').replace('\n', ' '))
    data.markupEnabled = markupEnabled

    glyphPositions.clear()
    var x = 0f
    if (glyphLayout.runs.nonEmpty) {
      val run       = glyphLayout.runs.first
      val xAdvances = run.xAdvances
      fontOffset = xAdvances.first
      var idx = 1
      while (idx < xAdvances.size) {
        glyphPositions.add(x)
        x += xAdvances(idx)
        idx += 1
      }
    } else {
      fontOffset = 0
    }
    glyphPositions.add(x)

    visibleTextStart = Math.min(visibleTextStart, glyphPositions.size - 1)
    visibleTextEnd = MathUtils.clamp(visibleTextEnd, visibleTextStart, glyphPositions.size - 1)

    if (selectionStart > newDisplayText.length()) selectionStart = textLength
  }

  /** Copies the contents of this TextField to the {@link Clipboard} implementation set on this TextField. */
  def copy(): Unit =
    if (hasSelection && !passwordMode) {
      clipboard.contents = Nullable(_text.substring(Math.min(cursor, selectionStart), Math.max(cursor, selectionStart)))
    }

  /** Copies the selected contents of this TextField to the {@link Clipboard} implementation set on this TextField, then removes it.
    */
  def cut(): Unit =
    cut(programmaticChangeEvents)

  private[ui] def cut(fireChangeEvent: Boolean): Unit =
    if (hasSelection && !passwordMode) {
      copy()
      cursor = delete(fireChangeEvent)
      updateDisplayText()
    }

  private[ui] def paste(content: Nullable[String], fireChangeEvent: Boolean): Unit =
    content.foreach { rawContent =>
      val buffer     = new java.lang.StringBuilder()
      var textLength = _text.length()
      if (hasSelection) textLength -= Math.abs(cursor - selectionStart)
      val data = _style.font.data
      var i    = 0
      val n    = rawContent.length()
      boundary {
        while (i < n) {
          if (!withinMaxLength(textLength + buffer.length())) boundary.break(())
          val c = rawContent.charAt(i)
          if (!(writeEnters && (c == NEWLINE || c == CARRIAGE_RETURN))) {
            if (c == '\r' || c == '\n') { i += 1 }
            else if (onlyFontChars && !data.hasGlyph(c)) { i += 1 }
            else {
              var accepted = true
              filter.foreach { f =>
                if (!f.acceptChar(this, c)) accepted = false
              }
              if (accepted) {
                buffer.append(c)
              }
              i += 1
            }
          } else {
            buffer.append(c)
            i += 1
          }
        }
      }
      val processedContent = buffer.toString

      if (hasSelection) cursor = delete(fireChangeEvent)
      if (fireChangeEvent)
        changeText(_text, insert(cursor, processedContent, _text))
      else
        _text = insert(cursor, processedContent, _text)
      updateDisplayText()
      cursor += processedContent.length()
    }

  private[ui] def insert(position: Int, text: CharSequence, to: String): String =
    if (to.length() == 0) text.toString
    else to.substring(0, position) + text + to.substring(position, to.length())

  private[ui] def delete(fireChangeEvent: Boolean): Int = {
    val from     = selectionStart
    val to       = cursor
    val minIndex = Math.min(from, to)
    val maxIndex = Math.max(from, to)
    val newText  = (if (minIndex > 0) _text.substring(0, minIndex) else "") +
      (if (maxIndex < _text.length()) _text.substring(maxIndex, _text.length()) else "")
    if (fireChangeEvent)
      changeText(_text, newText)
    else
      _text = newText
    clearSelection()
    minIndex
  }

  /** Sets the {@link Stage#setKeyboardFocus(Actor) keyboard focus} to the next TextField. If no next text field is found, the onscreen keyboard is hidden. Does nothing if the text field is not in a
    * stage.
    * @param up
    *   If true, the text field with the same or next smallest y coordinate is found, else the next highest.
    * @return
    *   The textfield, the focus has been transferred to
    */
  def next(up: Boolean): Nullable[TextField] = boundary {
    if (this.stage.isEmpty) boundary.break(Nullable.empty)
    val stg = this.stage.getOrElse(throw new IllegalStateException("TextField must be on a stage"))
    var current: TextField = this
    val currentCoords = current.getParent.getOrElse(throw new IllegalStateException("TextField must have a parent")).localToStageCoordinates(tmp2.set(current.x, current.y))
    val bestCoords    = tmp1
    val continue      = true
    while (continue) {
      var textField = current.findNextTextField(stg.getActors, Nullable.empty, bestCoords, currentCoords, up)
      if (textField.isEmpty) { // Try to wrap around.
        if (up)
          currentCoords.set(-Float.MaxValue, -Float.MaxValue)
        else
          currentCoords.set(Float.MaxValue, Float.MaxValue)
        textField = current.findNextTextField(stg.getActors, Nullable.empty, bestCoords, currentCoords, up)
      }
      if (textField.isEmpty) {
        boundary.break(Nullable.empty)
      }
      val tf = textField.getOrElse(throw new IllegalStateException("textField must be defined"))
      if (stg.setKeyboardFocus(Nullable(tf))) {
        tf.selectAll()
        boundary.break(Nullable(tf))
      }
      current = tf
      currentCoords.set(bestCoords)
    }
    Nullable.empty // unreachable but needed for type
  }

  /** @return May be null. */
  private def findNextTextField(actors: DynamicArray[Actor], best: Nullable[TextField], bestCoords: Vector2, currentCoords: Vector2, up: Boolean): Nullable[TextField] = boundary {
    var currentBest = best
    var i           = 0
    val n           = actors.size
    while (i < n) {
      val actor = actors(i)
      actor match {
        case textField: TextField if !(textField eq this) =>
          if (!(textField.isDisabled || !textField.focusTraversal || !textField.ascendantsVisible())) {
            val actorCoords = actor.getParent.getOrElse(throw new IllegalStateException("Actor must have a parent")).localToStageCoordinates(tmp3.set(actor.x, actor.y))
            val below       = actorCoords.y != currentCoords.y && (actorCoords.y < currentCoords.y ^ up)
            val right       = actorCoords.y == currentCoords.y && (actorCoords.x > currentCoords.x ^ up)
            if (below || right) {
              var better = currentBest.isEmpty || (actorCoords.y != bestCoords.y && (actorCoords.y > bestCoords.y ^ up))
              if (!better) better = actorCoords.y == bestCoords.y && (actorCoords.x < bestCoords.x ^ up)
              if (better) {
                currentBest = Nullable(textField)
                bestCoords.set(actorCoords)
              }
            }
          }
        case group: Group =>
          currentBest = findNextTextField(group.getChildren, currentBest, bestCoords, currentCoords, up)
        case _ =>
      }
      i += 1
    }
    currentBest
  }

  def getDefaultInputListener: InputListener = inputListener

  /** @param listener May be null. */
  def setTextFieldListener(listener: Nullable[TextFieldListener]): Unit =
    this.listener = listener

  /** @param filter May be null. */
  def setTextFieldFilter(filter: Nullable[TextFieldFilter]): Unit =
    this.filter = filter

  def getTextFieldFilter: Nullable[TextFieldFilter] = filter

  /** If true (the default), tab/shift+tab will move to the next text field. */
  def setFocusTraversal(focusTraversal: Boolean): Unit =
    this.focusTraversal = focusTraversal

  def getFocusTraversal: Boolean = focusTraversal

  /** @return May be null. */
  def getMessageText: Nullable[String] = messageText

  /** Sets the text that will be drawn in the text field if no text has been entered.
    * @param messageText
    *   may be null.
    */
  def setMessageText(messageText: Nullable[String]): Unit =
    this.messageText = messageText

  /** @param str If null, "" is used. */
  def appendText(str: Nullable[String]): Unit = {
    val s = str.getOrElse("")
    clearSelection()
    cursor = _text.length()
    paste(Nullable(s), programmaticChangeEvents)
  }

  /** @param str If null, "" is used. */
  def setText(str: Nullable[String]): Unit = {
    val s = str.getOrElse("")
    if (s == _text) ()
    else {
      clearSelection()
      val oldText = _text
      _text = ""
      paste(Nullable(s), false)
      if (programmaticChangeEvents) changeText(oldText, _text)
      cursor = 0
    }
  }

  /** @return Never null, might be an empty string. */
  def getText: String = _text

  /** @return True if the text was changed. */
  private[ui] def changeText(oldText: String, newText: String): Boolean =
    if (newText == oldText) false
    else {
      _text = newText
      val changeEvent = Actor.POOLS.obtain[ChangeListener.ChangeEvent]
      val cancelled   = fire(changeEvent)
      if (cancelled) _text = oldText
      Actor.POOLS.free(changeEvent)
      !cancelled
    }

  /** If false, methods that change the text will not fire {@link ChangeEvent}, the event will be fired only when the user changes the text.
    */
  def setProgrammaticChangeEvents(programmaticChangeEvents: Boolean): Unit =
    this.programmaticChangeEvents = programmaticChangeEvents

  def getProgrammaticChangeEvents: Boolean = programmaticChangeEvents

  def getSelectionStart: Int = selectionStart

  def getSelection: String =
    if (hasSelection) _text.substring(Math.min(selectionStart, cursor), Math.max(selectionStart, cursor))
    else ""

  /** Sets the selected text. */
  def setSelection(selectionStart: Int, selectionEnd: Int): Unit = {
    if (selectionStart < 0) throw new IllegalArgumentException("selectionStart must be >= 0")
    if (selectionEnd < 0) throw new IllegalArgumentException("selectionEnd must be >= 0")
    var ss = Math.min(_text.length(), selectionStart)
    var se = Math.min(_text.length(), selectionEnd)
    if (se == ss) {
      clearSelection()
    } else {
      if (se < ss) {
        val temp = se
        se = ss
        ss = temp
      }
      hasSelection = true
      this.selectionStart = ss
      cursor = se
    }
  }

  def selectAll(): Unit =
    setSelection(0, _text.length())

  def clearSelection(): Unit =
    hasSelection = false

  /** Sets the cursor position and clears any selection. */
  def setCursorPosition(cursorPosition: Int): Unit = {
    if (cursorPosition < 0) throw new IllegalArgumentException("cursorPosition must be >= 0")
    clearSelection()
    cursor = Math.min(cursorPosition, _text.length())
  }

  def getCursorPosition: Int = cursor

  /** Default is an instance of {@link DefaultOnscreenKeyboard}. */
  def getOnscreenKeyboard: OnscreenKeyboard = keyboard

  def setOnscreenKeyboard(keyboard: OnscreenKeyboard): Unit =
    this.keyboard = keyboard

  def setClipboard(clipboard: Clipboard): Unit =
    this.clipboard = clipboard

  override def getPrefWidth: Float = 150

  override def getPrefHeight: Float = {
    var topAndBottom = 0f
    var minHeight    = 0f
    _style.background.foreach { bg =>
      topAndBottom = Math.max(topAndBottom, bg.bottomHeight + bg.topHeight)
      minHeight = Math.max(minHeight, bg.minHeight)
    }
    _style.focusedBackground.foreach { fb =>
      topAndBottom = Math.max(topAndBottom, fb.bottomHeight + fb.topHeight)
      minHeight = Math.max(minHeight, fb.minHeight)
    }
    _style.disabledBackground.foreach { db =>
      topAndBottom = Math.max(topAndBottom, db.bottomHeight + db.topHeight)
      minHeight = Math.max(minHeight, db.minHeight)
    }
    Math.max(topAndBottom + textHeight, minHeight)
  }

  /** Sets text horizontal alignment (left, center or right).
    * @see
    *   Align
    */
  def setAlignment(alignment: Align): Unit =
    this.textHAlign = alignment

  def getAlignment: Align = textHAlign

  /** If true, the text in this text field will be shown as bullet characters.
    * @see
    *   #setPasswordCharacter(char)
    */
  def setPasswordMode(passwordMode: Boolean): Unit = {
    this.passwordMode = passwordMode
    updateDisplayText()
  }

  def isPasswordMode: Boolean = passwordMode

  /** Sets the password character for the text field. The character must be present in the {@link BitmapFont}. Default is 149 (bullet).
    */
  def setPasswordCharacter(passwordCharacter: Char): Unit = {
    this.passwordCharacter = passwordCharacter
    if (passwordMode) updateDisplayText()
  }

  def setBlinkTime(blinkTime: Float): Unit =
    this.blinkTime = Seconds(blinkTime)

  def setDisabled(isDisabled: Boolean): Unit =
    this.disabled = isDisabled

  def isDisabled: Boolean = disabled

  protected def moveCursor(forward: Boolean, jump: Boolean): Unit = {
    val limit      = if (forward) _text.length() else 0
    val charOffset = if (forward) 0 else -1
    if (forward) {
      cursor += 1
      while (cursor < limit && jump && continueCursor(cursor, charOffset))
        cursor += 1
    } else {
      cursor -= 1
      while (cursor > limit && jump && continueCursor(cursor, charOffset))
        cursor -= 1
    }
  }

  protected def continueCursor(index: Int, offset: Int): Boolean = {
    val c = _text.charAt(index + offset)
    isWordCharacter(c)
  }

  class KeyRepeatTask extends Timer.Task {
    var keycode: Key = Key(0)

    def run(): Unit =
      if (stage.isEmpty) {
        cancel()
      } else {
        inputListener.keyDown(null, keycode)
      }
  }

  /** Basic input listener for the text field */
  class TextFieldClickListener extends ClickListener {

    override def clicked(event: InputEvent, x: Float, y: Float): Unit = {
      val count = tapCount % 4
      if (count == 0) clearSelection()
      if (count == 2) {
        val array = wordUnderCursor(x)
        setSelection(array(0), array(1))
      }
      if (count == 3) selectAll()
    }

    override def touchDown(event: InputEvent, x: Float, y: Float, pointer: Int, button: Button): Boolean =
      if (!super.touchDown(event, x, y, pointer, button)) false
      else if (pointer == 0 && button != Button(0)) false
      else if (disabled) true
      else {
        setCursorPosition(x, y)
        selectionStart = cursor
        stage.foreach { stage =>
          stage.setKeyboardFocus(Nullable(TextField.this))
        }
        keyboard.show(TextField.this)
        hasSelection = true
        true
      }

    override def touchDragged(event: InputEvent, x: Float, y: Float, pointer: Int): Unit = {
      super.touchDragged(event, x, y, pointer)
      setCursorPosition(x, y)
    }

    override def touchUp(event: InputEvent, x: Float, y: Float, pointer: Int, button: Button): Unit = {
      if (selectionStart == cursor) hasSelection = false
      super.touchUp(event, x, y, pointer, button)
    }

    protected def setCursorPosition(x: Float, y: Float): Unit = {
      cursor = letterUnderCursor(x)

      cursorOn = focused
      blinkTask.cancel()
      if (focused) Timer.schedule(blinkTask, blinkTime, blinkTime)
    }

    protected def goHome(jump: Boolean): Unit =
      cursor = 0

    protected def goEnd(jump: Boolean): Unit =
      cursor = _text.length()

    override def keyDown(event: InputEvent, keycode: Key): Boolean = boundary {
      if (disabled) boundary.break(false)

      cursorOn = focused
      blinkTask.cancel()
      if (focused) Timer.schedule(blinkTask, blinkTime, blinkTime)

      if (!hasKeyboardFocus) boundary.break(false)

      var repeat  = false
      val ctrl    = UIUtils.ctrl()
      val jump    = ctrl && !passwordMode
      var handled = true

      if (ctrl) {
        keycode match {
          case Input.Keys.V =>
            paste(clipboard.contents, true)
            repeat = true
          case Input.Keys.C | Input.Keys.INSERT =>
            copy()
            boundary.break(true)
          case Input.Keys.X =>
            cut(true)
            boundary.break(true)
          case Input.Keys.A =>
            selectAll()
            boundary.break(true)
          case Input.Keys.Z =>
            val oldText = _text
            setText(Nullable(undoText))
            undoText = oldText
            updateDisplayText()
            boundary.break(true)
          case _ =>
            handled = false
        }
      }

      if (UIUtils.shift()) {
        keycode match {
          case Input.Keys.INSERT =>
            paste(clipboard.contents, true)
          case Input.Keys.FORWARD_DEL =>
            cut(true)
          case _ =>
        }

        // selection block
        val temp             = cursor
        var selectionHandled = false
        keycode match {
          case Input.Keys.LEFT =>
            moveCursor(false, jump)
            repeat = true
            handled = true
            selectionHandled = true
          case Input.Keys.RIGHT =>
            moveCursor(true, jump)
            repeat = true
            handled = true
            selectionHandled = true
          case Input.Keys.HOME =>
            goHome(jump)
            handled = true
            selectionHandled = true
          case Input.Keys.END =>
            goEnd(jump)
            handled = true
            selectionHandled = true
          case _ =>
        }
        if (selectionHandled) {
          if (!hasSelection) {
            selectionStart = temp
            hasSelection = true
          }
        }
      } else {
        // Cursor movement or other keys (kills selection).
        keycode match {
          case Input.Keys.LEFT =>
            moveCursor(false, jump)
            clearSelection()
            repeat = true
            handled = true
          case Input.Keys.RIGHT =>
            moveCursor(true, jump)
            clearSelection()
            repeat = true
            handled = true
          case Input.Keys.HOME =>
            goHome(jump)
            clearSelection()
            handled = true
          case Input.Keys.END =>
            goEnd(jump)
            clearSelection()
            handled = true
          case _ =>
        }
      }

      cursor = MathUtils.clamp(cursor, 0, _text.length())

      if (repeat) scheduleKeyRepeatTask(keycode)
      handled
    }

    protected def scheduleKeyRepeatTask(keycode: Key): Unit =
      if (!keyRepeatTask.isScheduled || keyRepeatTask.keycode != keycode) {
        keyRepeatTask.keycode = keycode
        keyRepeatTask.cancel()
        Timer.schedule(keyRepeatTask, keyRepeatInitialTime, keyRepeatTime)
      }

    override def keyUp(event: InputEvent, keycode: Key): Boolean =
      if (disabled) false
      else {
        keyRepeatTask.cancel()
        true
      }

    /** Checks if focus traversal should be triggered. The default implementation uses {@link TextField#focusTraversal} and the typed character, depending on the OS.
      * @param character
      *   The character that triggered a possible focus traversal.
      * @return
      *   true if the focus should change to the {@link TextField#next(boolean) next} input field.
      */
    protected def checkFocusTraversal(character: Char): Boolean =
      focusTraversal && (character == TAB ||
        ((character == CARRIAGE_RETURN || character == NEWLINE) && (UIUtils.isAndroid || UIUtils.isIos)))

    override def keyTyped(event: InputEvent, character: Char): Boolean = boundary {
      if (disabled) boundary.break(false)

      // Disallow "typing" most ASCII control characters, which would show up as a space when onlyFontChars is true.
      character match {
        case BACKSPACE | TAB | NEWLINE | CARRIAGE_RETURN =>
        // allowed
        case _ =>
          if (character < 32) boundary.break(false)
      }

      if (!hasKeyboardFocus) boundary.break(false)

      if (UIUtils.isMac && Sge().input.isKeyPressed(Input.Keys.SYM)) boundary.break(true)

      if (checkFocusTraversal(character)) {
        val transferred = next(UIUtils.shift())
        if (transferred.isEmpty) keyboard.close()
      } else {
        val enter     = character == CARRIAGE_RETURN || character == NEWLINE
        val delete    = character == DELETE
        val backspace = character == BACKSPACE
        val add       = if (enter) writeEnters else !onlyFontChars || _style.font.data.hasGlyph(character)
        val remove    = backspace || delete
        if (add || remove) {
          val oldText   = _text
          val oldCursor = cursor
          if (remove) {
            if (hasSelection)
              cursor = TextField.this.delete(false)
            else {
              if (backspace && cursor > 0) {
                _text = _text.substring(0, cursor - 1) + _text.substring(cursor)
                cursor -= 1
                renderOffset = 0
              }
              if (delete && cursor < _text.length()) {
                _text = _text.substring(0, cursor) + _text.substring(cursor + 1)
              }
            }
          }
          if (add && !remove) {
            // Character may be added to the text.
            if (!enter) {
              var filterReject = false
              filter.foreach { f =>
                if (!f.acceptChar(TextField.this, character)) filterReject = true
              }
              if (filterReject) boundary.break(true)
            }
            if (!withinMaxLength(_text.length() - (if (hasSelection) Math.abs(cursor - selectionStart) else 0)))
              boundary.break(true)
            if (hasSelection) cursor = TextField.this.delete(false)
            val insertion = if (enter) "\n" else String.valueOf(character)
            _text = insert(cursor, insertion, _text)
            cursor += 1
          }
          undoText
          if (changeText(oldText, _text)) {
            val time = System.currentTimeMillis()
            if (time - 750 > lastChangeTime) undoText = oldText
            lastChangeTime = time
            updateDisplayText()
          } else if (_text != oldText) {
            // Keep cursor movement if the text is the same.
            cursor = oldCursor
          }
        }
      }
      listener.foreach(_.keyTyped(TextField.this, character))
      true
    }
  }
}

object TextField {

  private[ui] val BACKSPACE:       Char = 8
  private[ui] val CARRIAGE_RETURN: Char = '\r'
  private[ui] val NEWLINE:         Char = '\n'
  private[ui] val TAB:             Char = '\t'
  private[ui] val DELETE:          Char = 127
  private[ui] val BULLET:          Char = 149

  var DEFAULT_ONSCREEN_KEYBOARD: OnscreenKeyboard = DefaultOnscreenKeyboard()

  private val tmp1: Vector2 = Vector2()
  private val tmp2: Vector2 = Vector2()
  private val tmp3: Vector2 = Vector2()

  var keyRepeatInitialTime: Seconds = Seconds(0.4f)
  var keyRepeatTime:        Seconds = Seconds(0.1f)

  /** Interface for listening to typed characters.
    * @author
    *   mzechner
    */
  trait TextFieldListener {
    def keyTyped(textField: TextField, c: Char): Unit
  }

  /** Interface for filtering characters entered into the text field.
    * @author
    *   mzechner
    */
  trait TextFieldFilter {
    def acceptChar(textField: TextField, c: Char): Boolean
  }

  object TextFieldFilter {
    class DigitsOnlyFilter extends TextFieldFilter {
      def acceptChar(textField: TextField, c: Char): Boolean =
        Character.isDigit(c)
    }
  }

  /** An interface for onscreen keyboards. Can invoke the default keyboard or render your own keyboard!
    * @author
    *   mzechner
    */
  trait OnscreenKeyboard {
    def show(textField: TextField)(using Sge): Unit

    def close()(using Sge): Unit
  }

  /** The default {@link OnscreenKeyboard} used by all {@link TextField} instances. Just uses {@link Input#setOnscreenKeyboardVisible(boolean)} as appropriate. Might overlap your actual rendering, so
    * use with care!
    * @author
    *   mzechner
    */
  class DefaultOnscreenKeyboard extends OnscreenKeyboard {
    def show(textField: TextField)(using Sge): Unit =
      Sge().input.setOnscreenKeyboardVisible(true)

    def close()(using Sge): Unit =
      Sge().input.setOnscreenKeyboardVisible(false)
  }

  /** An advanced {@link OnscreenKeyboard} utilising {@link Input#openTextInputField}. Might overlap your actual rendering, so use with care! This is mutually exclusive with using the
    * {@link DefaultOnscreenKeyboard} or {@link Input#setOnscreenKeyboardVisible(boolean)} API
    */
  class NativeOnscreenKeyboard extends OnscreenKeyboard {
    def close()(using Sge): Unit =
      Sge().input.closeTextInputField(false)

    def show(textField: TextField)(using Sge): Unit =
      if (Sge().input.isTextInputFieldOpened()) {
        Sge().input.closeTextInputField(
          false,
          Nullable(
            new input.NativeInputConfiguration.NativeInputCloseCallback {
              override def onClose(confirmativeAction: Boolean): Boolean = {
                openNativeInputField(textField)
                true
              }
            }
          )
        )
      } else {
        openNativeInputField(textField)
      }

    private def openNativeInputField(textField: TextField)(using Sge): Unit = {
      val configuration = input.NativeInputConfiguration()
      // If we are in password mode, assume that the user wants to show password keyboard
      val resolvedType =
        if (textField.passwordMode && textField.keyboardType == Input.OnscreenKeyboardType.Default)
          Input.OnscreenKeyboardType.Password
        else textField.keyboardType

      configuration
        .setType(resolvedType)
        .setMaskInput(textField.passwordMode)
        .setShowUnmaskButton(textField.passwordMode)
        .setMaxLength(if (textField.maxLength <= 0) None else Some(textField.maxLength))
        .setMultiLine(textField.writeEnters)
        .setPreventCorrection(textField.preventAutoCorrection || resolvedType == Input.OnscreenKeyboardType.Password)
        .setPlaceholder(textField.messageText.getOrElse(""))
        .setAutoComplete(textField.autocompleteOptions)

      textField.filter.foreach { f =>
        configuration.setValidator { toCheck =>
          boundary {
            var i = 0
            while (i < toCheck.length()) {
              if (!f.acceptChar(textField, toCheck.charAt(i))) boundary.break(false)
              i += 1
            }
            true
          }
        }
      }

      configuration.setCloseCallback((confirmativeAction: Boolean) =>
        if (confirmativeAction) {
          val focused = textField.next(false)
          focused.fold(false) { f =>
            f.getOnscreenKeyboard.show(f)
            true
          }
        } else false
      )

      configuration.setTextInputWrapper(
        new input.TextInputWrapper {
          override def getText(): String = textField.getText

          override def getSelectionStart(): Int = textField.getSelectionStart

          override def getSelectionEnd(): Int = textField.getCursorPosition

          override def writeResults(text: String, selectionStart: Int, selectionEnd: Int): Unit = {
            var t  = text
            var ss = selectionStart
            var se = selectionEnd
            if (textField.preventAutoCorrection) {
              t = t.trim()
              ss = Math.min(ss, t.length())
              se = Math.min(se, t.length())
            }
            textField.setText(t)
            if (ss == se) textField.setCursorPosition(se)
            else textField.setSelection(ss, se)
          }
        }
      )

      Sge().input.openTextInputField(configuration)
    }
  }

  /** The style for a text field, see {@link TextField}.
    * @author
    *   mzechner
    * @author
    *   Nathan Sweet
    */
  class TextFieldStyle() {
    var font:               BitmapFont           = scala.compiletime.uninitialized
    var fontColor:          Color                = scala.compiletime.uninitialized
    var focusedFontColor:   Nullable[Color]      = Nullable.empty
    var disabledFontColor:  Nullable[Color]      = Nullable.empty
    var background:         Nullable[Drawable]   = Nullable.empty
    var focusedBackground:  Nullable[Drawable]   = Nullable.empty
    var disabledBackground: Nullable[Drawable]   = Nullable.empty
    var cursor:             Nullable[Drawable]   = Nullable.empty
    var selection:          Nullable[Drawable]   = Nullable.empty
    var messageFont:        Nullable[BitmapFont] = Nullable.empty
    var messageFontColor:   Nullable[Color]      = Nullable.empty

    def this(font: BitmapFont, fontColor: Color, cursor: Nullable[Drawable], selection: Nullable[Drawable], background: Nullable[Drawable]) = {
      this()
      this.font = font
      this.fontColor = fontColor
      this.cursor = cursor
      this.selection = selection
      this.background = background
    }

    def this(style: TextFieldStyle) = {
      this()
      font = style.font
      Nullable(style.fontColor).foreach(c => fontColor = Color(c))
      focusedFontColor = style.focusedFontColor.map(c => Color(c))
      disabledFontColor = style.disabledFontColor.map(c => Color(c))

      background = style.background
      focusedBackground = style.focusedBackground
      disabledBackground = style.disabledBackground
      cursor = style.cursor
      selection = style.selection

      messageFont = style.messageFont
      messageFontColor = style.messageFontColor.map(c => Color(c))
    }
  }

}
