/*
 * Ported from TextraTypist - https://github.com/tommyettinger/textratypist
 * Original source: com/github/tommyettinger/textra/utils/BlockUtils.java
 * Licensed under the Apache License, Version 2.0
 *
 * Scala port copyright 2025-2026 Mateusz Kubuszok
 *
 * Covenant: full-port
 * Covenant-baseline-spec-pass: 0
 * Covenant-baseline-loc: 215
 * Covenant-baseline-methods: ALL_BLOCK_CHARS,BOX_DRAWING,BlockUtils,THIN_ACROSS,THIN_END,THIN_OVER,THIN_START,TWIN_ACROSS,TWIN_END1,TWIN_END2,TWIN_OVER1,TWIN_OVER2,TWIN_START1,TWIN_START2,WIDE_ACROSS,WIDE_END,WIDE_OVER,WIDE_START,isBlockGlyph
 * Covenant-source-reference: com/github/tommyettinger/textra/utils/BlockUtils.java
 * Covenant-verified: 2026-04-19
 */
package sge
package textra
package utils

object BlockUtils {

  val THIN_START:  Float = 0.45f
  val THIN_END:    Float = 0.55f
  val THIN_ACROSS: Float = 0.1f
  val THIN_OVER:   Float = 1f - THIN_START

  val WIDE_START:  Float = 0.4f
  val WIDE_END:    Float = 0.6f
  val WIDE_ACROSS: Float = 0.2f
  val WIDE_OVER:   Float = 1f - WIDE_START

  val TWIN_START1: Float = 0.35f
  val TWIN_END1:   Float = 0.45f
  val TWIN_START2: Float = 0.55f
  val TWIN_END2:   Float = 0.65f
  val TWIN_ACROSS: Float = 0.10000001f
  val TWIN_OVER1:  Float = 1f - TWIN_START1
  val TWIN_OVER2:  Float = 1f - TWIN_START2

  /** Returns true if the given char can be handled by the box drawing and block element data here. */
  def isBlockGlyph(c: Int): Boolean =
    (c >= '\u2500' && c <= '\u256c') || (c >= '\u2574' && c <= '\u2590') || (c >= '\u2594' && c <= '\u259f')

  /** Box-drawing and block element character data. Each entry is a float array defining rectangular regions to draw for that character, in groups of 4: (startX, startY, sizeX, sizeY). Indexed by
    * Unicode code point minus 0x2500.
    */
  // format: off
  val BOX_DRAWING: Array[Array[Float]] = Array(
    /* ─ : u2500 */ Array(0, THIN_START, 1, THIN_ACROSS),
    /* ━ : u2501 */ Array(0, WIDE_START, 1, WIDE_ACROSS),
    /* │ : u2502 */ Array(THIN_START, 0, THIN_ACROSS, 1),
    /* ┃ : u2503 */ Array(WIDE_START, 0, WIDE_ACROSS, 1),
    /* ┄ : u2504 */ Array(0, THIN_START, 0.2f, THIN_ACROSS, 0.4f, THIN_START, 0.2f, THIN_ACROSS, 0.8f, THIN_START, 0.2f, THIN_ACROSS),
    /* ┅ : u2505 */ Array(0, WIDE_START, 0.2f, WIDE_ACROSS, 0.4f, WIDE_START, 0.2f, WIDE_ACROSS, 0.8f, WIDE_START, 0.2f, WIDE_ACROSS),
    /* ┆ : u2506 */ Array(THIN_START, 0, THIN_ACROSS, 0.2f, THIN_START, 0.4f, THIN_ACROSS, 0.2f, THIN_START, 0.8f, THIN_ACROSS, 0.2f),
    /* ┇ : u2507 */ Array(WIDE_START, 0, WIDE_ACROSS, 0.2f, WIDE_START, 0.4f, WIDE_ACROSS, 0.2f, WIDE_START, 0.8f, WIDE_ACROSS, 0.2f),
    /* ┈ : u2508 */ Array(0, THIN_START, 1/7f, THIN_ACROSS, 2/7f, THIN_START, 1/7f, THIN_ACROSS, 4/7f, THIN_START, 1/7f, THIN_ACROSS, 6/7f, THIN_START, 1/7f, THIN_ACROSS),
    /* ┉ : u2509 */ Array(0, WIDE_START, 1/7f, WIDE_ACROSS, 2/7f, WIDE_START, 1/7f, WIDE_ACROSS, 4/7f, WIDE_START, 1/7f, WIDE_ACROSS, 6/7f, WIDE_START, 1/7f, WIDE_ACROSS),
    /* ┊ : u250A */ Array(THIN_START, 0, THIN_ACROSS, 1/7f, THIN_START, 2/7f, THIN_ACROSS, 1/7f, THIN_START, 4/7f, THIN_ACROSS, 1/7f, THIN_START, 6/7f, THIN_ACROSS, 1/7f),
    /* ┋ : u250B */ Array(WIDE_START, 0, WIDE_ACROSS, 1/7f, WIDE_START, 2/7f, WIDE_ACROSS, 1/7f, WIDE_START, 4/7f, WIDE_ACROSS, 1/7f, WIDE_START, 6/7f, WIDE_ACROSS, 1/7f),
    /* ┌ : u250C */ Array(THIN_START, THIN_START, THIN_OVER, THIN_ACROSS, THIN_START, 0, THIN_ACROSS, THIN_OVER),
    /* ┍ : u250D */ Array(THIN_START, WIDE_START, THIN_OVER, WIDE_ACROSS, THIN_START, 0, THIN_ACROSS, WIDE_OVER),
    /* ┎ : u250E */ Array(WIDE_START, THIN_START, WIDE_OVER, THIN_ACROSS, WIDE_START, 0, WIDE_ACROSS, THIN_OVER),
    /* ┏ : u250F */ Array(WIDE_START, WIDE_START, WIDE_OVER, WIDE_ACROSS, WIDE_START, 0, WIDE_ACROSS, WIDE_OVER),
    /* ┐ : u2510 */ Array(0, THIN_START, THIN_OVER, THIN_ACROSS, THIN_START, 0, THIN_ACROSS, THIN_OVER),
    /* ┑ : u2511 */ Array(0, WIDE_START, THIN_OVER, WIDE_ACROSS, THIN_START, 0, THIN_ACROSS, WIDE_OVER),
    /* ┒ : u2512 */ Array(0, THIN_START, WIDE_OVER, THIN_ACROSS, WIDE_START, 0, WIDE_ACROSS, THIN_OVER),
    /* ┓ : u2513 */ Array(0, WIDE_START, WIDE_OVER, WIDE_ACROSS, WIDE_START, 0, WIDE_ACROSS, WIDE_OVER),
    /* └ : u2514 */ Array(THIN_START, THIN_START, THIN_OVER, THIN_ACROSS, THIN_START, THIN_START, THIN_ACROSS, THIN_OVER),
    /* ┕ : u2515 */ Array(THIN_START, WIDE_START, THIN_OVER, WIDE_ACROSS, THIN_START, WIDE_START, THIN_ACROSS, WIDE_OVER),
    /* ┖ : u2516 */ Array(WIDE_START, THIN_START, WIDE_OVER, THIN_ACROSS, WIDE_START, THIN_START, WIDE_ACROSS, THIN_OVER),
    /* ┗ : u2517 */ Array(WIDE_START, WIDE_START, WIDE_OVER, WIDE_ACROSS, WIDE_START, WIDE_START, WIDE_ACROSS, WIDE_OVER),
    /* ┘ : u2518 */ Array(0, THIN_START, THIN_OVER, THIN_ACROSS, THIN_START, THIN_START, THIN_ACROSS, THIN_OVER),
    /* ┙ : u2519 */ Array(0, WIDE_START, THIN_OVER, WIDE_ACROSS, THIN_START, WIDE_START, THIN_ACROSS, WIDE_OVER),
    /* ┚ : u251A */ Array(0, THIN_START, WIDE_OVER, THIN_ACROSS, WIDE_START, THIN_START, WIDE_ACROSS, THIN_OVER),
    /* ┛ : u251B */ Array(0, WIDE_START, WIDE_OVER, WIDE_ACROSS, WIDE_START, WIDE_START, WIDE_ACROSS, WIDE_OVER),
    /* ├ : u251C */ Array(THIN_START, THIN_START, THIN_OVER, THIN_ACROSS, THIN_START, 0, THIN_ACROSS, 1),
    /* ┝ : u251D */ Array(THIN_START, WIDE_START, THIN_OVER, WIDE_ACROSS, THIN_START, 0, THIN_ACROSS, 1),
    /* ┞ : u251E */ Array(THIN_START, THIN_START, THIN_OVER, THIN_ACROSS, THIN_START, 0, THIN_ACROSS, THIN_OVER, WIDE_START, THIN_START, WIDE_ACROSS, THIN_OVER),
    /* ┟ : u251F */ Array(THIN_START, THIN_START, THIN_OVER, THIN_ACROSS, THIN_START, THIN_START, THIN_ACROSS, THIN_OVER, WIDE_START, 0, WIDE_ACROSS, WIDE_OVER),
    /* ┠ : u2520 */ Array(THIN_START, THIN_START, THIN_OVER, THIN_ACROSS, WIDE_START, 0, WIDE_ACROSS, 1),
    /* ┡ : u2521 */ Array(WIDE_START, WIDE_START, WIDE_OVER, WIDE_ACROSS, WIDE_START, WIDE_START, WIDE_ACROSS, WIDE_OVER, THIN_START, 0, THIN_ACROSS, THIN_OVER),
    /* ┢ : u2522 */ Array(WIDE_START, WIDE_START, WIDE_OVER, WIDE_ACROSS, WIDE_START, 0, WIDE_ACROSS, WIDE_OVER, THIN_START, THIN_START, THIN_ACROSS, THIN_OVER),
    /* ┣ : u2523 */ Array(WIDE_START, WIDE_START, WIDE_OVER, WIDE_ACROSS, WIDE_START, 0, WIDE_ACROSS, 1),
    /* ┤ : u2524 */ Array(0, THIN_START, THIN_OVER, THIN_ACROSS, THIN_START, 0, THIN_ACROSS, 1),
    /* ┥ : u2525 */ Array(0, WIDE_START, THIN_OVER, WIDE_ACROSS, THIN_START, 0, THIN_ACROSS, 1),
    /* ┦ : u2526 */ Array(0, THIN_START, THIN_OVER, THIN_ACROSS, THIN_START, 0, THIN_ACROSS, THIN_OVER, WIDE_START, THIN_START, WIDE_ACROSS, THIN_OVER),
    /* ┧ : u2527 */ Array(0, THIN_START, THIN_OVER, THIN_ACROSS, THIN_START, THIN_START, THIN_ACROSS, THIN_OVER, WIDE_START, 0, WIDE_ACROSS, WIDE_OVER),
    /* ┨ : u2528 */ Array(0, THIN_START, THIN_OVER, THIN_ACROSS, WIDE_START, 0, WIDE_ACROSS, 1),
    /* ┩ : u2529 */ Array(0, WIDE_START, WIDE_OVER, WIDE_ACROSS, WIDE_START, WIDE_START, WIDE_ACROSS, WIDE_OVER, THIN_START, 0, THIN_ACROSS, THIN_OVER),
    /* ┪ : u252A */ Array(0, WIDE_START, WIDE_OVER, WIDE_ACROSS, WIDE_START, 0, WIDE_ACROSS, WIDE_OVER, THIN_START, THIN_START, THIN_ACROSS, THIN_OVER),
    /* ┫ : u252B */ Array(0, WIDE_START, THIN_OVER, WIDE_ACROSS, WIDE_START, 0, WIDE_ACROSS, 1),
    /* ┬ : u252C */ Array(0, THIN_START, 1, THIN_ACROSS, THIN_START, 0, THIN_ACROSS, THIN_OVER),
    /* ┭ : u252D */ Array(0, WIDE_START, WIDE_OVER, WIDE_ACROSS, THIN_START, THIN_START, THIN_OVER, THIN_ACROSS, THIN_START, 0, THIN_ACROSS, THIN_OVER),
    /* ┮ : u252E */ Array(0, THIN_START, THIN_OVER, THIN_ACROSS, WIDE_START, WIDE_START, WIDE_OVER, WIDE_ACROSS, THIN_START, 0, THIN_ACROSS, THIN_OVER),
    /* ┯ : u252F */ Array(0, WIDE_START, 1, WIDE_ACROSS, THIN_START, 0, THIN_ACROSS, THIN_OVER),
    /* ┰ : u2530 */ Array(0, THIN_START, 1, THIN_ACROSS, WIDE_START, 0, WIDE_ACROSS, WIDE_OVER),
    /* ┱ : u2531 */ Array(0, WIDE_START, WIDE_OVER, WIDE_ACROSS, THIN_START, THIN_START, THIN_OVER, THIN_ACROSS, WIDE_START, 0, WIDE_ACROSS, WIDE_OVER),
    /* ┲ : u2532 */ Array(0, THIN_START, THIN_OVER, THIN_ACROSS, WIDE_START, WIDE_START, WIDE_OVER, WIDE_ACROSS, WIDE_START, 0, WIDE_ACROSS, WIDE_OVER),
    /* ┳ : u2533 */ Array(0, WIDE_START, 1, WIDE_ACROSS, WIDE_START, 0, WIDE_ACROSS, WIDE_OVER),
    /* ┴ : u2534 */ Array(0, THIN_START, 1, THIN_ACROSS, THIN_START, THIN_START, THIN_ACROSS, THIN_OVER),
    /* ┵ : u2535 */ Array(0, WIDE_START, WIDE_OVER, WIDE_ACROSS, THIN_START, THIN_START, THIN_OVER, THIN_ACROSS, THIN_START, THIN_START, THIN_ACROSS, THIN_OVER),
    /* ┶ : u2536 */ Array(0, THIN_START, THIN_OVER, THIN_ACROSS, WIDE_START, WIDE_START, WIDE_OVER, WIDE_ACROSS, THIN_START, THIN_START, THIN_ACROSS, THIN_OVER),
    /* ┷ : u2537 */ Array(0, WIDE_START, 1, WIDE_ACROSS, THIN_START, THIN_START, THIN_ACROSS, THIN_OVER),
    /* ┸ : u2538 */ Array(0, THIN_START, 1, THIN_ACROSS, WIDE_START, WIDE_START, WIDE_ACROSS, WIDE_OVER),
    /* ┹ : u2539 */ Array(0, WIDE_START, WIDE_OVER, WIDE_ACROSS, THIN_START, THIN_START, THIN_OVER, THIN_ACROSS, WIDE_START, WIDE_START, WIDE_ACROSS, WIDE_OVER),
    /* ┺ : u253A */ Array(0, THIN_START, THIN_OVER, THIN_ACROSS, WIDE_START, WIDE_START, WIDE_OVER, WIDE_ACROSS, WIDE_START, WIDE_START, WIDE_ACROSS, WIDE_OVER),
    /* ┻ : u253B */ Array(0, WIDE_START, 1, WIDE_ACROSS, WIDE_START, WIDE_START, WIDE_ACROSS, WIDE_OVER),
    /* ┼ : u253C */ Array(0, THIN_START, 1, THIN_ACROSS, THIN_START, 0, THIN_ACROSS, 1),
    /* ┽ : u253D */ Array(0, WIDE_START, WIDE_OVER, WIDE_ACROSS, THIN_START, THIN_START, THIN_OVER, THIN_ACROSS, THIN_START, 0, THIN_ACROSS, 1),
    /* ┾ : u253E */ Array(0, THIN_START, THIN_OVER, THIN_ACROSS, WIDE_START, WIDE_START, WIDE_OVER, WIDE_ACROSS, THIN_START, 0, THIN_ACROSS, 1),
    /* ┿ : u253F */ Array(0, WIDE_START, 1, WIDE_ACROSS, THIN_START, 0, THIN_ACROSS, 1),
    /* ╀ : u2540 */ Array(0, THIN_START, 1, THIN_ACROSS, WIDE_START, WIDE_START, WIDE_ACROSS, WIDE_OVER, THIN_START, 0, THIN_ACROSS, THIN_OVER),
    /* ╁ : u2541 */ Array(0, THIN_START, 1, THIN_ACROSS, THIN_START, THIN_START, THIN_ACROSS, THIN_OVER, WIDE_START, 0, WIDE_ACROSS, WIDE_OVER),
    /* ╂ : u2542 */ Array(0, THIN_START, 1, THIN_ACROSS, WIDE_START, 0, WIDE_ACROSS, 1),
    /* ╃ : u2543 */ Array(0, WIDE_START, WIDE_OVER, WIDE_ACROSS, THIN_START, THIN_START, THIN_OVER, THIN_ACROSS, WIDE_START, WIDE_START, WIDE_ACROSS, WIDE_OVER, THIN_START, 0, THIN_ACROSS, THIN_OVER),
    /* ╄ : u2544 */ Array(0, THIN_START, THIN_OVER, THIN_ACROSS, WIDE_START, WIDE_START, WIDE_OVER, WIDE_ACROSS, WIDE_START, WIDE_START, WIDE_ACROSS, WIDE_OVER, THIN_START, 0, THIN_ACROSS, THIN_OVER),
    /* ╅ : u2545 */ Array(0, WIDE_START, WIDE_OVER, WIDE_ACROSS, THIN_START, THIN_START, THIN_OVER, THIN_ACROSS, THIN_START, THIN_START, THIN_ACROSS, THIN_OVER, WIDE_START, 0, WIDE_ACROSS, WIDE_OVER),
    /* ╆ : u2546 */ Array(0, THIN_START, THIN_OVER, THIN_ACROSS, WIDE_START, WIDE_START, WIDE_OVER, WIDE_ACROSS, THIN_START, THIN_START, THIN_ACROSS, THIN_OVER, WIDE_START, 0, WIDE_ACROSS, WIDE_OVER),
    /* ╇ : u2547 */ Array(0, WIDE_START, 1, WIDE_ACROSS, WIDE_START, WIDE_START, WIDE_ACROSS, WIDE_OVER, THIN_START, 0, THIN_ACROSS, THIN_OVER),
    /* ╈ : u2548 */ Array(0, WIDE_START, 1, WIDE_ACROSS, THIN_START, THIN_START, THIN_ACROSS, THIN_OVER, WIDE_START, 0, WIDE_ACROSS, WIDE_OVER),
    /* ╉ : u2549 */ Array(0, WIDE_START, WIDE_OVER, WIDE_ACROSS, THIN_START, THIN_START, THIN_OVER, THIN_ACROSS, WIDE_START, 0, WIDE_ACROSS, 1),
    /* ╊ : u254A */ Array(0, THIN_START, THIN_OVER, THIN_ACROSS, WIDE_START, WIDE_START, WIDE_OVER, WIDE_ACROSS, WIDE_START, 0, WIDE_ACROSS, 1),
    /* ╋ : u254B */ Array(0, WIDE_START, 1, WIDE_ACROSS, WIDE_START, 0, WIDE_ACROSS, 1),
    /* ╌ : u254C */ Array(0.125f, THIN_START, 0.25f, THIN_ACROSS, 0.625f, THIN_START, 0.25f, THIN_ACROSS),
    /* ╍ : u254D */ Array(0.125f, WIDE_START, 0.25f, WIDE_ACROSS, 0.625f, WIDE_START, 0.25f, WIDE_ACROSS),
    /* ╎ : u254E */ Array(THIN_START, 0.125f, THIN_ACROSS, 0.25f, THIN_START, 0.625f, THIN_ACROSS, 0.25f),
    /* ╏ : u254F */ Array(WIDE_START, 0.125f, WIDE_ACROSS, 0.25f, WIDE_START, 0.625f, WIDE_ACROSS, 0.25f),
    /* ═ : u2550 */ Array(0, TWIN_START1, 1, TWIN_ACROSS, 0, TWIN_START2, 1, TWIN_ACROSS),
    /* ║ : u2551 */ Array(TWIN_START1, 0, TWIN_ACROSS, 1, TWIN_START2, 0, TWIN_ACROSS, 1),
    /* ╒ : u2552 */ Array(THIN_START, 0, THIN_ACROSS, TWIN_OVER1, THIN_START, TWIN_START1, THIN_OVER, TWIN_ACROSS, THIN_START, TWIN_START2, THIN_OVER, TWIN_ACROSS),
    /* ╓ : u2553 */ Array(TWIN_START1, 0, TWIN_ACROSS, THIN_OVER, TWIN_START2, 0, TWIN_ACROSS, THIN_OVER, TWIN_START1, THIN_START, TWIN_OVER1, THIN_ACROSS),
    /* ╔ : u2554 */ Array(TWIN_START1, 0, TWIN_ACROSS, TWIN_OVER1, TWIN_START2, 0, TWIN_ACROSS, TWIN_OVER2, TWIN_START2, TWIN_START1, TWIN_OVER2, TWIN_ACROSS, TWIN_START1, TWIN_START2, TWIN_OVER1, TWIN_ACROSS),
    /* ╕ : u2555 */ Array(THIN_START, 0, THIN_ACROSS, TWIN_OVER1, 0, TWIN_START1, THIN_OVER, TWIN_ACROSS, 0, TWIN_START2, THIN_OVER, TWIN_ACROSS),
    /* ╖ : u2556 */ Array(TWIN_START1, 0, TWIN_ACROSS, THIN_OVER, TWIN_START2, 0, TWIN_ACROSS, THIN_OVER, 0, THIN_START, TWIN_OVER1, THIN_ACROSS),
    /* ╗ : u2557 */ Array(TWIN_START1, 0, TWIN_ACROSS, TWIN_OVER2, TWIN_START2, 0, TWIN_ACROSS, TWIN_OVER1, 0, TWIN_START1, TWIN_OVER2, TWIN_ACROSS, 0, TWIN_START2, TWIN_OVER1, TWIN_ACROSS),
    /* ╘ : u2558 */ Array(THIN_START, TWIN_START1, THIN_OVER, TWIN_ACROSS, THIN_START, TWIN_START2, THIN_OVER, TWIN_ACROSS, THIN_START, TWIN_START1, THIN_ACROSS, TWIN_OVER1),
    /* ╙ : u2559 */ Array(TWIN_START1, THIN_START, TWIN_ACROSS, THIN_OVER, TWIN_START2, THIN_START, TWIN_ACROSS, THIN_OVER, TWIN_START1, THIN_START, TWIN_OVER1, THIN_ACROSS),
    /* ╚ : u255A */ Array(TWIN_START1, TWIN_START1, TWIN_ACROSS, TWIN_OVER1, TWIN_START2, TWIN_START2, TWIN_ACROSS, TWIN_OVER2, TWIN_START1, TWIN_START1, TWIN_OVER1, TWIN_ACROSS, TWIN_START2, TWIN_START2, TWIN_OVER2, TWIN_ACROSS),
    /* ╛ : u255B */ Array(THIN_START, TWIN_START1, THIN_ACROSS, TWIN_OVER1, 0, TWIN_START1, THIN_OVER, TWIN_ACROSS, 0, TWIN_START2, THIN_OVER, TWIN_ACROSS),
    /* ╜ : u255C */ Array(TWIN_START1, THIN_START, TWIN_ACROSS, THIN_OVER, TWIN_START2, THIN_START, TWIN_ACROSS, THIN_OVER, 0, THIN_START, TWIN_OVER1, THIN_ACROSS),
    /* ╝ : u255D */ Array(TWIN_START1, TWIN_START2, TWIN_ACROSS, TWIN_OVER2, TWIN_START2, TWIN_START1, TWIN_ACROSS, TWIN_OVER1, 0, TWIN_START1, TWIN_OVER1, TWIN_ACROSS, 0, TWIN_START2, TWIN_OVER2, TWIN_ACROSS),
    /* ╞ : u255E */ Array(THIN_START, 0, THIN_ACROSS, 1, THIN_START, TWIN_START1, THIN_OVER, TWIN_ACROSS, THIN_START, TWIN_START2, THIN_OVER, TWIN_ACROSS),
    /* ╟ : u255F */ Array(TWIN_START1, 0, TWIN_ACROSS, 1, TWIN_START2, 0, TWIN_ACROSS, 1, TWIN_START2, THIN_START, TWIN_OVER2, THIN_ACROSS),
    /* ╠ : u2560 */ Array(TWIN_START1, 0, TWIN_ACROSS, 1, TWIN_START2, TWIN_START2, TWIN_ACROSS, TWIN_OVER2, TWIN_START2, TWIN_START2, TWIN_OVER2, TWIN_ACROSS, TWIN_START2, 0, TWIN_ACROSS, TWIN_OVER2, TWIN_START2, TWIN_START1, TWIN_OVER2, TWIN_ACROSS),
    /* ╡ : u2561 */ Array(THIN_START, 0, THIN_ACROSS, 1, 0, TWIN_START1, THIN_OVER, TWIN_ACROSS, 0, TWIN_START2, THIN_OVER, TWIN_ACROSS),
    /* ╢ : u2562 */ Array(TWIN_START1, 0, TWIN_ACROSS, 1, TWIN_START2, 0, TWIN_ACROSS, 1, 0, THIN_START, TWIN_START1, THIN_ACROSS),
    /* ╣ : u2563 */ Array(TWIN_START2, 0, TWIN_ACROSS, 1, TWIN_START1, 0, TWIN_ACROSS, TWIN_OVER2, 0, TWIN_START1, TWIN_OVER2, TWIN_ACROSS, TWIN_START1, TWIN_START2, TWIN_ACROSS, TWIN_OVER2, 0, TWIN_START2, TWIN_OVER2, TWIN_ACROSS),
    /* ╤ : u2564 */ Array(THIN_START, 0, THIN_ACROSS, TWIN_START1, 0, TWIN_START1, 1, TWIN_ACROSS, 0, TWIN_START2, 1, TWIN_ACROSS),
    /* ╥ : u2565 */ Array(TWIN_START1, 0, TWIN_ACROSS, THIN_OVER, TWIN_START2, 0, TWIN_ACROSS, THIN_OVER, 0, THIN_START, 1, THIN_ACROSS),
    /* ╦ : u2566 */ Array(0, TWIN_START2, 1, TWIN_ACROSS, TWIN_START2, 0, TWIN_ACROSS, TWIN_OVER2, TWIN_START2, TWIN_START1, TWIN_OVER2, TWIN_ACROSS, TWIN_START1, 0, TWIN_ACROSS, TWIN_OVER2, 0, TWIN_START1, TWIN_OVER2, TWIN_ACROSS),
    /* ╧ : u2567 */ Array(THIN_START, TWIN_START2, THIN_ACROSS, TWIN_OVER2, 0, TWIN_START1, 1, TWIN_ACROSS, 0, TWIN_START2, 1, TWIN_ACROSS),
    /* ╨ : u2568 */ Array(TWIN_START1, THIN_START, TWIN_ACROSS, THIN_OVER, TWIN_START2, THIN_START, TWIN_ACROSS, THIN_OVER, 0, THIN_START, 1, THIN_ACROSS),
    /* ╩ : u2569 */ Array(0, TWIN_START1, 1, TWIN_ACROSS, TWIN_START2, TWIN_START2, TWIN_ACROSS, TWIN_OVER2, TWIN_START2, TWIN_START2, TWIN_OVER2, TWIN_ACROSS, TWIN_START1, TWIN_START2, TWIN_ACROSS, TWIN_OVER2, 0, TWIN_START2, TWIN_OVER2, TWIN_ACROSS),
    /* ╪ : u256A */ Array(THIN_START, 0, THIN_ACROSS, 1, 0, TWIN_START1, 1, TWIN_ACROSS, 0, TWIN_START2, 1, TWIN_ACROSS),
    /* ╫ : u256B */ Array(TWIN_START1, 0, TWIN_ACROSS, 1, TWIN_START2, 0, TWIN_ACROSS, 1, 0, THIN_START, 1, THIN_ACROSS),
    /* ╬ : u256C */ Array(TWIN_START2, TWIN_START2, TWIN_ACROSS, TWIN_OVER2, TWIN_START2, TWIN_START2, TWIN_OVER2, TWIN_ACROSS, TWIN_START2, 0, TWIN_ACROSS, TWIN_OVER2, TWIN_START2, TWIN_START1, TWIN_OVER2, TWIN_ACROSS, TWIN_START1, 0, TWIN_ACROSS, TWIN_OVER2, 0, TWIN_START1, TWIN_OVER2, TWIN_ACROSS, TWIN_START1, TWIN_START2, TWIN_ACROSS, TWIN_OVER2, 0, TWIN_START2, TWIN_OVER2, TWIN_ACROSS),
    /* ╭ : u256D */ Array.emptyFloatArray, // NOT USED (rounded corners)
    /* ╮ : u256E */ Array.emptyFloatArray,
    /* ╯ : u256F */ Array.emptyFloatArray,
    /* ╰ : u2570 */ Array.emptyFloatArray,
    /* ╱ : u2571 */ Array.emptyFloatArray,
    /* ╲ : u2572 */ Array.emptyFloatArray,
    /* ╳ : u2573 */ Array.emptyFloatArray,
    /* ╴ : u2574 */ Array(0, THIN_START, THIN_OVER, THIN_ACROSS),
    /* ╵ : u2575 */ Array(THIN_START, THIN_START, THIN_ACROSS, THIN_OVER),
    /* ╶ : u2576 */ Array(THIN_START, THIN_START, THIN_OVER, THIN_ACROSS),
    /* ╷ : u2577 */ Array(THIN_START, 0, THIN_ACROSS, THIN_OVER),
    /* ╸ : u2578 */ Array(0, WIDE_START, WIDE_OVER, WIDE_ACROSS),
    /* ╹ : u2579 */ Array(WIDE_START, WIDE_START, WIDE_ACROSS, WIDE_OVER),
    /* ╺ : u257A */ Array(WIDE_START, WIDE_START, WIDE_OVER, WIDE_ACROSS),
    /* ╻ : u257B */ Array(WIDE_START, 0, WIDE_ACROSS, WIDE_OVER),
    /* ╼ : u257C */ Array(0, THIN_START, THIN_OVER, THIN_ACROSS, WIDE_START, WIDE_START, WIDE_OVER, WIDE_ACROSS),
    /* ╽ : u257D */ Array(THIN_START, THIN_START, THIN_ACROSS, THIN_OVER, WIDE_START, 0, WIDE_ACROSS, WIDE_OVER),
    /* ╾ : u257E */ Array(0, WIDE_START, WIDE_OVER, WIDE_ACROSS, THIN_START, THIN_START, THIN_OVER, THIN_ACROSS),
    /* ╿ : u257F */ Array(WIDE_START, WIDE_START, WIDE_ACROSS, WIDE_OVER, THIN_START, 0, THIN_ACROSS, THIN_OVER),
    /* ▀ : u2580 */ Array(0, 0.5f, 1, 0.5f),
    /* ▁ : u2581 */ Array(0, 0, 1, 0.125f),
    /* ▂ : u2582 */ Array(0, 0, 1, 0.25f),
    /* ▃ : u2583 */ Array(0, 0, 1, 0.375f),
    /* ▄ : u2584 */ Array(0, 0, 1, 0.5f),
    /* ▅ : u2585 */ Array(0, 0, 1, 0.625f),
    /* ▆ : u2586 */ Array(0, 0, 1, 0.75f),
    /* ▇ : u2587 */ Array(0, 0, 1, 0.875f),
    /* █ : u2588 */ Array(0f, 0f, 1f, 1f),
    /* ▉ : u2589 */ Array(0, 0, 0.875f, 1),
    /* ▊ : u258A */ Array(0, 0, 0.75f, 1),
    /* ▋ : u258B */ Array(0, 0, 0.625f, 1),
    /* ▌ : u258C */ Array(0, 0, 0.5f, 1),
    /* ▍ : u258D */ Array(0, 0, 0.375f, 1),
    /* ▎ : u258E */ Array(0, 0, 0.25f, 1),
    /* ▏ : u258F */ Array(0, 0, 0.125f, 1),
    /* ▐ : u2590 */ Array(0.5f, 0, 0.5f, 1),
    /* ░ : u2591 */ Array.emptyFloatArray, // NOT USED (shade characters)
    /* ▒ : u2592 */ Array.emptyFloatArray,
    /* ▓ : u2593 */ Array.emptyFloatArray,
    /* ▔ : u2594 */ Array(0, 0.875f, 1, 0.125f),
    /* ▕ : u2595 */ Array(0.875f, 0, 0.125f, 1),
    /* ▖ : u2596 */ Array(0, 0, 0.5f, 0.5f),
    /* ▗ : u2597 */ Array(0.5f, 0, 0.5f, 0.5f),
    /* ▘ : u2598 */ Array(0, 0.5f, 0.5f, 0.5f),
    /* ▙ : u2599 */ Array(0, 0, 0.5f, 1f, 0.5f, 0, 0.5f, 0.5f),
    /* ▚ : u259A */ Array(0, 0, 0.5f, 0.5f, 0.5f, 0, 0.5f, 0.5f),
    /* ▛ : u259B */ Array(0, 0, 0.5f, 1f, 0.5f, 0.5f, 0.5f, 0.5f),
    /* ▜ : u259C */ Array(0.5f, 0, 0.5f, 1, 0, 0.5f, 0.5f, 0.5f),
    /* ▝ : u259D */ Array(0.5f, 0.5f, 0.5f, 0.5f),
    /* ▞ : u259E */ Array(0, 0, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f),
    /* ▟ : u259F */ Array(0.5f, 0, 0.5f, 1, 0, 0, 0.5f, 0.5f)
  )
  // format: on

  val ALL_BLOCK_CHARS: String =
    "\u2500\u2501\u2502\u2503\u2504\u2505\u2506\u2507\u2508\u2509\u250a\u250b\u250c\u250d\u250e\u250f" +
      "\u2510\u2511\u2512\u2513\u2514\u2515\u2516\u2517\u2518\u2519\u251a\u251b\u251c\u251d\u251e\u251f" +
      "\u2520\u2521\u2522\u2523\u2524\u2525\u2526\u2527\u2528\u2529\u252a\u252b\u252c\u252d\u252e\u252f" +
      "\u2530\u2531\u2532\u2533\u2534\u2535\u2536\u2537\u2538\u2539\u253a\u253b\u253c\u253d\u253e\u253f" +
      "\u2540\u2541\u2542\u2543\u2544\u2545\u2546\u2547\u2548\u2549\u254a\u254b\u254c\u254d\u254e\u254f" +
      "\u2550\u2551\u2552\u2553\u2554\u2555\u2556\u2557\u2558\u2559\u255a\u255b\u255c\u255d\u255e\u255f" +
      "\u2560\u2561\u2562\u2563\u2564\u2565\u2566\u2567\u2568\u2569\u256a\u256b\u256c\u2574\u2575\u2576" +
      "\u2577\u2578\u2579\u257a\u257b\u257c\u257d\u257e\u257f\u2580\u2581\u2582\u2583\u2584\u2585\u2586" +
      "\u2587\u2588\u2589\u258a\u258b\u258c\u258d\u258e\u258f\u2590\u2594\u2595\u2596\u2597\u2598\u2599" +
      "\u259a\u259b\u259c\u259d\u259e\u259f"
}
