/*
 * Ported from colorful-gdx - https://github.com/tommyettinger/colorful-gdx
 * Original authors: Tommy Ettinger
 * Licensed under the Apache License, Version 2.0
 *
 * Scala port copyright 2025-2026 Mateusz Kubuszok
 *
 * Covenant: full-port
 * Covenant-baseline-spec-pass: 0
 * Covenant-baseline-loc: 811
 * Covenant-baseline-methods: ABSINTHE,AIR_FORCE_BLUE,AMAZONITE,ANGEL_WING,APPLE_GREEN,APRICOT,AQUAMARINE,ARMY_GREEN,ARTICHOKE,ASPARAGUS,AVOCADO,BANANA_PUDDING,BEIGE,BLACK,BLACKLIGHT_GLOW,BLUE,BLUEBERRY,BLUE_EYE,BLUE_SMOKE,BLUE_STEEL,BOLOGNA,BOYSENBERRY,BRICK,BRIGHT_RED,BRONZE_SKIN_1,BRONZE_SKIN_2,BRONZE_SKIN_3,BRONZE_SKIN_4,BROWN_VELVET,BUBBLE,BUBBLEGUM_PINK,BUBBLE_GUM,BURNT_YELLOW,CALM_SKY,CARMINE,CEDAR_WOOD,CELADON,CELERY,CHARTREUSE,CHERRY_SYRUP,CHINCHILLA,CHIPPED_GRANITE,CLOUD,COAL_BLACK,COLD_IRON,CORNFLOWER_BLUE,CORN_SILK,COTTON_CANDY,CREAM,CRICKET,CYAN,DARK_GRAY,DARK_PINE,DARK_SKIN_1,DARK_SKIN_2,DARK_SKIN_3,DARK_TEAL,DEEP_JUNGLE,DEEP_PURPLE,DEEP_TEAL,DENIM_BLUE,DESERT_RAIN,DRAB_GREEN,DREARY_BLUE,DRIED_SAGE,DRIFTWOOD,DRY_BRUSH,DRY_PEPPER,DULL_AZURE,DULL_GREEN,DULL_VIOLET,DUN,DUSTY_GRAPE,DUSTY_GREEN,DUSTY_PINK,DUST_BUNNY,EARWAX,EGGPLANT,ELECTRIC_BLUE,EMBERS,EMERALD,EMINENCE,EUCALYPTUS,FADED_BLUE,FAWN,FEATHER_DOWN,FERN_GREEN,FLAMINGO,FLORAL_FOAM,FOREST_GLEN,FROG_GREEN,FRUIT_PUNCH,GARTER_SNAKE,GRAPE_LOLLIPOP,GRAPE_SODA,GRAPHITE,GRAY,GRAY_GREEN,GREEN,GREYHOUND,HAM,HELIOTROPE,HIDDEN_BLUE,HONEYDEW,HOSPITAL_GREEN,HOT_SAUCE,HUNTER_GREEN,INDIGO,INFECTION,IOLITE,IRIS,IRON,IVY_GREEN,JADE,JUICY_GRAPE,KELLY_GREEN,KOA,KYANITE,LAVENDER,LEAD,LIGHT_GRAY,LIGHT_SKIN_1,LIGHT_SKIN_2,LIGHT_SKIN_3,LIGHT_SKIN_4,LIGHT_SKIN_5,LIGHT_SKIN_6,LIGHT_SKIN_7,LIGHT_SKIN_8,LIGHT_SKIN_9,LILAC,LIST,LIZARD_SCALES,LURID_RED,MAGENTA,MAIDENHAIR_FERN,MALACHITE,MARSH,MAUVE,MEDIUM_PLUM,MEDIUM_TEAL,MILD_VIOLET,MINT_GREEN,MOSS_GREEN,MULBERRY,MUMMY_BROWN,MURK,MUSH,NAMED,NAVY_BLUE,NIGHTSHADE,NINJA,OCEAN_BLUE,OCHRE,OLD_ROSE,OLIVE_GREEN,OLIVE_OIL,ORANGE,ORCHID,PASTEL_SKY,PATINA,PEACH,PEAT_BOG,PEA_SOUP,PENCIL_YELLOW,PERIWINKLE,PINE_GREEN,PINK_LEMONADE,PINK_SKIN_1,PINK_SKIN_2,PINK_SKIN_3,PINK_SKIN_4,PINK_TUTU,PINK_VIOLET,PISTACHIO,PLATINUM,PLUM_JUICE,POLISHED_SAPPHIRE,PORK_CHOP,POWDER_BLUE,PRASE,PRUNE,PRUSSIAN_BLUE,PUCE,PURPLE,PURPLE_FREESIA,PUTTY,Palette,RASPBERRY,RAW_MEAT,RED,REDWOOD,REFRESHING_MIST,RIPE_PLUM,RIPPED_DENIM,ROBIN_EGG_BLUE,ROSE,ROSEATE_SPOONBILL,ROUGH_SAPPHIRE,ROYAL_BLUE,ROYAL_VIOLET,SAFFRON,SAGE_GREEN,SALMON,SCRIBE_INK,SEAFOAM,SEAL_BROWN,SEAWATER,SHADOW,SHARP_AZURE,SHINING_SKY,SHRIMP,SIENNA,SILVER,SILVER_GREEN,SILVER_PINK,SLATE_GRAY,SLOW_CREEK,SMOG,SOAP,SOFT_TEAL,SPACE_BLUE,SPEARMINT,SPRING_GREEN,STEAM,STRAW,STRONG_CYAN,STYGIAN_BLUE,SUBTLETY,SUDS,TAN,TARNISH,TAUPE,TAXICAB_YELLOW,TEA_ROSE,THICK_AMETHYST,THIN_AMETHYST,THISTLE,THULIAN_PINK,TRANSPARENT,TROPIC_MIST,TURQUOISE,TWILIGHT_CLOUD,TYRIAN_PURPLE,UMBER,VAPOR,VARISCITE,VARNISH,VIOLET,VIOLET_CUSHIONS,VIRIDIAN,WATERCOLOR_BLACK,WATERCOLOR_GRAY,WET_STONE,WHITE,WISTERIA,WOODLANDS,YELLOW,ZUCCHINI,appendToKnownColors,editKnownColors
 * Covenant-source-reference: com/github/tommyettinger/colorful/ipt_hq/Palette.java
 * Covenant-verified: 2026-04-19
 *
 * upstream-commit: e4a5fd960eef746ca5aa826063432fb79666d74f
 */
package sge
package colorful
package ipt_hq

import scala.collection.mutable

/** A palette of predefined colors as packed IPT_HQ floats, the kind [[ColorTools]] works with. You can access colors by their constant name, such as `OCEAN_BLUE`, by the [[NAMED]] map using
  * `NAMED.getOrElse("Ocean Blue", 0f)`, or by index in the list called [[LIST]].
  */
object Palette {

  /** Maps color names to packed float colors. */
  val NAMED: mutable.HashMap[String, Float] = mutable.HashMap.empty[String, Float]

  /** Lists packed float color values, in declaration order. */
  val LIST: mutable.ArrayBuffer[Float] = mutable.ArrayBuffer.empty[Float]

  val TRANSPARENT:       Float = java.lang.Float.intBitsToFloat(0x7f7f00)
  val BLACK:             Float = java.lang.Float.intBitsToFloat(0xfe7f7f00)
  val COAL_BLACK:        Float = java.lang.Float.intBitsToFloat(0xfe7f801b)
  val SHADOW:            Float = java.lang.Float.intBitsToFloat(0xfe7f8030)
  val GRAPHITE:          Float = java.lang.Float.intBitsToFloat(0xfe7f8044)
  val DARK_GRAY:         Float = java.lang.Float.intBitsToFloat(0xfe7f8057)
  val LEAD:              Float = java.lang.Float.intBitsToFloat(0xfe7f8069)
  val IRON:              Float = java.lang.Float.intBitsToFloat(0xfe7f807c)
  val GRAY:              Float = java.lang.Float.intBitsToFloat(0xfe7f808d)
  val CHINCHILLA:        Float = java.lang.Float.intBitsToFloat(0xfe7f809e)
  val GREYHOUND:         Float = java.lang.Float.intBitsToFloat(0xfe7f80af)
  val SILVER:            Float = java.lang.Float.intBitsToFloat(0xfe7f80bf)
  val LIGHT_GRAY:        Float = java.lang.Float.intBitsToFloat(0xfe7f80d0)
  val PLATINUM:          Float = java.lang.Float.intBitsToFloat(0xfe7f80e0)
  val CLOUD:             Float = java.lang.Float.intBitsToFloat(0xfe7f80f0)
  val WHITE:             Float = java.lang.Float.intBitsToFloat(0xfe7f80ff)
  val SEAWATER:          Float = java.lang.Float.intBitsToFloat(0xfe766880)
  val HOSPITAL_GREEN:    Float = java.lang.Float.intBitsToFloat(0xfe7462b8)
  val CYAN:              Float = java.lang.Float.intBitsToFloat(0xfe6e54e9)
  val BUBBLE:            Float = java.lang.Float.intBitsToFloat(0xfe786ef6)
  val PERIWINKLE:        Float = java.lang.Float.intBitsToFloat(0xfe4a7eac)
  val BLUE:              Float = java.lang.Float.intBitsToFloat(0xfe206171)
  val FADED_BLUE:        Float = java.lang.Float.intBitsToFloat(0xfe477971)
  val OCEAN_BLUE:        Float = java.lang.Float.intBitsToFloat(0xfe4b6f3e)
  val STYGIAN_BLUE:      Float = java.lang.Float.intBitsToFloat(0xfe5f782e)
  val DEEP_PURPLE:       Float = java.lang.Float.intBitsToFloat(0xfe64a85e)
  val TYRIAN_PURPLE:     Float = java.lang.Float.intBitsToFloat(0xfe5fad8f)
  val MAGENTA:           Float = java.lang.Float.intBitsToFloat(0xfe4fc6a5)
  val BUBBLEGUM_PINK:    Float = java.lang.Float.intBitsToFloat(0xfe5eaac6)
  val PORK_CHOP:         Float = java.lang.Float.intBitsToFloat(0xfe8494d6)
  val RAW_MEAT:          Float = java.lang.Float.intBitsToFloat(0xfe94abab)
  val RED:               Float = java.lang.Float.intBitsToFloat(0xfeb8cf74)
  val PUTTY:             Float = java.lang.Float.intBitsToFloat(0xfe99b071)
  val SIENNA:            Float = java.lang.Float.intBitsToFloat(0xfe9fab40)
  val SEAL_BROWN:        Float = java.lang.Float.intBitsToFloat(0xfe8f9b33)
  val MUMMY_BROWN:       Float = java.lang.Float.intBitsToFloat(0xfea39453)
  val FAWN:              Float = java.lang.Float.intBitsToFloat(0xfea6928d)
  val ORANGE:            Float = java.lang.Float.intBitsToFloat(0xfec0a597)
  val PEACH:             Float = java.lang.Float.intBitsToFloat(0xfea391c7)
  val CREAM:             Float = java.lang.Float.intBitsToFloat(0xfe9a7df3)
  val YELLOW:            Float = java.lang.Float.intBitsToFloat(0xfed372db)
  val EARWAX:            Float = java.lang.Float.intBitsToFloat(0xfeb478b0)
  val UMBER:             Float = java.lang.Float.intBitsToFloat(0xfead7878)
  val IVY_GREEN:         Float = java.lang.Float.intBitsToFloat(0xfea5606a)
  val JADE:              Float = java.lang.Float.intBitsToFloat(0xfea95a9f)
  val GREEN:             Float = java.lang.Float.intBitsToFloat(0xfec345c2)
  val CELADON:           Float = java.lang.Float.intBitsToFloat(0xfe9767e4)
  val PUCE:              Float = java.lang.Float.intBitsToFloat(0xfe7a84bf)
  val BEIGE:             Float = java.lang.Float.intBitsToFloat(0xfe9289b3)
  val WET_STONE:         Float = java.lang.Float.intBitsToFloat(0xfe8781a9)
  val SLOW_CREEK:        Float = java.lang.Float.intBitsToFloat(0xfe7d799c)
  val SLATE_GRAY:        Float = java.lang.Float.intBitsToFloat(0xfe7b7a8d)
  val LIGHT_SKIN_1:      Float = java.lang.Float.intBitsToFloat(0xfe88847c)
  val LIGHT_SKIN_2:      Float = java.lang.Float.intBitsToFloat(0xfe8d9281)
  val LIGHT_SKIN_3:      Float = java.lang.Float.intBitsToFloat(0xfe8e9894)
  val LIGHT_SKIN_4:      Float = java.lang.Float.intBitsToFloat(0xfe9496a0)
  val LIGHT_SKIN_5:      Float = java.lang.Float.intBitsToFloat(0xfe9795ae)
  val LIGHT_SKIN_6:      Float = java.lang.Float.intBitsToFloat(0xfe9693bb)
  val LIGHT_SKIN_7:      Float = java.lang.Float.intBitsToFloat(0xfe9591c7)
  val LIGHT_SKIN_8:      Float = java.lang.Float.intBitsToFloat(0xfe908dd3)
  val LIGHT_SKIN_9:      Float = java.lang.Float.intBitsToFloat(0xfe8885e6)
  val DARK_SKIN_1:       Float = java.lang.Float.intBitsToFloat(0xfe848a4f)
  val DARK_SKIN_2:       Float = java.lang.Float.intBitsToFloat(0xfe8b9259)
  val DARK_SKIN_3:       Float = java.lang.Float.intBitsToFloat(0xfe899470)
  val PINK_SKIN_1:       Float = java.lang.Float.intBitsToFloat(0xfe88938c)
  val PINK_SKIN_2:       Float = java.lang.Float.intBitsToFloat(0xfe8892a6)
  val PINK_SKIN_3:       Float = java.lang.Float.intBitsToFloat(0xfe8892c0)
  val PINK_SKIN_4:       Float = java.lang.Float.intBitsToFloat(0xfe818be1)
  val BRONZE_SKIN_4:     Float = java.lang.Float.intBitsToFloat(0xfe8f87ce)
  val BRONZE_SKIN_3:     Float = java.lang.Float.intBitsToFloat(0xfe988aa8)
  val BRONZE_SKIN_2:     Float = java.lang.Float.intBitsToFloat(0xfe908880)
  val BRONZE_SKIN_1:     Float = java.lang.Float.intBitsToFloat(0xfe918865)
  val TAUPE:             Float = java.lang.Float.intBitsToFloat(0xfe898439)
  val DRAB_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe8e7e48)
  val LIZARD_SCALES:     Float = java.lang.Float.intBitsToFloat(0xfe997c75)
  val CRICKET:           Float = java.lang.Float.intBitsToFloat(0xfe987d90)
  val OLIVE_OIL:         Float = java.lang.Float.intBitsToFloat(0xfea17b9d)
  val DUN:               Float = java.lang.Float.intBitsToFloat(0xfe9c7cb1)
  val CORN_SILK:         Float = java.lang.Float.intBitsToFloat(0xfe977dc3)
  val TAN:               Float = java.lang.Float.intBitsToFloat(0xfe937ed6)
  val STRAW:             Float = java.lang.Float.intBitsToFloat(0xfe8f7ee8)
  val HONEYDEW:          Float = java.lang.Float.intBitsToFloat(0xfe9375d7)
  val TARNISH:           Float = java.lang.Float.intBitsToFloat(0xfe9475be)
  val PEA_SOUP:          Float = java.lang.Float.intBitsToFloat(0xfea66caa)
  val MARSH:             Float = java.lang.Float.intBitsToFloat(0xfe95748b)
  val ASPARAGUS:         Float = java.lang.Float.intBitsToFloat(0xfe977177)
  val PEAT_BOG:          Float = java.lang.Float.intBitsToFloat(0xfe8d7b55)
  val DEEP_JUNGLE:       Float = java.lang.Float.intBitsToFloat(0xfe877d23)
  val PINE_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe867251)
  val OLIVE_GREEN:       Float = java.lang.Float.intBitsToFloat(0xfe89755a)
  val GRAY_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe86786a)
  val MAIDENHAIR_FERN:   Float = java.lang.Float.intBitsToFloat(0xfe8c6e6f)
  val KELLY_GREEN:       Float = java.lang.Float.intBitsToFloat(0xfe926d87)
  val DUSTY_GREEN:       Float = java.lang.Float.intBitsToFloat(0xfe916da1)
  val GARTER_SNAKE:      Float = java.lang.Float.intBitsToFloat(0xfe9065af)
  val SILVER_GREEN:      Float = java.lang.Float.intBitsToFloat(0xfe916eba)
  val PISTACHIO:         Float = java.lang.Float.intBitsToFloat(0xfe906eca)
  val ANGEL_WING:        Float = java.lang.Float.intBitsToFloat(0xfe7c79f6)
  val SAGE_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe886ee1)
  val DRIED_SAGE:        Float = java.lang.Float.intBitsToFloat(0xfe866fd9)
  val ARTICHOKE:         Float = java.lang.Float.intBitsToFloat(0xfe8a71ae)
  val VIRIDIAN:          Float = java.lang.Float.intBitsToFloat(0xfe88717d)
  val FLORAL_FOAM:       Float = java.lang.Float.intBitsToFloat(0xfe886a65)
  val HUNTER_GREEN:      Float = java.lang.Float.intBitsToFloat(0xfe837a34)
  val DARK_TEAL:         Float = java.lang.Float.intBitsToFloat(0xfe79774b)
  val KYANITE:           Float = java.lang.Float.intBitsToFloat(0xfe797078)
  val SPEARMINT:         Float = java.lang.Float.intBitsToFloat(0xfe786dab)
  val AMAZONITE:         Float = java.lang.Float.intBitsToFloat(0xfe7970c6)
  val PASTEL_SKY:        Float = java.lang.Float.intBitsToFloat(0xfe7970df)
  val AQUAMARINE:        Float = java.lang.Float.intBitsToFloat(0xfe7b74ed)
  val DUST_BUNNY:        Float = java.lang.Float.intBitsToFloat(0xfe717adb)
  val PATINA:            Float = java.lang.Float.intBitsToFloat(0xfe7078d0)
  val CHIPPED_GRANITE:   Float = java.lang.Float.intBitsToFloat(0xfe6f7bc7)
  val BLUE_SMOKE:        Float = java.lang.Float.intBitsToFloat(0xfe7078b7)
  val AIR_FORCE_BLUE:    Float = java.lang.Float.intBitsToFloat(0xfe6171a0)
  val COLD_IRON:         Float = java.lang.Float.intBitsToFloat(0xfe6f7882)
  val DREARY_BLUE:       Float = java.lang.Float.intBitsToFloat(0xfe6f7767)
  val MURK:              Float = java.lang.Float.intBitsToFloat(0xfe737c26)
  val NINJA:             Float = java.lang.Float.intBitsToFloat(0xfe717f32)
  val WATERCOLOR_BLACK:  Float = java.lang.Float.intBitsToFloat(0xfe72804f)
  val IOLITE:            Float = java.lang.Float.intBitsToFloat(0xfe6c8061)
  val BOYSENBERRY:       Float = java.lang.Float.intBitsToFloat(0xfe667f73)
  val WATERCOLOR_GRAY:   Float = java.lang.Float.intBitsToFloat(0xfe65818b)
  val BLUE_STEEL:        Float = java.lang.Float.intBitsToFloat(0xfe5b7f98)
  val TWILIGHT_CLOUD:    Float = java.lang.Float.intBitsToFloat(0xfe6780a8)
  val SMOG:              Float = java.lang.Float.intBitsToFloat(0xfe6880c1)
  val TROPIC_MIST:       Float = java.lang.Float.intBitsToFloat(0xfe727de4)
  val FEATHER_DOWN:      Float = java.lang.Float.intBitsToFloat(0xfe7480ed)
  val MILD_VIOLET:       Float = java.lang.Float.intBitsToFloat(0xfe6b89ad)
  val VIOLET_CUSHIONS:   Float = java.lang.Float.intBitsToFloat(0xfe57918d)
  val DULL_VIOLET:       Float = java.lang.Float.intBitsToFloat(0xfe6a8978)
  val ROYAL_VIOLET:      Float = java.lang.Float.intBitsToFloat(0xfe69895d)
  val EMINENCE:          Float = java.lang.Float.intBitsToFloat(0xfe778a3b)
  val PRUNE:             Float = java.lang.Float.intBitsToFloat(0xfe798848)
  val DUSTY_GRAPE:       Float = java.lang.Float.intBitsToFloat(0xfe719366)
  val PINK_VIOLET:       Float = java.lang.Float.intBitsToFloat(0xfe6f947f)
  val RIPE_PLUM:         Float = java.lang.Float.intBitsToFloat(0xfe689e8d)
  val MAUVE:             Float = java.lang.Float.intBitsToFloat(0xfe6f9399)
  val HAM:               Float = java.lang.Float.intBitsToFloat(0xfe7295cd)
  val COTTON_CANDY:      Float = java.lang.Float.intBitsToFloat(0xfe7a8bec)
  val SILVER_PINK:       Float = java.lang.Float.intBitsToFloat(0xfe7889d9)
  val TEA_ROSE:          Float = java.lang.Float.intBitsToFloat(0xfe7a8dce)
  val OLD_ROSE:          Float = java.lang.Float.intBitsToFloat(0xfe7b92bc)
  val DUSTY_PINK:        Float = java.lang.Float.intBitsToFloat(0xfe7693b0)
  val ROSEATE_SPOONBILL: Float = java.lang.Float.intBitsToFloat(0xfe7c9aa2)
  val THULIAN_PINK:      Float = java.lang.Float.intBitsToFloat(0xfe79a78e)
  val BROWN_VELVET:      Float = java.lang.Float.intBitsToFloat(0xfe7e8e41)
  val NIGHTSHADE:        Float = java.lang.Float.intBitsToFloat(0xfe7e8c2b)
  val SCRIBE_INK:        Float = java.lang.Float.intBitsToFloat(0xfe7c8e21)
  val VARNISH:           Float = java.lang.Float.intBitsToFloat(0xfe8c902c)
  val CEDAR_WOOD:        Float = java.lang.Float.intBitsToFloat(0xfe999c37)
  val HOT_SAUCE:         Float = java.lang.Float.intBitsToFloat(0xfea6b452)
  val LURID_RED:         Float = java.lang.Float.intBitsToFloat(0xfeafc16a)
  val BRICK:             Float = java.lang.Float.intBitsToFloat(0xfe9caf81)
  val BRIGHT_RED:        Float = java.lang.Float.intBitsToFloat(0xfeb9c27e)
  val EMBERS:            Float = java.lang.Float.intBitsToFloat(0xfeaeb589)
  val SALMON:            Float = java.lang.Float.intBitsToFloat(0xfe9cb898)
  val TAXICAB_YELLOW:    Float = java.lang.Float.intBitsToFloat(0xfebf89b8)
  val APRICOT:           Float = java.lang.Float.intBitsToFloat(0xfeb897af)
  val BURNT_YELLOW:      Float = java.lang.Float.intBitsToFloat(0xfebd8b9c)
  val DRY_PEPPER:        Float = java.lang.Float.intBitsToFloat(0xfeb7a085)
  val REDWOOD:           Float = java.lang.Float.intBitsToFloat(0xfeaf9b70)
  val KOA:               Float = java.lang.Float.intBitsToFloat(0xfeaa9b63)
  val OCHRE:             Float = java.lang.Float.intBitsToFloat(0xfe968f44)
  val DULL_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe9e7c51)
  val ARMY_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfea47960)
  val DRIFTWOOD:         Float = java.lang.Float.intBitsToFloat(0xfe928287)
  val DRY_BRUSH:         Float = java.lang.Float.intBitsToFloat(0xfeb77f8e)
  val MUSH:              Float = java.lang.Float.intBitsToFloat(0xfebc75a0)
  val BANANA_PUDDING:    Float = java.lang.Float.intBitsToFloat(0xfeb47ec7)
  val SAFFRON:           Float = java.lang.Float.intBitsToFloat(0xfecb81c4)
  val PENCIL_YELLOW:     Float = java.lang.Float.intBitsToFloat(0xfec17cd5)
  val CHARTREUSE:        Float = java.lang.Float.intBitsToFloat(0xfec365d6)
  val ABSINTHE:          Float = java.lang.Float.intBitsToFloat(0xfeba5fc8)
  val INFECTION:         Float = java.lang.Float.intBitsToFloat(0xfec061b6)
  val FROG_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfebb5ea5)
  val AVOCADO:           Float = java.lang.Float.intBitsToFloat(0xfeb3658f)
  val WOODLANDS:         Float = java.lang.Float.intBitsToFloat(0xfea06b63)
  val DARK_PINE:         Float = java.lang.Float.intBitsToFloat(0xfe937835)
  val MOSS_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe967042)
  val FERN_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe9b6851)
  val FOREST_GLEN:       Float = java.lang.Float.intBitsToFloat(0xfeab5b7b)
  val MALACHITE:         Float = java.lang.Float.intBitsToFloat(0xfeba4ea8)
  val APPLE_GREEN:       Float = java.lang.Float.intBitsToFloat(0xfebd4bb2)
  val CELERY:            Float = java.lang.Float.intBitsToFloat(0xfeab58d4)
  val MINT_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfeae52c3)
  val EMERALD:           Float = java.lang.Float.intBitsToFloat(0xfeb4519c)
  val PRASE:             Float = java.lang.Float.intBitsToFloat(0xfe9d5998)
  val EUCALYPTUS:        Float = java.lang.Float.intBitsToFloat(0xfe91637e)
  val ZUCCHINI:          Float = java.lang.Float.intBitsToFloat(0xfe7e753e)
  val SOFT_TEAL:         Float = java.lang.Float.intBitsToFloat(0xfe7f6390)
  val MEDIUM_TEAL:       Float = java.lang.Float.intBitsToFloat(0xfe875baf)
  val SPRING_GREEN:      Float = java.lang.Float.intBitsToFloat(0xfea052b8)
  val TURQUOISE:         Float = java.lang.Float.intBitsToFloat(0xfe8c56cc)
  val SEAFOAM:           Float = java.lang.Float.intBitsToFloat(0xfe9453d8)
  val VARISCITE:         Float = java.lang.Float.intBitsToFloat(0xfe865be3)
  val REFRESHING_MIST:   Float = java.lang.Float.intBitsToFloat(0xfe6e69e6)
  val SHINING_SKY:       Float = java.lang.Float.intBitsToFloat(0xfe685fdd)
  val STEAM:             Float = java.lang.Float.intBitsToFloat(0xfe6c69d5)
  val ROBIN_EGG_BLUE:    Float = java.lang.Float.intBitsToFloat(0xfe7459cd)
  val DENIM_BLUE:        Float = java.lang.Float.intBitsToFloat(0xfe5864a8)
  val DEEP_TEAL:         Float = java.lang.Float.intBitsToFloat(0xfe776e5f)
  val NAVY_BLUE:         Float = java.lang.Float.intBitsToFloat(0xfe6a783f)
  val BLUEBERRY:         Float = java.lang.Float.intBitsToFloat(0xfe5b7353)
  val PRUSSIAN_BLUE:     Float = java.lang.Float.intBitsToFloat(0xfe556f67)
  val DESERT_RAIN:       Float = java.lang.Float.intBitsToFloat(0xfe637277)
  val ELECTRIC_BLUE:     Float = java.lang.Float.intBitsToFloat(0xfe346886)
  val HIDDEN_BLUE:       Float = java.lang.Float.intBitsToFloat(0xfe536c83)
  val DULL_AZURE:        Float = java.lang.Float.intBitsToFloat(0xfe4c6b94)
  val RIPPED_DENIM:      Float = java.lang.Float.intBitsToFloat(0xfe6972a9)
  val CALM_SKY:          Float = java.lang.Float.intBitsToFloat(0xfe5069b8)
  val VAPOR:             Float = java.lang.Float.intBitsToFloat(0xfe5b77c6)
  val POWDER_BLUE:       Float = java.lang.Float.intBitsToFloat(0xfe5d66cb)
  val SUDS:              Float = java.lang.Float.intBitsToFloat(0xfe6582d1)
  val STRONG_CYAN:       Float = java.lang.Float.intBitsToFloat(0xfe575fc4)
  val SHARP_AZURE:       Float = java.lang.Float.intBitsToFloat(0xfe4066a0)
  val BLUE_EYE:          Float = java.lang.Float.intBitsToFloat(0xfe597295)
  val SUBTLETY:          Float = java.lang.Float.intBitsToFloat(0xfe49809e)
  val ROUGH_SAPPHIRE:    Float = java.lang.Float.intBitsToFloat(0xfe377392)
  val IRIS:              Float = java.lang.Float.intBitsToFloat(0xfe377f88)
  val CORNFLOWER_BLUE:   Float = java.lang.Float.intBitsToFloat(0xfe317280)
  val POLISHED_SAPPHIRE: Float = java.lang.Float.intBitsToFloat(0xfe2f6867)
  val ROYAL_BLUE:        Float = java.lang.Float.intBitsToFloat(0xfe376959)
  val INDIGO:            Float = java.lang.Float.intBitsToFloat(0xfe48764c)
  val SPACE_BLUE:        Float = java.lang.Float.intBitsToFloat(0xfe697834)
  val THICK_AMETHYST:    Float = java.lang.Float.intBitsToFloat(0xfe458760)
  val JUICY_GRAPE:       Float = java.lang.Float.intBitsToFloat(0xfe3c896f)
  val BLACKLIGHT_GLOW:   Float = java.lang.Float.intBitsToFloat(0xfe489681)
  val PURPLE_FREESIA:    Float = java.lang.Float.intBitsToFloat(0xfe3e9698)
  val THIN_AMETHYST:     Float = java.lang.Float.intBitsToFloat(0xfe309085)
  val ORCHID:            Float = java.lang.Float.intBitsToFloat(0xfe4b9bab)
  val LAVENDER:          Float = java.lang.Float.intBitsToFloat(0xfe578cbe)
  val LILAC:             Float = java.lang.Float.intBitsToFloat(0xfe6190cd)
  val SOAP:              Float = java.lang.Float.intBitsToFloat(0xfe6b87da)
  val PINK_TUTU:         Float = java.lang.Float.intBitsToFloat(0xfe7090e2)
  val THISTLE:           Float = java.lang.Float.intBitsToFloat(0xfe56a6bb)
  val HELIOTROPE:        Float = java.lang.Float.intBitsToFloat(0xfe55bab7)
  val PURPLE:            Float = java.lang.Float.intBitsToFloat(0xfe53bc99)
  val WISTERIA:          Float = java.lang.Float.intBitsToFloat(0xfe41a99b)
  val MEDIUM_PLUM:       Float = java.lang.Float.intBitsToFloat(0xfe56b687)
  val VIOLET:            Float = java.lang.Float.intBitsToFloat(0xfe4da176)
  val GRAPE_LOLLIPOP:    Float = java.lang.Float.intBitsToFloat(0xfe5e9453)
  val MULBERRY:          Float = java.lang.Float.intBitsToFloat(0xfe6b9d4e)
  val GRAPE_SODA:        Float = java.lang.Float.intBitsToFloat(0xfe618f3f)
  val EGGPLANT:          Float = java.lang.Float.intBitsToFloat(0xfe6a8c32)
  val CHERRY_SYRUP:      Float = java.lang.Float.intBitsToFloat(0xfe7d993e)
  val PLUM_JUICE:        Float = java.lang.Float.intBitsToFloat(0xfe6db16c)
  val FRUIT_PUNCH:       Float = java.lang.Float.intBitsToFloat(0xfe7ac375)
  val BUBBLE_GUM:        Float = java.lang.Float.intBitsToFloat(0xfe70c0a7)
  val PINK_LEMONADE:     Float = java.lang.Float.intBitsToFloat(0xfe72b6b1)
  val SHRIMP:            Float = java.lang.Float.intBitsToFloat(0xfe829ec3)
  val FLAMINGO:          Float = java.lang.Float.intBitsToFloat(0xfe82c894)
  val ROSE:              Float = java.lang.Float.intBitsToFloat(0xfe83c982)
  val CARMINE:           Float = java.lang.Float.intBitsToFloat(0xfe96bf63)
  val BOLOGNA:           Float = java.lang.Float.intBitsToFloat(0xfe88a763)
  val RASPBERRY:         Float = java.lang.Float.intBitsToFloat(0xfe8db153)

  // Register all colors
  locally {
    NAMED.put("Transparent", java.lang.Float.intBitsToFloat(0x7f7f00))
    LIST += java.lang.Float.intBitsToFloat(0x7f7f00)
    NAMED.put("Black", java.lang.Float.intBitsToFloat(0xfe7f7f00))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7f00)
    NAMED.put("Coal Black", java.lang.Float.intBitsToFloat(0xfe7f801b))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f801b)
    NAMED.put("Shadow", java.lang.Float.intBitsToFloat(0xfe7f8030))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f8030)
    NAMED.put("Graphite", java.lang.Float.intBitsToFloat(0xfe7f8044))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f8044)
    NAMED.put("Dark Gray", java.lang.Float.intBitsToFloat(0xfe7f8057))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f8057)
    NAMED.put("Lead", java.lang.Float.intBitsToFloat(0xfe7f8069))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f8069)
    NAMED.put("Iron", java.lang.Float.intBitsToFloat(0xfe7f807c))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f807c)
    NAMED.put("Gray", java.lang.Float.intBitsToFloat(0xfe7f808d))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f808d)
    NAMED.put("Chinchilla", java.lang.Float.intBitsToFloat(0xfe7f809e))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f809e)
    NAMED.put("Greyhound", java.lang.Float.intBitsToFloat(0xfe7f80af))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f80af)
    NAMED.put("Silver", java.lang.Float.intBitsToFloat(0xfe7f80bf))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f80bf)
    NAMED.put("Light Gray", java.lang.Float.intBitsToFloat(0xfe7f80d0))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f80d0)
    NAMED.put("Platinum", java.lang.Float.intBitsToFloat(0xfe7f80e0))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f80e0)
    NAMED.put("Cloud", java.lang.Float.intBitsToFloat(0xfe7f80f0))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f80f0)
    NAMED.put("White", java.lang.Float.intBitsToFloat(0xfe7f80ff))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f80ff)
    NAMED.put("Seawater", java.lang.Float.intBitsToFloat(0xfe766880))
    LIST += java.lang.Float.intBitsToFloat(0xfe766880)
    NAMED.put("Hospital Green", java.lang.Float.intBitsToFloat(0xfe7462b8))
    LIST += java.lang.Float.intBitsToFloat(0xfe7462b8)
    NAMED.put("Cyan", java.lang.Float.intBitsToFloat(0xfe6e54e9))
    LIST += java.lang.Float.intBitsToFloat(0xfe6e54e9)
    NAMED.put("Bubble", java.lang.Float.intBitsToFloat(0xfe786ef6))
    LIST += java.lang.Float.intBitsToFloat(0xfe786ef6)
    NAMED.put("Periwinkle", java.lang.Float.intBitsToFloat(0xfe4a7eac))
    LIST += java.lang.Float.intBitsToFloat(0xfe4a7eac)
    NAMED.put("Blue", java.lang.Float.intBitsToFloat(0xfe206171))
    LIST += java.lang.Float.intBitsToFloat(0xfe206171)
    NAMED.put("Faded Blue", java.lang.Float.intBitsToFloat(0xfe477971))
    LIST += java.lang.Float.intBitsToFloat(0xfe477971)
    NAMED.put("Ocean Blue", java.lang.Float.intBitsToFloat(0xfe4b6f3e))
    LIST += java.lang.Float.intBitsToFloat(0xfe4b6f3e)
    NAMED.put("Stygian Blue", java.lang.Float.intBitsToFloat(0xfe5f782e))
    LIST += java.lang.Float.intBitsToFloat(0xfe5f782e)
    NAMED.put("Deep Purple", java.lang.Float.intBitsToFloat(0xfe64a85e))
    LIST += java.lang.Float.intBitsToFloat(0xfe64a85e)
    NAMED.put("Tyrian Purple", java.lang.Float.intBitsToFloat(0xfe5fad8f))
    LIST += java.lang.Float.intBitsToFloat(0xfe5fad8f)
    NAMED.put("Magenta", java.lang.Float.intBitsToFloat(0xfe4fc6a5))
    LIST += java.lang.Float.intBitsToFloat(0xfe4fc6a5)
    NAMED.put("Bubblegum Pink", java.lang.Float.intBitsToFloat(0xfe5eaac6))
    LIST += java.lang.Float.intBitsToFloat(0xfe5eaac6)
    NAMED.put("Pork Chop", java.lang.Float.intBitsToFloat(0xfe8494d6))
    LIST += java.lang.Float.intBitsToFloat(0xfe8494d6)
    NAMED.put("Raw Meat", java.lang.Float.intBitsToFloat(0xfe94abab))
    LIST += java.lang.Float.intBitsToFloat(0xfe94abab)
    NAMED.put("Red", java.lang.Float.intBitsToFloat(0xfeb8cf74))
    LIST += java.lang.Float.intBitsToFloat(0xfeb8cf74)
    NAMED.put("Putty", java.lang.Float.intBitsToFloat(0xfe99b071))
    LIST += java.lang.Float.intBitsToFloat(0xfe99b071)
    NAMED.put("Sienna", java.lang.Float.intBitsToFloat(0xfe9fab40))
    LIST += java.lang.Float.intBitsToFloat(0xfe9fab40)
    NAMED.put("Seal Brown", java.lang.Float.intBitsToFloat(0xfe8f9b33))
    LIST += java.lang.Float.intBitsToFloat(0xfe8f9b33)
    NAMED.put("Mummy Brown", java.lang.Float.intBitsToFloat(0xfea39453))
    LIST += java.lang.Float.intBitsToFloat(0xfea39453)
    NAMED.put("Fawn", java.lang.Float.intBitsToFloat(0xfea6928d))
    LIST += java.lang.Float.intBitsToFloat(0xfea6928d)
    NAMED.put("Orange", java.lang.Float.intBitsToFloat(0xfec0a597))
    LIST += java.lang.Float.intBitsToFloat(0xfec0a597)
    NAMED.put("Peach", java.lang.Float.intBitsToFloat(0xfea391c7))
    LIST += java.lang.Float.intBitsToFloat(0xfea391c7)
    NAMED.put("Cream", java.lang.Float.intBitsToFloat(0xfe9a7df3))
    LIST += java.lang.Float.intBitsToFloat(0xfe9a7df3)
    NAMED.put("Yellow", java.lang.Float.intBitsToFloat(0xfed372db))
    LIST += java.lang.Float.intBitsToFloat(0xfed372db)
    NAMED.put("Earwax", java.lang.Float.intBitsToFloat(0xfeb478b0))
    LIST += java.lang.Float.intBitsToFloat(0xfeb478b0)
    NAMED.put("Umber", java.lang.Float.intBitsToFloat(0xfead7878))
    LIST += java.lang.Float.intBitsToFloat(0xfead7878)
    NAMED.put("Ivy Green", java.lang.Float.intBitsToFloat(0xfea5606a))
    LIST += java.lang.Float.intBitsToFloat(0xfea5606a)
    NAMED.put("Jade", java.lang.Float.intBitsToFloat(0xfea95a9f))
    LIST += java.lang.Float.intBitsToFloat(0xfea95a9f)
    NAMED.put("Green", java.lang.Float.intBitsToFloat(0xfec345c2))
    LIST += java.lang.Float.intBitsToFloat(0xfec345c2)
    NAMED.put("Celadon", java.lang.Float.intBitsToFloat(0xfe9767e4))
    LIST += java.lang.Float.intBitsToFloat(0xfe9767e4)
    NAMED.put("Puce", java.lang.Float.intBitsToFloat(0xfe7a84bf))
    LIST += java.lang.Float.intBitsToFloat(0xfe7a84bf)
    NAMED.put("Beige", java.lang.Float.intBitsToFloat(0xfe9289b3))
    LIST += java.lang.Float.intBitsToFloat(0xfe9289b3)
    NAMED.put("Wet Stone", java.lang.Float.intBitsToFloat(0xfe8781a9))
    LIST += java.lang.Float.intBitsToFloat(0xfe8781a9)
    NAMED.put("Slow Creek", java.lang.Float.intBitsToFloat(0xfe7d799c))
    LIST += java.lang.Float.intBitsToFloat(0xfe7d799c)
    NAMED.put("Slate Gray", java.lang.Float.intBitsToFloat(0xfe7b7a8d))
    LIST += java.lang.Float.intBitsToFloat(0xfe7b7a8d)
    NAMED.put("Light Skin 1", java.lang.Float.intBitsToFloat(0xfe88847c))
    LIST += java.lang.Float.intBitsToFloat(0xfe88847c)
    NAMED.put("Light Skin 2", java.lang.Float.intBitsToFloat(0xfe8d9281))
    LIST += java.lang.Float.intBitsToFloat(0xfe8d9281)
    NAMED.put("Light Skin 3", java.lang.Float.intBitsToFloat(0xfe8e9894))
    LIST += java.lang.Float.intBitsToFloat(0xfe8e9894)
    NAMED.put("Light Skin 4", java.lang.Float.intBitsToFloat(0xfe9496a0))
    LIST += java.lang.Float.intBitsToFloat(0xfe9496a0)
    NAMED.put("Light Skin 5", java.lang.Float.intBitsToFloat(0xfe9795ae))
    LIST += java.lang.Float.intBitsToFloat(0xfe9795ae)
    NAMED.put("Light Skin 6", java.lang.Float.intBitsToFloat(0xfe9693bb))
    LIST += java.lang.Float.intBitsToFloat(0xfe9693bb)
    NAMED.put("Light Skin 7", java.lang.Float.intBitsToFloat(0xfe9591c7))
    LIST += java.lang.Float.intBitsToFloat(0xfe9591c7)
    NAMED.put("Light Skin 8", java.lang.Float.intBitsToFloat(0xfe908dd3))
    LIST += java.lang.Float.intBitsToFloat(0xfe908dd3)
    NAMED.put("Light Skin 9", java.lang.Float.intBitsToFloat(0xfe8885e6))
    LIST += java.lang.Float.intBitsToFloat(0xfe8885e6)
    NAMED.put("Dark Skin 1", java.lang.Float.intBitsToFloat(0xfe848a4f))
    LIST += java.lang.Float.intBitsToFloat(0xfe848a4f)
    NAMED.put("Dark Skin 2", java.lang.Float.intBitsToFloat(0xfe8b9259))
    LIST += java.lang.Float.intBitsToFloat(0xfe8b9259)
    NAMED.put("Dark Skin 3", java.lang.Float.intBitsToFloat(0xfe899470))
    LIST += java.lang.Float.intBitsToFloat(0xfe899470)
    NAMED.put("Pink Skin 1", java.lang.Float.intBitsToFloat(0xfe88938c))
    LIST += java.lang.Float.intBitsToFloat(0xfe88938c)
    NAMED.put("Pink Skin 2", java.lang.Float.intBitsToFloat(0xfe8892a6))
    LIST += java.lang.Float.intBitsToFloat(0xfe8892a6)
    NAMED.put("Pink Skin 3", java.lang.Float.intBitsToFloat(0xfe8892c0))
    LIST += java.lang.Float.intBitsToFloat(0xfe8892c0)
    NAMED.put("Pink Skin 4", java.lang.Float.intBitsToFloat(0xfe818be1))
    LIST += java.lang.Float.intBitsToFloat(0xfe818be1)
    NAMED.put("Bronze Skin 4", java.lang.Float.intBitsToFloat(0xfe8f87ce))
    LIST += java.lang.Float.intBitsToFloat(0xfe8f87ce)
    NAMED.put("Bronze Skin 3", java.lang.Float.intBitsToFloat(0xfe988aa8))
    LIST += java.lang.Float.intBitsToFloat(0xfe988aa8)
    NAMED.put("Bronze Skin 2", java.lang.Float.intBitsToFloat(0xfe908880))
    LIST += java.lang.Float.intBitsToFloat(0xfe908880)
    NAMED.put("Bronze Skin 1", java.lang.Float.intBitsToFloat(0xfe918865))
    LIST += java.lang.Float.intBitsToFloat(0xfe918865)
    NAMED.put("Taupe", java.lang.Float.intBitsToFloat(0xfe898439))
    LIST += java.lang.Float.intBitsToFloat(0xfe898439)
    NAMED.put("Drab Green", java.lang.Float.intBitsToFloat(0xfe8e7e48))
    LIST += java.lang.Float.intBitsToFloat(0xfe8e7e48)
    NAMED.put("Lizard Scales", java.lang.Float.intBitsToFloat(0xfe997c75))
    LIST += java.lang.Float.intBitsToFloat(0xfe997c75)
    NAMED.put("Cricket", java.lang.Float.intBitsToFloat(0xfe987d90))
    LIST += java.lang.Float.intBitsToFloat(0xfe987d90)
    NAMED.put("Olive Oil", java.lang.Float.intBitsToFloat(0xfea17b9d))
    LIST += java.lang.Float.intBitsToFloat(0xfea17b9d)
    NAMED.put("Dun", java.lang.Float.intBitsToFloat(0xfe9c7cb1))
    LIST += java.lang.Float.intBitsToFloat(0xfe9c7cb1)
    NAMED.put("Corn Silk", java.lang.Float.intBitsToFloat(0xfe977dc3))
    LIST += java.lang.Float.intBitsToFloat(0xfe977dc3)
    NAMED.put("Tan", java.lang.Float.intBitsToFloat(0xfe937ed6))
    LIST += java.lang.Float.intBitsToFloat(0xfe937ed6)
    NAMED.put("Straw", java.lang.Float.intBitsToFloat(0xfe8f7ee8))
    LIST += java.lang.Float.intBitsToFloat(0xfe8f7ee8)
    NAMED.put("Honeydew", java.lang.Float.intBitsToFloat(0xfe9375d7))
    LIST += java.lang.Float.intBitsToFloat(0xfe9375d7)
    NAMED.put("Tarnish", java.lang.Float.intBitsToFloat(0xfe9475be))
    LIST += java.lang.Float.intBitsToFloat(0xfe9475be)
    NAMED.put("Pea Soup", java.lang.Float.intBitsToFloat(0xfea66caa))
    LIST += java.lang.Float.intBitsToFloat(0xfea66caa)
    NAMED.put("Marsh", java.lang.Float.intBitsToFloat(0xfe95748b))
    LIST += java.lang.Float.intBitsToFloat(0xfe95748b)
    NAMED.put("Asparagus", java.lang.Float.intBitsToFloat(0xfe977177))
    LIST += java.lang.Float.intBitsToFloat(0xfe977177)
    NAMED.put("Peat Bog", java.lang.Float.intBitsToFloat(0xfe8d7b55))
    LIST += java.lang.Float.intBitsToFloat(0xfe8d7b55)
    NAMED.put("Deep Jungle", java.lang.Float.intBitsToFloat(0xfe877d23))
    LIST += java.lang.Float.intBitsToFloat(0xfe877d23)
    NAMED.put("Pine Green", java.lang.Float.intBitsToFloat(0xfe867251))
    LIST += java.lang.Float.intBitsToFloat(0xfe867251)
    NAMED.put("Olive Green", java.lang.Float.intBitsToFloat(0xfe89755a))
    LIST += java.lang.Float.intBitsToFloat(0xfe89755a)
    NAMED.put("Gray Green", java.lang.Float.intBitsToFloat(0xfe86786a))
    LIST += java.lang.Float.intBitsToFloat(0xfe86786a)
    NAMED.put("Maidenhair Fern", java.lang.Float.intBitsToFloat(0xfe8c6e6f))
    LIST += java.lang.Float.intBitsToFloat(0xfe8c6e6f)
    NAMED.put("Kelly Green", java.lang.Float.intBitsToFloat(0xfe926d87))
    LIST += java.lang.Float.intBitsToFloat(0xfe926d87)
    NAMED.put("Dusty Green", java.lang.Float.intBitsToFloat(0xfe916da1))
    LIST += java.lang.Float.intBitsToFloat(0xfe916da1)
    NAMED.put("Garter Snake", java.lang.Float.intBitsToFloat(0xfe9065af))
    LIST += java.lang.Float.intBitsToFloat(0xfe9065af)
    NAMED.put("Silver Green", java.lang.Float.intBitsToFloat(0xfe916eba))
    LIST += java.lang.Float.intBitsToFloat(0xfe916eba)
    NAMED.put("Pistachio", java.lang.Float.intBitsToFloat(0xfe906eca))
    LIST += java.lang.Float.intBitsToFloat(0xfe906eca)
    NAMED.put("Angel Wing", java.lang.Float.intBitsToFloat(0xfe7c79f6))
    LIST += java.lang.Float.intBitsToFloat(0xfe7c79f6)
    NAMED.put("Sage Green", java.lang.Float.intBitsToFloat(0xfe886ee1))
    LIST += java.lang.Float.intBitsToFloat(0xfe886ee1)
    NAMED.put("Dried Sage", java.lang.Float.intBitsToFloat(0xfe866fd9))
    LIST += java.lang.Float.intBitsToFloat(0xfe866fd9)
    NAMED.put("Artichoke", java.lang.Float.intBitsToFloat(0xfe8a71ae))
    LIST += java.lang.Float.intBitsToFloat(0xfe8a71ae)
    NAMED.put("Viridian", java.lang.Float.intBitsToFloat(0xfe88717d))
    LIST += java.lang.Float.intBitsToFloat(0xfe88717d)
    NAMED.put("Floral Foam", java.lang.Float.intBitsToFloat(0xfe886a65))
    LIST += java.lang.Float.intBitsToFloat(0xfe886a65)
    NAMED.put("Hunter Green", java.lang.Float.intBitsToFloat(0xfe837a34))
    LIST += java.lang.Float.intBitsToFloat(0xfe837a34)
    NAMED.put("Dark Teal", java.lang.Float.intBitsToFloat(0xfe79774b))
    LIST += java.lang.Float.intBitsToFloat(0xfe79774b)
    NAMED.put("Kyanite", java.lang.Float.intBitsToFloat(0xfe797078))
    LIST += java.lang.Float.intBitsToFloat(0xfe797078)
    NAMED.put("Spearmint", java.lang.Float.intBitsToFloat(0xfe786dab))
    LIST += java.lang.Float.intBitsToFloat(0xfe786dab)
    NAMED.put("Amazonite", java.lang.Float.intBitsToFloat(0xfe7970c6))
    LIST += java.lang.Float.intBitsToFloat(0xfe7970c6)
    NAMED.put("Pastel Sky", java.lang.Float.intBitsToFloat(0xfe7970df))
    LIST += java.lang.Float.intBitsToFloat(0xfe7970df)
    NAMED.put("Aquamarine", java.lang.Float.intBitsToFloat(0xfe7b74ed))
    LIST += java.lang.Float.intBitsToFloat(0xfe7b74ed)
    NAMED.put("Dust Bunny", java.lang.Float.intBitsToFloat(0xfe717adb))
    LIST += java.lang.Float.intBitsToFloat(0xfe717adb)
    NAMED.put("Patina", java.lang.Float.intBitsToFloat(0xfe7078d0))
    LIST += java.lang.Float.intBitsToFloat(0xfe7078d0)
    NAMED.put("Chipped Granite", java.lang.Float.intBitsToFloat(0xfe6f7bc7))
    LIST += java.lang.Float.intBitsToFloat(0xfe6f7bc7)
    NAMED.put("Blue Smoke", java.lang.Float.intBitsToFloat(0xfe7078b7))
    LIST += java.lang.Float.intBitsToFloat(0xfe7078b7)
    NAMED.put("Air Force Blue", java.lang.Float.intBitsToFloat(0xfe6171a0))
    LIST += java.lang.Float.intBitsToFloat(0xfe6171a0)
    NAMED.put("Cold Iron", java.lang.Float.intBitsToFloat(0xfe6f7882))
    LIST += java.lang.Float.intBitsToFloat(0xfe6f7882)
    NAMED.put("Dreary Blue", java.lang.Float.intBitsToFloat(0xfe6f7767))
    LIST += java.lang.Float.intBitsToFloat(0xfe6f7767)
    NAMED.put("Murk", java.lang.Float.intBitsToFloat(0xfe737c26))
    LIST += java.lang.Float.intBitsToFloat(0xfe737c26)
    NAMED.put("Ninja", java.lang.Float.intBitsToFloat(0xfe717f32))
    LIST += java.lang.Float.intBitsToFloat(0xfe717f32)
    NAMED.put("Watercolor Black", java.lang.Float.intBitsToFloat(0xfe72804f))
    LIST += java.lang.Float.intBitsToFloat(0xfe72804f)
    NAMED.put("Iolite", java.lang.Float.intBitsToFloat(0xfe6c8061))
    LIST += java.lang.Float.intBitsToFloat(0xfe6c8061)
    NAMED.put("Boysenberry", java.lang.Float.intBitsToFloat(0xfe667f73))
    LIST += java.lang.Float.intBitsToFloat(0xfe667f73)
    NAMED.put("Watercolor Gray", java.lang.Float.intBitsToFloat(0xfe65818b))
    LIST += java.lang.Float.intBitsToFloat(0xfe65818b)
    NAMED.put("Blue Steel", java.lang.Float.intBitsToFloat(0xfe5b7f98))
    LIST += java.lang.Float.intBitsToFloat(0xfe5b7f98)
    NAMED.put("Twilight Cloud", java.lang.Float.intBitsToFloat(0xfe6780a8))
    LIST += java.lang.Float.intBitsToFloat(0xfe6780a8)
    NAMED.put("Smog", java.lang.Float.intBitsToFloat(0xfe6880c1))
    LIST += java.lang.Float.intBitsToFloat(0xfe6880c1)
    NAMED.put("Tropic Mist", java.lang.Float.intBitsToFloat(0xfe727de4))
    LIST += java.lang.Float.intBitsToFloat(0xfe727de4)
    NAMED.put("Feather Down", java.lang.Float.intBitsToFloat(0xfe7480ed))
    LIST += java.lang.Float.intBitsToFloat(0xfe7480ed)
    NAMED.put("Mild Violet", java.lang.Float.intBitsToFloat(0xfe6b89ad))
    LIST += java.lang.Float.intBitsToFloat(0xfe6b89ad)
    NAMED.put("Violet Cushions", java.lang.Float.intBitsToFloat(0xfe57918d))
    LIST += java.lang.Float.intBitsToFloat(0xfe57918d)
    NAMED.put("Dull Violet", java.lang.Float.intBitsToFloat(0xfe6a8978))
    LIST += java.lang.Float.intBitsToFloat(0xfe6a8978)
    NAMED.put("Royal Violet", java.lang.Float.intBitsToFloat(0xfe69895d))
    LIST += java.lang.Float.intBitsToFloat(0xfe69895d)
    NAMED.put("Eminence", java.lang.Float.intBitsToFloat(0xfe778a3b))
    LIST += java.lang.Float.intBitsToFloat(0xfe778a3b)
    NAMED.put("Prune", java.lang.Float.intBitsToFloat(0xfe798848))
    LIST += java.lang.Float.intBitsToFloat(0xfe798848)
    NAMED.put("Dusty Grape", java.lang.Float.intBitsToFloat(0xfe719366))
    LIST += java.lang.Float.intBitsToFloat(0xfe719366)
    NAMED.put("Pink Violet", java.lang.Float.intBitsToFloat(0xfe6f947f))
    LIST += java.lang.Float.intBitsToFloat(0xfe6f947f)
    NAMED.put("Ripe Plum", java.lang.Float.intBitsToFloat(0xfe689e8d))
    LIST += java.lang.Float.intBitsToFloat(0xfe689e8d)
    NAMED.put("Mauve", java.lang.Float.intBitsToFloat(0xfe6f9399))
    LIST += java.lang.Float.intBitsToFloat(0xfe6f9399)
    NAMED.put("Ham", java.lang.Float.intBitsToFloat(0xfe7295cd))
    LIST += java.lang.Float.intBitsToFloat(0xfe7295cd)
    NAMED.put("Cotton Candy", java.lang.Float.intBitsToFloat(0xfe7a8bec))
    LIST += java.lang.Float.intBitsToFloat(0xfe7a8bec)
    NAMED.put("Silver Pink", java.lang.Float.intBitsToFloat(0xfe7889d9))
    LIST += java.lang.Float.intBitsToFloat(0xfe7889d9)
    NAMED.put("Tea Rose", java.lang.Float.intBitsToFloat(0xfe7a8dce))
    LIST += java.lang.Float.intBitsToFloat(0xfe7a8dce)
    NAMED.put("Old Rose", java.lang.Float.intBitsToFloat(0xfe7b92bc))
    LIST += java.lang.Float.intBitsToFloat(0xfe7b92bc)
    NAMED.put("Dusty Pink", java.lang.Float.intBitsToFloat(0xfe7693b0))
    LIST += java.lang.Float.intBitsToFloat(0xfe7693b0)
    NAMED.put("Roseate Spoonbill", java.lang.Float.intBitsToFloat(0xfe7c9aa2))
    LIST += java.lang.Float.intBitsToFloat(0xfe7c9aa2)
    NAMED.put("Thulian Pink", java.lang.Float.intBitsToFloat(0xfe79a78e))
    LIST += java.lang.Float.intBitsToFloat(0xfe79a78e)
    NAMED.put("Brown Velvet", java.lang.Float.intBitsToFloat(0xfe7e8e41))
    LIST += java.lang.Float.intBitsToFloat(0xfe7e8e41)
    NAMED.put("Nightshade", java.lang.Float.intBitsToFloat(0xfe7e8c2b))
    LIST += java.lang.Float.intBitsToFloat(0xfe7e8c2b)
    NAMED.put("Scribe Ink", java.lang.Float.intBitsToFloat(0xfe7c8e21))
    LIST += java.lang.Float.intBitsToFloat(0xfe7c8e21)
    NAMED.put("Varnish", java.lang.Float.intBitsToFloat(0xfe8c902c))
    LIST += java.lang.Float.intBitsToFloat(0xfe8c902c)
    NAMED.put("Cedar Wood", java.lang.Float.intBitsToFloat(0xfe999c37))
    LIST += java.lang.Float.intBitsToFloat(0xfe999c37)
    NAMED.put("Hot Sauce", java.lang.Float.intBitsToFloat(0xfea6b452))
    LIST += java.lang.Float.intBitsToFloat(0xfea6b452)
    NAMED.put("Lurid Red", java.lang.Float.intBitsToFloat(0xfeafc16a))
    LIST += java.lang.Float.intBitsToFloat(0xfeafc16a)
    NAMED.put("Brick", java.lang.Float.intBitsToFloat(0xfe9caf81))
    LIST += java.lang.Float.intBitsToFloat(0xfe9caf81)
    NAMED.put("Bright Red", java.lang.Float.intBitsToFloat(0xfeb9c27e))
    LIST += java.lang.Float.intBitsToFloat(0xfeb9c27e)
    NAMED.put("Embers", java.lang.Float.intBitsToFloat(0xfeaeb589))
    LIST += java.lang.Float.intBitsToFloat(0xfeaeb589)
    NAMED.put("Salmon", java.lang.Float.intBitsToFloat(0xfe9cb898))
    LIST += java.lang.Float.intBitsToFloat(0xfe9cb898)
    NAMED.put("Taxicab Yellow", java.lang.Float.intBitsToFloat(0xfebf89b8))
    LIST += java.lang.Float.intBitsToFloat(0xfebf89b8)
    NAMED.put("Apricot", java.lang.Float.intBitsToFloat(0xfeb897af))
    LIST += java.lang.Float.intBitsToFloat(0xfeb897af)
    NAMED.put("Burnt Yellow", java.lang.Float.intBitsToFloat(0xfebd8b9c))
    LIST += java.lang.Float.intBitsToFloat(0xfebd8b9c)
    NAMED.put("Dry Pepper", java.lang.Float.intBitsToFloat(0xfeb7a085))
    LIST += java.lang.Float.intBitsToFloat(0xfeb7a085)
    NAMED.put("Redwood", java.lang.Float.intBitsToFloat(0xfeaf9b70))
    LIST += java.lang.Float.intBitsToFloat(0xfeaf9b70)
    NAMED.put("Koa", java.lang.Float.intBitsToFloat(0xfeaa9b63))
    LIST += java.lang.Float.intBitsToFloat(0xfeaa9b63)
    NAMED.put("Ochre", java.lang.Float.intBitsToFloat(0xfe968f44))
    LIST += java.lang.Float.intBitsToFloat(0xfe968f44)
    NAMED.put("Dull Green", java.lang.Float.intBitsToFloat(0xfe9e7c51))
    LIST += java.lang.Float.intBitsToFloat(0xfe9e7c51)
    NAMED.put("Army Green", java.lang.Float.intBitsToFloat(0xfea47960))
    LIST += java.lang.Float.intBitsToFloat(0xfea47960)
    NAMED.put("Driftwood", java.lang.Float.intBitsToFloat(0xfe928287))
    LIST += java.lang.Float.intBitsToFloat(0xfe928287)
    NAMED.put("Dry Brush", java.lang.Float.intBitsToFloat(0xfeb77f8e))
    LIST += java.lang.Float.intBitsToFloat(0xfeb77f8e)
    NAMED.put("Mush", java.lang.Float.intBitsToFloat(0xfebc75a0))
    LIST += java.lang.Float.intBitsToFloat(0xfebc75a0)
    NAMED.put("Banana Pudding", java.lang.Float.intBitsToFloat(0xfeb47ec7))
    LIST += java.lang.Float.intBitsToFloat(0xfeb47ec7)
    NAMED.put("Saffron", java.lang.Float.intBitsToFloat(0xfecb81c4))
    LIST += java.lang.Float.intBitsToFloat(0xfecb81c4)
    NAMED.put("Pencil Yellow", java.lang.Float.intBitsToFloat(0xfec17cd5))
    LIST += java.lang.Float.intBitsToFloat(0xfec17cd5)
    NAMED.put("Chartreuse", java.lang.Float.intBitsToFloat(0xfec365d6))
    LIST += java.lang.Float.intBitsToFloat(0xfec365d6)
    NAMED.put("Absinthe", java.lang.Float.intBitsToFloat(0xfeba5fc8))
    LIST += java.lang.Float.intBitsToFloat(0xfeba5fc8)
    NAMED.put("Infection", java.lang.Float.intBitsToFloat(0xfec061b6))
    LIST += java.lang.Float.intBitsToFloat(0xfec061b6)
    NAMED.put("Frog Green", java.lang.Float.intBitsToFloat(0xfebb5ea5))
    LIST += java.lang.Float.intBitsToFloat(0xfebb5ea5)
    NAMED.put("Avocado", java.lang.Float.intBitsToFloat(0xfeb3658f))
    LIST += java.lang.Float.intBitsToFloat(0xfeb3658f)
    NAMED.put("Woodlands", java.lang.Float.intBitsToFloat(0xfea06b63))
    LIST += java.lang.Float.intBitsToFloat(0xfea06b63)
    NAMED.put("Dark Pine", java.lang.Float.intBitsToFloat(0xfe937835))
    LIST += java.lang.Float.intBitsToFloat(0xfe937835)
    NAMED.put("Moss Green", java.lang.Float.intBitsToFloat(0xfe967042))
    LIST += java.lang.Float.intBitsToFloat(0xfe967042)
    NAMED.put("Fern Green", java.lang.Float.intBitsToFloat(0xfe9b6851))
    LIST += java.lang.Float.intBitsToFloat(0xfe9b6851)
    NAMED.put("Forest Glen", java.lang.Float.intBitsToFloat(0xfeab5b7b))
    LIST += java.lang.Float.intBitsToFloat(0xfeab5b7b)
    NAMED.put("Malachite", java.lang.Float.intBitsToFloat(0xfeba4ea8))
    LIST += java.lang.Float.intBitsToFloat(0xfeba4ea8)
    NAMED.put("Apple Green", java.lang.Float.intBitsToFloat(0xfebd4bb2))
    LIST += java.lang.Float.intBitsToFloat(0xfebd4bb2)
    NAMED.put("Celery", java.lang.Float.intBitsToFloat(0xfeab58d4))
    LIST += java.lang.Float.intBitsToFloat(0xfeab58d4)
    NAMED.put("Mint Green", java.lang.Float.intBitsToFloat(0xfeae52c3))
    LIST += java.lang.Float.intBitsToFloat(0xfeae52c3)
    NAMED.put("Emerald", java.lang.Float.intBitsToFloat(0xfeb4519c))
    LIST += java.lang.Float.intBitsToFloat(0xfeb4519c)
    NAMED.put("Prase", java.lang.Float.intBitsToFloat(0xfe9d5998))
    LIST += java.lang.Float.intBitsToFloat(0xfe9d5998)
    NAMED.put("Eucalyptus", java.lang.Float.intBitsToFloat(0xfe91637e))
    LIST += java.lang.Float.intBitsToFloat(0xfe91637e)
    NAMED.put("Zucchini", java.lang.Float.intBitsToFloat(0xfe7e753e))
    LIST += java.lang.Float.intBitsToFloat(0xfe7e753e)
    NAMED.put("Soft Teal", java.lang.Float.intBitsToFloat(0xfe7f6390))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f6390)
    NAMED.put("Medium Teal", java.lang.Float.intBitsToFloat(0xfe875baf))
    LIST += java.lang.Float.intBitsToFloat(0xfe875baf)
    NAMED.put("Spring Green", java.lang.Float.intBitsToFloat(0xfea052b8))
    LIST += java.lang.Float.intBitsToFloat(0xfea052b8)
    NAMED.put("Turquoise", java.lang.Float.intBitsToFloat(0xfe8c56cc))
    LIST += java.lang.Float.intBitsToFloat(0xfe8c56cc)
    NAMED.put("Seafoam", java.lang.Float.intBitsToFloat(0xfe9453d8))
    LIST += java.lang.Float.intBitsToFloat(0xfe9453d8)
    NAMED.put("Variscite", java.lang.Float.intBitsToFloat(0xfe865be3))
    LIST += java.lang.Float.intBitsToFloat(0xfe865be3)
    NAMED.put("Refreshing Mist", java.lang.Float.intBitsToFloat(0xfe6e69e6))
    LIST += java.lang.Float.intBitsToFloat(0xfe6e69e6)
    NAMED.put("Shining Sky", java.lang.Float.intBitsToFloat(0xfe685fdd))
    LIST += java.lang.Float.intBitsToFloat(0xfe685fdd)
    NAMED.put("Steam", java.lang.Float.intBitsToFloat(0xfe6c69d5))
    LIST += java.lang.Float.intBitsToFloat(0xfe6c69d5)
    NAMED.put("Robin Egg Blue", java.lang.Float.intBitsToFloat(0xfe7459cd))
    LIST += java.lang.Float.intBitsToFloat(0xfe7459cd)
    NAMED.put("Denim Blue", java.lang.Float.intBitsToFloat(0xfe5864a8))
    LIST += java.lang.Float.intBitsToFloat(0xfe5864a8)
    NAMED.put("Deep Teal", java.lang.Float.intBitsToFloat(0xfe776e5f))
    LIST += java.lang.Float.intBitsToFloat(0xfe776e5f)
    NAMED.put("Navy Blue", java.lang.Float.intBitsToFloat(0xfe6a783f))
    LIST += java.lang.Float.intBitsToFloat(0xfe6a783f)
    NAMED.put("Blueberry", java.lang.Float.intBitsToFloat(0xfe5b7353))
    LIST += java.lang.Float.intBitsToFloat(0xfe5b7353)
    NAMED.put("Prussian Blue", java.lang.Float.intBitsToFloat(0xfe556f67))
    LIST += java.lang.Float.intBitsToFloat(0xfe556f67)
    NAMED.put("Desert Rain", java.lang.Float.intBitsToFloat(0xfe637277))
    LIST += java.lang.Float.intBitsToFloat(0xfe637277)
    NAMED.put("Electric Blue", java.lang.Float.intBitsToFloat(0xfe346886))
    LIST += java.lang.Float.intBitsToFloat(0xfe346886)
    NAMED.put("Hidden Blue", java.lang.Float.intBitsToFloat(0xfe536c83))
    LIST += java.lang.Float.intBitsToFloat(0xfe536c83)
    NAMED.put("Dull Azure", java.lang.Float.intBitsToFloat(0xfe4c6b94))
    LIST += java.lang.Float.intBitsToFloat(0xfe4c6b94)
    NAMED.put("Ripped Denim", java.lang.Float.intBitsToFloat(0xfe6972a9))
    LIST += java.lang.Float.intBitsToFloat(0xfe6972a9)
    NAMED.put("Calm Sky", java.lang.Float.intBitsToFloat(0xfe5069b8))
    LIST += java.lang.Float.intBitsToFloat(0xfe5069b8)
    NAMED.put("Vapor", java.lang.Float.intBitsToFloat(0xfe5b77c6))
    LIST += java.lang.Float.intBitsToFloat(0xfe5b77c6)
    NAMED.put("Powder Blue", java.lang.Float.intBitsToFloat(0xfe5d66cb))
    LIST += java.lang.Float.intBitsToFloat(0xfe5d66cb)
    NAMED.put("Suds", java.lang.Float.intBitsToFloat(0xfe6582d1))
    LIST += java.lang.Float.intBitsToFloat(0xfe6582d1)
    NAMED.put("Strong Cyan", java.lang.Float.intBitsToFloat(0xfe575fc4))
    LIST += java.lang.Float.intBitsToFloat(0xfe575fc4)
    NAMED.put("Sharp Azure", java.lang.Float.intBitsToFloat(0xfe4066a0))
    LIST += java.lang.Float.intBitsToFloat(0xfe4066a0)
    NAMED.put("Blue Eye", java.lang.Float.intBitsToFloat(0xfe597295))
    LIST += java.lang.Float.intBitsToFloat(0xfe597295)
    NAMED.put("Subtlety", java.lang.Float.intBitsToFloat(0xfe49809e))
    LIST += java.lang.Float.intBitsToFloat(0xfe49809e)
    NAMED.put("Rough Sapphire", java.lang.Float.intBitsToFloat(0xfe377392))
    LIST += java.lang.Float.intBitsToFloat(0xfe377392)
    NAMED.put("Iris", java.lang.Float.intBitsToFloat(0xfe377f88))
    LIST += java.lang.Float.intBitsToFloat(0xfe377f88)
    NAMED.put("Cornflower Blue", java.lang.Float.intBitsToFloat(0xfe317280))
    LIST += java.lang.Float.intBitsToFloat(0xfe317280)
    NAMED.put("Polished Sapphire", java.lang.Float.intBitsToFloat(0xfe2f6867))
    LIST += java.lang.Float.intBitsToFloat(0xfe2f6867)
    NAMED.put("Royal Blue", java.lang.Float.intBitsToFloat(0xfe376959))
    LIST += java.lang.Float.intBitsToFloat(0xfe376959)
    NAMED.put("Indigo", java.lang.Float.intBitsToFloat(0xfe48764c))
    LIST += java.lang.Float.intBitsToFloat(0xfe48764c)
    NAMED.put("Space Blue", java.lang.Float.intBitsToFloat(0xfe697834))
    LIST += java.lang.Float.intBitsToFloat(0xfe697834)
    NAMED.put("Thick Amethyst", java.lang.Float.intBitsToFloat(0xfe458760))
    LIST += java.lang.Float.intBitsToFloat(0xfe458760)
    NAMED.put("Juicy Grape", java.lang.Float.intBitsToFloat(0xfe3c896f))
    LIST += java.lang.Float.intBitsToFloat(0xfe3c896f)
    NAMED.put("Blacklight Glow", java.lang.Float.intBitsToFloat(0xfe489681))
    LIST += java.lang.Float.intBitsToFloat(0xfe489681)
    NAMED.put("Purple Freesia", java.lang.Float.intBitsToFloat(0xfe3e9698))
    LIST += java.lang.Float.intBitsToFloat(0xfe3e9698)
    NAMED.put("Thin Amethyst", java.lang.Float.intBitsToFloat(0xfe309085))
    LIST += java.lang.Float.intBitsToFloat(0xfe309085)
    NAMED.put("Orchid", java.lang.Float.intBitsToFloat(0xfe4b9bab))
    LIST += java.lang.Float.intBitsToFloat(0xfe4b9bab)
    NAMED.put("Lavender", java.lang.Float.intBitsToFloat(0xfe578cbe))
    LIST += java.lang.Float.intBitsToFloat(0xfe578cbe)
    NAMED.put("Lilac", java.lang.Float.intBitsToFloat(0xfe6190cd))
    LIST += java.lang.Float.intBitsToFloat(0xfe6190cd)
    NAMED.put("Soap", java.lang.Float.intBitsToFloat(0xfe6b87da))
    LIST += java.lang.Float.intBitsToFloat(0xfe6b87da)
    NAMED.put("Pink Tutu", java.lang.Float.intBitsToFloat(0xfe7090e2))
    LIST += java.lang.Float.intBitsToFloat(0xfe7090e2)
    NAMED.put("Thistle", java.lang.Float.intBitsToFloat(0xfe56a6bb))
    LIST += java.lang.Float.intBitsToFloat(0xfe56a6bb)
    NAMED.put("Heliotrope", java.lang.Float.intBitsToFloat(0xfe55bab7))
    LIST += java.lang.Float.intBitsToFloat(0xfe55bab7)
    NAMED.put("Purple", java.lang.Float.intBitsToFloat(0xfe53bc99))
    LIST += java.lang.Float.intBitsToFloat(0xfe53bc99)
    NAMED.put("Wisteria", java.lang.Float.intBitsToFloat(0xfe41a99b))
    LIST += java.lang.Float.intBitsToFloat(0xfe41a99b)
    NAMED.put("Medium Plum", java.lang.Float.intBitsToFloat(0xfe56b687))
    LIST += java.lang.Float.intBitsToFloat(0xfe56b687)
    NAMED.put("Violet", java.lang.Float.intBitsToFloat(0xfe4da176))
    LIST += java.lang.Float.intBitsToFloat(0xfe4da176)
    NAMED.put("Grape Lollipop", java.lang.Float.intBitsToFloat(0xfe5e9453))
    LIST += java.lang.Float.intBitsToFloat(0xfe5e9453)
    NAMED.put("Mulberry", java.lang.Float.intBitsToFloat(0xfe6b9d4e))
    LIST += java.lang.Float.intBitsToFloat(0xfe6b9d4e)
    NAMED.put("Grape Soda", java.lang.Float.intBitsToFloat(0xfe618f3f))
    LIST += java.lang.Float.intBitsToFloat(0xfe618f3f)
    NAMED.put("Eggplant", java.lang.Float.intBitsToFloat(0xfe6a8c32))
    LIST += java.lang.Float.intBitsToFloat(0xfe6a8c32)
    NAMED.put("Cherry Syrup", java.lang.Float.intBitsToFloat(0xfe7d993e))
    LIST += java.lang.Float.intBitsToFloat(0xfe7d993e)
    NAMED.put("Plum Juice", java.lang.Float.intBitsToFloat(0xfe6db16c))
    LIST += java.lang.Float.intBitsToFloat(0xfe6db16c)
    NAMED.put("Fruit Punch", java.lang.Float.intBitsToFloat(0xfe7ac375))
    LIST += java.lang.Float.intBitsToFloat(0xfe7ac375)
    NAMED.put("Bubble Gum", java.lang.Float.intBitsToFloat(0xfe70c0a7))
    LIST += java.lang.Float.intBitsToFloat(0xfe70c0a7)
    NAMED.put("Pink Lemonade", java.lang.Float.intBitsToFloat(0xfe72b6b1))
    LIST += java.lang.Float.intBitsToFloat(0xfe72b6b1)
    NAMED.put("Shrimp", java.lang.Float.intBitsToFloat(0xfe829ec3))
    LIST += java.lang.Float.intBitsToFloat(0xfe829ec3)
    NAMED.put("Flamingo", java.lang.Float.intBitsToFloat(0xfe82c894))
    LIST += java.lang.Float.intBitsToFloat(0xfe82c894)
    NAMED.put("Rose", java.lang.Float.intBitsToFloat(0xfe83c982))
    LIST += java.lang.Float.intBitsToFloat(0xfe83c982)
    NAMED.put("Carmine", java.lang.Float.intBitsToFloat(0xfe96bf63))
    LIST += java.lang.Float.intBitsToFloat(0xfe96bf63)
    NAMED.put("Bologna", java.lang.Float.intBitsToFloat(0xfe88a763))
    LIST += java.lang.Float.intBitsToFloat(0xfe88a763)
    NAMED.put("Raspberry", java.lang.Float.intBitsToFloat(0xfe8db153))
    LIST += java.lang.Float.intBitsToFloat(0xfe8db153)
  }

  /** Converts existing Color entries in [[sge.graphics.Colors]] from RGBA to IPT_HQ format. */
  def editKnownColors(): Unit =
    for (c <- sge.graphics.Colors.colors.values) {
      val f = ColorTools.fromColor(c)
      c.set(ColorTools.intensity(f), ColorTools.protan(f), ColorTools.tritan(f), c.a)
    }

  /** Appends IPT_HQ-compatible Color instances to the map in [[sge.graphics.Colors]]. */
  def appendToKnownColors(): Unit =
    for ((key, value) <- NAMED) {
      val f = value
      sge.graphics.Colors.put(key, new sge.graphics.Color(ColorTools.intensity(f), ColorTools.protan(f), ColorTools.tritan(f), ColorTools.alpha(f)))
    }
}
