/*
 * Ported from libGDX gdx-ai - https://github.com/libgdx/gdx-ai
 * Original source: com/badlogic/gdx/ai/btree/utils/BehaviorTreeReader.java
 * Original authors: davebaol
 * Licensed under the Apache License, Version 2.0
 *
 * The original Java source is generated by Ragel from BehaviorTreeReader.rl.
 * This Scala port preserves the Ragel state machine tables and logic exactly.
 *
 * Migration notes:
 *   Renames: `com.badlogic.gdx.ai.btree.utils` -> `sge.ai.btree.utils`
 *   Convention: split packages, Nullable instead of null, boundary/break instead of labeled break/continue
 *   Idiom: static arrays -> companion object vals; GdxRuntimeException -> SgeError.InvalidInput;
 *     SerializationException -> SgeError.SerializationError; GdxAI.getLogger() -> debug flag println
 *   Idiom: Java labeled `break outer` -> `scala.util.boundary`/`break`
 *   Idiom: Java `do { ... } while(false)` -> `boundary { ... }` block
 *
 * Scala port copyright 2025-2026 Mateusz Kubuszok
 *
 * Covenant: full-port
 * Covenant-baseline-spec-pass: 0
 * Covenant-baseline-loc: 535
 * Covenant-baseline-methods: BehaviorTreeReader,attrName,attribute,btreeActions,btreeEofActions,btreeIndexOffsets,btreeIndicies,btreeKeyOffsets,btreeRangeLengths,btreeSingleLengths,btreeStart,btreeTransActions,btreeTransKeys,btreeTransTargs,buffer,comment,containsFloatingPointCharacters,cs,data,debug,endLine,endStatement,eof,executeAction,i,indent,isGuard,isSubtreeRef,length,lineNumber,needsUnescape,p,parse,parseRuntimeEx,pe,processEndLine,processValue,s,startLine,startStatement,statementName,stringIsUnquoted,taskIndex,taskProcessed,unescape
 * Covenant-source-reference: auto
 * Covenant-verified: 2026-04-19
 */
package sge
package ai
package btree
package utils

import java.io.IOException
import java.io.InputStream
import java.io.InputStreamReader
import java.io.Reader

import scala.util.boundary
import scala.util.boundary.break

import sge.files.FileHandle
import sge.utils.Nullable
import sge.utils.SgeError
import sge.utils.StreamUtils

/** An abstract event driven [[BehaviorTree]] parser.
  *
  * @author
  *   davebaol (original implementation)
  */
abstract class BehaviorTreeReader(val reportsComments: Boolean = false) {

  protected var debug:      Boolean = false
  protected var lineNumber: Int     = 0

  protected def startLine(indent: Int): Unit

  protected def startStatement(name: String, isSubtreeReference: Boolean, isGuard: Boolean): Unit

  protected def attribute(name: String, value: Any): Unit

  protected def endStatement(): Unit

  protected def endLine(): Unit

  protected def comment(text: String): Unit = {}

  /** Parses the given string.
    * @param string
    *   the string
    * @throws SgeError.SerializationError
    *   if the string cannot be successfully parsed.
    */
  def parse(string: String): Unit = {
    val data = string.toCharArray
    parse(data, 0, data.length)
  }

  /** Parses the given reader.
    * @param reader
    *   the reader
    * @throws SgeError.SerializationError
    *   if the reader cannot be successfully parsed.
    */
  def parse(reader: Reader): Unit =
    try {
      var data   = new Array[Char](1024)
      var offset = 0
      var done   = false
      while (!done) {
        val length = reader.read(data, offset, data.length - offset)
        if (length == -1) {
          done = true
        } else if (length == 0) {
          val newData = new Array[Char](data.length * 2)
          System.arraycopy(data, 0, newData, 0, data.length)
          data = newData
        } else {
          offset += length
        }
      }
      parse(data, 0, offset)
    } catch {
      case ex: IOException =>
        throw SgeError.SerializationError(ex.getMessage, Some(ex))
    } finally
      StreamUtils.closeQuietly(reader)

  /** Parses the given input stream.
    * @param input
    *   the input stream
    * @throws SgeError.SerializationError
    *   if the input stream cannot be successfully parsed.
    */
  def parse(input: InputStream): Unit =
    try
      parse(new InputStreamReader(input, "UTF-8"))
    catch {
      case ex: IOException =>
        throw SgeError.SerializationError(ex.getMessage, Some(ex))
    } finally
      StreamUtils.closeQuietly(input)

  /** Parses the given file.
    * @param file
    *   the file
    * @throws SgeError.SerializationError
    *   if the file cannot be successfully parsed.
    */
  def parse(file: FileHandle): Unit =
    try
      parse(file.reader("UTF-8"))
    catch {
      case ex: Exception =>
        throw SgeError.SerializationError("Error parsing file: " + file, Some(ex))
    }

  /** Parses the given data buffer from the offset up to the specified number of characters.
    * @param data
    *   the buffer
    * @param offset
    *   the initial index
    * @param length
    *   the specified number of characters to parse.
    * @throws SgeError.SerializationError
    *   if the buffer cannot be successfully parsed.
    */
  def parse(data: Array[Char], offset: Int, length: Int): Unit = {
    import BehaviorTreeReader.*

    var p   = offset
    val pe  = length
    val eof = pe

    var s            = 0
    var indent       = 0
    var taskIndex    = -1
    var isGuard      = false
    var isSubtreeRef = false
    var statementName: Nullable[String] = Nullable.empty
    var taskProcessed    = false
    var needsUnescape    = false
    var stringIsUnquoted = false
    var parseRuntimeEx: Nullable[RuntimeException] = Nullable.empty
    var attrName:       String                     = ""

    lineNumber = 1

    var cs: Int = btreeStart

    /** Shared logic for processing a parsed value (actions 0). Extracted into a local method since it is used both in the main action loop and the EOF action loop.
      */
    def processValue(): Unit = {
      var value = new String(data, s, p - s)
      s = p
      if (needsUnescape) value = unescape(value)
      boundary {
        if (stringIsUnquoted) {
          if (value == "true") {
            attribute(attrName, java.lang.Boolean.TRUE)
            break()
          } else if (value == "false") {
            attribute(attrName, java.lang.Boolean.FALSE)
            break()
          } else if (value == "null") {
            attribute(attrName, null) // @nowarn — null required for parser protocol (attribute value can be null)
            break()
          } else { // number
            try
              if (containsFloatingPointCharacters(value)) {
                attribute(attrName, java.lang.Double.valueOf(value))
                break()
              } else {
                attribute(attrName, java.lang.Long.valueOf(value))
                break()
              }
            catch {
              case _: NumberFormatException =>
                throw SgeError.InvalidInput("Attribute value must be a number, a boolean, a string or null")
            }
          }
        } else {
          attribute(attrName, value)
        }
      }
      stringIsUnquoted = false
    }

    /** Process end-of-line (action 5). Shared between main and EOF action processing. */
    def processEndLine(): Unit = {
      if (taskIndex >= 0) {
        endStatement() // Close the last task of the line
      }
      taskProcessed = true
      statementName.foreach(_ => endLine())
    }

    /** Process action by index. Returns true if we need to process value (action 0). */
    def executeAction(action: Int): Unit =
      action match {
        case 0 => // processValue
          processValue()
        case 1 => // unquotedChars
          s = p
          needsUnescape = false
          stringIsUnquoted = true
          boundary {
            while (true) {
              data(p) match {
                case '\\' =>
                  needsUnescape = true
                case ')' | '(' | ' ' | '\r' | '\n' | '\t' =>
                  break()
                case _ => // continue
              }
              p += 1
              if (p == eof) break()
            }
          }
          p -= 1
        case 2 => // quotedChars
          p += 1
          s = p
          needsUnescape = false
          boundary {
            while (true) {
              data(p) match {
                case '\\' =>
                  needsUnescape = true
                  p += 1
                case '"' =>
                  break()
                case _ => // continue
              }
              p += 1
              if (p == eof) break()
            }
          }
          p -= 1
        case 3 => // newline
          indent = 0
          taskIndex = -1
          isGuard = false
          isSubtreeRef = false
          statementName = Nullable.empty
          taskProcessed = false
          lineNumber += 1
        case 4 => // indent
          indent += 1
        case 5 => // endLine
          processEndLine()
        case 6 => // mark start
          s = p
        case 7 => // comment
          if (reportsComments) {
            comment(new String(data, s, p - s))
          }
        case 8 => // task name
          if (taskIndex < 0) {
            taskIndex = 0
            startLine(indent) // First task/guard of the line
          } else {
            taskIndex += 1
            endStatement() // Close previous task/guard in line
          }
          statementName = Nullable(new String(data, s, p - s))
          startStatement(statementName.get, isSubtreeRef, isGuard) // Start this task/guard
          isGuard = false
        case 9 => // attr name
          attrName = new String(data, s, p - s)
        case 10 => // isSubtreeRef = false
          isSubtreeRef = false
        case 11 => // isSubtreeRef = true
          isSubtreeRef = true
        case 12 => // isGuard = true
          isGuard = true
        case 13 => // isGuard = false
          isGuard = false
        case _ => // unknown action, ignore
      }

    try {
      var _gotoTarg = 0
      var running   = true

      while (running) {
        _gotoTarg match {
          case 0 =>
            if (p == pe) {
              _gotoTarg = 4
            } else if (cs == 0) {
              _gotoTarg = 5
            } else {
              _gotoTarg = 1
            }

          case 1 =>
            // _match block — find transition
            // All local vars are Int to avoid Short arithmetic issues.
            // This mirrors the Java `_match: do { ... } while(false)` pattern.
            val _transIdx: Int = boundary {
              var _keys:  Int = btreeKeyOffsets(cs).toInt
              var _trans: Int = btreeIndexOffsets(cs).toInt
              var _klen:  Int = btreeSingleLengths(cs).toInt

              if (_klen > 0) {
                var _lower  = _keys
                var _upper  = _keys + _klen - 1
                var matched = false
                while (!matched && _upper >= _lower) {
                  val _mid = _lower + ((_upper - _lower) >> 1)
                  if (data(p) < btreeTransKeys(_mid)) {
                    _upper = _mid - 1
                  } else if (data(p) > btreeTransKeys(_mid)) {
                    _lower = _mid + 1
                  } else {
                    _trans += (_mid - _keys)
                    matched = true
                  }
                }
                _keys += _klen
                _trans += (if (matched) 0 else _klen)
                if (matched) break(_trans)
              }

              _klen = btreeRangeLengths(cs).toInt
              if (_klen > 0) {
                var _lower = _keys
                var _upper = _keys + (_klen << 1) - 2
                while (_upper >= _lower) {
                  val _mid = _lower + (((_upper - _lower) >> 1) & ~1)
                  if (data(p) < btreeTransKeys(_mid)) {
                    _upper = _mid - 2
                  } else if (data(p) > btreeTransKeys(_mid + 1)) {
                    _lower = _mid + 2
                  } else {
                    _trans += ((_mid - _keys) >> 1)
                    break(_trans)
                  }
                }
                _trans += _klen
              }
              _trans
            }

            val _realTrans = btreeIndicies(_transIdx)
            cs = btreeTransTargs(_realTrans)

            if (btreeTransActions(_realTrans) != 0) {
              var _acts  = btreeTransActions(_realTrans).toInt
              var _nacts = btreeActions(_acts).toInt
              _acts += 1
              while (_nacts > 0) {
                executeAction(btreeActions(_acts).toInt)
                _acts += 1
                _nacts -= 1
              }
            }
            _gotoTarg = 2

          case 2 =>
            if (cs == 0) {
              _gotoTarg = 5
            } else {
              p += 1
              if (p != pe) {
                _gotoTarg = 1
              } else {
                _gotoTarg = 4
              }
            }

          case 4 =>
            if (p == eof) {
              var __acts  = btreeEofActions(cs).toInt
              var __nacts = btreeActions(__acts).toInt
              __acts += 1
              while (__nacts > 0) {
                executeAction(btreeActions(__acts).toInt)
                __acts += 1
                __nacts -= 1
              }
            }
            _gotoTarg = 5

          case 5 =>
            running = false

          case _ =>
            running = false
        }
      }

    } catch {
      case ex: RuntimeException =>
        parseRuntimeEx = Nullable(ex)
    }

    if (p < pe || (!statementName.isEmpty && !taskProcessed)) {
      throw SgeError.SerializationError(
        "Error parsing behavior tree on line " + lineNumber + " near: " + new String(data, p, pe - p),
        parseRuntimeEx.fold(Option.empty[Throwable])(ex => Some(ex))
      )
    } else {
      parseRuntimeEx.foreach { ex =>
        throw SgeError.SerializationError(
          "Error parsing behavior tree: " + new String(data),
          Some(ex)
        )
      }
    }
  }
}

object BehaviorTreeReader {

  private def containsFloatingPointCharacters(value: String): Boolean =
    boundary {
      var i = 0
      val n = value.length
      while (i < n) {
        value.charAt(i) match {
          case '.' | 'E' | 'e' => break(true)
          case _               =>
        }
        i += 1
      }
      false
    }

  private[utils] def unescape(value: String): String = {
    val length = value.length
    val buffer = new StringBuilder(length + 16)
    var i      = 0
    while (i < length) {
      var c = value.charAt(i)
      i += 1
      if (c != '\\') {
        buffer.append(c)
      } else if (i < length) {
        c = value.charAt(i)
        i += 1
        if (c == 'u') {
          buffer.appendAll(Character.toChars(Integer.parseInt(value.substring(i, i + 4), 16)))
          i += 4
        } else {
          c match {
            case '"' | '\\' | '/' => // keep c as-is
            case 'b'              => c = '\b'
            case 'f'              => c = '\f'
            case 'n'              => c = '\n'
            case 'r'              => c = '\r'
            case 't'              => c = '\t'
            case _                =>
              throw SgeError.SerializationError("Illegal escaped character: \\" + c)
          }
          buffer.append(c)
        }
      }
    }
    buffer.toString()
  }

  // ── Ragel state machine tables ──────────────────────────────────────
  // These arrays are copied exactly from the Ragel-generated Java source.
  // Any modification will break the parser.

  private val btreeActions: Array[Byte] = Array[Byte](
    0, 1, 0, 1, 1, 1, 2, 1, 3, 1, 4, 1, 5, 1, 6, 1, 9, 1, 12, 1, 13, 2, 0, 5, 2, 0, 13, 2, 5, 3, 2, 7, 5, 2, 10, 8, 2, 11, 8, 3, 0, 5, 3, 3, 6, 7, 5, 3, 7, 5, 3, 3, 10, 8, 5, 3, 10, 8, 13, 3, 11, 8,
    5, 3, 11, 8, 13, 4, 6, 7, 5, 3, 4, 10, 8, 5, 3, 4, 11, 8, 5, 3
  )

  private val btreeKeyOffsets: Array[Short] = Array[Short](
    0, 0, 1, 6, 16, 21, 33, 37, 47, 59, 63, 72, 73, 77, 82, 87, 91, 105, 114, 126, 130, 139, 143, 144, 148, 152, 157, 170, 174, 179, 191, 196, 198, 200, 213, 218, 233, 243, 248, 253, 267
  )

  private val btreeTransKeys: Array[Char] = Array[Char](
    10, 95, 65, 90, 97, 122, 9, 13, 32, 36, 41, 95, 65, 90, 97, 122, 95, 65, 90, 97, 122, 9, 13, 32, 41, 63, 95, 48, 57, 65, 90, 97, 122, 9, 13, 32, 41, 9, 13, 32, 36, 40, 95, 65, 90, 97, 122, 9, 13,
    32, 58, 63, 95, 48, 57, 65, 90, 97, 122, 9, 13, 32, 58, 9, 10, 13, 32, 34, 35, 58, 40, 41, 34, 9, 13, 32, 58, 95, 65, 90, 97, 122, 95, 65, 90, 97, 122, 9, 13, 32, 41, 9, 13, 32, 36, 41, 46, 63,
    95, 48, 57, 65, 90, 97, 122, 9, 13, 32, 41, 95, 65, 90, 97, 122, 9, 13, 32, 58, 63, 95, 48, 57, 65, 90, 97, 122, 9, 13, 32, 58, 9, 10, 13, 32, 34, 35, 58, 40, 41, 9, 13, 32, 41, 34, 9, 13, 32, 41,
    9, 13, 32, 58, 95, 65, 90, 97, 122, 9, 13, 32, 36, 41, 63, 95, 48, 57, 65, 90, 97, 122, 9, 13, 32, 41, 95, 65, 90, 97, 122, 9, 10, 13, 32, 35, 36, 40, 95, 65, 90, 97, 122, 9, 10, 13, 32, 35, 10,
    13, 10, 13, 9, 10, 13, 32, 35, 63, 95, 48, 57, 65, 90, 97, 122, 9, 10, 13, 32, 35, 9, 10, 13, 32, 35, 36, 46, 63, 95, 48, 57, 65, 90, 97, 122, 9, 10, 13, 32, 35, 95, 65, 90, 97, 122, 9, 10, 13,
    32, 35, 9, 10, 13, 32, 35, 9, 10, 13, 32, 35, 36, 63, 95, 48, 57, 65, 90, 97, 122, 9, 10, 13, 32, 35, 0
  )

  private val btreeSingleLengths: Array[Byte] = Array[Byte](
    0, 1, 1, 6, 1, 6, 4, 6, 6, 4, 7, 1, 4, 1, 1, 4, 8, 5, 6, 4, 7, 4, 1, 4, 4, 1, 7, 4, 1, 8, 5, 2, 2, 7, 5, 9, 6, 5, 5, 8, 5
  )

  private val btreeRangeLengths: Array[Byte] = Array[Byte](
    0, 0, 2, 2, 2, 3, 0, 2, 3, 0, 1, 0, 0, 2, 2, 0, 3, 2, 3, 0, 1, 0, 0, 0, 0, 2, 3, 0, 2, 2, 0, 0, 0, 3, 0, 3, 2, 0, 0, 3, 0
  )

  private val btreeIndexOffsets: Array[Short] = Array[Short](
    0, 0, 2, 6, 15, 19, 29, 34, 43, 53, 58, 67, 69, 74, 78, 82, 87, 99, 107, 117, 122, 131, 136, 138, 143, 148, 152, 163, 168, 172, 183, 189, 192, 195, 206, 212, 225, 234, 240, 246, 258
  )

  private val btreeIndicies: Array[Byte] = Array[Byte](
    0, 1, 2, 2, 2, 1, 3, 3, 3, 4, 5, 6, 6, 6, 1, 7, 7, 7, 1, 8, 8, 8, 9, 11, 10, 10, 10, 10, 1, 12, 12, 12, 5, 1, 13, 13, 13, 14, 15, 16, 16, 16, 1, 17, 17, 17, 19, 20, 18, 18, 18, 18, 1, 21, 21, 21,
    22, 1, 22, 1, 22, 22, 24, 1, 1, 1, 23, 25, 1, 17, 17, 17, 19, 1, 26, 26, 26, 1, 27, 27, 27, 1, 8, 8, 8, 9, 1, 28, 28, 28, 29, 30, 31, 33, 32, 32, 32, 32, 1, 34, 34, 34, 5, 35, 35, 35, 1, 36, 36,
    36, 38, 39, 37, 37, 37, 37, 1, 40, 40, 40, 41, 1, 41, 1, 41, 41, 43, 1, 1, 1, 42, 44, 44, 44, 45, 1, 46, 1, 34, 34, 34, 5, 1, 36, 36, 36, 38, 1, 47, 47, 47, 1, 28, 28, 28, 29, 30, 33, 47, 47, 47,
    47, 1, 28, 28, 28, 30, 1, 32, 32, 32, 1, 48, 49, 50, 48, 51, 14, 15, 16, 16, 16, 1, 50, 49, 50, 50, 51, 1, 53, 54, 52, 56, 57, 55, 58, 59, 58, 58, 60, 62, 61, 61, 61, 61, 1, 58, 59, 58, 58, 60, 1,
    63, 64, 63, 63, 65, 66, 67, 68, 27, 27, 27, 27, 1, 69, 49, 69, 69, 51, 70, 70, 70, 1, 71, 72, 71, 71, 73, 1, 69, 49, 69, 69, 51, 1, 63, 64, 63, 63, 65, 66, 68, 26, 26, 26, 26, 1, 63, 64, 63, 63,
    65, 1, 0
  )

  private val btreeTransTargs: Array[Byte] = Array[Byte](
    29, 0, 33, 3, 4, 7, 16, 5, 6, 7, 5, 15, 6, 7, 2, 3, 35, 9, 8, 10, 12, 9, 10, 37, 11, 38, 39, 35, 17, 25, 7, 28, 16, 27, 17, 18, 19, 18, 20, 24, 19, 20, 21, 22, 17, 7, 23, 26, 29, 29, 30, 31, 32,
    29, 1, 32, 29, 1, 30, 29, 31, 33, 34, 36, 29, 31, 13, 14, 40, 36, 8, 36, 29, 31
  )

  private val btreeTransActions: Array[Byte] = Array[Byte](
    7, 0, 13, 0, 0, 19, 13, 13, 36, 63, 0, 0, 0, 0, 0, 17, 13, 15, 0, 15, 0, 0, 0, 3, 5, 1, 0, 0, 33, 0, 55, 0, 0, 0, 0, 13, 15, 0, 15, 0, 0, 0, 3, 5, 1, 24, 1, 0, 9, 27, 0, 0, 13, 67, 43, 0, 47, 30,
    36, 77, 36, 0, 0, 33, 72, 33, 0, 0, 0, 0, 13, 1, 39, 1
  )

  private val btreeEofActions: Array[Byte] = Array[Byte](
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 11, 43, 30, 59, 59, 51, 11, 21, 11, 51, 51
  )

  private val btreeStart: Int = 29
  // btree_first_final = 29, btree_error = 0, btree_en_main = 29 — kept as comments for reference
}
