/*
 * Ported from colorful-gdx - https://github.com/tommyettinger/colorful-gdx
 * Original authors: Tommy Ettinger
 * Licensed under the Apache License, Version 2.0
 *
 * Scala port copyright 2025-2026 Mateusz Kubuszok
 */
package sge
package colorful
package rgb

import scala.collection.mutable

/** A palette of predefined colors as packed RGB floats, the kind [[ColorTools]] works with. You can access colors by their constant name, such as `OCEAN_BLUE`, by the [[NAMED]] map using
  * `NAMED.getOrElse("Ocean Blue", 0f)`, or by index in the list called [[LIST]].
  */
object Palette {

  /** Maps color names to packed float colors. */
  val NAMED: mutable.HashMap[String, Float] = mutable.HashMap.empty[String, Float]

  /** Lists packed float color values, in declaration order. */
  val LIST: mutable.ArrayBuffer[Float] = mutable.ArrayBuffer.empty[Float]

  val TRANSPARENT:       Float = java.lang.Float.intBitsToFloat(0x0)
  val BLACK:             Float = java.lang.Float.intBitsToFloat(0xfe000000)
  val COAL_BLACK:        Float = java.lang.Float.intBitsToFloat(0xfe131313)
  val SHADOW:            Float = java.lang.Float.intBitsToFloat(0xfe252525)
  val GRAPHITE:          Float = java.lang.Float.intBitsToFloat(0xfe373737)
  val DARK_GRAY:         Float = java.lang.Float.intBitsToFloat(0xfe494949)
  val LEAD:              Float = java.lang.Float.intBitsToFloat(0xfe5b5b5b)
  val IRON:              Float = java.lang.Float.intBitsToFloat(0xfe6e6e6e)
  val GRAY:              Float = java.lang.Float.intBitsToFloat(0xfe808080)
  val CHINCHILLA:        Float = java.lang.Float.intBitsToFloat(0xfe929292)
  val GREYHOUND:         Float = java.lang.Float.intBitsToFloat(0xfea4a4a4)
  val SILVER:            Float = java.lang.Float.intBitsToFloat(0xfeb6b6b6)
  val LIGHT_GRAY:        Float = java.lang.Float.intBitsToFloat(0xfec9c9c9)
  val PLATINUM:          Float = java.lang.Float.intBitsToFloat(0xfedbdbdb)
  val CLOUD:             Float = java.lang.Float.intBitsToFloat(0xfeededed)
  val WHITE:             Float = java.lang.Float.intBitsToFloat(0xfeffffff)
  val SEAWATER:          Float = java.lang.Float.intBitsToFloat(0xfe7f7f00)
  val HOSPITAL_GREEN:    Float = java.lang.Float.intBitsToFloat(0xfebfbf3f)
  val CYAN:              Float = java.lang.Float.intBitsToFloat(0xfeffff00)
  val BUBBLE:            Float = java.lang.Float.intBitsToFloat(0xfeffffbf)
  val PERIWINKLE:        Float = java.lang.Float.intBitsToFloat(0xfeff8181)
  val BLUE:              Float = java.lang.Float.intBitsToFloat(0xfeff0000)
  val FADED_BLUE:        Float = java.lang.Float.intBitsToFloat(0xfebf3f3f)
  val OCEAN_BLUE:        Float = java.lang.Float.intBitsToFloat(0xfe7f0000)
  val STYGIAN_BLUE:      Float = java.lang.Float.intBitsToFloat(0xfe500f0f)
  val DEEP_PURPLE:       Float = java.lang.Float.intBitsToFloat(0xfe7f007f)
  val TYRIAN_PURPLE:     Float = java.lang.Float.intBitsToFloat(0xfebf3fbf)
  val MAGENTA:           Float = java.lang.Float.intBitsToFloat(0xfef500f5)
  val BUBBLEGUM_PINK:    Float = java.lang.Float.intBitsToFloat(0xfeff81fd)
  val PORK_CHOP:         Float = java.lang.Float.intBitsToFloat(0xfecbc0ff)
  val RAW_MEAT:          Float = java.lang.Float.intBitsToFloat(0xfe8181ff)
  val RED:               Float = java.lang.Float.intBitsToFloat(0xfe0000ff)
  val PUTTY:             Float = java.lang.Float.intBitsToFloat(0xfe3f3fbf)
  val SIENNA:            Float = java.lang.Float.intBitsToFloat(0xfe00007f)
  val SEAL_BROWN:        Float = java.lang.Float.intBitsToFloat(0xfe141455)
  val MUMMY_BROWN:       Float = java.lang.Float.intBitsToFloat(0xfe003f7f)
  val FAWN:              Float = java.lang.Float.intBitsToFloat(0xfe3f7fbf)
  val ORANGE:            Float = java.lang.Float.intBitsToFloat(0xfe007fff)
  val PEACH:             Float = java.lang.Float.intBitsToFloat(0xfe81bfff)
  val CREAM:             Float = java.lang.Float.intBitsToFloat(0xfebfffff)
  val YELLOW:            Float = java.lang.Float.intBitsToFloat(0xfe00ffff)
  val EARWAX:            Float = java.lang.Float.intBitsToFloat(0xfe3fbfbf)
  val UMBER:             Float = java.lang.Float.intBitsToFloat(0xfe007f7f)
  val IVY_GREEN:         Float = java.lang.Float.intBitsToFloat(0xfe007f00)
  val JADE:              Float = java.lang.Float.intBitsToFloat(0xfe3fbf3f)
  val GREEN:             Float = java.lang.Float.intBitsToFloat(0xfe00ff00)
  val CELADON:           Float = java.lang.Float.intBitsToFloat(0xfeafffaf)
  val PUCE:              Float = java.lang.Float.intBitsToFloat(0xfec0afbc)
  val BEIGE:             Float = java.lang.Float.intBitsToFloat(0xfe89aacb)
  val WET_STONE:         Float = java.lang.Float.intBitsToFloat(0xfe90a0a6)
  val SLOW_CREEK:        Float = java.lang.Float.intBitsToFloat(0xfe94947e)
  val SLATE_GRAY:        Float = java.lang.Float.intBitsToFloat(0xfe87826e)
  val LIGHT_SKIN_1:      Float = java.lang.Float.intBitsToFloat(0xfe606e7e)
  val LIGHT_SKIN_2:      Float = java.lang.Float.intBitsToFloat(0xfe5f69a0)
  val LIGHT_SKIN_3:      Float = java.lang.Float.intBitsToFloat(0xfe7278c0)
  val LIGHT_SKIN_4:      Float = java.lang.Float.intBitsToFloat(0xfe748ad0)
  val LIGHT_SKIN_5:      Float = java.lang.Float.intBitsToFloat(0xfe7d9be1)
  val LIGHT_SKIN_6:      Float = java.lang.Float.intBitsToFloat(0xfe8caaeb)
  val LIGHT_SKIN_7:      Float = java.lang.Float.intBitsToFloat(0xfe9bb9f5)
  val LIGHT_SKIN_8:      Float = java.lang.Float.intBitsToFloat(0xfeafc8f6)
  val LIGHT_SKIN_9:      Float = java.lang.Float.intBitsToFloat(0xfed2e1f5)
  val DARK_SKIN_1:       Float = java.lang.Float.intBitsToFloat(0xfe3b3b57)
  val DARK_SKIN_2:       Float = java.lang.Float.intBitsToFloat(0xfe3c4173)
  val DARK_SKIN_3:       Float = java.lang.Float.intBitsToFloat(0xfe55558e)
  val PINK_SKIN_1:       Float = java.lang.Float.intBitsToFloat(0xfe7373ab)
  val PINK_SKIN_2:       Float = java.lang.Float.intBitsToFloat(0xfe8f8fc7)
  val PINK_SKIN_3:       Float = java.lang.Float.intBitsToFloat(0xfeababe3)
  val PINK_SKIN_4:       Float = java.lang.Float.intBitsToFloat(0xfedad2f8)
  val BRONZE_SKIN_4:     Float = java.lang.Float.intBitsToFloat(0xfeabc7e3)
  val BRONZE_SKIN_3:     Float = java.lang.Float.intBitsToFloat(0xfe739ec4)
  val BRONZE_SKIN_2:     Float = java.lang.Float.intBitsToFloat(0xfe57738f)
  val BRONZE_SKIN_1:     Float = java.lang.Float.intBitsToFloat(0xfe3b5773)
  val TAUPE:             Float = java.lang.Float.intBitsToFloat(0xfe1f2d3b)
  val DRAB_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe234141)
  val LIZARD_SCALES:     Float = java.lang.Float.intBitsToFloat(0xfe3b7373)
  val CRICKET:           Float = java.lang.Float.intBitsToFloat(0xfe578f8f)
  val OLIVE_OIL:         Float = java.lang.Float.intBitsToFloat(0xfe55a2a2)
  val DUN:               Float = java.lang.Float.intBitsToFloat(0xfe72b5b5)
  val CORN_SILK:         Float = java.lang.Float.intBitsToFloat(0xfe8fc7c7)
  val TAN:               Float = java.lang.Float.intBitsToFloat(0xfeabdada)
  val STRAW:             Float = java.lang.Float.intBitsToFloat(0xfec7eded)
  val HONEYDEW:          Float = java.lang.Float.intBitsToFloat(0xfeabe3c7)
  val TARNISH:           Float = java.lang.Float.intBitsToFloat(0xfe8fc7ab)
  val PEA_SOUP:          Float = java.lang.Float.intBitsToFloat(0xfe55be8e)
  val MARSH:             Float = java.lang.Float.intBitsToFloat(0xfe578f73)
  val ASPARAGUS:         Float = java.lang.Float.intBitsToFloat(0xfe3e7d58)
  val PEAT_BOG:          Float = java.lang.Float.intBitsToFloat(0xfe325046)
  val DEEP_JUNGLE:       Float = java.lang.Float.intBitsToFloat(0xfe0f1e19)
  val PINE_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe375023)
  val OLIVE_GREEN:       Float = java.lang.Float.intBitsToFloat(0xfe3b573b)
  val GRAY_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe506450)
  val MAIDENHAIR_FERN:   Float = java.lang.Float.intBitsToFloat(0xfe49733b)
  val KELLY_GREEN:       Float = java.lang.Float.intBitsToFloat(0xfe578f57)
  val DUSTY_GREEN:       Float = java.lang.Float.intBitsToFloat(0xfe73ab73)
  val GARTER_SNAKE:      Float = java.lang.Float.intBitsToFloat(0xfe82c064)
  val SILVER_GREEN:      Float = java.lang.Float.intBitsToFloat(0xfe8fc78f)
  val PISTACHIO:         Float = java.lang.Float.intBitsToFloat(0xfea2d8a2)
  val ANGEL_WING:        Float = java.lang.Float.intBitsToFloat(0xfefaf8e1)
  val SAGE_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfecaeeb4)
  val DRIED_SAGE:        Float = java.lang.Float.intBitsToFloat(0xfec5e3ab)
  val ARTICHOKE:         Float = java.lang.Float.intBitsToFloat(0xfe8eb487)
  val VIRIDIAN:          Float = java.lang.Float.intBitsToFloat(0xfe5f7d50)
  val FLORAL_FOAM:       Float = java.lang.Float.intBitsToFloat(0xfe46690f)
  val HUNTER_GREEN:      Float = java.lang.Float.intBitsToFloat(0xfe232d1e)
  val DARK_TEAL:         Float = java.lang.Float.intBitsToFloat(0xfe464123)
  val KYANITE:           Float = java.lang.Float.intBitsToFloat(0xfe73733b)
  val SPEARMINT:         Float = java.lang.Float.intBitsToFloat(0xfeabab64)
  val AMAZONITE:         Float = java.lang.Float.intBitsToFloat(0xfec7c78f)
  val PASTEL_SKY:        Float = java.lang.Float.intBitsToFloat(0xfee3e3ab)
  val AQUAMARINE:        Float = java.lang.Float.intBitsToFloat(0xfef1f1c7)
  val DUST_BUNNY:        Float = java.lang.Float.intBitsToFloat(0xfef0d2be)
  val PATINA:            Float = java.lang.Float.intBitsToFloat(0xfee3c7ab)
  val CHIPPED_GRANITE:   Float = java.lang.Float.intBitsToFloat(0xfedcb9a8)
  val BLUE_SMOKE:        Float = java.lang.Float.intBitsToFloat(0xfec7ab8f)
  val AIR_FORCE_BLUE:    Float = java.lang.Float.intBitsToFloat(0xfec78f57)
  val COLD_IRON:         Float = java.lang.Float.intBitsToFloat(0xfe8f7357)
  val DREARY_BLUE:       Float = java.lang.Float.intBitsToFloat(0xfe73573b)
  val MURK:              Float = java.lang.Float.intBitsToFloat(0xfe2d190f)
  val NINJA:             Float = java.lang.Float.intBitsToFloat(0xfe3b1f1f)
  val WATERCOLOR_BLACK:  Float = java.lang.Float.intBitsToFloat(0xfe573b3b)
  val IOLITE:            Float = java.lang.Float.intBitsToFloat(0xfe734949)
  val BOYSENBERRY:       Float = java.lang.Float.intBitsToFloat(0xfe8f5757)
  val WATERCOLOR_GRAY:   Float = java.lang.Float.intBitsToFloat(0xfeaa6e73)
  val BLUE_STEEL:        Float = java.lang.Float.intBitsToFloat(0xfeca7676)
  val TWILIGHT_CLOUD:    Float = java.lang.Float.intBitsToFloat(0xfec78f8f)
  val SMOG:              Float = java.lang.Float.intBitsToFloat(0xfee3abab)
  val TROPIC_MIST:       Float = java.lang.Float.intBitsToFloat(0xfef8dad0)
  val FEATHER_DOWN:      Float = java.lang.Float.intBitsToFloat(0xfeffe3e3)
  val MILD_VIOLET:       Float = java.lang.Float.intBitsToFloat(0xfec78fab)
  val VIOLET_CUSHIONS:   Float = java.lang.Float.intBitsToFloat(0xfec7578f)
  val DULL_VIOLET:       Float = java.lang.Float.intBitsToFloat(0xfe8f5773)
  val ROYAL_VIOLET:      Float = java.lang.Float.intBitsToFloat(0xfe733b57)
  val EMINENCE:          Float = java.lang.Float.intBitsToFloat(0xfe3c233c)
  val PRUNE:             Float = java.lang.Float.intBitsToFloat(0xfe463246)
  val DUSTY_GRAPE:       Float = java.lang.Float.intBitsToFloat(0xfe724072)
  val PINK_VIOLET:       Float = java.lang.Float.intBitsToFloat(0xfe8f578f)
  val RIPE_PLUM:         Float = java.lang.Float.intBitsToFloat(0xfeab57ab)
  val MAUVE:             Float = java.lang.Float.intBitsToFloat(0xfeab73ab)
  val HAM:               Float = java.lang.Float.intBitsToFloat(0xfee1aceb)
  val COTTON_CANDY:      Float = java.lang.Float.intBitsToFloat(0xfef5dcff)
  val SILVER_PINK:       Float = java.lang.Float.intBitsToFloat(0xfee3c7e3)
  val TEA_ROSE:          Float = java.lang.Float.intBitsToFloat(0xfed2b9e1)
  val OLD_ROSE:          Float = java.lang.Float.intBitsToFloat(0xfebea0d7)
  val DUSTY_PINK:        Float = java.lang.Float.intBitsToFloat(0xfeb98fc7)
  val ROSEATE_SPOONBILL: Float = java.lang.Float.intBitsToFloat(0xfea07dc8)
  val THULIAN_PINK:      Float = java.lang.Float.intBitsToFloat(0xfe915ac3)
  val BROWN_VELVET:      Float = java.lang.Float.intBitsToFloat(0xfe37284b)
  val NIGHTSHADE:        Float = java.lang.Float.intBitsToFloat(0xfe231632)
  val SCRIBE_INK:        Float = java.lang.Float.intBitsToFloat(0xfe1e0a28)
  val VARNISH:           Float = java.lang.Float.intBitsToFloat(0xfe111840)
  val CEDAR_WOOD:        Float = java.lang.Float.intBitsToFloat(0xfe001862)
  val HOT_SAUCE:         Float = java.lang.Float.intBitsToFloat(0xfe0a14a5)
  val LURID_RED:         Float = java.lang.Float.intBitsToFloat(0xfe1020da)
  val BRICK:             Float = java.lang.Float.intBitsToFloat(0xfe4a52d5)
  val BRIGHT_RED:        Float = java.lang.Float.intBitsToFloat(0xfe0a3cff)
  val EMBERS:            Float = java.lang.Float.intBitsToFloat(0xfe325af5)
  val SALMON:            Float = java.lang.Float.intBitsToFloat(0xfe6262ff)
  val TAXICAB_YELLOW:    Float = java.lang.Float.intBitsToFloat(0xfe31bdf6)
  val APRICOT:           Float = java.lang.Float.intBitsToFloat(0xfe3ca5ff)
  val BURNT_YELLOW:      Float = java.lang.Float.intBitsToFloat(0xfe0f9bd7)
  val DRY_PEPPER:        Float = java.lang.Float.intBitsToFloat(0xfe0a6eda)
  val REDWOOD:           Float = java.lang.Float.intBitsToFloat(0xfe005ab4)
  val KOA:               Float = java.lang.Float.intBitsToFloat(0xfe054ba0)
  val OCHRE:             Float = java.lang.Float.intBitsToFloat(0xfe14325f)
  val DULL_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe0a5053)
  val ARMY_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe006262)
  val DRIFTWOOD:         Float = java.lang.Float.intBitsToFloat(0xfe5a808c)
  val DRY_BRUSH:         Float = java.lang.Float.intBitsToFloat(0xfe0094ac)
  val MUSH:              Float = java.lang.Float.intBitsToFloat(0xfe0ab1b1)
  val BANANA_PUDDING:    Float = java.lang.Float.intBitsToFloat(0xfe5ad5e6)
  val SAFFRON:           Float = java.lang.Float.intBitsToFloat(0xfe10d5ff)
  val PENCIL_YELLOW:     Float = java.lang.Float.intBitsToFloat(0xfe4aeaff)
  val CHARTREUSE:        Float = java.lang.Float.intBitsToFloat(0xfe41ffc8)
  val ABSINTHE:          Float = java.lang.Float.intBitsToFloat(0xfe46f09b)
  val INFECTION:         Float = java.lang.Float.intBitsToFloat(0xfe19dc96)
  val FROG_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe05c873)
  val AVOCADO:           Float = java.lang.Float.intBitsToFloat(0xfe05a86a)
  val WOODLANDS:         Float = java.lang.Float.intBitsToFloat(0xfe146e3c)
  val DARK_PINE:         Float = java.lang.Float.intBitsToFloat(0xfe053428)
  val MOSS_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe084620)
  val FERN_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe0c5c0c)
  val FOREST_GLEN:       Float = java.lang.Float.intBitsToFloat(0xfe059614)
  val MALACHITE:         Float = java.lang.Float.intBitsToFloat(0xfe0ad70a)
  val APPLE_GREEN:       Float = java.lang.Float.intBitsToFloat(0xfe0ae614)
  val CELERY:            Float = java.lang.Float.intBitsToFloat(0xfe73ff7d)
  val MINT_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe5af04b)
  val EMERALD:           Float = java.lang.Float.intBitsToFloat(0xfe14c500)
  val PRASE:             Float = java.lang.Float.intBitsToFloat(0xfe50b405)
  val EUCALYPTUS:        Float = java.lang.Float.intBitsToFloat(0xfe4e8c1c)
  val ZUCCHINI:          Float = java.lang.Float.intBitsToFloat(0xfe323812)
  val SOFT_TEAL:         Float = java.lang.Float.intBitsToFloat(0xfe809812)
  val MEDIUM_TEAL:       Float = java.lang.Float.intBitsToFloat(0xfe91c406)
  val SPRING_GREEN:      Float = java.lang.Float.intBitsToFloat(0xfe6ade00)
  val TURQUOISE:         Float = java.lang.Float.intBitsToFloat(0xfea8eb2d)
  val SEAFOAM:           Float = java.lang.Float.intBitsToFloat(0xfea5fe3c)
  val VARISCITE:         Float = java.lang.Float.intBitsToFloat(0xfecdff6a)
  val REFRESHING_MIST:   Float = java.lang.Float.intBitsToFloat(0xfeffeb91)
  val SHINING_SKY:       Float = java.lang.Float.intBitsToFloat(0xfeffe655)
  val STEAM:             Float = java.lang.Float.intBitsToFloat(0xfef0d77d)
  val ROBIN_EGG_BLUE:    Float = java.lang.Float.intBitsToFloat(0xfed5de08)
  val DENIM_BLUE:        Float = java.lang.Float.intBitsToFloat(0xfede9c10)
  val DEEP_TEAL:         Float = java.lang.Float.intBitsToFloat(0xfe5c5a05)
  val NAVY_BLUE:         Float = java.lang.Float.intBitsToFloat(0xfe522c16)
  val BLUEBERRY:         Float = java.lang.Float.intBitsToFloat(0xfe7d370f)
  val PRUSSIAN_BLUE:     Float = java.lang.Float.intBitsToFloat(0xfe9c4a00)
  val DESERT_RAIN:       Float = java.lang.Float.intBitsToFloat(0xfe966432)
  val ELECTRIC_BLUE:     Float = java.lang.Float.intBitsToFloat(0xfef65200)
  val HIDDEN_BLUE:       Float = java.lang.Float.intBitsToFloat(0xfebd6a18)
  val DULL_AZURE:        Float = java.lang.Float.intBitsToFloat(0xfedc7823)
  val RIPPED_DENIM:      Float = java.lang.Float.intBitsToFloat(0xfec39d69)
  val CALM_SKY:          Float = java.lang.Float.intBitsToFloat(0xfeffa44a)
  val VAPOR:             Float = java.lang.Float.intBitsToFloat(0xfeffb090)
  val POWDER_BLUE:       Float = java.lang.Float.intBitsToFloat(0xfeffc55a)
  val SUDS:              Float = java.lang.Float.intBitsToFloat(0xfefab9be)
  val STRONG_CYAN:       Float = java.lang.Float.intBitsToFloat(0xfeffbf00)
  val SHARP_AZURE:       Float = java.lang.Float.intBitsToFloat(0xfeff7f00)
  val BLUE_EYE:          Float = java.lang.Float.intBitsToFloat(0xfec87d4b)
  val SUBTLETY:          Float = java.lang.Float.intBitsToFloat(0xfef06e78)
  val ROUGH_SAPPHIRE:    Float = java.lang.Float.intBitsToFloat(0xfeff5a4a)
  val IRIS:              Float = java.lang.Float.intBitsToFloat(0xfef64162)
  val CORNFLOWER_BLUE:   Float = java.lang.Float.intBitsToFloat(0xfef53c3c)
  val POLISHED_SAPPHIRE: Float = java.lang.Float.intBitsToFloat(0xfeda1c10)
  val ROYAL_BLUE:        Float = java.lang.Float.intBitsToFloat(0xfebd1000)
  val INDIGO:            Float = java.lang.Float.intBitsToFloat(0xfe941023)
  val SPACE_BLUE:        Float = java.lang.Float.intBitsToFloat(0xfe48210c)
  val THICK_AMETHYST:    Float = java.lang.Float.intBitsToFloat(0xfeb01050)
  val JUICY_GRAPE:       Float = java.lang.Float.intBitsToFloat(0xfed01060)
  val BLACKLIGHT_GLOW:   Float = java.lang.Float.intBitsToFloat(0xfed23287)
  val PURPLE_FREESIA:    Float = java.lang.Float.intBitsToFloat(0xfeff419c)
  val THIN_AMETHYST:     Float = java.lang.Float.intBitsToFloat(0xfeff007f)
  val ORCHID:            Float = java.lang.Float.intBitsToFloat(0xfeff62bd)
  val LAVENDER:          Float = java.lang.Float.intBitsToFloat(0xfeff91b9)
  val LILAC:             Float = java.lang.Float.intBitsToFloat(0xfeffa5d7)
  val SOAP:              Float = java.lang.Float.intBitsToFloat(0xfefac3d7)
  val PINK_TUTU:         Float = java.lang.Float.intBitsToFloat(0xfefcc6f8)
  val THISTLE:           Float = java.lang.Float.intBitsToFloat(0xfeff73e6)
  val HELIOTROPE:        Float = java.lang.Float.intBitsToFloat(0xfeff52ff)
  val PURPLE:            Float = java.lang.Float.intBitsToFloat(0xfee020da)
  val WISTERIA:          Float = java.lang.Float.intBitsToFloat(0xfeff29bd)
  val MEDIUM_PLUM:       Float = java.lang.Float.intBitsToFloat(0xfec510bd)
  val VIOLET:            Float = java.lang.Float.intBitsToFloat(0xfebe148c)
  val GRAPE_LOLLIPOP:    Float = java.lang.Float.intBitsToFloat(0xfe7b185a)
  val MULBERRY:          Float = java.lang.Float.intBitsToFloat(0xfe641464)
  val GRAPE_SODA:        Float = java.lang.Float.intBitsToFloat(0xfe620041)
  val EGGPLANT:          Float = java.lang.Float.intBitsToFloat(0xfe460a32)
  val CHERRY_SYRUP:      Float = java.lang.Float.intBitsToFloat(0xfe371955)
  val PLUM_JUICE:        Float = java.lang.Float.intBitsToFloat(0xfe8219a0)
  val FRUIT_PUNCH:       Float = java.lang.Float.intBitsToFloat(0xfe7800c8)
  val BUBBLE_GUM:        Float = java.lang.Float.intBitsToFloat(0xfebf50ff)
  val PINK_LEMONADE:     Float = java.lang.Float.intBitsToFloat(0xfec56aff)
  val SHRIMP:            Float = java.lang.Float.intBitsToFloat(0xfeb9a0fa)
  val FLAMINGO:          Float = java.lang.Float.intBitsToFloat(0xfe8c3afc)
  val ROSE:              Float = java.lang.Float.intBitsToFloat(0xfe781ee6)
  val CARMINE:           Float = java.lang.Float.intBitsToFloat(0xfe3910bd)
  val BOLOGNA:           Float = java.lang.Float.intBitsToFloat(0xfe4d3498)
  val RASPBERRY:         Float = java.lang.Float.intBitsToFloat(0xfe371491)

  // Register all colors
  locally {
    NAMED.put("Transparent", java.lang.Float.intBitsToFloat(0x0))
    LIST += java.lang.Float.intBitsToFloat(0x0)
    NAMED.put("Black", java.lang.Float.intBitsToFloat(0xfe000000))
    LIST += java.lang.Float.intBitsToFloat(0xfe000000)
    NAMED.put("Coal Black", java.lang.Float.intBitsToFloat(0xfe131313))
    LIST += java.lang.Float.intBitsToFloat(0xfe131313)
    NAMED.put("Shadow", java.lang.Float.intBitsToFloat(0xfe252525))
    LIST += java.lang.Float.intBitsToFloat(0xfe252525)
    NAMED.put("Graphite", java.lang.Float.intBitsToFloat(0xfe373737))
    LIST += java.lang.Float.intBitsToFloat(0xfe373737)
    NAMED.put("Dark Gray", java.lang.Float.intBitsToFloat(0xfe494949))
    LIST += java.lang.Float.intBitsToFloat(0xfe494949)
    NAMED.put("Lead", java.lang.Float.intBitsToFloat(0xfe5b5b5b))
    LIST += java.lang.Float.intBitsToFloat(0xfe5b5b5b)
    NAMED.put("Iron", java.lang.Float.intBitsToFloat(0xfe6e6e6e))
    LIST += java.lang.Float.intBitsToFloat(0xfe6e6e6e)
    NAMED.put("Gray", java.lang.Float.intBitsToFloat(0xfe808080))
    LIST += java.lang.Float.intBitsToFloat(0xfe808080)
    NAMED.put("Chinchilla", java.lang.Float.intBitsToFloat(0xfe929292))
    LIST += java.lang.Float.intBitsToFloat(0xfe929292)
    NAMED.put("Greyhound", java.lang.Float.intBitsToFloat(0xfea4a4a4))
    LIST += java.lang.Float.intBitsToFloat(0xfea4a4a4)
    NAMED.put("Silver", java.lang.Float.intBitsToFloat(0xfeb6b6b6))
    LIST += java.lang.Float.intBitsToFloat(0xfeb6b6b6)
    NAMED.put("Light Gray", java.lang.Float.intBitsToFloat(0xfec9c9c9))
    LIST += java.lang.Float.intBitsToFloat(0xfec9c9c9)
    NAMED.put("Platinum", java.lang.Float.intBitsToFloat(0xfedbdbdb))
    LIST += java.lang.Float.intBitsToFloat(0xfedbdbdb)
    NAMED.put("Cloud", java.lang.Float.intBitsToFloat(0xfeededed))
    LIST += java.lang.Float.intBitsToFloat(0xfeededed)
    NAMED.put("White", java.lang.Float.intBitsToFloat(0xfeffffff))
    LIST += java.lang.Float.intBitsToFloat(0xfeffffff)
    NAMED.put("Seawater", java.lang.Float.intBitsToFloat(0xfe7f7f00))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7f00)
    NAMED.put("Hospital Green", java.lang.Float.intBitsToFloat(0xfebfbf3f))
    LIST += java.lang.Float.intBitsToFloat(0xfebfbf3f)
    NAMED.put("Cyan", java.lang.Float.intBitsToFloat(0xfeffff00))
    LIST += java.lang.Float.intBitsToFloat(0xfeffff00)
    NAMED.put("Bubble", java.lang.Float.intBitsToFloat(0xfeffffbf))
    LIST += java.lang.Float.intBitsToFloat(0xfeffffbf)
    NAMED.put("Periwinkle", java.lang.Float.intBitsToFloat(0xfeff8181))
    LIST += java.lang.Float.intBitsToFloat(0xfeff8181)
    NAMED.put("Blue", java.lang.Float.intBitsToFloat(0xfeff0000))
    LIST += java.lang.Float.intBitsToFloat(0xfeff0000)
    NAMED.put("Faded Blue", java.lang.Float.intBitsToFloat(0xfebf3f3f))
    LIST += java.lang.Float.intBitsToFloat(0xfebf3f3f)
    NAMED.put("Ocean Blue", java.lang.Float.intBitsToFloat(0xfe7f0000))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f0000)
    NAMED.put("Stygian Blue", java.lang.Float.intBitsToFloat(0xfe500f0f))
    LIST += java.lang.Float.intBitsToFloat(0xfe500f0f)
    NAMED.put("Deep Purple", java.lang.Float.intBitsToFloat(0xfe7f007f))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f007f)
    NAMED.put("Tyrian Purple", java.lang.Float.intBitsToFloat(0xfebf3fbf))
    LIST += java.lang.Float.intBitsToFloat(0xfebf3fbf)
    NAMED.put("Magenta", java.lang.Float.intBitsToFloat(0xfef500f5))
    LIST += java.lang.Float.intBitsToFloat(0xfef500f5)
    NAMED.put("Bubblegum Pink", java.lang.Float.intBitsToFloat(0xfeff81fd))
    LIST += java.lang.Float.intBitsToFloat(0xfeff81fd)
    NAMED.put("Pork Chop", java.lang.Float.intBitsToFloat(0xfecbc0ff))
    LIST += java.lang.Float.intBitsToFloat(0xfecbc0ff)
    NAMED.put("Raw Meat", java.lang.Float.intBitsToFloat(0xfe8181ff))
    LIST += java.lang.Float.intBitsToFloat(0xfe8181ff)
    NAMED.put("Red", java.lang.Float.intBitsToFloat(0xfe0000ff))
    LIST += java.lang.Float.intBitsToFloat(0xfe0000ff)
    NAMED.put("Putty", java.lang.Float.intBitsToFloat(0xfe3f3fbf))
    LIST += java.lang.Float.intBitsToFloat(0xfe3f3fbf)
    NAMED.put("Sienna", java.lang.Float.intBitsToFloat(0xfe00007f))
    LIST += java.lang.Float.intBitsToFloat(0xfe00007f)
    NAMED.put("Seal Brown", java.lang.Float.intBitsToFloat(0xfe141455))
    LIST += java.lang.Float.intBitsToFloat(0xfe141455)
    NAMED.put("Mummy Brown", java.lang.Float.intBitsToFloat(0xfe003f7f))
    LIST += java.lang.Float.intBitsToFloat(0xfe003f7f)
    NAMED.put("Fawn", java.lang.Float.intBitsToFloat(0xfe3f7fbf))
    LIST += java.lang.Float.intBitsToFloat(0xfe3f7fbf)
    NAMED.put("Orange", java.lang.Float.intBitsToFloat(0xfe007fff))
    LIST += java.lang.Float.intBitsToFloat(0xfe007fff)
    NAMED.put("Peach", java.lang.Float.intBitsToFloat(0xfe81bfff))
    LIST += java.lang.Float.intBitsToFloat(0xfe81bfff)
    NAMED.put("Cream", java.lang.Float.intBitsToFloat(0xfebfffff))
    LIST += java.lang.Float.intBitsToFloat(0xfebfffff)
    NAMED.put("Yellow", java.lang.Float.intBitsToFloat(0xfe00ffff))
    LIST += java.lang.Float.intBitsToFloat(0xfe00ffff)
    NAMED.put("Earwax", java.lang.Float.intBitsToFloat(0xfe3fbfbf))
    LIST += java.lang.Float.intBitsToFloat(0xfe3fbfbf)
    NAMED.put("Umber", java.lang.Float.intBitsToFloat(0xfe007f7f))
    LIST += java.lang.Float.intBitsToFloat(0xfe007f7f)
    NAMED.put("Ivy Green", java.lang.Float.intBitsToFloat(0xfe007f00))
    LIST += java.lang.Float.intBitsToFloat(0xfe007f00)
    NAMED.put("Jade", java.lang.Float.intBitsToFloat(0xfe3fbf3f))
    LIST += java.lang.Float.intBitsToFloat(0xfe3fbf3f)
    NAMED.put("Green", java.lang.Float.intBitsToFloat(0xfe00ff00))
    LIST += java.lang.Float.intBitsToFloat(0xfe00ff00)
    NAMED.put("Celadon", java.lang.Float.intBitsToFloat(0xfeafffaf))
    LIST += java.lang.Float.intBitsToFloat(0xfeafffaf)
    NAMED.put("Puce", java.lang.Float.intBitsToFloat(0xfec0afbc))
    LIST += java.lang.Float.intBitsToFloat(0xfec0afbc)
    NAMED.put("Beige", java.lang.Float.intBitsToFloat(0xfe89aacb))
    LIST += java.lang.Float.intBitsToFloat(0xfe89aacb)
    NAMED.put("Wet Stone", java.lang.Float.intBitsToFloat(0xfe90a0a6))
    LIST += java.lang.Float.intBitsToFloat(0xfe90a0a6)
    NAMED.put("Slow Creek", java.lang.Float.intBitsToFloat(0xfe94947e))
    LIST += java.lang.Float.intBitsToFloat(0xfe94947e)
    NAMED.put("Slate Gray", java.lang.Float.intBitsToFloat(0xfe87826e))
    LIST += java.lang.Float.intBitsToFloat(0xfe87826e)
    NAMED.put("Light Skin 1", java.lang.Float.intBitsToFloat(0xfe606e7e))
    LIST += java.lang.Float.intBitsToFloat(0xfe606e7e)
    NAMED.put("Light Skin 2", java.lang.Float.intBitsToFloat(0xfe5f69a0))
    LIST += java.lang.Float.intBitsToFloat(0xfe5f69a0)
    NAMED.put("Light Skin 3", java.lang.Float.intBitsToFloat(0xfe7278c0))
    LIST += java.lang.Float.intBitsToFloat(0xfe7278c0)
    NAMED.put("Light Skin 4", java.lang.Float.intBitsToFloat(0xfe748ad0))
    LIST += java.lang.Float.intBitsToFloat(0xfe748ad0)
    NAMED.put("Light Skin 5", java.lang.Float.intBitsToFloat(0xfe7d9be1))
    LIST += java.lang.Float.intBitsToFloat(0xfe7d9be1)
    NAMED.put("Light Skin 6", java.lang.Float.intBitsToFloat(0xfe8caaeb))
    LIST += java.lang.Float.intBitsToFloat(0xfe8caaeb)
    NAMED.put("Light Skin 7", java.lang.Float.intBitsToFloat(0xfe9bb9f5))
    LIST += java.lang.Float.intBitsToFloat(0xfe9bb9f5)
    NAMED.put("Light Skin 8", java.lang.Float.intBitsToFloat(0xfeafc8f6))
    LIST += java.lang.Float.intBitsToFloat(0xfeafc8f6)
    NAMED.put("Light Skin 9", java.lang.Float.intBitsToFloat(0xfed2e1f5))
    LIST += java.lang.Float.intBitsToFloat(0xfed2e1f5)
    NAMED.put("Dark Skin 1", java.lang.Float.intBitsToFloat(0xfe3b3b57))
    LIST += java.lang.Float.intBitsToFloat(0xfe3b3b57)
    NAMED.put("Dark Skin 2", java.lang.Float.intBitsToFloat(0xfe3c4173))
    LIST += java.lang.Float.intBitsToFloat(0xfe3c4173)
    NAMED.put("Dark Skin 3", java.lang.Float.intBitsToFloat(0xfe55558e))
    LIST += java.lang.Float.intBitsToFloat(0xfe55558e)
    NAMED.put("Pink Skin 1", java.lang.Float.intBitsToFloat(0xfe7373ab))
    LIST += java.lang.Float.intBitsToFloat(0xfe7373ab)
    NAMED.put("Pink Skin 2", java.lang.Float.intBitsToFloat(0xfe8f8fc7))
    LIST += java.lang.Float.intBitsToFloat(0xfe8f8fc7)
    NAMED.put("Pink Skin 3", java.lang.Float.intBitsToFloat(0xfeababe3))
    LIST += java.lang.Float.intBitsToFloat(0xfeababe3)
    NAMED.put("Pink Skin 4", java.lang.Float.intBitsToFloat(0xfedad2f8))
    LIST += java.lang.Float.intBitsToFloat(0xfedad2f8)
    NAMED.put("Bronze Skin 4", java.lang.Float.intBitsToFloat(0xfeabc7e3))
    LIST += java.lang.Float.intBitsToFloat(0xfeabc7e3)
    NAMED.put("Bronze Skin 3", java.lang.Float.intBitsToFloat(0xfe739ec4))
    LIST += java.lang.Float.intBitsToFloat(0xfe739ec4)
    NAMED.put("Bronze Skin 2", java.lang.Float.intBitsToFloat(0xfe57738f))
    LIST += java.lang.Float.intBitsToFloat(0xfe57738f)
    NAMED.put("Bronze Skin 1", java.lang.Float.intBitsToFloat(0xfe3b5773))
    LIST += java.lang.Float.intBitsToFloat(0xfe3b5773)
    NAMED.put("Taupe", java.lang.Float.intBitsToFloat(0xfe1f2d3b))
    LIST += java.lang.Float.intBitsToFloat(0xfe1f2d3b)
    NAMED.put("Drab Green", java.lang.Float.intBitsToFloat(0xfe234141))
    LIST += java.lang.Float.intBitsToFloat(0xfe234141)
    NAMED.put("Lizard Scales", java.lang.Float.intBitsToFloat(0xfe3b7373))
    LIST += java.lang.Float.intBitsToFloat(0xfe3b7373)
    NAMED.put("Cricket", java.lang.Float.intBitsToFloat(0xfe578f8f))
    LIST += java.lang.Float.intBitsToFloat(0xfe578f8f)
    NAMED.put("Olive Oil", java.lang.Float.intBitsToFloat(0xfe55a2a2))
    LIST += java.lang.Float.intBitsToFloat(0xfe55a2a2)
    NAMED.put("Dun", java.lang.Float.intBitsToFloat(0xfe72b5b5))
    LIST += java.lang.Float.intBitsToFloat(0xfe72b5b5)
    NAMED.put("Corn Silk", java.lang.Float.intBitsToFloat(0xfe8fc7c7))
    LIST += java.lang.Float.intBitsToFloat(0xfe8fc7c7)
    NAMED.put("Tan", java.lang.Float.intBitsToFloat(0xfeabdada))
    LIST += java.lang.Float.intBitsToFloat(0xfeabdada)
    NAMED.put("Straw", java.lang.Float.intBitsToFloat(0xfec7eded))
    LIST += java.lang.Float.intBitsToFloat(0xfec7eded)
    NAMED.put("Honeydew", java.lang.Float.intBitsToFloat(0xfeabe3c7))
    LIST += java.lang.Float.intBitsToFloat(0xfeabe3c7)
    NAMED.put("Tarnish", java.lang.Float.intBitsToFloat(0xfe8fc7ab))
    LIST += java.lang.Float.intBitsToFloat(0xfe8fc7ab)
    NAMED.put("Pea Soup", java.lang.Float.intBitsToFloat(0xfe55be8e))
    LIST += java.lang.Float.intBitsToFloat(0xfe55be8e)
    NAMED.put("Marsh", java.lang.Float.intBitsToFloat(0xfe578f73))
    LIST += java.lang.Float.intBitsToFloat(0xfe578f73)
    NAMED.put("Asparagus", java.lang.Float.intBitsToFloat(0xfe3e7d58))
    LIST += java.lang.Float.intBitsToFloat(0xfe3e7d58)
    NAMED.put("Peat Bog", java.lang.Float.intBitsToFloat(0xfe325046))
    LIST += java.lang.Float.intBitsToFloat(0xfe325046)
    NAMED.put("Deep Jungle", java.lang.Float.intBitsToFloat(0xfe0f1e19))
    LIST += java.lang.Float.intBitsToFloat(0xfe0f1e19)
    NAMED.put("Pine Green", java.lang.Float.intBitsToFloat(0xfe375023))
    LIST += java.lang.Float.intBitsToFloat(0xfe375023)
    NAMED.put("Olive Green", java.lang.Float.intBitsToFloat(0xfe3b573b))
    LIST += java.lang.Float.intBitsToFloat(0xfe3b573b)
    NAMED.put("Gray Green", java.lang.Float.intBitsToFloat(0xfe506450))
    LIST += java.lang.Float.intBitsToFloat(0xfe506450)
    NAMED.put("Maidenhair Fern", java.lang.Float.intBitsToFloat(0xfe49733b))
    LIST += java.lang.Float.intBitsToFloat(0xfe49733b)
    NAMED.put("Kelly Green", java.lang.Float.intBitsToFloat(0xfe578f57))
    LIST += java.lang.Float.intBitsToFloat(0xfe578f57)
    NAMED.put("Dusty Green", java.lang.Float.intBitsToFloat(0xfe73ab73))
    LIST += java.lang.Float.intBitsToFloat(0xfe73ab73)
    NAMED.put("Garter Snake", java.lang.Float.intBitsToFloat(0xfe82c064))
    LIST += java.lang.Float.intBitsToFloat(0xfe82c064)
    NAMED.put("Silver Green", java.lang.Float.intBitsToFloat(0xfe8fc78f))
    LIST += java.lang.Float.intBitsToFloat(0xfe8fc78f)
    NAMED.put("Pistachio", java.lang.Float.intBitsToFloat(0xfea2d8a2))
    LIST += java.lang.Float.intBitsToFloat(0xfea2d8a2)
    NAMED.put("Angel Wing", java.lang.Float.intBitsToFloat(0xfefaf8e1))
    LIST += java.lang.Float.intBitsToFloat(0xfefaf8e1)
    NAMED.put("Sage Green", java.lang.Float.intBitsToFloat(0xfecaeeb4))
    LIST += java.lang.Float.intBitsToFloat(0xfecaeeb4)
    NAMED.put("Dried Sage", java.lang.Float.intBitsToFloat(0xfec5e3ab))
    LIST += java.lang.Float.intBitsToFloat(0xfec5e3ab)
    NAMED.put("Artichoke", java.lang.Float.intBitsToFloat(0xfe8eb487))
    LIST += java.lang.Float.intBitsToFloat(0xfe8eb487)
    NAMED.put("Viridian", java.lang.Float.intBitsToFloat(0xfe5f7d50))
    LIST += java.lang.Float.intBitsToFloat(0xfe5f7d50)
    NAMED.put("Floral Foam", java.lang.Float.intBitsToFloat(0xfe46690f))
    LIST += java.lang.Float.intBitsToFloat(0xfe46690f)
    NAMED.put("Hunter Green", java.lang.Float.intBitsToFloat(0xfe232d1e))
    LIST += java.lang.Float.intBitsToFloat(0xfe232d1e)
    NAMED.put("Dark Teal", java.lang.Float.intBitsToFloat(0xfe464123))
    LIST += java.lang.Float.intBitsToFloat(0xfe464123)
    NAMED.put("Kyanite", java.lang.Float.intBitsToFloat(0xfe73733b))
    LIST += java.lang.Float.intBitsToFloat(0xfe73733b)
    NAMED.put("Spearmint", java.lang.Float.intBitsToFloat(0xfeabab64))
    LIST += java.lang.Float.intBitsToFloat(0xfeabab64)
    NAMED.put("Amazonite", java.lang.Float.intBitsToFloat(0xfec7c78f))
    LIST += java.lang.Float.intBitsToFloat(0xfec7c78f)
    NAMED.put("Pastel Sky", java.lang.Float.intBitsToFloat(0xfee3e3ab))
    LIST += java.lang.Float.intBitsToFloat(0xfee3e3ab)
    NAMED.put("Aquamarine", java.lang.Float.intBitsToFloat(0xfef1f1c7))
    LIST += java.lang.Float.intBitsToFloat(0xfef1f1c7)
    NAMED.put("Dust Bunny", java.lang.Float.intBitsToFloat(0xfef0d2be))
    LIST += java.lang.Float.intBitsToFloat(0xfef0d2be)
    NAMED.put("Patina", java.lang.Float.intBitsToFloat(0xfee3c7ab))
    LIST += java.lang.Float.intBitsToFloat(0xfee3c7ab)
    NAMED.put("Chipped Granite", java.lang.Float.intBitsToFloat(0xfedcb9a8))
    LIST += java.lang.Float.intBitsToFloat(0xfedcb9a8)
    NAMED.put("Blue Smoke", java.lang.Float.intBitsToFloat(0xfec7ab8f))
    LIST += java.lang.Float.intBitsToFloat(0xfec7ab8f)
    NAMED.put("Air Force Blue", java.lang.Float.intBitsToFloat(0xfec78f57))
    LIST += java.lang.Float.intBitsToFloat(0xfec78f57)
    NAMED.put("Cold Iron", java.lang.Float.intBitsToFloat(0xfe8f7357))
    LIST += java.lang.Float.intBitsToFloat(0xfe8f7357)
    NAMED.put("Dreary Blue", java.lang.Float.intBitsToFloat(0xfe73573b))
    LIST += java.lang.Float.intBitsToFloat(0xfe73573b)
    NAMED.put("Murk", java.lang.Float.intBitsToFloat(0xfe2d190f))
    LIST += java.lang.Float.intBitsToFloat(0xfe2d190f)
    NAMED.put("Ninja", java.lang.Float.intBitsToFloat(0xfe3b1f1f))
    LIST += java.lang.Float.intBitsToFloat(0xfe3b1f1f)
    NAMED.put("Watercolor Black", java.lang.Float.intBitsToFloat(0xfe573b3b))
    LIST += java.lang.Float.intBitsToFloat(0xfe573b3b)
    NAMED.put("Iolite", java.lang.Float.intBitsToFloat(0xfe734949))
    LIST += java.lang.Float.intBitsToFloat(0xfe734949)
    NAMED.put("Boysenberry", java.lang.Float.intBitsToFloat(0xfe8f5757))
    LIST += java.lang.Float.intBitsToFloat(0xfe8f5757)
    NAMED.put("Watercolor Gray", java.lang.Float.intBitsToFloat(0xfeaa6e73))
    LIST += java.lang.Float.intBitsToFloat(0xfeaa6e73)
    NAMED.put("Blue Steel", java.lang.Float.intBitsToFloat(0xfeca7676))
    LIST += java.lang.Float.intBitsToFloat(0xfeca7676)
    NAMED.put("Twilight Cloud", java.lang.Float.intBitsToFloat(0xfec78f8f))
    LIST += java.lang.Float.intBitsToFloat(0xfec78f8f)
    NAMED.put("Smog", java.lang.Float.intBitsToFloat(0xfee3abab))
    LIST += java.lang.Float.intBitsToFloat(0xfee3abab)
    NAMED.put("Tropic Mist", java.lang.Float.intBitsToFloat(0xfef8dad0))
    LIST += java.lang.Float.intBitsToFloat(0xfef8dad0)
    NAMED.put("Feather Down", java.lang.Float.intBitsToFloat(0xfeffe3e3))
    LIST += java.lang.Float.intBitsToFloat(0xfeffe3e3)
    NAMED.put("Mild Violet", java.lang.Float.intBitsToFloat(0xfec78fab))
    LIST += java.lang.Float.intBitsToFloat(0xfec78fab)
    NAMED.put("Violet Cushions", java.lang.Float.intBitsToFloat(0xfec7578f))
    LIST += java.lang.Float.intBitsToFloat(0xfec7578f)
    NAMED.put("Dull Violet", java.lang.Float.intBitsToFloat(0xfe8f5773))
    LIST += java.lang.Float.intBitsToFloat(0xfe8f5773)
    NAMED.put("Royal Violet", java.lang.Float.intBitsToFloat(0xfe733b57))
    LIST += java.lang.Float.intBitsToFloat(0xfe733b57)
    NAMED.put("Eminence", java.lang.Float.intBitsToFloat(0xfe3c233c))
    LIST += java.lang.Float.intBitsToFloat(0xfe3c233c)
    NAMED.put("Prune", java.lang.Float.intBitsToFloat(0xfe463246))
    LIST += java.lang.Float.intBitsToFloat(0xfe463246)
    NAMED.put("Dusty Grape", java.lang.Float.intBitsToFloat(0xfe724072))
    LIST += java.lang.Float.intBitsToFloat(0xfe724072)
    NAMED.put("Pink Violet", java.lang.Float.intBitsToFloat(0xfe8f578f))
    LIST += java.lang.Float.intBitsToFloat(0xfe8f578f)
    NAMED.put("Ripe Plum", java.lang.Float.intBitsToFloat(0xfeab57ab))
    LIST += java.lang.Float.intBitsToFloat(0xfeab57ab)
    NAMED.put("Mauve", java.lang.Float.intBitsToFloat(0xfeab73ab))
    LIST += java.lang.Float.intBitsToFloat(0xfeab73ab)
    NAMED.put("Ham", java.lang.Float.intBitsToFloat(0xfee1aceb))
    LIST += java.lang.Float.intBitsToFloat(0xfee1aceb)
    NAMED.put("Cotton Candy", java.lang.Float.intBitsToFloat(0xfef5dcff))
    LIST += java.lang.Float.intBitsToFloat(0xfef5dcff)
    NAMED.put("Silver Pink", java.lang.Float.intBitsToFloat(0xfee3c7e3))
    LIST += java.lang.Float.intBitsToFloat(0xfee3c7e3)
    NAMED.put("Tea Rose", java.lang.Float.intBitsToFloat(0xfed2b9e1))
    LIST += java.lang.Float.intBitsToFloat(0xfed2b9e1)
    NAMED.put("Old Rose", java.lang.Float.intBitsToFloat(0xfebea0d7))
    LIST += java.lang.Float.intBitsToFloat(0xfebea0d7)
    NAMED.put("Dusty Pink", java.lang.Float.intBitsToFloat(0xfeb98fc7))
    LIST += java.lang.Float.intBitsToFloat(0xfeb98fc7)
    NAMED.put("Roseate Spoonbill", java.lang.Float.intBitsToFloat(0xfea07dc8))
    LIST += java.lang.Float.intBitsToFloat(0xfea07dc8)
    NAMED.put("Thulian Pink", java.lang.Float.intBitsToFloat(0xfe915ac3))
    LIST += java.lang.Float.intBitsToFloat(0xfe915ac3)
    NAMED.put("Brown Velvet", java.lang.Float.intBitsToFloat(0xfe37284b))
    LIST += java.lang.Float.intBitsToFloat(0xfe37284b)
    NAMED.put("Nightshade", java.lang.Float.intBitsToFloat(0xfe231632))
    LIST += java.lang.Float.intBitsToFloat(0xfe231632)
    NAMED.put("Scribe Ink", java.lang.Float.intBitsToFloat(0xfe1e0a28))
    LIST += java.lang.Float.intBitsToFloat(0xfe1e0a28)
    NAMED.put("Varnish", java.lang.Float.intBitsToFloat(0xfe111840))
    LIST += java.lang.Float.intBitsToFloat(0xfe111840)
    NAMED.put("Cedar Wood", java.lang.Float.intBitsToFloat(0xfe001862))
    LIST += java.lang.Float.intBitsToFloat(0xfe001862)
    NAMED.put("Hot Sauce", java.lang.Float.intBitsToFloat(0xfe0a14a5))
    LIST += java.lang.Float.intBitsToFloat(0xfe0a14a5)
    NAMED.put("Lurid Red", java.lang.Float.intBitsToFloat(0xfe1020da))
    LIST += java.lang.Float.intBitsToFloat(0xfe1020da)
    NAMED.put("Brick", java.lang.Float.intBitsToFloat(0xfe4a52d5))
    LIST += java.lang.Float.intBitsToFloat(0xfe4a52d5)
    NAMED.put("Bright Red", java.lang.Float.intBitsToFloat(0xfe0a3cff))
    LIST += java.lang.Float.intBitsToFloat(0xfe0a3cff)
    NAMED.put("Embers", java.lang.Float.intBitsToFloat(0xfe325af5))
    LIST += java.lang.Float.intBitsToFloat(0xfe325af5)
    NAMED.put("Salmon", java.lang.Float.intBitsToFloat(0xfe6262ff))
    LIST += java.lang.Float.intBitsToFloat(0xfe6262ff)
    NAMED.put("Taxicab Yellow", java.lang.Float.intBitsToFloat(0xfe31bdf6))
    LIST += java.lang.Float.intBitsToFloat(0xfe31bdf6)
    NAMED.put("Apricot", java.lang.Float.intBitsToFloat(0xfe3ca5ff))
    LIST += java.lang.Float.intBitsToFloat(0xfe3ca5ff)
    NAMED.put("Burnt Yellow", java.lang.Float.intBitsToFloat(0xfe0f9bd7))
    LIST += java.lang.Float.intBitsToFloat(0xfe0f9bd7)
    NAMED.put("Dry Pepper", java.lang.Float.intBitsToFloat(0xfe0a6eda))
    LIST += java.lang.Float.intBitsToFloat(0xfe0a6eda)
    NAMED.put("Redwood", java.lang.Float.intBitsToFloat(0xfe005ab4))
    LIST += java.lang.Float.intBitsToFloat(0xfe005ab4)
    NAMED.put("Koa", java.lang.Float.intBitsToFloat(0xfe054ba0))
    LIST += java.lang.Float.intBitsToFloat(0xfe054ba0)
    NAMED.put("Ochre", java.lang.Float.intBitsToFloat(0xfe14325f))
    LIST += java.lang.Float.intBitsToFloat(0xfe14325f)
    NAMED.put("Dull Green", java.lang.Float.intBitsToFloat(0xfe0a5053))
    LIST += java.lang.Float.intBitsToFloat(0xfe0a5053)
    NAMED.put("Army Green", java.lang.Float.intBitsToFloat(0xfe006262))
    LIST += java.lang.Float.intBitsToFloat(0xfe006262)
    NAMED.put("Driftwood", java.lang.Float.intBitsToFloat(0xfe5a808c))
    LIST += java.lang.Float.intBitsToFloat(0xfe5a808c)
    NAMED.put("Dry Brush", java.lang.Float.intBitsToFloat(0xfe0094ac))
    LIST += java.lang.Float.intBitsToFloat(0xfe0094ac)
    NAMED.put("Mush", java.lang.Float.intBitsToFloat(0xfe0ab1b1))
    LIST += java.lang.Float.intBitsToFloat(0xfe0ab1b1)
    NAMED.put("Banana Pudding", java.lang.Float.intBitsToFloat(0xfe5ad5e6))
    LIST += java.lang.Float.intBitsToFloat(0xfe5ad5e6)
    NAMED.put("Saffron", java.lang.Float.intBitsToFloat(0xfe10d5ff))
    LIST += java.lang.Float.intBitsToFloat(0xfe10d5ff)
    NAMED.put("Pencil Yellow", java.lang.Float.intBitsToFloat(0xfe4aeaff))
    LIST += java.lang.Float.intBitsToFloat(0xfe4aeaff)
    NAMED.put("Chartreuse", java.lang.Float.intBitsToFloat(0xfe41ffc8))
    LIST += java.lang.Float.intBitsToFloat(0xfe41ffc8)
    NAMED.put("Absinthe", java.lang.Float.intBitsToFloat(0xfe46f09b))
    LIST += java.lang.Float.intBitsToFloat(0xfe46f09b)
    NAMED.put("Infection", java.lang.Float.intBitsToFloat(0xfe19dc96))
    LIST += java.lang.Float.intBitsToFloat(0xfe19dc96)
    NAMED.put("Frog Green", java.lang.Float.intBitsToFloat(0xfe05c873))
    LIST += java.lang.Float.intBitsToFloat(0xfe05c873)
    NAMED.put("Avocado", java.lang.Float.intBitsToFloat(0xfe05a86a))
    LIST += java.lang.Float.intBitsToFloat(0xfe05a86a)
    NAMED.put("Woodlands", java.lang.Float.intBitsToFloat(0xfe146e3c))
    LIST += java.lang.Float.intBitsToFloat(0xfe146e3c)
    NAMED.put("Dark Pine", java.lang.Float.intBitsToFloat(0xfe053428))
    LIST += java.lang.Float.intBitsToFloat(0xfe053428)
    NAMED.put("Moss Green", java.lang.Float.intBitsToFloat(0xfe084620))
    LIST += java.lang.Float.intBitsToFloat(0xfe084620)
    NAMED.put("Fern Green", java.lang.Float.intBitsToFloat(0xfe0c5c0c))
    LIST += java.lang.Float.intBitsToFloat(0xfe0c5c0c)
    NAMED.put("Forest Glen", java.lang.Float.intBitsToFloat(0xfe059614))
    LIST += java.lang.Float.intBitsToFloat(0xfe059614)
    NAMED.put("Malachite", java.lang.Float.intBitsToFloat(0xfe0ad70a))
    LIST += java.lang.Float.intBitsToFloat(0xfe0ad70a)
    NAMED.put("Apple Green", java.lang.Float.intBitsToFloat(0xfe0ae614))
    LIST += java.lang.Float.intBitsToFloat(0xfe0ae614)
    NAMED.put("Celery", java.lang.Float.intBitsToFloat(0xfe73ff7d))
    LIST += java.lang.Float.intBitsToFloat(0xfe73ff7d)
    NAMED.put("Mint Green", java.lang.Float.intBitsToFloat(0xfe5af04b))
    LIST += java.lang.Float.intBitsToFloat(0xfe5af04b)
    NAMED.put("Emerald", java.lang.Float.intBitsToFloat(0xfe14c500))
    LIST += java.lang.Float.intBitsToFloat(0xfe14c500)
    NAMED.put("Prase", java.lang.Float.intBitsToFloat(0xfe50b405))
    LIST += java.lang.Float.intBitsToFloat(0xfe50b405)
    NAMED.put("Eucalyptus", java.lang.Float.intBitsToFloat(0xfe4e8c1c))
    LIST += java.lang.Float.intBitsToFloat(0xfe4e8c1c)
    NAMED.put("Zucchini", java.lang.Float.intBitsToFloat(0xfe323812))
    LIST += java.lang.Float.intBitsToFloat(0xfe323812)
    NAMED.put("Soft Teal", java.lang.Float.intBitsToFloat(0xfe809812))
    LIST += java.lang.Float.intBitsToFloat(0xfe809812)
    NAMED.put("Medium Teal", java.lang.Float.intBitsToFloat(0xfe91c406))
    LIST += java.lang.Float.intBitsToFloat(0xfe91c406)
    NAMED.put("Spring Green", java.lang.Float.intBitsToFloat(0xfe6ade00))
    LIST += java.lang.Float.intBitsToFloat(0xfe6ade00)
    NAMED.put("Turquoise", java.lang.Float.intBitsToFloat(0xfea8eb2d))
    LIST += java.lang.Float.intBitsToFloat(0xfea8eb2d)
    NAMED.put("Seafoam", java.lang.Float.intBitsToFloat(0xfea5fe3c))
    LIST += java.lang.Float.intBitsToFloat(0xfea5fe3c)
    NAMED.put("Variscite", java.lang.Float.intBitsToFloat(0xfecdff6a))
    LIST += java.lang.Float.intBitsToFloat(0xfecdff6a)
    NAMED.put("Refreshing Mist", java.lang.Float.intBitsToFloat(0xfeffeb91))
    LIST += java.lang.Float.intBitsToFloat(0xfeffeb91)
    NAMED.put("Shining Sky", java.lang.Float.intBitsToFloat(0xfeffe655))
    LIST += java.lang.Float.intBitsToFloat(0xfeffe655)
    NAMED.put("Steam", java.lang.Float.intBitsToFloat(0xfef0d77d))
    LIST += java.lang.Float.intBitsToFloat(0xfef0d77d)
    NAMED.put("Robin Egg Blue", java.lang.Float.intBitsToFloat(0xfed5de08))
    LIST += java.lang.Float.intBitsToFloat(0xfed5de08)
    NAMED.put("Denim Blue", java.lang.Float.intBitsToFloat(0xfede9c10))
    LIST += java.lang.Float.intBitsToFloat(0xfede9c10)
    NAMED.put("Deep Teal", java.lang.Float.intBitsToFloat(0xfe5c5a05))
    LIST += java.lang.Float.intBitsToFloat(0xfe5c5a05)
    NAMED.put("Navy Blue", java.lang.Float.intBitsToFloat(0xfe522c16))
    LIST += java.lang.Float.intBitsToFloat(0xfe522c16)
    NAMED.put("Blueberry", java.lang.Float.intBitsToFloat(0xfe7d370f))
    LIST += java.lang.Float.intBitsToFloat(0xfe7d370f)
    NAMED.put("Prussian Blue", java.lang.Float.intBitsToFloat(0xfe9c4a00))
    LIST += java.lang.Float.intBitsToFloat(0xfe9c4a00)
    NAMED.put("Desert Rain", java.lang.Float.intBitsToFloat(0xfe966432))
    LIST += java.lang.Float.intBitsToFloat(0xfe966432)
    NAMED.put("Electric Blue", java.lang.Float.intBitsToFloat(0xfef65200))
    LIST += java.lang.Float.intBitsToFloat(0xfef65200)
    NAMED.put("Hidden Blue", java.lang.Float.intBitsToFloat(0xfebd6a18))
    LIST += java.lang.Float.intBitsToFloat(0xfebd6a18)
    NAMED.put("Dull Azure", java.lang.Float.intBitsToFloat(0xfedc7823))
    LIST += java.lang.Float.intBitsToFloat(0xfedc7823)
    NAMED.put("Ripped Denim", java.lang.Float.intBitsToFloat(0xfec39d69))
    LIST += java.lang.Float.intBitsToFloat(0xfec39d69)
    NAMED.put("Calm Sky", java.lang.Float.intBitsToFloat(0xfeffa44a))
    LIST += java.lang.Float.intBitsToFloat(0xfeffa44a)
    NAMED.put("Vapor", java.lang.Float.intBitsToFloat(0xfeffb090))
    LIST += java.lang.Float.intBitsToFloat(0xfeffb090)
    NAMED.put("Powder Blue", java.lang.Float.intBitsToFloat(0xfeffc55a))
    LIST += java.lang.Float.intBitsToFloat(0xfeffc55a)
    NAMED.put("Suds", java.lang.Float.intBitsToFloat(0xfefab9be))
    LIST += java.lang.Float.intBitsToFloat(0xfefab9be)
    NAMED.put("Strong Cyan", java.lang.Float.intBitsToFloat(0xfeffbf00))
    LIST += java.lang.Float.intBitsToFloat(0xfeffbf00)
    NAMED.put("Sharp Azure", java.lang.Float.intBitsToFloat(0xfeff7f00))
    LIST += java.lang.Float.intBitsToFloat(0xfeff7f00)
    NAMED.put("Blue Eye", java.lang.Float.intBitsToFloat(0xfec87d4b))
    LIST += java.lang.Float.intBitsToFloat(0xfec87d4b)
    NAMED.put("Subtlety", java.lang.Float.intBitsToFloat(0xfef06e78))
    LIST += java.lang.Float.intBitsToFloat(0xfef06e78)
    NAMED.put("Rough Sapphire", java.lang.Float.intBitsToFloat(0xfeff5a4a))
    LIST += java.lang.Float.intBitsToFloat(0xfeff5a4a)
    NAMED.put("Iris", java.lang.Float.intBitsToFloat(0xfef64162))
    LIST += java.lang.Float.intBitsToFloat(0xfef64162)
    NAMED.put("Cornflower Blue", java.lang.Float.intBitsToFloat(0xfef53c3c))
    LIST += java.lang.Float.intBitsToFloat(0xfef53c3c)
    NAMED.put("Polished Sapphire", java.lang.Float.intBitsToFloat(0xfeda1c10))
    LIST += java.lang.Float.intBitsToFloat(0xfeda1c10)
    NAMED.put("Royal Blue", java.lang.Float.intBitsToFloat(0xfebd1000))
    LIST += java.lang.Float.intBitsToFloat(0xfebd1000)
    NAMED.put("Indigo", java.lang.Float.intBitsToFloat(0xfe941023))
    LIST += java.lang.Float.intBitsToFloat(0xfe941023)
    NAMED.put("Space Blue", java.lang.Float.intBitsToFloat(0xfe48210c))
    LIST += java.lang.Float.intBitsToFloat(0xfe48210c)
    NAMED.put("Thick Amethyst", java.lang.Float.intBitsToFloat(0xfeb01050))
    LIST += java.lang.Float.intBitsToFloat(0xfeb01050)
    NAMED.put("Juicy Grape", java.lang.Float.intBitsToFloat(0xfed01060))
    LIST += java.lang.Float.intBitsToFloat(0xfed01060)
    NAMED.put("Blacklight Glow", java.lang.Float.intBitsToFloat(0xfed23287))
    LIST += java.lang.Float.intBitsToFloat(0xfed23287)
    NAMED.put("Purple Freesia", java.lang.Float.intBitsToFloat(0xfeff419c))
    LIST += java.lang.Float.intBitsToFloat(0xfeff419c)
    NAMED.put("Thin Amethyst", java.lang.Float.intBitsToFloat(0xfeff007f))
    LIST += java.lang.Float.intBitsToFloat(0xfeff007f)
    NAMED.put("Orchid", java.lang.Float.intBitsToFloat(0xfeff62bd))
    LIST += java.lang.Float.intBitsToFloat(0xfeff62bd)
    NAMED.put("Lavender", java.lang.Float.intBitsToFloat(0xfeff91b9))
    LIST += java.lang.Float.intBitsToFloat(0xfeff91b9)
    NAMED.put("Lilac", java.lang.Float.intBitsToFloat(0xfeffa5d7))
    LIST += java.lang.Float.intBitsToFloat(0xfeffa5d7)
    NAMED.put("Soap", java.lang.Float.intBitsToFloat(0xfefac3d7))
    LIST += java.lang.Float.intBitsToFloat(0xfefac3d7)
    NAMED.put("Pink Tutu", java.lang.Float.intBitsToFloat(0xfefcc6f8))
    LIST += java.lang.Float.intBitsToFloat(0xfefcc6f8)
    NAMED.put("Thistle", java.lang.Float.intBitsToFloat(0xfeff73e6))
    LIST += java.lang.Float.intBitsToFloat(0xfeff73e6)
    NAMED.put("Heliotrope", java.lang.Float.intBitsToFloat(0xfeff52ff))
    LIST += java.lang.Float.intBitsToFloat(0xfeff52ff)
    NAMED.put("Purple", java.lang.Float.intBitsToFloat(0xfee020da))
    LIST += java.lang.Float.intBitsToFloat(0xfee020da)
    NAMED.put("Wisteria", java.lang.Float.intBitsToFloat(0xfeff29bd))
    LIST += java.lang.Float.intBitsToFloat(0xfeff29bd)
    NAMED.put("Medium Plum", java.lang.Float.intBitsToFloat(0xfec510bd))
    LIST += java.lang.Float.intBitsToFloat(0xfec510bd)
    NAMED.put("Violet", java.lang.Float.intBitsToFloat(0xfebe148c))
    LIST += java.lang.Float.intBitsToFloat(0xfebe148c)
    NAMED.put("Grape Lollipop", java.lang.Float.intBitsToFloat(0xfe7b185a))
    LIST += java.lang.Float.intBitsToFloat(0xfe7b185a)
    NAMED.put("Mulberry", java.lang.Float.intBitsToFloat(0xfe641464))
    LIST += java.lang.Float.intBitsToFloat(0xfe641464)
    NAMED.put("Grape Soda", java.lang.Float.intBitsToFloat(0xfe620041))
    LIST += java.lang.Float.intBitsToFloat(0xfe620041)
    NAMED.put("Eggplant", java.lang.Float.intBitsToFloat(0xfe460a32))
    LIST += java.lang.Float.intBitsToFloat(0xfe460a32)
    NAMED.put("Cherry Syrup", java.lang.Float.intBitsToFloat(0xfe371955))
    LIST += java.lang.Float.intBitsToFloat(0xfe371955)
    NAMED.put("Plum Juice", java.lang.Float.intBitsToFloat(0xfe8219a0))
    LIST += java.lang.Float.intBitsToFloat(0xfe8219a0)
    NAMED.put("Fruit Punch", java.lang.Float.intBitsToFloat(0xfe7800c8))
    LIST += java.lang.Float.intBitsToFloat(0xfe7800c8)
    NAMED.put("Bubble Gum", java.lang.Float.intBitsToFloat(0xfebf50ff))
    LIST += java.lang.Float.intBitsToFloat(0xfebf50ff)
    NAMED.put("Pink Lemonade", java.lang.Float.intBitsToFloat(0xfec56aff))
    LIST += java.lang.Float.intBitsToFloat(0xfec56aff)
    NAMED.put("Shrimp", java.lang.Float.intBitsToFloat(0xfeb9a0fa))
    LIST += java.lang.Float.intBitsToFloat(0xfeb9a0fa)
    NAMED.put("Flamingo", java.lang.Float.intBitsToFloat(0xfe8c3afc))
    LIST += java.lang.Float.intBitsToFloat(0xfe8c3afc)
    NAMED.put("Rose", java.lang.Float.intBitsToFloat(0xfe781ee6))
    LIST += java.lang.Float.intBitsToFloat(0xfe781ee6)
    NAMED.put("Carmine", java.lang.Float.intBitsToFloat(0xfe3910bd))
    LIST += java.lang.Float.intBitsToFloat(0xfe3910bd)
    NAMED.put("Bologna", java.lang.Float.intBitsToFloat(0xfe4d3498))
    LIST += java.lang.Float.intBitsToFloat(0xfe4d3498)
    NAMED.put("Raspberry", java.lang.Float.intBitsToFloat(0xfe371491))
    LIST += java.lang.Float.intBitsToFloat(0xfe371491)
  }

  /** Appends standard RGBA Color instances to the map in [[sge.graphics.Colors]], using the names in [[NAMED]] (which are "Title Cased" instead of "ALL UPPER CASE"). This doesn't need any changes to
    * be made to Colors in order for it to be compatible; just remember that the colors originally in Colors use "UPPER CASE" and these use "Title Case".
    */
  def appendToKnownColors(): Unit =
    for ((key, value) <- NAMED)
      sge.graphics.Colors.put(key, ColorTools.toColor(new sge.graphics.Color(), value))
}
