/*
 * Ported from gdx-controllers - https://github.com/libgdx/gdx-controllers
 * Licensed under the Apache License, Version 2.0
 *
 * Scala port copyright 2025-2026 Mateusz Kubuszok
 *
 * Covenant: full-port
 * Covenant-baseline-spec-pass: 0
 * Covenant-baseline-loc: 69
 * Covenant-baseline-methods: Controllers,addListener,clearListeners,current,dispose,getControllers,getListeners,getManager,initialize,manager,removeListener
 * Covenant-source-reference: com/badlogic/gdx/controllers/Controllers.java
 * Covenant-verified: 2026-04-19
 *
 * upstream-commit: 124b68125c7ef9c552085865379f77e8bee2ae3b
 */
package sge
package controllers

import sge.utils.Nullable

/** Provides access to connected [[Controller]] instances. Query the available controllers via [[getControllers]], add and remove global [[ControllerListener]] instances via [[addListener]] and
  * [[removeListener]]. The listeners will be invoked on the rendering thread. The global listeners will be invoked for all events generated by all controllers. Polling a Controller can be done by
  * invoking one of its getter methods.
  *
  * In SGE, the [[ControllerManager]] is provided via explicit initialization rather than via reflection-based discovery.
  *
  * @author
  *   Nathan Sweet
  */
object Controllers {

  private var manager: Nullable[ControllerManager] = Nullable.empty

  /** Initializes the controller subsystem with the given manager implementation. This should be called once during application startup.
    */
  def initialize(controllerManager: ControllerManager): Unit =
    manager = Nullable(controllerManager)

  /** Shuts down the controller subsystem and removes the manager. */
  def dispose(): Unit =
    manager = Nullable.empty

  /** Returns a sequence of connected [[Controller]] instances. This method should only be called on the rendering thread.
    *
    * @return
    *   the connected controllers
    */
  def getControllers: Seq[Controller] =
    getManager.getControllers

  /** @return
    *   the controller the player used most recently. This might return [[Nullable.empty]] if there is no controller connected or the last used controller disconnected.
    */
  def current: Nullable[Controller] =
    getManager.currentController

  /** Add a global [[ControllerListener]] that can react to events from all [[Controller]] instances. The listener will be invoked on the rendering thread.
    */
  def addListener(listener: ControllerListener): Unit =
    getManager.addListener(listener)

  /** Removes a global [[ControllerListener]]. The method must be called on the rendering thread. */
  def removeListener(listener: ControllerListener): Unit =
    getManager.removeListener(listener)

  /** Removes every global [[ControllerListener]] previously added. */
  def clearListeners(): Unit =
    getManager.clearListeners()

  /** Returns all listeners currently registered. Modifying the returned sequence will result in undefined behaviour. */
  def getListeners: Seq[ControllerListener] =
    getManager.getListeners

  private def getManager: ControllerManager =
    manager.getOrElse {
      throw IllegalStateException("Controllers not initialized. Call Controllers.initialize() first.")
    }
}
