/*
 * Ported from gdx-controllers - https://github.com/libgdx/gdx-controllers
 * Licensed under the Apache License, Version 2.0
 *
 * Scala port copyright 2025-2026 Mateusz Kubuszok
 *
 * Covenant: full-port
 * Covenant-baseline-spec-pass: 0
 * Covenant-baseline-loc: 69
 * Covenant-baseline-methods: Controllers,addListener,clearListeners,current,dispose,getControllers,getListeners,getManager,initialize,manager,removeListener
 * Covenant-source-reference: com/badlogic/gdx/controllers/Controllers.java
 * Covenant-verified: 2026-04-19
 *
 * upstream-commit: 124b68125c7ef9c552085865379f77e8bee2ae3b
 */
package sge
package controllers

import lowlevel.Nullable
import scala.collection.mutable.ArrayBuffer

/** Provides access to connected [[Controller]] instances. Query the available controllers via [[getControllers]], add and remove global [[ControllerListener]] instances via [[addListener]] and
  * [[removeListener]]. The listeners will be invoked on the rendering thread. The global listeners will be invoked for all events generated by all controllers. Polling a Controller can be done by
  * invoking one of its getter methods.
  *
  * In SGE, the [[ControllerManager]] is provided via explicit initialization rather than via reflection-based discovery.
  *
  * ==Auto-poll wiring (SGE-original)==
  *
  * gdx-controllers is event/callback driven; SGE is polling-based. To keep the LibGDX promise that [[getControllers]] just works after a short bootstrap, [[initialize]] registers a per-frame hook
  * that calls [[ControllerManager.poll]] each frame (tracked in [[registeredFrameHooks]] so hook-only tests can drive frames). To make that hook actually fire in a running application, call
  * [[installAutoPoll]] with the [[Sge]] context in scope; it registers the same per-frame poll into the running [[Application]] via [[Application.registerFrameHook]], so every concrete platform main
  * loop drives controller polling automatically (no manual per-frame `poll()` from the game). [[dispose]] removes the hook again — from both the local list and the host [[Application]] — so repeated
  * initialize/dispose cycles do not leak hooks.
  *
  * ===One-line-ish bootstrap===
  *
  * Real applications wire the platform backend and the manager, then install the auto-poll into the running app. Each platform exposes the matching `init()` so the platform
  * `pollControllerImpl`/`getConnectedControllersImpl` is installed (the issue's "zero call sites" complaint):
  * {{{
  *   // Desktop JVM:    GlfwControllerJvmInit.init();    Controllers.initialize(DefaultControllerManager(GlfwControllerBackend()))
  *   // Desktop Native: GlfwControllerNativeInit.init();  Controllers.initialize(DefaultControllerManager(GlfwControllerBackend()))
  *   // Browser:        BrowserControllerInit.init();     Controllers.initialize(DefaultControllerManager(BrowserControllerBackend()))
  *   // Android:        AndroidControllerInit.init();      Controllers.initialize(DefaultControllerManager(AndroidControllerBackend()))
  *
  *   Controllers.installAutoPoll() // (using Sge) — registers the per-frame poll into the running app
  * }}}
  * With an `Sge` `given` in scope (the application context), [[installAutoPoll]] makes polling run automatically every frame. [[initialize]] alone does NOT auto-wire the running app; it only tracks
  * the hook locally for manual/test frame driving.
  *
  * @author
  *   Nathan Sweet
  */
object Controllers {

  private var manager: Nullable[ControllerManager] = Nullable.empty

  /** The per-frame poll hooks this facade has registered. Each calls the current [[ControllerManager.poll]]. Exposed so wiring/tests can drive frames; modifying the returned sequence has no effect on
    * registration.
    */
  private val frameHooks: ArrayBuffer[() => Unit] = ArrayBuffer.empty

  /** The [[FrameHookHost]] (the running [[Application]], if any) the auto-poll hook was installed into via [[installAutoPoll]], so [[dispose]] can remove it again. */
  private var hostApplication: Nullable[FrameHookHost] = Nullable.empty

  /** The hook instance registered into [[hostApplication]] (if any). Tracked separately from [[frameHooks]] because the local list is for manual/test frame driving, whereas this is the live
    * registration in the running application that [[dispose]] must remove to avoid leaks.
    */
  private var appFrameHook: Nullable[() => Unit] = Nullable.empty

  /** Returns the per-frame poll hooks [[Controllers]] has registered. After [[initialize]] this is non-empty; after [[dispose]] it is empty. Invoking a hook calls the current manager's
    * [[ControllerManager.poll]]. SGE-original (no LibGDX equivalent).
    */
  def registeredFrameHooks: Seq[() => Unit] = frameHooks.toSeq

  /** Initializes the controller subsystem with the given manager implementation. This should be called once during application startup.
    *
    * Registers a per-frame hook that calls [[ControllerManager.poll]] each frame, tracked in [[registeredFrameHooks]] so frames can be driven manually (e.g. unit tests). This method is intentionally
    * app-less: it does NOT register the hook into a running [[Application]]. To make the hook fire automatically every frame in a real application, call [[installAutoPoll]] with the [[Sge]] context
    * in scope after initializing.
    *
    * @param controllerManager
    *   the platform controller manager to drive
    */
  def initialize(controllerManager: ControllerManager): Unit = {
    // Remove any previously registered hook before re-wiring (idempotent re-init).
    removeFrameHooks()
    manager = Nullable(controllerManager)
    val hook: () => Unit = () => poll()
    frameHooks += hook
  }

  /** Installs the per-frame poll into the running [[Application]] so controller polling happens automatically every frame, with no manual `poll()` from the game.
    *
    * Resolves the in-scope `given Sge` directly (standard given resolution) and registers a hook calling [[poll]] into `sge.application` via [[Application.registerFrameHook]]. The registration is
    * tracked so [[dispose]] removes it again, leaving no leaked hooks across initialize/install/dispose cycles. Call this once after [[initialize]], during application startup.
    *
    * Calling [[installAutoPoll]] more than once without an intervening [[dispose]] is idempotent: the previously installed app hook is removed before the new one is registered, so the running
    * application ends up with exactly one controller poll hook.
    *
    * @param sge
    *   the running application context (resolved from an in-scope `given Sge`)
    */
  def installAutoPoll()(using sge: Sge): Unit =
    installAutoPollInto(sge.application)

  /** Registers the per-frame poll into the given [[FrameHookHost]] (the running [[Application]]), tracking the registration so [[dispose]] removes it. Removes any previously installed app hook first
    * (idempotent). This is the reliable seam behind [[installAutoPoll]]: it takes the host directly, so it is driven the same way the running main loop drives it (via
    * [[FrameHookHost.runFrameHooks]]).
    *
    * @param host
    *   the running frame-hook host to register the per-frame poll into
    */
  private[controllers] def installAutoPollInto(host: FrameHookHost): Unit = {
    // Remove any previously installed app hook so re-install does not leak hooks.
    removeAppFrameHook()
    val hook: () => Unit = () => poll()
    appFrameHook = Nullable(hook)
    host.registerFrameHook(hook)
    hostApplication = Nullable(host)
  }

  /** Shuts down the controller subsystem and removes the manager. Also removes the auto-registered per-frame poll hook from the [[Application]] (if any), so repeated initialize/dispose cycles do not
    * leak hooks.
    */
  def dispose(): Unit = {
    removeFrameHooks()
    manager = Nullable.empty
  }

  /** Removes the installed app hook (if any) from the host application and clears the local hook list. */
  private def removeFrameHooks(): Unit = {
    removeAppFrameHook()
    frameHooks.clear()
  }

  /** Removes the per-frame poll hook installed into the host [[Application]] (if any) and clears the tracking, so no hook leaks across installs/disposals. */
  private def removeAppFrameHook(): Unit = {
    for {
      app <- hostApplication
      hook <- appFrameHook
    } app.removeFrameHook(hook)
    hostApplication = Nullable.empty
    appFrameHook = Nullable.empty
  }

  /** Polls the current [[ControllerManager]] once, dispatching connect/disconnect/button/axis events. This is the facade the auto-registered frame hook drives; games may also call it manually.
    */
  def poll(): Unit =
    getManager.poll()

  /** Returns a sequence of connected [[Controller]] instances. This method should only be called on the rendering thread.
    *
    * @return
    *   the connected controllers
    */
  def getControllers: Seq[Controller] =
    getManager.getControllers

  /** @return
    *   the controller the player used most recently. This might return [[Nullable.empty]] if there is no controller connected or the last used controller disconnected.
    */
  def current: Nullable[Controller] =
    getManager.currentController

  /** Add a global [[ControllerListener]] that can react to events from all [[Controller]] instances. The listener will be invoked on the rendering thread.
    */
  def addListener(listener: ControllerListener): Unit =
    getManager.addListener(listener)

  /** Removes a global [[ControllerListener]]. The method must be called on the rendering thread. */
  def removeListener(listener: ControllerListener): Unit =
    getManager.removeListener(listener)

  /** Removes every global [[ControllerListener]] previously added. */
  def clearListeners(): Unit =
    getManager.clearListeners()

  /** Returns all listeners currently registered. Modifying the returned sequence will result in undefined behaviour. */
  def getListeners: Seq[ControllerListener] =
    getManager.getListeners

  private def getManager: ControllerManager =
    manager.getOrElse {
      throw IllegalStateException("Controllers not initialized. Call Controllers.initialize() first.")
    }
}
