/*
 * Ported from colorful-gdx - https://github.com/tommyettinger/colorful-gdx
 * Original authors: Tommy Ettinger
 * Licensed under the Apache License, Version 2.0
 *
 * Scala port copyright 2025-2026 Mateusz Kubuszok
 *
 * Covenant: full-port
 * Covenant-baseline-spec-pass: 0
 * Covenant-baseline-loc: 811
 * Covenant-baseline-methods: ABSINTHE,AIR_FORCE_BLUE,AMAZONITE,ANGEL_WING,APPLE_GREEN,APRICOT,AQUAMARINE,ARMY_GREEN,ARTICHOKE,ASPARAGUS,AVOCADO,BANANA_PUDDING,BEIGE,BLACK,BLACKLIGHT_GLOW,BLUE,BLUEBERRY,BLUE_EYE,BLUE_SMOKE,BLUE_STEEL,BOLOGNA,BOYSENBERRY,BRICK,BRIGHT_RED,BRONZE_SKIN_1,BRONZE_SKIN_2,BRONZE_SKIN_3,BRONZE_SKIN_4,BROWN_VELVET,BUBBLE,BUBBLEGUM_PINK,BUBBLE_GUM,BURNT_YELLOW,CALM_SKY,CARMINE,CEDAR_WOOD,CELADON,CELERY,CHARTREUSE,CHERRY_SYRUP,CHINCHILLA,CHIPPED_GRANITE,CLOUD,COAL_BLACK,COLD_IRON,CORNFLOWER_BLUE,CORN_SILK,COTTON_CANDY,CREAM,CRICKET,CYAN,DARK_GRAY,DARK_PINE,DARK_SKIN_1,DARK_SKIN_2,DARK_SKIN_3,DARK_TEAL,DEEP_JUNGLE,DEEP_PURPLE,DEEP_TEAL,DENIM_BLUE,DESERT_RAIN,DRAB_GREEN,DREARY_BLUE,DRIED_SAGE,DRIFTWOOD,DRY_BRUSH,DRY_PEPPER,DULL_AZURE,DULL_GREEN,DULL_VIOLET,DUN,DUSTY_GRAPE,DUSTY_GREEN,DUSTY_PINK,DUST_BUNNY,EARWAX,EGGPLANT,ELECTRIC_BLUE,EMBERS,EMERALD,EMINENCE,EUCALYPTUS,FADED_BLUE,FAWN,FEATHER_DOWN,FERN_GREEN,FLAMINGO,FLORAL_FOAM,FOREST_GLEN,FROG_GREEN,FRUIT_PUNCH,GARTER_SNAKE,GRAPE_LOLLIPOP,GRAPE_SODA,GRAPHITE,GRAY,GRAY_GREEN,GREEN,GREYHOUND,HAM,HELIOTROPE,HIDDEN_BLUE,HONEYDEW,HOSPITAL_GREEN,HOT_SAUCE,HUNTER_GREEN,INDIGO,INFECTION,IOLITE,IRIS,IRON,IVY_GREEN,JADE,JUICY_GRAPE,KELLY_GREEN,KOA,KYANITE,LAVENDER,LEAD,LIGHT_GRAY,LIGHT_SKIN_1,LIGHT_SKIN_2,LIGHT_SKIN_3,LIGHT_SKIN_4,LIGHT_SKIN_5,LIGHT_SKIN_6,LIGHT_SKIN_7,LIGHT_SKIN_8,LIGHT_SKIN_9,LILAC,LIST,LIZARD_SCALES,LURID_RED,MAGENTA,MAIDENHAIR_FERN,MALACHITE,MARSH,MAUVE,MEDIUM_PLUM,MEDIUM_TEAL,MILD_VIOLET,MINT_GREEN,MOSS_GREEN,MULBERRY,MUMMY_BROWN,MURK,MUSH,NAMED,NAVY_BLUE,NIGHTSHADE,NINJA,OCEAN_BLUE,OCHRE,OLD_ROSE,OLIVE_GREEN,OLIVE_OIL,ORANGE,ORCHID,PASTEL_SKY,PATINA,PEACH,PEAT_BOG,PEA_SOUP,PENCIL_YELLOW,PERIWINKLE,PINE_GREEN,PINK_LEMONADE,PINK_SKIN_1,PINK_SKIN_2,PINK_SKIN_3,PINK_SKIN_4,PINK_TUTU,PINK_VIOLET,PISTACHIO,PLATINUM,PLUM_JUICE,POLISHED_SAPPHIRE,PORK_CHOP,POWDER_BLUE,PRASE,PRUNE,PRUSSIAN_BLUE,PUCE,PURPLE,PURPLE_FREESIA,PUTTY,Palette,RASPBERRY,RAW_MEAT,RED,REDWOOD,REFRESHING_MIST,RIPE_PLUM,RIPPED_DENIM,ROBIN_EGG_BLUE,ROSE,ROSEATE_SPOONBILL,ROUGH_SAPPHIRE,ROYAL_BLUE,ROYAL_VIOLET,SAFFRON,SAGE_GREEN,SALMON,SCRIBE_INK,SEAFOAM,SEAL_BROWN,SEAWATER,SHADOW,SHARP_AZURE,SHINING_SKY,SHRIMP,SIENNA,SILVER,SILVER_GREEN,SILVER_PINK,SLATE_GRAY,SLOW_CREEK,SMOG,SOAP,SOFT_TEAL,SPACE_BLUE,SPEARMINT,SPRING_GREEN,STEAM,STRAW,STRONG_CYAN,STYGIAN_BLUE,SUBTLETY,SUDS,TAN,TARNISH,TAUPE,TAXICAB_YELLOW,TEA_ROSE,THICK_AMETHYST,THIN_AMETHYST,THISTLE,THULIAN_PINK,TRANSPARENT,TROPIC_MIST,TURQUOISE,TWILIGHT_CLOUD,TYRIAN_PURPLE,UMBER,VAPOR,VARISCITE,VARNISH,VIOLET,VIOLET_CUSHIONS,VIRIDIAN,WATERCOLOR_BLACK,WATERCOLOR_GRAY,WET_STONE,WHITE,WISTERIA,WOODLANDS,YELLOW,ZUCCHINI,appendToKnownColors,editKnownColors
 * Covenant-source-reference: com/github/tommyettinger/colorful/ycwcm/Palette.java
 * Covenant-verified: 2026-04-19
 *
 * upstream-commit: e4a5fd960eef746ca5aa826063432fb79666d74f
 */
package sge
package colorful
package ycwcm

import scala.collection.mutable

/** A palette of predefined colors as packed YCWCM floats, the kind [[ColorTools]] works with. You can access colors by their constant name, such as `OCEAN_BLUE`, by the [[NAMED]] map using
  * `NAMED.getOrElse("Ocean Blue", 0f)`, or by index in the list called [[LIST]].
  */
object Palette {

  /** Maps color names to packed float colors. */
  val NAMED: mutable.HashMap[String, Float] = mutable.HashMap.empty[String, Float]

  /** Lists packed float color values, in declaration order. */
  val LIST: mutable.ArrayBuffer[Float] = mutable.ArrayBuffer.empty[Float]

  val TRANSPARENT:       Float = java.lang.Float.intBitsToFloat(0x7f7f00)
  val BLACK:             Float = java.lang.Float.intBitsToFloat(0xfe7f7f00)
  val COAL_BLACK:        Float = java.lang.Float.intBitsToFloat(0xfe7f7f13)
  val SHADOW:            Float = java.lang.Float.intBitsToFloat(0xfe7f7f25)
  val GRAPHITE:          Float = java.lang.Float.intBitsToFloat(0xfe7f7f37)
  val DARK_GRAY:         Float = java.lang.Float.intBitsToFloat(0xfe7f7f49)
  val LEAD:              Float = java.lang.Float.intBitsToFloat(0xfe7f7f5b)
  val IRON:              Float = java.lang.Float.intBitsToFloat(0xfe7f7f6e)
  val GRAY:              Float = java.lang.Float.intBitsToFloat(0xfe7f7f80)
  val CHINCHILLA:        Float = java.lang.Float.intBitsToFloat(0xfe7f7f92)
  val GREYHOUND:         Float = java.lang.Float.intBitsToFloat(0xfe7f7fa4)
  val SILVER:            Float = java.lang.Float.intBitsToFloat(0xfe7f7fb6)
  val LIGHT_GRAY:        Float = java.lang.Float.intBitsToFloat(0xfe7f7fc9)
  val PLATINUM:          Float = java.lang.Float.intBitsToFloat(0xfe7f7fdb)
  val CLOUD:             Float = java.lang.Float.intBitsToFloat(0xfe7f7fed)
  val WHITE:             Float = java.lang.Float.intBitsToFloat(0xfe7f7fff)
  val SEAWATER:          Float = java.lang.Float.intBitsToFloat(0xfe7f404f)
  val HOSPITAL_GREEN:    Float = java.lang.Float.intBitsToFloat(0xfe7f3f8f)
  val CYAN:              Float = java.lang.Float.intBitsToFloat(0xfe7f009f)
  val BUBBLE:            Float = java.lang.Float.intBitsToFloat(0xfe7f5fe7)
  val PERIWINKLE:        Float = java.lang.Float.intBitsToFloat(0xfe404090)
  val BLUE:              Float = java.lang.Float.intBitsToFloat(0xfe00001f)
  val FADED_BLUE:        Float = java.lang.Float.intBitsToFloat(0xfe3f3f4f)
  val OCEAN_BLUE:        Float = java.lang.Float.intBitsToFloat(0xfe40400f)
  val STYGIAN_BLUE:      Float = java.lang.Float.intBitsToFloat(0xfe5f5f17)
  val DEEP_PURPLE:       Float = java.lang.Float.intBitsToFloat(0xfe407f3f)
  val TYRIAN_PURPLE:     Float = java.lang.Float.intBitsToFloat(0xfe3f7f7f)
  val MAGENTA:           Float = java.lang.Float.intBitsToFloat(0xfe057f7a)
  val BUBBLEGUM_PINK:    Float = java.lang.Float.intBitsToFloat(0xfe407ebf)
  val PORK_CHOP:         Float = java.lang.Float.intBitsToFloat(0xfe7a99d9)
  val RAW_MEAT:          Float = java.lang.Float.intBitsToFloat(0xfe7fbeb0)
  val RED:               Float = java.lang.Float.intBitsToFloat(0xfe7fff5f)
  val PUTTY:             Float = java.lang.Float.intBitsToFloat(0xfe7fbf6f)
  val SIENNA:            Float = java.lang.Float.intBitsToFloat(0xfe7fbf2f)
  val SEAL_BROWN:        Float = java.lang.Float.intBitsToFloat(0xfe7fa02c)
  val MUMMY_BROWN:       Float = java.lang.Float.intBitsToFloat(0xfe9fbf4f)
  val FAWN:              Float = java.lang.Float.intBitsToFloat(0xfe9fbf8f)
  val ORANGE:            Float = java.lang.Float.intBitsToFloat(0xfebfff9f)
  val PEACH:             Float = java.lang.Float.intBitsToFloat(0xfe9ebecf)
  val CREAM:             Float = java.lang.Float.intBitsToFloat(0xfe9f9ff7)
  val YELLOW:            Float = java.lang.Float.intBitsToFloat(0xfeffffdf)
  val EARWAX:            Float = java.lang.Float.intBitsToFloat(0xfebfbfaf)
  val UMBER:             Float = java.lang.Float.intBitsToFloat(0xfebfbf6f)
  val IVY_GREEN:         Float = java.lang.Float.intBitsToFloat(0xfebf7f3f)
  val JADE:              Float = java.lang.Float.intBitsToFloat(0xfebf7f7f)
  val GREEN:             Float = java.lang.Float.intBitsToFloat(0xfeff7f7f)
  val CELADON:           Float = java.lang.Float.intBitsToFloat(0xfea77fd7)
  val PUCE:              Float = java.lang.Float.intBitsToFloat(0xfe777db6)
  val BEIGE:             Float = java.lang.Float.intBitsToFloat(0xfe90a0b2)
  val WET_STONE:         Float = java.lang.Float.intBitsToFloat(0xfe878aa0)
  val SLOW_CREEK:        Float = java.lang.Float.intBitsToFloat(0xfe7f748b)
  val SLATE_GRAY:        Float = java.lang.Float.intBitsToFloat(0xfe7d737b)
  val LIGHT_SKIN_1:      Float = java.lang.Float.intBitsToFloat(0xfe868e72)
  val LIGHT_SKIN_2:      Float = java.lang.Float.intBitsToFloat(0xfe84a07c)
  val LIGHT_SKIN_3:      Float = java.lang.Float.intBitsToFloat(0xfe82a692)
  val LIGHT_SKIN_4:      Float = java.lang.Float.intBitsToFloat(0xfe8aada1)
  val LIGHT_SKIN_5:      Float = java.lang.Float.intBitsToFloat(0xfe8eb1b1)
  val LIGHT_SKIN_6:      Float = java.lang.Float.intBitsToFloat(0xfe8eafbe)
  val LIGHT_SKIN_7:      Float = java.lang.Float.intBitsToFloat(0xfe8eaccb)
  val LIGHT_SKIN_8:      Float = java.lang.Float.intBitsToFloat(0xfe8ca3d6)
  val LIGHT_SKIN_9:      Float = java.lang.Float.intBitsToFloat(0xfe8791e6)
  val DARK_SKIN_1:       Float = java.lang.Float.intBitsToFloat(0xfe7f8d45)
  val DARK_SKIN_2:       Float = java.lang.Float.intBitsToFloat(0xfe829b53)
  val DARK_SKIN_3:       Float = java.lang.Float.intBitsToFloat(0xfe7f9c6a)
  val PINK_SKIN_1:       Float = java.lang.Float.intBitsToFloat(0xfe7f9b88)
  val PINK_SKIN_2:       Float = java.lang.Float.intBitsToFloat(0xfe7f9ba4)
  val PINK_SKIN_3:       Float = java.lang.Float.intBitsToFloat(0xfe7f9bc0)
  val PINK_SKIN_4:       Float = java.lang.Float.intBitsToFloat(0xfe7b8ee1)
  val BRONZE_SKIN_4:     Float = java.lang.Float.intBitsToFloat(0xfe8d9bce)
  val BRONZE_SKIN_3:     Float = java.lang.Float.intBitsToFloat(0xfe95a8a6)
  val BRONZE_SKIN_2:     Float = java.lang.Float.intBitsToFloat(0xfe8d9b7a)
  val BRONZE_SKIN_1:     Float = java.lang.Float.intBitsToFloat(0xfe8d9b5e)
  val TAUPE:             Float = java.lang.Float.intBitsToFloat(0xfe868d30)
  val DRAB_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe8e8e3d)
  val LIZARD_SCALES:     Float = java.lang.Float.intBitsToFloat(0xfe9b9b6c)
  val CRICKET:           Float = java.lang.Float.intBitsToFloat(0xfe9b9b88)
  val OLIVE_OIL:         Float = java.lang.Float.intBitsToFloat(0xfea6a698)
  val DUN:               Float = java.lang.Float.intBitsToFloat(0xfea1a1ac)
  val CORN_SILK:         Float = java.lang.Float.intBitsToFloat(0xfe9b9bc0)
  val TAN:               Float = java.lang.Float.intBitsToFloat(0xfe9797d4)
  val STRAW:             Float = java.lang.Float.intBitsToFloat(0xfe9292e8)
  val HONEYDEW:          Float = java.lang.Float.intBitsToFloat(0xfe9b8dd1)
  val TARNISH:           Float = java.lang.Float.intBitsToFloat(0xfe9b8db5)
  val PEA_SOUP:          Float = java.lang.Float.intBitsToFloat(0xfeb49c9e)
  val MARSH:             Float = java.lang.Float.intBitsToFloat(0xfe9b8d7d)
  val ASPARAGUS:         Float = java.lang.Float.intBitsToFloat(0xfe9f8c67)
  val PEAT_BOG:          Float = java.lang.Float.intBitsToFloat(0xfe8e8948)
  val DEEP_JUNGLE:       Float = java.lang.Float.intBitsToFloat(0xfe87841a)
  val PINE_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe8c753c)
  val OLIVE_GREEN:       Float = java.lang.Float.intBitsToFloat(0xfe8d7f49)
  val GRAY_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe897f5a)
  val MAIDENHAIR_FERN:   Float = java.lang.Float.intBitsToFloat(0xfe947858)
  val KELLY_GREEN:       Float = java.lang.Float.intBitsToFloat(0xfe9b7f73)
  val DUSTY_GREEN:       Float = java.lang.Float.intBitsToFloat(0xfe9b7f8f)
  val GARTER_SNAKE:      Float = java.lang.Float.intBitsToFloat(0xfe9e7095)
  val SILVER_GREEN:      Float = java.lang.Float.intBitsToFloat(0xfe9b7fab)
  val PISTACHIO:         Float = java.lang.Float.intBitsToFloat(0xfe9a7fbd)
  val ANGEL_WING:        Float = java.lang.Float.intBitsToFloat(0xfe7e73ef)
  val SAGE_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe9174d3)
  val DRIED_SAGE:        Float = java.lang.Float.intBitsToFloat(0xfe8e72ca)
  val ARTICHOKE:         Float = java.lang.Float.intBitsToFloat(0xfe927c9e)
  val VIRIDIAN:          Float = java.lang.Float.intBitsToFloat(0xfe8e7868)
  val FLORAL_FOAM:       Float = java.lang.Float.intBitsToFloat(0xfe916442)
  val HUNTER_GREEN:      Float = java.lang.Float.intBitsToFloat(0xfe847d26)
  val DARK_TEAL:         Float = java.lang.Float.intBitsToFloat(0xfe7d6e36)
  val KYANITE:           Float = java.lang.Float.intBitsToFloat(0xfe7f635e)
  val SPEARMINT:         Float = java.lang.Float.intBitsToFloat(0xfe7f5c90)
  val AMAZONITE:         Float = java.lang.Float.intBitsToFloat(0xfe7f63b2)
  val PASTEL_SKY:        Float = java.lang.Float.intBitsToFloat(0xfe7f63ce)
  val AQUAMARINE:        Float = java.lang.Float.intBitsToFloat(0xfe7f6ae1)
  val DUST_BUNNY:        Float = java.lang.Float.intBitsToFloat(0xfe7066ce)
  val PATINA:            Float = java.lang.Float.intBitsToFloat(0xfe7163c0)
  val CHIPPED_GRANITE:   Float = java.lang.Float.intBitsToFloat(0xfe6e65b7)
  val BLUE_SMOKE:        Float = java.lang.Float.intBitsToFloat(0xfe7163a4)
  val AIR_FORCE_BLUE:    Float = java.lang.Float.intBitsToFloat(0xfe634781)
  val COLD_IRON:         Float = java.lang.Float.intBitsToFloat(0xfe71636c)
  val DREARY_BLUE:       Float = java.lang.Float.intBitsToFloat(0xfe716350)
  val MURK:              Float = java.lang.Float.intBitsToFloat(0xfe757017)
  val NINJA:             Float = java.lang.Float.intBitsToFloat(0xfe717122)
  val WATERCOLOR_BLACK:  Float = java.lang.Float.intBitsToFloat(0xfe71713e)
  val IOLITE:            Float = java.lang.Float.intBitsToFloat(0xfe6a6a4e)
  val BOYSENBERRY:       Float = java.lang.Float.intBitsToFloat(0xfe63635e)
  val WATERCOLOR_GRAY:   Float = java.lang.Float.intBitsToFloat(0xfe616477)
  val BLUE_STEEL:        Float = java.lang.Float.intBitsToFloat(0xfe555580)
  val TWILIGHT_CLOUD:    Float = java.lang.Float.intBitsToFloat(0xfe636396)
  val SMOG:              Float = java.lang.Float.intBitsToFloat(0xfe6363b2)
  val TROPIC_MIST:       Float = java.lang.Float.intBitsToFloat(0xfe706bda)
  val FEATHER_DOWN:      Float = java.lang.Float.intBitsToFloat(0xfe7171e6)
  val MILD_VIOLET:       Float = java.lang.Float.intBitsToFloat(0xfe6371a0)
  val VIOLET_CUSHIONS:   Float = java.lang.Float.intBitsToFloat(0xfe47637a)
  val DULL_VIOLET:       Float = java.lang.Float.intBitsToFloat(0xfe637168)
  val ROYAL_VIOLET:      Float = java.lang.Float.intBitsToFloat(0xfe63714c)
  val EMINENCE:          Float = java.lang.Float.intBitsToFloat(0xfe737f2f)
  val PRUNE:             Float = java.lang.Float.intBitsToFloat(0xfe757f3c)
  val DUSTY_GRAPE:       Float = java.lang.Float.intBitsToFloat(0xfe667f59)
  val PINK_VIOLET:       Float = java.lang.Float.intBitsToFloat(0xfe637f73)
  val RIPE_PLUM:         Float = java.lang.Float.intBitsToFloat(0xfe557f81)
  val MAUVE:             Float = java.lang.Float.intBitsToFloat(0xfe637f8f)
  val HAM:               Float = java.lang.Float.intBitsToFloat(0xfe6584ca)
  val COTTON_CANDY:      Float = java.lang.Float.intBitsToFloat(0xfe7384ec)
  val SILVER_PINK:       Float = java.lang.Float.intBitsToFloat(0xfe717fd5)
  val TEA_ROSE:          Float = java.lang.Float.intBitsToFloat(0xfe7387cb)
  val OLD_ROSE:          Float = java.lang.Float.intBitsToFloat(0xfe708cb8)
  val DUSTY_PINK:        Float = java.lang.Float.intBitsToFloat(0xfe6a86a9)
  val ROSEATE_SPOONBILL: Float = java.lang.Float.intBitsToFloat(0xfe6e939d)
  val THULIAN_PINK:      Float = java.lang.Float.intBitsToFloat(0xfe649888)
  val BROWN_VELVET:      Float = java.lang.Float.intBitsToFloat(0xfe788937)
  val NIGHTSHADE:        Float = java.lang.Float.intBitsToFloat(0xfe798722)
  val SCRIBE_INK:        Float = java.lang.Float.intBitsToFloat(0xfe758417)
  val VARNISH:           Float = java.lang.Float.intBitsToFloat(0xfe839726)
  val CEDAR_WOOD:        Float = java.lang.Float.intBitsToFloat(0xfe8bb030)
  val HOT_SAUCE:         Float = java.lang.Float.intBitsToFloat(0xfe84cd49)
  val LURID_RED:         Float = java.lang.Float.intBitsToFloat(0xfe87e463)
  val BRICK:             Float = java.lang.Float.intBitsToFloat(0xfe83c582)
  val BRIGHT_RED:        Float = java.lang.Float.intBitsToFloat(0xfe98fa7e)
  val EMBERS:            Float = java.lang.Float.intBitsToFloat(0xfe93e18f)
  val SALMON:            Float = java.lang.Float.intBitsToFloat(0xfe7fce9c)
  val TAXICAB_YELLOW:    Float = java.lang.Float.intBitsToFloat(0xfec5e2c0)
  val APRICOT:           Float = java.lang.Float.intBitsToFloat(0xfeb4e1b9)
  val BURNT_YELLOW:      Float = java.lang.Float.intBitsToFloat(0xfec5e3a0)
  val DRY_PEPPER:        Float = java.lang.Float.intBitsToFloat(0xfeb1e78a)
  val REDWOOD:           Float = java.lang.Float.intBitsToFloat(0xfeacd970)
  val KOA:               Float = java.lang.Float.intBitsToFloat(0xfea2cd62)
  val OCHRE:             Float = java.lang.Float.intBitsToFloat(0xfe8ea53f)
  val DULL_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfea2a448)
  val ARMY_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfeb0b055)
  val DRIFTWOOD:         Float = java.lang.Float.intBitsToFloat(0xfe92987f)
  val DRY_BRUSH:         Float = java.lang.Float.intBitsToFloat(0xfec9d58a)
  val MUSH:              Float = java.lang.Float.intBitsToFloat(0xfed3d39c)
  val BANANA_PUDDING:    Float = java.lang.Float.intBitsToFloat(0xfebdc5cc)
  val SAFFRON:           Float = java.lang.Float.intBitsToFloat(0xfee2f7cc)
  val PENCIL_YELLOW:     Float = java.lang.Float.intBitsToFloat(0xfecfdadd)
  val CHARTREUSE:        Float = java.lang.Float.intBitsToFloat(0xfedec3d2)
  val ABSINTHE:          Float = java.lang.Float.intBitsToFloat(0xfed4aaba)
  val INFECTION:         Float = java.lang.Float.intBitsToFloat(0xfee1bea9)
  val FROG_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfee1b68f)
  val AVOCADO:           Float = java.lang.Float.intBitsToFloat(0xfed1b27c)
  val WOODLANDS:         Float = java.lang.Float.intBitsToFloat(0xfeac9350)
  val DARK_PINE:         Float = java.lang.Float.intBitsToFloat(0xfe979129)
  val MOSS_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe9e8b30)
  val FERN_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfea77f34)
  val FOREST_GLEN:       Float = java.lang.Float.intBitsToFloat(0xfec88753)
  val MALACHITE:         Float = java.lang.Float.intBitsToFloat(0xfee67f70)
  val APPLE_GREEN:       Float = java.lang.Float.intBitsToFloat(0xfeed847b)
  val CELERY:            Float = java.lang.Float.intBitsToFloat(0xfec584bc)
  val MINT_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfeca789f)
  val EMERALD:           Float = java.lang.Float.intBitsToFloat(0xfed87565)
  val PRASE:             Float = java.lang.Float.intBitsToFloat(0xfeb15a65)
  val EUCALYPTUS:        Float = java.lang.Float.intBitsToFloat(0xfe9e665a)
  val ZUCCHINI:          Float = java.lang.Float.intBitsToFloat(0xfe826f29)
  val SOFT_TEAL:         Float = java.lang.Float.intBitsToFloat(0xfe8b4862)
  val MEDIUM_TEAL:       Float = java.lang.Float.intBitsToFloat(0xfe993a76)
  val SPRING_GREEN:      Float = java.lang.Float.intBitsToFloat(0xfeb94a7c)
  val TURQUOISE:         Float = java.lang.Float.intBitsToFloat(0xfea1429b)
  val SEAFOAM:           Float = java.lang.Float.intBitsToFloat(0xfeac4baa)
  val VARISCITE:         Float = java.lang.Float.intBitsToFloat(0xfe984ec0)
  val REFRESHING_MIST:   Float = java.lang.Float.intBitsToFloat(0xfe7548cb)
  val SHINING_SKY:       Float = java.lang.Float.intBitsToFloat(0xfe732ab2)
  val STEAM:             Float = java.lang.Float.intBitsToFloat(0xfe7346b8)
  val ROBIN_EGG_BLUE:    Float = java.lang.Float.intBitsToFloat(0xfe84198c)
  val DENIM_BLUE:        Float = java.lang.Float.intBitsToFloat(0xfe5e186f)
  val DEEP_TEAL:         Float = java.lang.Float.intBitsToFloat(0xfe7e543a)
  val NAVY_BLUE:         Float = java.lang.Float.intBitsToFloat(0xfe6c6128)
  val BLUEBERRY:         Float = java.lang.Float.intBitsToFloat(0xfe5c4830)
  val PRUSSIAN_BLUE:     Float = java.lang.Float.intBitsToFloat(0xfe563138)
  val DESERT_RAIN:       Float = java.lang.Float.intBitsToFloat(0xfe664d57)
  val ELECTRIC_BLUE:     Float = java.lang.Float.intBitsToFloat(0xfe2d0447)
  val HIDDEN_BLUE:       Float = java.lang.Float.intBitsToFloat(0xfe562d55)
  val DULL_AZURE:        Float = java.lang.Float.intBitsToFloat(0xfe4d2364)
  val RIPPED_DENIM:      Float = java.lang.Float.intBitsToFloat(0xfe6c528e)
  val CALM_SKY:          Float = java.lang.Float.intBitsToFloat(0xfe52258d)
  val VAPOR:             Float = java.lang.Float.intBitsToFloat(0xfe5848ad)
  val POWDER_BLUE:       Float = java.lang.Float.intBitsToFloat(0xfe622da4)
  val SUDS:              Float = java.lang.Float.intBitsToFloat(0xfe5f61c3)
  val STRONG_CYAN:       Float = java.lang.Float.intBitsToFloat(0xfe5f007f)
  val SHARP_AZURE:       Float = java.lang.Float.intBitsToFloat(0xfe3f005f)
  val BLUE_EYE:          Float = java.lang.Float.intBitsToFloat(0xfe5a4173)
  val SUBTLETY:          Float = java.lang.Float.intBitsToFloat(0xfe3e4382)
  val ROUGH_SAPPHIRE:    Float = java.lang.Float.intBitsToFloat(0xfe2d2568)
  val IRIS:              Float = java.lang.Float.intBitsToFloat(0xfe253564)
  val CORNFLOWER_BLUE:   Float = java.lang.Float.intBitsToFloat(0xfe232353)
  val POLISHED_SAPPHIRE: Float = java.lang.Float.intBitsToFloat(0xfe201a2f)
  val ROYAL_BLUE:        Float = java.lang.Float.intBitsToFloat(0xfe29211f)
  val INDIGO:            Float = java.lang.Float.intBitsToFloat(0xfe3d4727)
  val SPACE_BLUE:        Float = java.lang.Float.intBitsToFloat(0xfe6c611e)
  val THICK_AMETHYST:    Float = java.lang.Float.intBitsToFloat(0xfe2f4f3c)
  val JUICY_GRAPE:       Float = java.lang.Float.intBitsToFloat(0xfe1f4746)
  val BLACKLIGHT_GLOW:   Float = java.lang.Float.intBitsToFloat(0xfe2f5a65)
  val PURPLE_FREESIA:    Float = java.lang.Float.intBitsToFloat(0xfe204e7a)
  val THIN_AMETHYST:     Float = java.lang.Float.intBitsToFloat(0xfe003f4f)
  val ORCHID:            Float = java.lang.Float.intBitsToFloat(0xfe315e97)
  val LAVENDER:          Float = java.lang.Float.intBitsToFloat(0xfe485cad)
  val LILAC:             Float = java.lang.Float.intBitsToFloat(0xfe526bc3)
  val SOAP:              Float = java.lang.Float.intBitsToFloat(0xfe646ed1)
  val PINK_TUTU:         Float = java.lang.Float.intBitsToFloat(0xfe647ddf)
  val THISTLE:           Float = java.lang.Float.intBitsToFloat(0xfe3973af)
  val HELIOTROPE:        Float = java.lang.Float.intBitsToFloat(0xfe297fa8)
  val PURPLE:            Float = java.lang.Float.intBitsToFloat(0xfe1f7c7d)
  val WISTERIA:          Float = java.lang.Float.intBitsToFloat(0xfe145e7b)
  val MEDIUM_PLUM:       Float = java.lang.Float.intBitsToFloat(0xfe257b67)
  val VIOLET:            Float = java.lang.Float.intBitsToFloat(0xfe2a6656)
  val GRAPE_LOLLIPOP:    Float = java.lang.Float.intBitsToFloat(0xfe4e6f3d)
  val MULBERRY:          Float = java.lang.Float.intBitsToFloat(0xfe577f3c)
  val GRAPE_SODA:        Float = java.lang.Float.intBitsToFloat(0xfe4e6f24)
  val EGGPLANT:          Float = java.lang.Float.intBitsToFloat(0xfe617520)
  val CHERRY_SYRUP:      Float = java.lang.Float.intBitsToFloat(0xfe708e33)
  val PLUM_JUICE:        Float = java.lang.Float.intBitsToFloat(0xfe4b8e58)
  val FRUIT_PUNCH:       Float = java.lang.Float.intBitsToFloat(0xfe43a75a)
  val BUBBLE_GUM:        Float = java.lang.Float.intBitsToFloat(0xfe489f9f)
  val PINK_LEMONADE:     Float = java.lang.Float.intBitsToFloat(0xfe529cad)
  val SHRIMP:            Float = java.lang.Float.intBitsToFloat(0xfe73a0c4)
  val FLAMINGO:          Float = java.lang.Float.intBitsToFloat(0xfe56b78d)
  val ROSE:              Float = java.lang.Float.intBitsToFloat(0xfe52b674)
  val CARMINE:           Float = java.lang.Float.intBitsToFloat(0xfe6bc156)
  val BOLOGNA:           Float = java.lang.Float.intBitsToFloat(0xfe73a55c)
  val RASPBERRY:         Float = java.lang.Float.intBitsToFloat(0xfe6eac47)

  // Register all colors
  locally {
    NAMED.put("Transparent", java.lang.Float.intBitsToFloat(0x7f7f00))
    LIST += java.lang.Float.intBitsToFloat(0x7f7f00)
    NAMED.put("Black", java.lang.Float.intBitsToFloat(0xfe7f7f00))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7f00)
    NAMED.put("Coal Black", java.lang.Float.intBitsToFloat(0xfe7f7f13))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7f13)
    NAMED.put("Shadow", java.lang.Float.intBitsToFloat(0xfe7f7f25))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7f25)
    NAMED.put("Graphite", java.lang.Float.intBitsToFloat(0xfe7f7f37))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7f37)
    NAMED.put("Dark Gray", java.lang.Float.intBitsToFloat(0xfe7f7f49))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7f49)
    NAMED.put("Lead", java.lang.Float.intBitsToFloat(0xfe7f7f5b))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7f5b)
    NAMED.put("Iron", java.lang.Float.intBitsToFloat(0xfe7f7f6e))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7f6e)
    NAMED.put("Gray", java.lang.Float.intBitsToFloat(0xfe7f7f80))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7f80)
    NAMED.put("Chinchilla", java.lang.Float.intBitsToFloat(0xfe7f7f92))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7f92)
    NAMED.put("Greyhound", java.lang.Float.intBitsToFloat(0xfe7f7fa4))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7fa4)
    NAMED.put("Silver", java.lang.Float.intBitsToFloat(0xfe7f7fb6))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7fb6)
    NAMED.put("Light Gray", java.lang.Float.intBitsToFloat(0xfe7f7fc9))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7fc9)
    NAMED.put("Platinum", java.lang.Float.intBitsToFloat(0xfe7f7fdb))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7fdb)
    NAMED.put("Cloud", java.lang.Float.intBitsToFloat(0xfe7f7fed))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7fed)
    NAMED.put("White", java.lang.Float.intBitsToFloat(0xfe7f7fff))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7fff)
    NAMED.put("Seawater", java.lang.Float.intBitsToFloat(0xfe7f404f))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f404f)
    NAMED.put("Hospital Green", java.lang.Float.intBitsToFloat(0xfe7f3f8f))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f3f8f)
    NAMED.put("Cyan", java.lang.Float.intBitsToFloat(0xfe7f009f))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f009f)
    NAMED.put("Bubble", java.lang.Float.intBitsToFloat(0xfe7f5fe7))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f5fe7)
    NAMED.put("Periwinkle", java.lang.Float.intBitsToFloat(0xfe404090))
    LIST += java.lang.Float.intBitsToFloat(0xfe404090)
    NAMED.put("Blue", java.lang.Float.intBitsToFloat(0xfe00001f))
    LIST += java.lang.Float.intBitsToFloat(0xfe00001f)
    NAMED.put("Faded Blue", java.lang.Float.intBitsToFloat(0xfe3f3f4f))
    LIST += java.lang.Float.intBitsToFloat(0xfe3f3f4f)
    NAMED.put("Ocean Blue", java.lang.Float.intBitsToFloat(0xfe40400f))
    LIST += java.lang.Float.intBitsToFloat(0xfe40400f)
    NAMED.put("Stygian Blue", java.lang.Float.intBitsToFloat(0xfe5f5f17))
    LIST += java.lang.Float.intBitsToFloat(0xfe5f5f17)
    NAMED.put("Deep Purple", java.lang.Float.intBitsToFloat(0xfe407f3f))
    LIST += java.lang.Float.intBitsToFloat(0xfe407f3f)
    NAMED.put("Tyrian Purple", java.lang.Float.intBitsToFloat(0xfe3f7f7f))
    LIST += java.lang.Float.intBitsToFloat(0xfe3f7f7f)
    NAMED.put("Magenta", java.lang.Float.intBitsToFloat(0xfe057f7a))
    LIST += java.lang.Float.intBitsToFloat(0xfe057f7a)
    NAMED.put("Bubblegum Pink", java.lang.Float.intBitsToFloat(0xfe407ebf))
    LIST += java.lang.Float.intBitsToFloat(0xfe407ebf)
    NAMED.put("Pork Chop", java.lang.Float.intBitsToFloat(0xfe7a99d9))
    LIST += java.lang.Float.intBitsToFloat(0xfe7a99d9)
    NAMED.put("Raw Meat", java.lang.Float.intBitsToFloat(0xfe7fbeb0))
    LIST += java.lang.Float.intBitsToFloat(0xfe7fbeb0)
    NAMED.put("Red", java.lang.Float.intBitsToFloat(0xfe7fff5f))
    LIST += java.lang.Float.intBitsToFloat(0xfe7fff5f)
    NAMED.put("Putty", java.lang.Float.intBitsToFloat(0xfe7fbf6f))
    LIST += java.lang.Float.intBitsToFloat(0xfe7fbf6f)
    NAMED.put("Sienna", java.lang.Float.intBitsToFloat(0xfe7fbf2f))
    LIST += java.lang.Float.intBitsToFloat(0xfe7fbf2f)
    NAMED.put("Seal Brown", java.lang.Float.intBitsToFloat(0xfe7fa02c))
    LIST += java.lang.Float.intBitsToFloat(0xfe7fa02c)
    NAMED.put("Mummy Brown", java.lang.Float.intBitsToFloat(0xfe9fbf4f))
    LIST += java.lang.Float.intBitsToFloat(0xfe9fbf4f)
    NAMED.put("Fawn", java.lang.Float.intBitsToFloat(0xfe9fbf8f))
    LIST += java.lang.Float.intBitsToFloat(0xfe9fbf8f)
    NAMED.put("Orange", java.lang.Float.intBitsToFloat(0xfebfff9f))
    LIST += java.lang.Float.intBitsToFloat(0xfebfff9f)
    NAMED.put("Peach", java.lang.Float.intBitsToFloat(0xfe9ebecf))
    LIST += java.lang.Float.intBitsToFloat(0xfe9ebecf)
    NAMED.put("Cream", java.lang.Float.intBitsToFloat(0xfe9f9ff7))
    LIST += java.lang.Float.intBitsToFloat(0xfe9f9ff7)
    NAMED.put("Yellow", java.lang.Float.intBitsToFloat(0xfeffffdf))
    LIST += java.lang.Float.intBitsToFloat(0xfeffffdf)
    NAMED.put("Earwax", java.lang.Float.intBitsToFloat(0xfebfbfaf))
    LIST += java.lang.Float.intBitsToFloat(0xfebfbfaf)
    NAMED.put("Umber", java.lang.Float.intBitsToFloat(0xfebfbf6f))
    LIST += java.lang.Float.intBitsToFloat(0xfebfbf6f)
    NAMED.put("Ivy Green", java.lang.Float.intBitsToFloat(0xfebf7f3f))
    LIST += java.lang.Float.intBitsToFloat(0xfebf7f3f)
    NAMED.put("Jade", java.lang.Float.intBitsToFloat(0xfebf7f7f))
    LIST += java.lang.Float.intBitsToFloat(0xfebf7f7f)
    NAMED.put("Green", java.lang.Float.intBitsToFloat(0xfeff7f7f))
    LIST += java.lang.Float.intBitsToFloat(0xfeff7f7f)
    NAMED.put("Celadon", java.lang.Float.intBitsToFloat(0xfea77fd7))
    LIST += java.lang.Float.intBitsToFloat(0xfea77fd7)
    NAMED.put("Puce", java.lang.Float.intBitsToFloat(0xfe777db6))
    LIST += java.lang.Float.intBitsToFloat(0xfe777db6)
    NAMED.put("Beige", java.lang.Float.intBitsToFloat(0xfe90a0b2))
    LIST += java.lang.Float.intBitsToFloat(0xfe90a0b2)
    NAMED.put("Wet Stone", java.lang.Float.intBitsToFloat(0xfe878aa0))
    LIST += java.lang.Float.intBitsToFloat(0xfe878aa0)
    NAMED.put("Slow Creek", java.lang.Float.intBitsToFloat(0xfe7f748b))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f748b)
    NAMED.put("Slate Gray", java.lang.Float.intBitsToFloat(0xfe7d737b))
    LIST += java.lang.Float.intBitsToFloat(0xfe7d737b)
    NAMED.put("Light Skin 1", java.lang.Float.intBitsToFloat(0xfe868e72))
    LIST += java.lang.Float.intBitsToFloat(0xfe868e72)
    NAMED.put("Light Skin 2", java.lang.Float.intBitsToFloat(0xfe84a07c))
    LIST += java.lang.Float.intBitsToFloat(0xfe84a07c)
    NAMED.put("Light Skin 3", java.lang.Float.intBitsToFloat(0xfe82a692))
    LIST += java.lang.Float.intBitsToFloat(0xfe82a692)
    NAMED.put("Light Skin 4", java.lang.Float.intBitsToFloat(0xfe8aada1))
    LIST += java.lang.Float.intBitsToFloat(0xfe8aada1)
    NAMED.put("Light Skin 5", java.lang.Float.intBitsToFloat(0xfe8eb1b1))
    LIST += java.lang.Float.intBitsToFloat(0xfe8eb1b1)
    NAMED.put("Light Skin 6", java.lang.Float.intBitsToFloat(0xfe8eafbe))
    LIST += java.lang.Float.intBitsToFloat(0xfe8eafbe)
    NAMED.put("Light Skin 7", java.lang.Float.intBitsToFloat(0xfe8eaccb))
    LIST += java.lang.Float.intBitsToFloat(0xfe8eaccb)
    NAMED.put("Light Skin 8", java.lang.Float.intBitsToFloat(0xfe8ca3d6))
    LIST += java.lang.Float.intBitsToFloat(0xfe8ca3d6)
    NAMED.put("Light Skin 9", java.lang.Float.intBitsToFloat(0xfe8791e6))
    LIST += java.lang.Float.intBitsToFloat(0xfe8791e6)
    NAMED.put("Dark Skin 1", java.lang.Float.intBitsToFloat(0xfe7f8d45))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f8d45)
    NAMED.put("Dark Skin 2", java.lang.Float.intBitsToFloat(0xfe829b53))
    LIST += java.lang.Float.intBitsToFloat(0xfe829b53)
    NAMED.put("Dark Skin 3", java.lang.Float.intBitsToFloat(0xfe7f9c6a))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f9c6a)
    NAMED.put("Pink Skin 1", java.lang.Float.intBitsToFloat(0xfe7f9b88))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f9b88)
    NAMED.put("Pink Skin 2", java.lang.Float.intBitsToFloat(0xfe7f9ba4))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f9ba4)
    NAMED.put("Pink Skin 3", java.lang.Float.intBitsToFloat(0xfe7f9bc0))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f9bc0)
    NAMED.put("Pink Skin 4", java.lang.Float.intBitsToFloat(0xfe7b8ee1))
    LIST += java.lang.Float.intBitsToFloat(0xfe7b8ee1)
    NAMED.put("Bronze Skin 4", java.lang.Float.intBitsToFloat(0xfe8d9bce))
    LIST += java.lang.Float.intBitsToFloat(0xfe8d9bce)
    NAMED.put("Bronze Skin 3", java.lang.Float.intBitsToFloat(0xfe95a8a6))
    LIST += java.lang.Float.intBitsToFloat(0xfe95a8a6)
    NAMED.put("Bronze Skin 2", java.lang.Float.intBitsToFloat(0xfe8d9b7a))
    LIST += java.lang.Float.intBitsToFloat(0xfe8d9b7a)
    NAMED.put("Bronze Skin 1", java.lang.Float.intBitsToFloat(0xfe8d9b5e))
    LIST += java.lang.Float.intBitsToFloat(0xfe8d9b5e)
    NAMED.put("Taupe", java.lang.Float.intBitsToFloat(0xfe868d30))
    LIST += java.lang.Float.intBitsToFloat(0xfe868d30)
    NAMED.put("Drab Green", java.lang.Float.intBitsToFloat(0xfe8e8e3d))
    LIST += java.lang.Float.intBitsToFloat(0xfe8e8e3d)
    NAMED.put("Lizard Scales", java.lang.Float.intBitsToFloat(0xfe9b9b6c))
    LIST += java.lang.Float.intBitsToFloat(0xfe9b9b6c)
    NAMED.put("Cricket", java.lang.Float.intBitsToFloat(0xfe9b9b88))
    LIST += java.lang.Float.intBitsToFloat(0xfe9b9b88)
    NAMED.put("Olive Oil", java.lang.Float.intBitsToFloat(0xfea6a698))
    LIST += java.lang.Float.intBitsToFloat(0xfea6a698)
    NAMED.put("Dun", java.lang.Float.intBitsToFloat(0xfea1a1ac))
    LIST += java.lang.Float.intBitsToFloat(0xfea1a1ac)
    NAMED.put("Corn Silk", java.lang.Float.intBitsToFloat(0xfe9b9bc0))
    LIST += java.lang.Float.intBitsToFloat(0xfe9b9bc0)
    NAMED.put("Tan", java.lang.Float.intBitsToFloat(0xfe9797d4))
    LIST += java.lang.Float.intBitsToFloat(0xfe9797d4)
    NAMED.put("Straw", java.lang.Float.intBitsToFloat(0xfe9292e8))
    LIST += java.lang.Float.intBitsToFloat(0xfe9292e8)
    NAMED.put("Honeydew", java.lang.Float.intBitsToFloat(0xfe9b8dd1))
    LIST += java.lang.Float.intBitsToFloat(0xfe9b8dd1)
    NAMED.put("Tarnish", java.lang.Float.intBitsToFloat(0xfe9b8db5))
    LIST += java.lang.Float.intBitsToFloat(0xfe9b8db5)
    NAMED.put("Pea Soup", java.lang.Float.intBitsToFloat(0xfeb49c9e))
    LIST += java.lang.Float.intBitsToFloat(0xfeb49c9e)
    NAMED.put("Marsh", java.lang.Float.intBitsToFloat(0xfe9b8d7d))
    LIST += java.lang.Float.intBitsToFloat(0xfe9b8d7d)
    NAMED.put("Asparagus", java.lang.Float.intBitsToFloat(0xfe9f8c67))
    LIST += java.lang.Float.intBitsToFloat(0xfe9f8c67)
    NAMED.put("Peat Bog", java.lang.Float.intBitsToFloat(0xfe8e8948))
    LIST += java.lang.Float.intBitsToFloat(0xfe8e8948)
    NAMED.put("Deep Jungle", java.lang.Float.intBitsToFloat(0xfe87841a))
    LIST += java.lang.Float.intBitsToFloat(0xfe87841a)
    NAMED.put("Pine Green", java.lang.Float.intBitsToFloat(0xfe8c753c))
    LIST += java.lang.Float.intBitsToFloat(0xfe8c753c)
    NAMED.put("Olive Green", java.lang.Float.intBitsToFloat(0xfe8d7f49))
    LIST += java.lang.Float.intBitsToFloat(0xfe8d7f49)
    NAMED.put("Gray Green", java.lang.Float.intBitsToFloat(0xfe897f5a))
    LIST += java.lang.Float.intBitsToFloat(0xfe897f5a)
    NAMED.put("Maidenhair Fern", java.lang.Float.intBitsToFloat(0xfe947858))
    LIST += java.lang.Float.intBitsToFloat(0xfe947858)
    NAMED.put("Kelly Green", java.lang.Float.intBitsToFloat(0xfe9b7f73))
    LIST += java.lang.Float.intBitsToFloat(0xfe9b7f73)
    NAMED.put("Dusty Green", java.lang.Float.intBitsToFloat(0xfe9b7f8f))
    LIST += java.lang.Float.intBitsToFloat(0xfe9b7f8f)
    NAMED.put("Garter Snake", java.lang.Float.intBitsToFloat(0xfe9e7095))
    LIST += java.lang.Float.intBitsToFloat(0xfe9e7095)
    NAMED.put("Silver Green", java.lang.Float.intBitsToFloat(0xfe9b7fab))
    LIST += java.lang.Float.intBitsToFloat(0xfe9b7fab)
    NAMED.put("Pistachio", java.lang.Float.intBitsToFloat(0xfe9a7fbd))
    LIST += java.lang.Float.intBitsToFloat(0xfe9a7fbd)
    NAMED.put("Angel Wing", java.lang.Float.intBitsToFloat(0xfe7e73ef))
    LIST += java.lang.Float.intBitsToFloat(0xfe7e73ef)
    NAMED.put("Sage Green", java.lang.Float.intBitsToFloat(0xfe9174d3))
    LIST += java.lang.Float.intBitsToFloat(0xfe9174d3)
    NAMED.put("Dried Sage", java.lang.Float.intBitsToFloat(0xfe8e72ca))
    LIST += java.lang.Float.intBitsToFloat(0xfe8e72ca)
    NAMED.put("Artichoke", java.lang.Float.intBitsToFloat(0xfe927c9e))
    LIST += java.lang.Float.intBitsToFloat(0xfe927c9e)
    NAMED.put("Viridian", java.lang.Float.intBitsToFloat(0xfe8e7868))
    LIST += java.lang.Float.intBitsToFloat(0xfe8e7868)
    NAMED.put("Floral Foam", java.lang.Float.intBitsToFloat(0xfe916442))
    LIST += java.lang.Float.intBitsToFloat(0xfe916442)
    NAMED.put("Hunter Green", java.lang.Float.intBitsToFloat(0xfe847d26))
    LIST += java.lang.Float.intBitsToFloat(0xfe847d26)
    NAMED.put("Dark Teal", java.lang.Float.intBitsToFloat(0xfe7d6e36))
    LIST += java.lang.Float.intBitsToFloat(0xfe7d6e36)
    NAMED.put("Kyanite", java.lang.Float.intBitsToFloat(0xfe7f635e))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f635e)
    NAMED.put("Spearmint", java.lang.Float.intBitsToFloat(0xfe7f5c90))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f5c90)
    NAMED.put("Amazonite", java.lang.Float.intBitsToFloat(0xfe7f63b2))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f63b2)
    NAMED.put("Pastel Sky", java.lang.Float.intBitsToFloat(0xfe7f63ce))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f63ce)
    NAMED.put("Aquamarine", java.lang.Float.intBitsToFloat(0xfe7f6ae1))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f6ae1)
    NAMED.put("Dust Bunny", java.lang.Float.intBitsToFloat(0xfe7066ce))
    LIST += java.lang.Float.intBitsToFloat(0xfe7066ce)
    NAMED.put("Patina", java.lang.Float.intBitsToFloat(0xfe7163c0))
    LIST += java.lang.Float.intBitsToFloat(0xfe7163c0)
    NAMED.put("Chipped Granite", java.lang.Float.intBitsToFloat(0xfe6e65b7))
    LIST += java.lang.Float.intBitsToFloat(0xfe6e65b7)
    NAMED.put("Blue Smoke", java.lang.Float.intBitsToFloat(0xfe7163a4))
    LIST += java.lang.Float.intBitsToFloat(0xfe7163a4)
    NAMED.put("Air Force Blue", java.lang.Float.intBitsToFloat(0xfe634781))
    LIST += java.lang.Float.intBitsToFloat(0xfe634781)
    NAMED.put("Cold Iron", java.lang.Float.intBitsToFloat(0xfe71636c))
    LIST += java.lang.Float.intBitsToFloat(0xfe71636c)
    NAMED.put("Dreary Blue", java.lang.Float.intBitsToFloat(0xfe716350))
    LIST += java.lang.Float.intBitsToFloat(0xfe716350)
    NAMED.put("Murk", java.lang.Float.intBitsToFloat(0xfe757017))
    LIST += java.lang.Float.intBitsToFloat(0xfe757017)
    NAMED.put("Ninja", java.lang.Float.intBitsToFloat(0xfe717122))
    LIST += java.lang.Float.intBitsToFloat(0xfe717122)
    NAMED.put("Watercolor Black", java.lang.Float.intBitsToFloat(0xfe71713e))
    LIST += java.lang.Float.intBitsToFloat(0xfe71713e)
    NAMED.put("Iolite", java.lang.Float.intBitsToFloat(0xfe6a6a4e))
    LIST += java.lang.Float.intBitsToFloat(0xfe6a6a4e)
    NAMED.put("Boysenberry", java.lang.Float.intBitsToFloat(0xfe63635e))
    LIST += java.lang.Float.intBitsToFloat(0xfe63635e)
    NAMED.put("Watercolor Gray", java.lang.Float.intBitsToFloat(0xfe616477))
    LIST += java.lang.Float.intBitsToFloat(0xfe616477)
    NAMED.put("Blue Steel", java.lang.Float.intBitsToFloat(0xfe555580))
    LIST += java.lang.Float.intBitsToFloat(0xfe555580)
    NAMED.put("Twilight Cloud", java.lang.Float.intBitsToFloat(0xfe636396))
    LIST += java.lang.Float.intBitsToFloat(0xfe636396)
    NAMED.put("Smog", java.lang.Float.intBitsToFloat(0xfe6363b2))
    LIST += java.lang.Float.intBitsToFloat(0xfe6363b2)
    NAMED.put("Tropic Mist", java.lang.Float.intBitsToFloat(0xfe706bda))
    LIST += java.lang.Float.intBitsToFloat(0xfe706bda)
    NAMED.put("Feather Down", java.lang.Float.intBitsToFloat(0xfe7171e6))
    LIST += java.lang.Float.intBitsToFloat(0xfe7171e6)
    NAMED.put("Mild Violet", java.lang.Float.intBitsToFloat(0xfe6371a0))
    LIST += java.lang.Float.intBitsToFloat(0xfe6371a0)
    NAMED.put("Violet Cushions", java.lang.Float.intBitsToFloat(0xfe47637a))
    LIST += java.lang.Float.intBitsToFloat(0xfe47637a)
    NAMED.put("Dull Violet", java.lang.Float.intBitsToFloat(0xfe637168))
    LIST += java.lang.Float.intBitsToFloat(0xfe637168)
    NAMED.put("Royal Violet", java.lang.Float.intBitsToFloat(0xfe63714c))
    LIST += java.lang.Float.intBitsToFloat(0xfe63714c)
    NAMED.put("Eminence", java.lang.Float.intBitsToFloat(0xfe737f2f))
    LIST += java.lang.Float.intBitsToFloat(0xfe737f2f)
    NAMED.put("Prune", java.lang.Float.intBitsToFloat(0xfe757f3c))
    LIST += java.lang.Float.intBitsToFloat(0xfe757f3c)
    NAMED.put("Dusty Grape", java.lang.Float.intBitsToFloat(0xfe667f59))
    LIST += java.lang.Float.intBitsToFloat(0xfe667f59)
    NAMED.put("Pink Violet", java.lang.Float.intBitsToFloat(0xfe637f73))
    LIST += java.lang.Float.intBitsToFloat(0xfe637f73)
    NAMED.put("Ripe Plum", java.lang.Float.intBitsToFloat(0xfe557f81))
    LIST += java.lang.Float.intBitsToFloat(0xfe557f81)
    NAMED.put("Mauve", java.lang.Float.intBitsToFloat(0xfe637f8f))
    LIST += java.lang.Float.intBitsToFloat(0xfe637f8f)
    NAMED.put("Ham", java.lang.Float.intBitsToFloat(0xfe6584ca))
    LIST += java.lang.Float.intBitsToFloat(0xfe6584ca)
    NAMED.put("Cotton Candy", java.lang.Float.intBitsToFloat(0xfe7384ec))
    LIST += java.lang.Float.intBitsToFloat(0xfe7384ec)
    NAMED.put("Silver Pink", java.lang.Float.intBitsToFloat(0xfe717fd5))
    LIST += java.lang.Float.intBitsToFloat(0xfe717fd5)
    NAMED.put("Tea Rose", java.lang.Float.intBitsToFloat(0xfe7387cb))
    LIST += java.lang.Float.intBitsToFloat(0xfe7387cb)
    NAMED.put("Old Rose", java.lang.Float.intBitsToFloat(0xfe708cb8))
    LIST += java.lang.Float.intBitsToFloat(0xfe708cb8)
    NAMED.put("Dusty Pink", java.lang.Float.intBitsToFloat(0xfe6a86a9))
    LIST += java.lang.Float.intBitsToFloat(0xfe6a86a9)
    NAMED.put("Roseate Spoonbill", java.lang.Float.intBitsToFloat(0xfe6e939d))
    LIST += java.lang.Float.intBitsToFloat(0xfe6e939d)
    NAMED.put("Thulian Pink", java.lang.Float.intBitsToFloat(0xfe649888))
    LIST += java.lang.Float.intBitsToFloat(0xfe649888)
    NAMED.put("Brown Velvet", java.lang.Float.intBitsToFloat(0xfe788937))
    LIST += java.lang.Float.intBitsToFloat(0xfe788937)
    NAMED.put("Nightshade", java.lang.Float.intBitsToFloat(0xfe798722))
    LIST += java.lang.Float.intBitsToFloat(0xfe798722)
    NAMED.put("Scribe Ink", java.lang.Float.intBitsToFloat(0xfe758417))
    LIST += java.lang.Float.intBitsToFloat(0xfe758417)
    NAMED.put("Varnish", java.lang.Float.intBitsToFloat(0xfe839726))
    LIST += java.lang.Float.intBitsToFloat(0xfe839726)
    NAMED.put("Cedar Wood", java.lang.Float.intBitsToFloat(0xfe8bb030))
    LIST += java.lang.Float.intBitsToFloat(0xfe8bb030)
    NAMED.put("Hot Sauce", java.lang.Float.intBitsToFloat(0xfe84cd49))
    LIST += java.lang.Float.intBitsToFloat(0xfe84cd49)
    NAMED.put("Lurid Red", java.lang.Float.intBitsToFloat(0xfe87e463))
    LIST += java.lang.Float.intBitsToFloat(0xfe87e463)
    NAMED.put("Brick", java.lang.Float.intBitsToFloat(0xfe83c582))
    LIST += java.lang.Float.intBitsToFloat(0xfe83c582)
    NAMED.put("Bright Red", java.lang.Float.intBitsToFloat(0xfe98fa7e))
    LIST += java.lang.Float.intBitsToFloat(0xfe98fa7e)
    NAMED.put("Embers", java.lang.Float.intBitsToFloat(0xfe93e18f))
    LIST += java.lang.Float.intBitsToFloat(0xfe93e18f)
    NAMED.put("Salmon", java.lang.Float.intBitsToFloat(0xfe7fce9c))
    LIST += java.lang.Float.intBitsToFloat(0xfe7fce9c)
    NAMED.put("Taxicab Yellow", java.lang.Float.intBitsToFloat(0xfec5e2c0))
    LIST += java.lang.Float.intBitsToFloat(0xfec5e2c0)
    NAMED.put("Apricot", java.lang.Float.intBitsToFloat(0xfeb4e1b9))
    LIST += java.lang.Float.intBitsToFloat(0xfeb4e1b9)
    NAMED.put("Burnt Yellow", java.lang.Float.intBitsToFloat(0xfec5e3a0))
    LIST += java.lang.Float.intBitsToFloat(0xfec5e3a0)
    NAMED.put("Dry Pepper", java.lang.Float.intBitsToFloat(0xfeb1e78a))
    LIST += java.lang.Float.intBitsToFloat(0xfeb1e78a)
    NAMED.put("Redwood", java.lang.Float.intBitsToFloat(0xfeacd970))
    LIST += java.lang.Float.intBitsToFloat(0xfeacd970)
    NAMED.put("Koa", java.lang.Float.intBitsToFloat(0xfea2cd62))
    LIST += java.lang.Float.intBitsToFloat(0xfea2cd62)
    NAMED.put("Ochre", java.lang.Float.intBitsToFloat(0xfe8ea53f))
    LIST += java.lang.Float.intBitsToFloat(0xfe8ea53f)
    NAMED.put("Dull Green", java.lang.Float.intBitsToFloat(0xfea2a448))
    LIST += java.lang.Float.intBitsToFloat(0xfea2a448)
    NAMED.put("Army Green", java.lang.Float.intBitsToFloat(0xfeb0b055))
    LIST += java.lang.Float.intBitsToFloat(0xfeb0b055)
    NAMED.put("Driftwood", java.lang.Float.intBitsToFloat(0xfe92987f))
    LIST += java.lang.Float.intBitsToFloat(0xfe92987f)
    NAMED.put("Dry Brush", java.lang.Float.intBitsToFloat(0xfec9d58a))
    LIST += java.lang.Float.intBitsToFloat(0xfec9d58a)
    NAMED.put("Mush", java.lang.Float.intBitsToFloat(0xfed3d39c))
    LIST += java.lang.Float.intBitsToFloat(0xfed3d39c)
    NAMED.put("Banana Pudding", java.lang.Float.intBitsToFloat(0xfebdc5cc))
    LIST += java.lang.Float.intBitsToFloat(0xfebdc5cc)
    NAMED.put("Saffron", java.lang.Float.intBitsToFloat(0xfee2f7cc))
    LIST += java.lang.Float.intBitsToFloat(0xfee2f7cc)
    NAMED.put("Pencil Yellow", java.lang.Float.intBitsToFloat(0xfecfdadd))
    LIST += java.lang.Float.intBitsToFloat(0xfecfdadd)
    NAMED.put("Chartreuse", java.lang.Float.intBitsToFloat(0xfedec3d2))
    LIST += java.lang.Float.intBitsToFloat(0xfedec3d2)
    NAMED.put("Absinthe", java.lang.Float.intBitsToFloat(0xfed4aaba))
    LIST += java.lang.Float.intBitsToFloat(0xfed4aaba)
    NAMED.put("Infection", java.lang.Float.intBitsToFloat(0xfee1bea9))
    LIST += java.lang.Float.intBitsToFloat(0xfee1bea9)
    NAMED.put("Frog Green", java.lang.Float.intBitsToFloat(0xfee1b68f))
    LIST += java.lang.Float.intBitsToFloat(0xfee1b68f)
    NAMED.put("Avocado", java.lang.Float.intBitsToFloat(0xfed1b27c))
    LIST += java.lang.Float.intBitsToFloat(0xfed1b27c)
    NAMED.put("Woodlands", java.lang.Float.intBitsToFloat(0xfeac9350))
    LIST += java.lang.Float.intBitsToFloat(0xfeac9350)
    NAMED.put("Dark Pine", java.lang.Float.intBitsToFloat(0xfe979129))
    LIST += java.lang.Float.intBitsToFloat(0xfe979129)
    NAMED.put("Moss Green", java.lang.Float.intBitsToFloat(0xfe9e8b30))
    LIST += java.lang.Float.intBitsToFloat(0xfe9e8b30)
    NAMED.put("Fern Green", java.lang.Float.intBitsToFloat(0xfea77f34))
    LIST += java.lang.Float.intBitsToFloat(0xfea77f34)
    NAMED.put("Forest Glen", java.lang.Float.intBitsToFloat(0xfec88753))
    LIST += java.lang.Float.intBitsToFloat(0xfec88753)
    NAMED.put("Malachite", java.lang.Float.intBitsToFloat(0xfee67f70))
    LIST += java.lang.Float.intBitsToFloat(0xfee67f70)
    NAMED.put("Apple Green", java.lang.Float.intBitsToFloat(0xfeed847b))
    LIST += java.lang.Float.intBitsToFloat(0xfeed847b)
    NAMED.put("Celery", java.lang.Float.intBitsToFloat(0xfec584bc))
    LIST += java.lang.Float.intBitsToFloat(0xfec584bc)
    NAMED.put("Mint Green", java.lang.Float.intBitsToFloat(0xfeca789f))
    LIST += java.lang.Float.intBitsToFloat(0xfeca789f)
    NAMED.put("Emerald", java.lang.Float.intBitsToFloat(0xfed87565))
    LIST += java.lang.Float.intBitsToFloat(0xfed87565)
    NAMED.put("Prase", java.lang.Float.intBitsToFloat(0xfeb15a65))
    LIST += java.lang.Float.intBitsToFloat(0xfeb15a65)
    NAMED.put("Eucalyptus", java.lang.Float.intBitsToFloat(0xfe9e665a))
    LIST += java.lang.Float.intBitsToFloat(0xfe9e665a)
    NAMED.put("Zucchini", java.lang.Float.intBitsToFloat(0xfe826f29))
    LIST += java.lang.Float.intBitsToFloat(0xfe826f29)
    NAMED.put("Soft Teal", java.lang.Float.intBitsToFloat(0xfe8b4862))
    LIST += java.lang.Float.intBitsToFloat(0xfe8b4862)
    NAMED.put("Medium Teal", java.lang.Float.intBitsToFloat(0xfe993a76))
    LIST += java.lang.Float.intBitsToFloat(0xfe993a76)
    NAMED.put("Spring Green", java.lang.Float.intBitsToFloat(0xfeb94a7c))
    LIST += java.lang.Float.intBitsToFloat(0xfeb94a7c)
    NAMED.put("Turquoise", java.lang.Float.intBitsToFloat(0xfea1429b))
    LIST += java.lang.Float.intBitsToFloat(0xfea1429b)
    NAMED.put("Seafoam", java.lang.Float.intBitsToFloat(0xfeac4baa))
    LIST += java.lang.Float.intBitsToFloat(0xfeac4baa)
    NAMED.put("Variscite", java.lang.Float.intBitsToFloat(0xfe984ec0))
    LIST += java.lang.Float.intBitsToFloat(0xfe984ec0)
    NAMED.put("Refreshing Mist", java.lang.Float.intBitsToFloat(0xfe7548cb))
    LIST += java.lang.Float.intBitsToFloat(0xfe7548cb)
    NAMED.put("Shining Sky", java.lang.Float.intBitsToFloat(0xfe732ab2))
    LIST += java.lang.Float.intBitsToFloat(0xfe732ab2)
    NAMED.put("Steam", java.lang.Float.intBitsToFloat(0xfe7346b8))
    LIST += java.lang.Float.intBitsToFloat(0xfe7346b8)
    NAMED.put("Robin Egg Blue", java.lang.Float.intBitsToFloat(0xfe84198c))
    LIST += java.lang.Float.intBitsToFloat(0xfe84198c)
    NAMED.put("Denim Blue", java.lang.Float.intBitsToFloat(0xfe5e186f))
    LIST += java.lang.Float.intBitsToFloat(0xfe5e186f)
    NAMED.put("Deep Teal", java.lang.Float.intBitsToFloat(0xfe7e543a))
    LIST += java.lang.Float.intBitsToFloat(0xfe7e543a)
    NAMED.put("Navy Blue", java.lang.Float.intBitsToFloat(0xfe6c6128))
    LIST += java.lang.Float.intBitsToFloat(0xfe6c6128)
    NAMED.put("Blueberry", java.lang.Float.intBitsToFloat(0xfe5c4830))
    LIST += java.lang.Float.intBitsToFloat(0xfe5c4830)
    NAMED.put("Prussian Blue", java.lang.Float.intBitsToFloat(0xfe563138))
    LIST += java.lang.Float.intBitsToFloat(0xfe563138)
    NAMED.put("Desert Rain", java.lang.Float.intBitsToFloat(0xfe664d57))
    LIST += java.lang.Float.intBitsToFloat(0xfe664d57)
    NAMED.put("Electric Blue", java.lang.Float.intBitsToFloat(0xfe2d0447))
    LIST += java.lang.Float.intBitsToFloat(0xfe2d0447)
    NAMED.put("Hidden Blue", java.lang.Float.intBitsToFloat(0xfe562d55))
    LIST += java.lang.Float.intBitsToFloat(0xfe562d55)
    NAMED.put("Dull Azure", java.lang.Float.intBitsToFloat(0xfe4d2364))
    LIST += java.lang.Float.intBitsToFloat(0xfe4d2364)
    NAMED.put("Ripped Denim", java.lang.Float.intBitsToFloat(0xfe6c528e))
    LIST += java.lang.Float.intBitsToFloat(0xfe6c528e)
    NAMED.put("Calm Sky", java.lang.Float.intBitsToFloat(0xfe52258d))
    LIST += java.lang.Float.intBitsToFloat(0xfe52258d)
    NAMED.put("Vapor", java.lang.Float.intBitsToFloat(0xfe5848ad))
    LIST += java.lang.Float.intBitsToFloat(0xfe5848ad)
    NAMED.put("Powder Blue", java.lang.Float.intBitsToFloat(0xfe622da4))
    LIST += java.lang.Float.intBitsToFloat(0xfe622da4)
    NAMED.put("Suds", java.lang.Float.intBitsToFloat(0xfe5f61c3))
    LIST += java.lang.Float.intBitsToFloat(0xfe5f61c3)
    NAMED.put("Strong Cyan", java.lang.Float.intBitsToFloat(0xfe5f007f))
    LIST += java.lang.Float.intBitsToFloat(0xfe5f007f)
    NAMED.put("Sharp Azure", java.lang.Float.intBitsToFloat(0xfe3f005f))
    LIST += java.lang.Float.intBitsToFloat(0xfe3f005f)
    NAMED.put("Blue Eye", java.lang.Float.intBitsToFloat(0xfe5a4173))
    LIST += java.lang.Float.intBitsToFloat(0xfe5a4173)
    NAMED.put("Subtlety", java.lang.Float.intBitsToFloat(0xfe3e4382))
    LIST += java.lang.Float.intBitsToFloat(0xfe3e4382)
    NAMED.put("Rough Sapphire", java.lang.Float.intBitsToFloat(0xfe2d2568))
    LIST += java.lang.Float.intBitsToFloat(0xfe2d2568)
    NAMED.put("Iris", java.lang.Float.intBitsToFloat(0xfe253564))
    LIST += java.lang.Float.intBitsToFloat(0xfe253564)
    NAMED.put("Cornflower Blue", java.lang.Float.intBitsToFloat(0xfe232353))
    LIST += java.lang.Float.intBitsToFloat(0xfe232353)
    NAMED.put("Polished Sapphire", java.lang.Float.intBitsToFloat(0xfe201a2f))
    LIST += java.lang.Float.intBitsToFloat(0xfe201a2f)
    NAMED.put("Royal Blue", java.lang.Float.intBitsToFloat(0xfe29211f))
    LIST += java.lang.Float.intBitsToFloat(0xfe29211f)
    NAMED.put("Indigo", java.lang.Float.intBitsToFloat(0xfe3d4727))
    LIST += java.lang.Float.intBitsToFloat(0xfe3d4727)
    NAMED.put("Space Blue", java.lang.Float.intBitsToFloat(0xfe6c611e))
    LIST += java.lang.Float.intBitsToFloat(0xfe6c611e)
    NAMED.put("Thick Amethyst", java.lang.Float.intBitsToFloat(0xfe2f4f3c))
    LIST += java.lang.Float.intBitsToFloat(0xfe2f4f3c)
    NAMED.put("Juicy Grape", java.lang.Float.intBitsToFloat(0xfe1f4746))
    LIST += java.lang.Float.intBitsToFloat(0xfe1f4746)
    NAMED.put("Blacklight Glow", java.lang.Float.intBitsToFloat(0xfe2f5a65))
    LIST += java.lang.Float.intBitsToFloat(0xfe2f5a65)
    NAMED.put("Purple Freesia", java.lang.Float.intBitsToFloat(0xfe204e7a))
    LIST += java.lang.Float.intBitsToFloat(0xfe204e7a)
    NAMED.put("Thin Amethyst", java.lang.Float.intBitsToFloat(0xfe003f4f))
    LIST += java.lang.Float.intBitsToFloat(0xfe003f4f)
    NAMED.put("Orchid", java.lang.Float.intBitsToFloat(0xfe315e97))
    LIST += java.lang.Float.intBitsToFloat(0xfe315e97)
    NAMED.put("Lavender", java.lang.Float.intBitsToFloat(0xfe485cad))
    LIST += java.lang.Float.intBitsToFloat(0xfe485cad)
    NAMED.put("Lilac", java.lang.Float.intBitsToFloat(0xfe526bc3))
    LIST += java.lang.Float.intBitsToFloat(0xfe526bc3)
    NAMED.put("Soap", java.lang.Float.intBitsToFloat(0xfe646ed1))
    LIST += java.lang.Float.intBitsToFloat(0xfe646ed1)
    NAMED.put("Pink Tutu", java.lang.Float.intBitsToFloat(0xfe647ddf))
    LIST += java.lang.Float.intBitsToFloat(0xfe647ddf)
    NAMED.put("Thistle", java.lang.Float.intBitsToFloat(0xfe3973af))
    LIST += java.lang.Float.intBitsToFloat(0xfe3973af)
    NAMED.put("Heliotrope", java.lang.Float.intBitsToFloat(0xfe297fa8))
    LIST += java.lang.Float.intBitsToFloat(0xfe297fa8)
    NAMED.put("Purple", java.lang.Float.intBitsToFloat(0xfe1f7c7d))
    LIST += java.lang.Float.intBitsToFloat(0xfe1f7c7d)
    NAMED.put("Wisteria", java.lang.Float.intBitsToFloat(0xfe145e7b))
    LIST += java.lang.Float.intBitsToFloat(0xfe145e7b)
    NAMED.put("Medium Plum", java.lang.Float.intBitsToFloat(0xfe257b67))
    LIST += java.lang.Float.intBitsToFloat(0xfe257b67)
    NAMED.put("Violet", java.lang.Float.intBitsToFloat(0xfe2a6656))
    LIST += java.lang.Float.intBitsToFloat(0xfe2a6656)
    NAMED.put("Grape Lollipop", java.lang.Float.intBitsToFloat(0xfe4e6f3d))
    LIST += java.lang.Float.intBitsToFloat(0xfe4e6f3d)
    NAMED.put("Mulberry", java.lang.Float.intBitsToFloat(0xfe577f3c))
    LIST += java.lang.Float.intBitsToFloat(0xfe577f3c)
    NAMED.put("Grape Soda", java.lang.Float.intBitsToFloat(0xfe4e6f24))
    LIST += java.lang.Float.intBitsToFloat(0xfe4e6f24)
    NAMED.put("Eggplant", java.lang.Float.intBitsToFloat(0xfe617520))
    LIST += java.lang.Float.intBitsToFloat(0xfe617520)
    NAMED.put("Cherry Syrup", java.lang.Float.intBitsToFloat(0xfe708e33))
    LIST += java.lang.Float.intBitsToFloat(0xfe708e33)
    NAMED.put("Plum Juice", java.lang.Float.intBitsToFloat(0xfe4b8e58))
    LIST += java.lang.Float.intBitsToFloat(0xfe4b8e58)
    NAMED.put("Fruit Punch", java.lang.Float.intBitsToFloat(0xfe43a75a))
    LIST += java.lang.Float.intBitsToFloat(0xfe43a75a)
    NAMED.put("Bubble Gum", java.lang.Float.intBitsToFloat(0xfe489f9f))
    LIST += java.lang.Float.intBitsToFloat(0xfe489f9f)
    NAMED.put("Pink Lemonade", java.lang.Float.intBitsToFloat(0xfe529cad))
    LIST += java.lang.Float.intBitsToFloat(0xfe529cad)
    NAMED.put("Shrimp", java.lang.Float.intBitsToFloat(0xfe73a0c4))
    LIST += java.lang.Float.intBitsToFloat(0xfe73a0c4)
    NAMED.put("Flamingo", java.lang.Float.intBitsToFloat(0xfe56b78d))
    LIST += java.lang.Float.intBitsToFloat(0xfe56b78d)
    NAMED.put("Rose", java.lang.Float.intBitsToFloat(0xfe52b674))
    LIST += java.lang.Float.intBitsToFloat(0xfe52b674)
    NAMED.put("Carmine", java.lang.Float.intBitsToFloat(0xfe6bc156))
    LIST += java.lang.Float.intBitsToFloat(0xfe6bc156)
    NAMED.put("Bologna", java.lang.Float.intBitsToFloat(0xfe73a55c))
    LIST += java.lang.Float.intBitsToFloat(0xfe73a55c)
    NAMED.put("Raspberry", java.lang.Float.intBitsToFloat(0xfe6eac47))
    LIST += java.lang.Float.intBitsToFloat(0xfe6eac47)
  }

  /** Converts existing Color entries in [[sge.graphics.Colors]] from RGBA to YCwCm format. */
  def editKnownColors(): Unit =
    for (c <- sge.graphics.Colors.colors.values) {
      val f = ColorTools.fromColor(c)
      c.set(ColorTools.luma(f), ColorTools.chromaWarm(f), ColorTools.chromaMild(f), c.a)
    }

  /** Appends YCwCm-compatible Color instances to the map in [[sge.graphics.Colors]]. */
  def appendToKnownColors(): Unit =
    for ((key, value) <- NAMED) {
      val f = value
      sge.graphics.Colors.put(key, new sge.graphics.Color(ColorTools.luma(f), ColorTools.chromaWarm(f), ColorTools.chromaMild(f), ColorTools.alpha(f)))
    }
}
