/*
 * Ported from libGDX - https://github.com/libgdx/libgdx
 * Original source: com/badlogic/gdx/Graphics.java
 * Original authors: mzechner, badlogic
 * Licensed under the Apache License, Version 2.0
 *
 * Migration notes:
 *   Convention: Java interface -> Scala trait; added convenience properties gl, gl20, gl30, gl31, gl32
 *   Idiom: split packages; Nullable used
 *   Issues: type GLVersion = AnyRef is a placeholder — should reference sge.graphics.glutils.GLVersion
 *   TODO: type GLVersion = AnyRef is placeholder -- should use sge.graphics.glutils.GLVersion
 *   TODO: opaque Pixels for width/height params in getWidth/Height, getBackBufferWidth/Height, setWindowedMode, newCursor hotspot -- see docs/improvements/opaque-types.md
 *   Audited: 2026-03-03
 *
 * Scala port Copyright 2024-2026 Mateusz Kubuszok
 */
package sge

import sge.graphics.Cursor
import sge.graphics.Cursor.SystemCursor
import sge.graphics.GL20
import sge.graphics.GL30
import sge.graphics.GL31
import sge.graphics.GL32
import sge.graphics.Pixmap
import sge.utils.Nullable

/** This interface encapsulates communication with the graphics processor. Depending on the available hardware and the current {@link Application} configuration, access to {@link GL20} and
  * {@link GL30} are provided here. <p> If supported by the backend, this interface lets you query the available display modes (graphics resolution and color depth) and change it. <p> This interface
  * can be used to switch between continuous and non-continuous rendering (see {@link #setContinuousRendering(boolean)} ), and to explicitly {@link #requestRendering()} . <p> There are many more
  * utility classes that are not directly generated by the {@link Graphics} interfaces. See {@link VertexArray} , {@link VertexBufferObject} , {@link IndexBufferObject} , {@link Mesh} ,
  * {@link ShaderProgram} and {@link FrameBuffer} , {@link BitmapFont} , {@link Batch} and so on. All these classes are managed, meaning they don't need to be reloaded on a context loss. Explore the
  * com.badlogic.gdx.graphics package for more classes that might come in handy.
  * @author
  *   mzechner
  */
trait Graphics {

  /** Returns whether OpenGL ES 3.0 is available. If it is you can get an instance of {@link GL30} via {@link #getGL30()} to access OpenGL ES 3.0 functionality. Note that this functionality will only
    * be available if you instructed the {@link Application} instance to use OpenGL ES 3.0!
    *
    * @return
    *   whether OpenGL ES 3.0 is available
    */
  def isGL30Available(): Boolean

  /** Returns whether OpenGL ES 3.1 is available. If it is you can get an instance of {@link GL31} via {@link #getGL31()} to access OpenGL ES 3.1 functionality. Note that this functionality will only
    * be available if you instructed the {@link Application} instance to use OpenGL ES 3.1!
    *
    * @return
    *   whether OpenGL ES 3.1 is available
    */
  def isGL31Available(): Boolean

  /** Returns whether OpenGL ES 3.2 is available. If it is you can get an instance of {@link GL32} via {@link #getGL32()} to access OpenGL ES 3.2 functionality. Note that this functionality will only
    * be available if you instructed the {@link Application} instance to use OpenGL ES 3.2!
    *
    * @return
    *   whether OpenGL ES 3.2 is available
    */
  def isGL32Available(): Boolean

  /** @return the {@link GL20} instance */
  def getGL20(): GL20

  /** @return the {@link GL30} instance or null if not supported */
  def getGL30(): Nullable[GL30]

  /** @return the {@link GL31} instance or null if not supported */
  def getGL31(): Nullable[GL31]

  /** @return the {@link GL32} instance or null if not supported */
  def getGL32(): Nullable[GL32]

  // TODO: Make the convention uniform across the codebase
  // Convenience properties for easier access
  /** Convenience property for GL20 access */
  def gl: GL20 = getGL20()

  /** Convenience property for GL20 access */
  def gl20: GL20 = getGL20()

  /** Convenience property for GL30 access */
  def gl30: Nullable[GL30] = getGL30()

  /** Convenience property for GL31 access */
  def gl31: Nullable[GL31] = getGL31()

  /** Convenience property for GL32 access */
  def gl32: Nullable[GL32] = getGL32()

  /** Set the GL20 instance * */
  def setGL20(gl20: GL20): Unit

  /** Set the GL30 instance * */
  def setGL30(gl30: GL30): Unit

  /** Set the GL31 instance * */
  def setGL31(gl31: GL31): Unit

  /** Set the GL32 instance * */
  def setGL32(gl32: GL32): Unit

  /** @return the width of the client area in logical pixels. */
  def getWidth(): Int

  /** @return the height of the client area in logical pixels */
  def getHeight(): Int

  /** @return the width of the framebuffer in physical pixels */
  def getBackBufferWidth(): Int

  /** @return the height of the framebuffer in physical pixels */
  def getBackBufferHeight(): Int

  /** @return amount of pixels per logical pixel (point) */
  def getBackBufferScale(): Float

  /** @return the inset from the left which avoids display cutouts in logical pixels */
  def getSafeInsetLeft(): Int

  /** @return the inset from the top which avoids display cutouts in logical pixels */
  def getSafeInsetTop(): Int

  /** @return the inset from the bottom which avoids display cutouts or floating gesture bars, in logical pixels */
  def getSafeInsetBottom(): Int

  /** @return the inset from the right which avoids display cutouts in logical pixels */
  def getSafeInsetRight(): Int

  /** Returns the id of the current frame. The general contract of this method is that the id is incremented only when the application is in the running state right before calling the
    * {@link ApplicationListener#render()} method. Also, the id of the first frame is 0; the id of subsequent frames is guaranteed to take increasing values for 2<sup>63</sup>-1 rendering cycles.
    * @return
    *   the id of the current frame
    */
  def getFrameId(): Long

  /** @return the time span between the current frame and the last frame in seconds. */
  def getDeltaTime(): Float

  /** @return
    *   the time span between the current frame and the last frame in seconds, without smoothing
    * @deprecated
    *   use {@link #getDeltaTime()} instead.
    */
  @deprecated("use getDeltaTime() instead", "1.0")
  def getRawDeltaTime(): Float

  /** @return the average number of frames per second */
  def getFramesPerSecond(): Int

  /** @return the {@link GraphicsType} of this Graphics instance */
  def getType(): Graphics.GraphicsType

  /** @return the {@link GLVersion} of this Graphics instance */
  def getGLVersion(): Graphics.GLVersion

  /** @return the pixels per inch on the x-axis */
  def getPpiX(): Float

  /** @return the pixels per inch on the y-axis */
  def getPpiY(): Float

  /** @return the pixels per centimeter on the x-axis */
  def getPpcX(): Float

  /** @return the pixels per centimeter on the y-axis. */
  def getPpcY(): Float

  /** This is a scaling factor for the Density Independent Pixel unit, following the same conventions as android.util.DisplayMetrics#density, where one DIP is one pixel on an approximately 160 dpi
    * screen. Thus on a 160dpi screen this density value will be 1; on a 120 dpi screen it would be .75; etc.
    *
    * If the density could not be determined, this returns a default value of 1.
    *
    * Depending on the underlying platform implementation this might be a relatively expensive operation. Therefore it should not be called continously on each frame.
    *
    * @return
    *   the Density Independent Pixel factor of the display.
    */
  def getDensity(): Float

  /** Whether the given backend supports a display mode change via calling {@link Graphics#setFullscreenMode(DisplayMode)}
    *
    * @return
    *   whether display mode changes are supported or not.
    */
  def supportsDisplayModeChange(): Boolean

  /** @return the primary monitor * */
  def getPrimaryMonitor(): Graphics.Monitor

  /** @return the monitor the application's window is located on */
  def getMonitor(): Graphics.Monitor

  /** @return the currently connected {@link Monitor}s */
  def getMonitors(): Array[Graphics.Monitor]

  /** @return the supported fullscreen {@link DisplayMode}(s) of the monitor the window is on */
  def getDisplayModes(): Array[Graphics.DisplayMode]

  /** @return the supported fullscreen {@link DisplayMode}s of the given {@link Monitor} */
  def getDisplayModes(monitor: Graphics.Monitor): Array[Graphics.DisplayMode]

  /** @return the current {@link DisplayMode} of the monitor the window is on. */
  def getDisplayMode(): Graphics.DisplayMode

  /** @return the current {@link DisplayMode} of the given {@link Monitor} */
  def getDisplayMode(monitor: Graphics.Monitor): Graphics.DisplayMode

  /** Sets the window to full-screen mode.
    *
    * @param displayMode
    *   the display mode.
    * @return
    *   whether the operation succeeded.
    */
  def setFullscreenMode(displayMode: Graphics.DisplayMode): Boolean

  /** Sets the window to windowed mode.
    *
    * @param width
    *   the width in pixels
    * @param height
    *   the height in pixels
    * @return
    *   whether the operation succeeded
    */
  def setWindowedMode(width: Int, height: Int): Boolean

  /** Sets the title of the window. Ignored on Android.
    *
    * @param title
    *   the title.
    */
  def setTitle(title: String): Unit

  /** Sets the window decoration as enabled or disabled. On Android, this will enable/disable the menu bar.
    *
    * Note that immediate behavior of this method may vary depending on the implementation. It may be necessary for the window to be recreated in order for the changes to take effect. Consult the
    * documentation for the backend in use for more information.
    *
    * Supported on all GDX desktop backends and on Android (to disable the menu bar).
    *
    * @param undecorated
    *   true if the window border or status bar should be hidden. false otherwise.
    */
  def setUndecorated(undecorated: Boolean): Unit

  /** Sets whether or not the window should be resizable. Ignored on Android.
    *
    * Note that immediate behavior of this method may vary depending on the implementation. It may be necessary for the window to be recreated in order for the changes to take effect. Consult the
    * documentation for the backend in use for more information.
    *
    * Supported on all GDX desktop backends.
    *
    * @param resizable
    */
  def setResizable(resizable: Boolean): Unit

  /** Enable/Disable vsynching. This is a best-effort attempt which might not work on all platforms.
    *
    * @param vsync
    *   vsync enabled or not.
    */
  def setVSync(vsync: Boolean): Unit

  /** Sets the target framerate for the application when using continuous rendering. Might not work on all platforms. Is not generally advised to be used on mobile platforms.
    *
    * @param fps
    *   the targeted fps; default differs by platform
    */
  def setForegroundFPS(fps: Int): Unit

  /** @return the format of the color, depth and stencil buffer in a {@link BufferFormat} instance */
  def getBufferFormat(): Graphics.BufferFormat

  /** @param extension
    *   the extension name
    * @return
    *   whether the extension is supported
    */
  def supportsExtension(extension: String): Boolean

  /** Sets whether to render continuously. In case rendering is performed non-continuously, the following events will trigger a redraw:
    *
    * <ul> <li>A call to {@link #requestRendering()} </li> <li>Input events from the touch screen/mouse or keyboard</li> <li>A {@link Runnable} is posted to the rendering thread via
    * {@link Application#postRunnable(Runnable)} . In the case of a multi-window app, all windows will request rendering if a runnable is posted to the application. To avoid this, post a runnable to
    * the window instead.</li> </ul>
    *
    * Life-cycle events will also be reported as usual, see {@link ApplicationListener} . This method can be called from any thread.
    *
    * @param isContinuous
    *   whether the rendering should be continuous or not.
    */
  def setContinuousRendering(isContinuous: Boolean): Unit

  /** @return whether rendering is continuous. */
  def isContinuousRendering(): Boolean

  /** Requests a new frame to be rendered if the rendering mode is non-continuous. This method can be called from any thread. */
  def requestRendering(): Unit

  /** Whether the app is fullscreen or not */
  def isFullscreen(): Boolean

  /** Create a new cursor represented by the {@link com.badlogic.gdx.graphics.Pixmap} . The Pixmap must be in RGBA8888 format, width & height must be powers-of-two greater than zero (not necessarily
    * equal) and of a certain minimum size (32x32 is a safe bet), and alpha transparency must be single-bit (i.e., 0x00 or 0xFF only). This function returns a Cursor object that can be set as the
    * system cursor by calling {@link #setCursor(Cursor)} .
    *
    * @param pixmap
    *   the mouse cursor image as a {@link com.badlogic.gdx.graphics.Pixmap}
    * @param xHotspot
    *   the x location of the hotspot pixel within the cursor image (origin top-left corner)
    * @param yHotspot
    *   the y location of the hotspot pixel within the cursor image (origin top-left corner)
    * @return
    *   a cursor object that can be used by calling {@link #setCursor(Cursor)} or null if not supported
    */
  def newCursor(pixmap: Pixmap, xHotspot: Int, yHotspot: Int): Nullable[Cursor]

  /** Only viable on the lwjgl-backend and on the gwt-backend. Browsers that support cursor:url() and support the png format (the pixmap is converted to a data-url of type image/png) should also
    * support custom cursors. Will set the mouse cursor image to the image represented by the {@link com.badlogic.gdx.graphics.Cursor} . It is recommended to call this function in the main render
    * thread, and maximum one time per frame.
    *
    * @param cursor
    *   the mouse cursor as a {@link com.badlogic.gdx.graphics.Cursor}
    */
  def setCursor(cursor: Cursor): Unit

  /** Sets one of the predefined {@link SystemCursor}s */
  def setSystemCursor(systemCursor: SystemCursor): Unit
}

object Graphics {

  /** Enumeration describing different types of {@link Graphics} implementations.
    *
    * @author
    *   mzechner
    */
  enum GraphicsType {
    case AndroidGL, LWJGL, WebGL, iOSGL, JGLFW, Mock, LWJGL3
  }

  /** Describe a fullscreen display mode
    *
    * @author
    *   mzechner
    */
  case class DisplayMode(
    /** the width in physical pixels * */
    width: Int,
    /** the height in physical pixels * */
    height: Int,
    /** the refresh rate in Hertz * */
    refreshRate: Int,
    /** the number of bits per pixel, may exclude alpha * */
    bitsPerPixel: Int
  ) {
    override def toString(): String = s"${width}x${height}, bpp: ${bitsPerPixel}, hz: ${refreshRate}"
  }

  /** Describes a monitor
    *
    * @author
    *   badlogic
    */
  case class Monitor(
    virtualX: Int,
    virtualY: Int,
    name:     String
  )

  /** Class describing the bits per pixel, depth buffer precision, stencil precision and number of MSAA samples. */
  case class BufferFormat(
    /* number of bits per color channel */
    r: Int,
    g: Int,
    b: Int,
    a: Int,
    /* number of bits for depth and stencil buffer */
    depth:   Int,
    stencil: Int,
    /** number of samples for multi-sample anti-aliasing (MSAA) * */
    samples: Int,
    /** whether coverage sampling anti-aliasing is used. in that case you have to clear the coverage buffer as well! */
    coverageSampling: Boolean
  ) {
    override def toString(): String =
      s"r: $r, g: $g, b: $b, a: $a, depth: $depth, stencil: $stencil, num samples: $samples, coverage sampling: $coverageSampling"
  }

  // Placeholder for GLVersion - this should be defined elsewhere
  type GLVersion = AnyRef
}
