/*
 * Ported from gdx-gltf - https://github.com/mgsx-dev/gdx-gltf
 * Original source: net/mgsx/gltf/scene3d/utils/IBLBuilder.java
 * Licensed under the Apache License, Version 2.0
 *
 * Scala port for SGE
 *
 * Quick procedural IBL environment generation.
 * Should be closed when no longer used.
 *
 * IBL generated by this class are accurate, some fast approximation are performed to provide
 * a quick way to setup an IBL environment. For accurate IBL, see:
 * https://learnopengl.com/PBR/IBL/Specular-IBL
 * and
 * https://learnopengl.com/PBR/IBL/Diffuse-irradiance
 * and related tools to generate them from HDRIs.
 *
 * Migration notes:
 *   Convention: uses (using Sge) context parameter
 *   Convention: rect() → rectangle(), dispose() → close(), getSide() → side (Nullable)
 *   Convention: typed GL enums (EnableCap, BlendFactor, ClearMask)
 *   Idiom: split packages
 *   Audited: 2026-04-18
 *
 * Covenant: full-port
 * Covenant-source-reference: gdx-gltf/gltf/src/net/mgsx/gltf/scene3d/utils/IBLBuilder.java
 * Covenant-verified: 2026-04-18
 */
package sge
package gltf
package scene3d
package utils

import sge.{ Pixels, Sge }
import sge.graphics.{ BlendFactor, ClearMask, Color, Cubemap, EnableCap }
import sge.graphics.Texture.TextureFilter
import sge.graphics.g3d.environment.DirectionalLight
import sge.graphics.glutils.{ FrameBuffer, FrameBufferCubemap, ShaderProgram, ShapeRenderer }
import sge.graphics.glutils.ShapeRenderer.ShapeType
import sge.graphics.Pixmap
import sge.math.{ Matrix4, Vector3 }
import sge.utils.{ DynamicArray, Nullable, ScreenUtils, SgeError }

class IBLBuilder private (using sge: Sge) extends AutoCloseable {

  val nearGroundColor: Color = Color()
  val farGroundColor:  Color = Color()
  val nearSkyColor:    Color = Color()
  val farSkyColor:     Color = Color()

  val lights: DynamicArray[IBLBuilder.Light] = DynamicArray[IBLBuilder.Light]()

  var renderSun:      Boolean = true
  var renderGradient: Boolean = true

  private val sunShader: ShaderProgram = ShaderProgram(
    sge.files.classpath("net/mgsx/gltf/shaders/ibl-sun.vs.glsl"),
    sge.files.classpath("net/mgsx/gltf/shaders/ibl-sun.fs.glsl")
  )
  if (!sunShader.compiled) throw SgeError.InvalidInput(sunShader.log)

  private val shapes:    ShapeRenderer = ShapeRenderer(20)
  private val sunShapes: ShapeRenderer = ShapeRenderer(20, Nullable(sunShader))

  shapes.projectionMatrix.setToOrtho2D(0f, 0f, 1f, 1f)
  sunShapes.projectionMatrix.setToOrtho2D(0f, 0f, 1f, 1f)

  override def close(): Unit = {
    sunShader.close()
    sunShapes.close()
    shapes.close()
  }

  /** Create an environment map, to be used with SceneSkybox.
    * @param size
    *   base size (width and height) for generated cubemap
    * @return
    *   generated cubemap, caller is responsible to close it when no longer used.
    */
  def buildEnvMap(size: Int): Cubemap = {
    val fbo = new FrameBufferCubemap(Pixmap.Format.RGBA8888, size, size, false) {
      override protected def disposeColorTexture(colorTexture: Cubemap): Unit = {
        // intentionally empty — preserve the cubemap after FBO disposal
      }
    }
    fbo.begin()
    while (fbo.nextSide()) {
      val gl = sge.graphics.gl20
      gl.glClearColor(0, 0, 0, 0)
      gl.glClear(ClearMask.ColorBufferBit)
      fbo.side.foreach { side =>
        renderGradientForSide(side, 0)
        renderLightsForSide(side, false)
      }
    }
    fbo.end()
    val map = fbo.colorBufferTexture
    fbo.close()
    map
  }

  /** Creates an irradiance map, to be used with PBRCubemapAttribute.DiffuseEnv.
    * @param size
    *   base size (width and height) for generated cubemap
    * @return
    *   generated cubemap, caller is responsible to close it when no longer used.
    */
  def buildIrradianceMap(size: Int): Cubemap = {
    val fbo = new FrameBufferCubemap(Pixmap.Format.RGBA8888, size, size, false) {
      override protected def disposeColorTexture(colorTexture: Cubemap): Unit = {
        // intentionally empty — preserve the cubemap after FBO disposal
      }
    }
    fbo.begin()
    while (fbo.nextSide()) {
      val gl = sge.graphics.gl20
      gl.glClearColor(0, 0, 0, 0)
      gl.glClear(ClearMask.ColorBufferBit)
      fbo.side.foreach { side =>
        renderGradientForSide(side, 0.5f)
        renderLightsForSide(side, true)
      }
    }
    fbo.end()
    val map = fbo.colorBufferTexture
    fbo.close()
    map
  }

  /** Creates a radiance map, to be used with PBRCubemapAttribute.SpecularEnv. Generated cubemap contains mipmaps in order to perform roughness in PBR shading.
    * @param mipMapLevels
    *   how many mipmaps level, eg. 10 levels produce a 1024x1024 cubemap with mipmaps.
    * @return
    *   generated cubemap, caller is responsible to close it when no longer used.
    */
  def buildRadianceMap(mipMapLevels: Int): Cubemap = {
    val maps  = new Array[Pixmap](mipMapLevels * 6)
    var index = 0
    var level = 0
    while (level < mipMapLevels) {
      val size = 1 << (mipMapLevels - level - 1)
      val fbo  = FrameBuffer(Pixmap.Format.RGBA8888, Pixels(size), Pixels(size), false)
      fbo.begin()
      var s = 0
      while (s < 6) {
        val gl = sge.graphics.gl20
        gl.glClearColor(0, 0, 0, 0)
        gl.glClear(ClearMask.ColorBufferBit)

        val side = Cubemap.CubemapSide.values(s)
        val blur = level.toFloat / mipMapLevels.toFloat

        renderGradientForSide(side, blur)
        renderLightsForSide(side, false)

        maps(index) = ScreenUtils.getFrameBufferPixmap(Pixels.zero, Pixels.zero, Pixels(size), Pixels(size))
        index += 1
        s += 1
      }
      fbo.end()
      fbo.close()
      level += 1
    }
    val data = FacedMultiCubemapData(maps, mipMapLevels)
    val map  = Cubemap(data)
    map.setFilter(TextureFilter.MipMap, TextureFilter.Linear)
    map
  }

  private def renderGradientForSide(side: Cubemap.CubemapSide, blur: Float): Unit = scala.util.boundary {
    if (!renderGradient) scala.util.boundary.break(())

    val aveSky     = farSkyColor.cpy().lerp(nearSkyColor, 0.5f)
    val aveGnd     = farGroundColor.cpy().lerp(nearGroundColor, 0.5f)
    val ave        = aveSky.cpy().lerp(aveGnd, 0.5f)
    val aveHorizon = farGroundColor.cpy().lerp(farSkyColor, 0.5f)

    // blur!
    val t2 = 1 - Math.pow(1 - blur, 4).toFloat
    val t  = 1 - Math.pow(1 - blur, 1).toFloat

    val ngc = nearGroundColor.cpy().lerp(ave, t)
    val nsc = nearSkyColor.cpy().lerp(ave, t)

    val fgc = farGroundColor.cpy().lerp(aveHorizon, t2).lerp(ave, t)
    val fsc = farSkyColor.cpy().lerp(aveHorizon, t2).lerp(ave, t)

    shapes.begin(ShapeType.Filled)
    if (side == Cubemap.CubemapSide.PositiveY) {
      shapes.rectangle(0, 0, 1, 1, nsc, nsc, nsc, nsc)
    } else if (side == Cubemap.CubemapSide.NegativeY) {
      shapes.rectangle(0, 0, 1, 1, ngc, ngc, ngc, ngc)
    } else {
      // draw vertical gradient
      shapes.rectangle(0, 0, 1, 0.5f, nsc, nsc, fsc, fsc)
      shapes.rectangle(0, 0.5f, 1, 0.5f, fgc, fgc, ngc, ngc)
    }
    shapes.end()
  }

  private def renderLightsForSide(side: Cubemap.CubemapSide, blured: Boolean): Unit = {
    val gl = sge.graphics.gl20
    gl.glEnable(EnableCap.Blend)
    gl.glBlendFunc(BlendFactor.SrcAlpha, BlendFactor.One)

    var i = 0
    while (i < lights.size) {
      val light = lights(i)
      if (blured) {
        light.render(side, sunShapes, sunShader, 0.5f, 1f)
      } else {
        light.render(side, sunShapes, sunShader, 1f)
      }
      i += 1
    }

    gl.glDisable(EnableCap.Blend)
    gl.glBlendFunc(BlendFactor.SrcAlpha, BlendFactor.OneMinusSrcAlpha)
  }
}

object IBLBuilder {

  def createOutdoor(sun: DirectionalLight)(using Sge): IBLBuilder = {
    val ibl = IBLBuilder()
    ibl.nearGroundColor.set(0.5f, 0.45f, 0.4f, 1f)
    ibl.farGroundColor.set(0.3f, 0.25f, 0.2f, 1f)
    ibl.nearSkyColor.set(0.7f, 0.8f, 1f, 1f)
    ibl.farSkyColor.set(0.9f, 0.95f, 1f, 1f)
    val light = Light()
    light.direction.set(sun.direction).nor()
    light.color.set(sun.color)
    light.exponent = 30f
    ibl.lights.add(light)
    ibl
  }

  def createIndoor(sun: DirectionalLight)(using Sge): IBLBuilder = {
    val ibl  = IBLBuilder()
    val tint = Color(1f, 0.9f, 0.8f, 1f).mul(0.3f)
    ibl.nearGroundColor.set(tint).mul(0.7f)
    ibl.farGroundColor.set(tint)
    ibl.farSkyColor.set(tint)
    ibl.nearSkyColor.set(tint).mul(2f)
    val light = Light()
    light.direction.set(sun.direction).nor()
    light.color.set(1f, 0.5f, 0f, 1f).mul(0.3f)
    light.exponent = 3f
    ibl.lights.add(light)
    ibl
  }

  def createCustom(sun: DirectionalLight)(using Sge): IBLBuilder = {
    val ibl   = IBLBuilder()
    val light = Light()
    light.direction.set(sun.direction).nor()
    light.color.set(sun.color)
    light.exponent = 100f
    ibl.lights.add(light)
    ibl
  }

  class Light {
    val color:     Color   = Color(1f, 1f, 1f, 1f)
    val direction: Vector3 = Vector3(0f, -1f, 0f)
    var exponent:  Float   = 30f

    def render(side: Cubemap.CubemapSide, shapes: ShapeRenderer, shader: ShaderProgram, strength: Float): Unit =
      render(side, shapes, shader, strength, exponent)

    def render(side: Cubemap.CubemapSide, shapes: ShapeRenderer, shader: ShaderProgram, strength: Float, exponent: Float): Unit = {
      shader.bind()
      shader.setUniformf("u_exponent", exponent)
      shader.setUniformf("u_ambient", color.r, color.g, color.b, 0f)
      shader.setUniformf("u_diffuse", color.r, color.g, color.b, strength)

      Light.localDir.set(side.direction)
      Light.localUp.set(side.up)

      // XXX patch
      if (side == Cubemap.CubemapSide.NegativeX || side == Cubemap.CubemapSide.PositiveX) {
        Light.localDir.x = -Light.localDir.x
      }

      Light.matrix.setToLookAt(Light.localDir, Light.localUp).tra()
      Light.localSunDir.set(direction).scl(-1, -1, 1).mul(Light.matrix) // XXX patch again

      shader.setUniformf("u_direction", Light.localSunDir)

      shapes.begin(ShapeType.Filled)
      shapes.rectangle(0, 0, 1, 1)
      shapes.end()
    }
  }

  object Light {
    private val localSunDir: Vector3 = Vector3()
    private val localDir:    Vector3 = Vector3()
    private val localUp:     Vector3 = Vector3()
    private val matrix:      Matrix4 = Matrix4()
  }
}
