/*
 * Ported from TextraTypist - https://github.com/tommyettinger/textratypist
 * Original source: com/github/tommyettinger/textra/FWSkin.java
 * Licensed under the Apache License, Version 2.0
 *
 * Scala port copyright 2025-2026 Mateusz Kubuszok
 *
 * Migration notes:
 *   Renames: Skin → sge.scenes.scene2d.ui.Skin, Json/JsonValue → sge.utils.Json AST,
 *     SerializationException → SgeError, Gdx.files → Sge().files,
 *     Viewport → sge.utils.viewport.Viewport
 *   Convention: getJsonLoader() override replaced by load() override that calls
 *     super.load() then does a second pass to create Font and TextraTypist style
 *     objects from the skin JSON (SGE Skin uses SkinStyleReader + Json AST, not
 *     libGDX's Json serializer framework).
 *   Idiom: boundary/break for early returns; Nullable[A] for nullable fields;
 *     split packages; no return keyword.
 *
 * Covenant: full-port
 * Covenant-baseline-spec-pass: 0
 * Covenant-baseline-loc: 607
 * Covenant-baseline-methods: FWSkin,allFonts,atlasFile,fontFile,fontPath,fw,getBoolField,getField,getFloatField,getStringField,hAdj,js,jslzma,load,loadFontsFromBitmapFontSection,loadFontsFromFontSection,loadTextraCheckBoxStyles,loadTextraImageTextButtonStyles,loadTextraLabelStyles,loadTextraListStyles,loadTextraSelectBoxStyles,loadTextraTextButtonStyles,loadTextraTextFieldStyles,loadTextraTextTooltipStyles,loadTextraWindowStyles,lzb,makeGridGlyphs,nameStart,path,readFont,regionName,resizeDistanceFields,scaledSize,this,ubj,ublzma,useIntegerPositions,wAdj,xAdj,yAdj
 * Covenant-source-reference: com/github/tommyettinger/textra/FWSkin.java
 * Covenant-verified: 2026-04-19
 *
 * upstream-commit: 3fe5c930acc9d66cb0ab1a29751e44591c18e2c4
 */
package sge
package textra

import sge.files.FileHandle
import sge.graphics.Color
import sge.graphics.Texture
import sge.graphics.g2d.TextureAtlas
import sge.graphics.g2d.TextureRegion
import sge.scenes.scene2d.ui.CheckBox
import sge.scenes.scene2d.ui.ImageTextButton
import sge.scenes.scene2d.ui.Label
import sge.scenes.scene2d.ui.SelectBox
import sge.scenes.scene2d.ui.SgeList
import sge.scenes.scene2d.ui.Skin
import sge.scenes.scene2d.ui.TextButton
import sge.scenes.scene2d.ui.TextField
import sge.scenes.scene2d.ui.TextTooltip
import sge.scenes.scene2d.ui.Window
import sge.utils.Json
import sge.utils.Nullable
import sge.utils.SgeError
import sge.utils.given
import sge.utils.readJson
import sge.utils.viewport.Viewport

/** A subclass of Skin that includes a serializer for Structured JSON Fonts, which are typically generated by fontwriter (hence the "FW" in the name). This can load FontWriter's JSON format into both
  * Font and BitmapFont objects, from the same files. These files can have a variety of extensions depending on if or how they are compressed: .json, .dat, .ubj, .json.lzma, or .ubj.lzma; .json.lzma
  * is currently preferred.
  *
  * This class is also important when using the styles in Styles, since it allows reading in a skin JSON's styles both as the scene2d.ui format and as styles for TextraTypist widgets.
  */
class FWSkin()(using Sge) extends Skin() {

  /** Creates a skin containing the resources in the specified skin JSON file. If a file in the same directory with a ".atlas" extension exists, it is loaded as a TextureAtlas and the texture regions
    * added to the skin. The atlas is automatically disposed when the skin is disposed.
    * @param skinFile
    *   The JSON file to be read.
    */
  def this(skinFile: FileHandle)(using Sge) = {
    this()
    val atlasFile = skinFile.sibling(skinFile.nameWithoutExtension + ".atlas")
    if (atlasFile.exists()) {
      val atlas = TextureAtlas(atlasFile)
      addRegions(atlas)
    }
    load(skinFile)
  }

  /** Creates a skin containing the resources in the specified skin JSON file and the texture regions from the specified atlas. The atlas is automatically disposed when the skin is disposed.
    * @param skinFile
    *   The JSON file to be read.
    * @param atlas
    *   The texture atlas to be associated with the Skin.
    */
  def this(skinFile: FileHandle, atlas: TextureAtlas)(using Sge) = {
    this()
    addRegions(atlas)
    load(skinFile)
  }

  /** Creates a skin containing the texture regions from the specified atlas. The atlas is automatically disposed when the skin is disposed.
    * @param atlas
    *   The texture atlas to be associated with the Skin.
    */
  def this(atlas: TextureAtlas)(using Sge) = {
    this()
    addRegions(atlas)
  }

  /** Overrides load to first perform standard skin loading, then re-reads the skin JSON to create Font objects from BitmapFont entries and TextraTypist styles from scene2d widget style entries.
    */
  override def load(skinFile: FileHandle): Unit = {
    // First, do the standard skin loading (BitmapFont, Color, widget styles, etc.)
    super.load(skinFile)

    // Second pass: re-read the JSON to create Font and TextraTypist style objects.
    try {
      val root = skinFile.readJson[Json]
      root match {
        case Json.Obj(rootObj) =>
          rootObj.fields.foreach { case (typeName, typeValue) =>
            typeName match {
              case "Font" | "com.github.tommyettinger.textra.Font" =>
                loadFontsFromFontSection(typeValue, skinFile)
              case "BitmapFont" | "com.badlogic.gdx.graphics.g2d.BitmapFont" =>
                loadFontsFromBitmapFontSection(typeValue, skinFile)
              case "LabelStyle" | "com.badlogic.gdx.scenes.scene2d.ui.Label$LabelStyle" =>
                loadTextraLabelStyles(typeValue)
              case "TextButtonStyle" | "com.badlogic.gdx.scenes.scene2d.ui.TextButton$TextButtonStyle" =>
                loadTextraTextButtonStyles(typeValue)
              case "ImageTextButtonStyle" | "com.badlogic.gdx.scenes.scene2d.ui.ImageTextButton$ImageTextButtonStyle" =>
                loadTextraImageTextButtonStyles(typeValue)
              case "CheckBoxStyle" | "com.badlogic.gdx.scenes.scene2d.ui.CheckBox$CheckBoxStyle" =>
                loadTextraCheckBoxStyles(typeValue)
              case "WindowStyle" | "com.badlogic.gdx.scenes.scene2d.ui.Window$WindowStyle" =>
                loadTextraWindowStyles(typeValue)
              case "TextTooltipStyle" | "com.badlogic.gdx.scenes.scene2d.ui.TextTooltip$TextTooltipStyle" =>
                loadTextraTextTooltipStyles(typeValue)
              case "ListStyle" | "com.badlogic.gdx.scenes.scene2d.ui.List$ListStyle" =>
                loadTextraListStyles(typeValue)
              case "SelectBoxStyle" | "com.badlogic.gdx.scenes.scene2d.ui.SelectBox$SelectBoxStyle" =>
                loadTextraSelectBoxStyles(typeValue)
              case "TextFieldStyle" | "com.badlogic.gdx.scenes.scene2d.ui.TextField$TextFieldStyle" =>
                loadTextraTextFieldStyles(typeValue)
              case _ => () // handled by super.load
            }
          }
        case _ => ()
      }
    } catch {
      case ex: SgeError  => throw ex
      case ex: Exception =>
        throw SgeError.InvalidInput("Error reading FWSkin file: " + skinFile + ": " + ex.getMessage)
    }
  }

  // ---------------------------------------------------------------------------
  // Font loading from BitmapFont JSON entries
  // ---------------------------------------------------------------------------

  /** Reads standalone Font entries from the skin JSON and creates corresponding Font objects directly. Unlike BitmapFont entries which create both a BitmapFont and a Font, these entries only create
    * Font objects.
    */
  private def loadFontsFromFontSection(typeValue: Json, skinFile: FileHandle): Unit =
    typeValue match {
      case Json.Obj(entries) =>
        entries.fields.foreach { case (entryName, jsonData) =>
          try {
            val font = readFont(jsonData, skinFile)
            add(entryName, font, classOf[Font])
          } catch {
            case ex: RuntimeException =>
              throw SgeError.InvalidInput("Error loading Font entry: " + entryName + ": " + ex.getMessage)
          }
        }
      case _ => ()
    }

  /** Reads BitmapFont entries from the skin JSON and creates corresponding Font objects. Each BitmapFont entry that references a Structured JSON font file (.json, .dat, .ubj, .json.lzma, .ubj.lzma)
    * gets a Font created alongside the BitmapFont that super.load() already stored. For .fnt files, a Font is also created using the FNT data.
    */
  private def loadFontsFromBitmapFontSection(typeValue: Json, skinFile: FileHandle): Unit =
    typeValue match {
      case Json.Obj(entries) =>
        entries.fields.foreach { case (entryName, jsonData) =>
          try {
            val font = readFont(jsonData, skinFile)
            add(entryName, font, classOf[Font])
          } catch {
            case ex: RuntimeException =>
              throw SgeError.InvalidInput("Error loading Font from BitmapFont entry: " + entryName + ": " + ex.getMessage)
          }
        }
      case _ => ()
    }

  /** Creates a Font from BitmapFont JSON data, handling both Structured JSON fonts (.json, .dat, .ubj, .json.lzma, .ubj.lzma) and .fnt files.
    */
  private def readFont(jsonData: Json, skinFile: FileHandle): Font = {
    val path = getStringField(jsonData, "file", "")

    var fontFile = skinFile.sibling(path)
    if (!fontFile.exists()) fontFile = Sge().files.internal(path)
    if (!fontFile.exists()) throw SgeError.InvalidInput("Font file not found: " + fontFile)

    val fontPath = fontFile.path

    val lzb    = "dat".equalsIgnoreCase(fontFile.extension)
    val js     = "json".equalsIgnoreCase(fontFile.extension)
    val ubj    = "ubj".equalsIgnoreCase(fontFile.extension)
    val jslzma = fontFile.name.length > 10 && ".json.lzma".equalsIgnoreCase(fontFile.name.substring(fontFile.name.length - 10))
    val ublzma = fontFile.name.length > 9 && ".ubj.lzma".equalsIgnoreCase(fontFile.name.substring(fontFile.name.length - 9))
    val fw     = lzb || js || ubj || jslzma || ublzma

    val scaledSize = getFloatField(jsonData, "scaledSize", -1f)
    val xAdj       = getFloatField(jsonData, "xAdjust", 0f)
    val yAdj       = getFloatField(jsonData, "yAdjust", 0f)
    val wAdj       = getFloatField(jsonData, "widthAdjust", 0f)
    val hAdj       = getFloatField(jsonData, "heightAdjust", 0f)
    // This defaults to false, which is not what Skin normally defaults to.
    // You can set it to true if you expect a BitmapFont to be used at pixel-perfect 100% zoom only.
    val useIntegerPositions = getBoolField(jsonData, "useIntegerPositions", false)
    // This defaults to true, because anything FontWriter produces is compatible with makeGridGlyphs.
    val makeGridGlyphs = getBoolField(jsonData, "makeGridGlyphs", true)

    // Use a region with the same name as the font, else use a PNG file in the same directory as the font file.
    val nameStart  = Math.max(fontPath.lastIndexOf('/'), fontPath.lastIndexOf('\\')) + 1
    val regionName = fontPath.substring(nameStart, Math.max(0, fontPath.indexOf('.', nameStart)))
    try {
      val font    = new Font()
      val regions = getRegions(regionName)
      if (regions.isDefined) {
        val firstRegion = regions.get.apply(0)
        if (fw) {
          font.loadJSON(fontFile, firstRegion, xAdj, yAdj, wAdj, hAdj, makeGridGlyphs)
        } else {
          font.loadFNT(fontFile, xAdj, yAdj, wAdj, hAdj, makeGridGlyphs)
        }
      } else {
        val region = optional(regionName, classOf[TextureRegion])
        if (region.isDefined) {
          if (fw) {
            font.loadJSON(fontFile, region.get, xAdj, yAdj, wAdj, hAdj, makeGridGlyphs)
          } else {
            font.loadFNT(fontFile, xAdj, yAdj, wAdj, hAdj, makeGridGlyphs)
          }
        } else {
          val imageFile = Sge().files.internal(fontPath).sibling(regionName + ".png")
          if (imageFile.exists()) {
            val texRegion = TextureRegion(Texture(imageFile))
            if (fw) {
              font.loadJSON(fontFile, texRegion, xAdj, yAdj, wAdj, hAdj, makeGridGlyphs)
            } else {
              font.loadFNT(fontFile, xAdj, yAdj, wAdj, hAdj, makeGridGlyphs)
            }
          } else {
            if (fw) {
              throw RuntimeException("Missing image file or TextureRegion.")
            } else {
              font.loadFNT(fontFile, xAdj, yAdj, wAdj, hAdj, makeGridGlyphs)
            }
          }
        }
      }
      font.useIntegerPositions(useIntegerPositions)
      // Scaled size is the desired line height to scale the font to.
      // This is different from with BitmapFont, which has a desired cap height.
      if (scaledSize != -1) font.scaleHeightTo(scaledSize)
      font
    } catch {
      case ex: RuntimeException =>
        throw SgeError.InvalidInput("Error loading Font: " + fontPath + ": " + ex.getMessage)
    }
  }

  // ---------------------------------------------------------------------------
  // TextraTypist style loading
  // ---------------------------------------------------------------------------

  /** For each LabelStyle entry, creates a corresponding Styles.LabelStyle and adds it to the skin. */
  private def loadTextraLabelStyles(typeValue: Json): Unit =
    typeValue match {
      case Json.Obj(entries) =>
        entries.fields.foreach { case (entryName, jsonData) =>
          val s2d      = get(entryName, classOf[Label.LabelStyle])
          val fontName = getStringField(jsonData, "font", "default-font")
          val fontOpt  = optional(fontName, classOf[Font])
          fontOpt.foreach { font =>
            val stt = new Styles.LabelStyle(font, s2d.fontColor)
            stt.background = s2d.background.map(_.asInstanceOf[AnyRef])
            add(entryName, stt, classOf[Styles.LabelStyle])
          }
        }
      case _ => ()
    }

  /** For each TextButtonStyle entry, creates a corresponding Styles.TextButtonStyle. */
  private def loadTextraTextButtonStyles(typeValue: Json): Unit =
    typeValue match {
      case Json.Obj(entries) =>
        entries.fields.foreach { case (entryName, jsonData) =>
          val s2d      = get(entryName, classOf[TextButton.TextButtonStyle])
          val fontName = getStringField(jsonData, "font", "default-font")
          val fontOpt  = optional(fontName, classOf[Font])
          fontOpt.foreach { font =>
            val stt = new Styles.TextButtonStyle(
              s2d.up.map(_.asInstanceOf[AnyRef]),
              s2d.down.map(_.asInstanceOf[AnyRef]),
              s2d.checked.map(_.asInstanceOf[AnyRef]),
              Nullable(font)
            )

            s2d.fontColor.foreach(c => stt.fontColor = Nullable(new Color(c)))
            s2d.downFontColor.foreach(c => stt.downFontColor = Nullable(new Color(c)))
            s2d.overFontColor.foreach(c => stt.overFontColor = Nullable(new Color(c)))
            s2d.focusedFontColor.foreach(c => stt.focusedFontColor = Nullable(new Color(c)))
            s2d.disabledFontColor.foreach(c => stt.disabledFontColor = Nullable(new Color(c)))

            s2d.checkedFontColor.foreach(c => stt.checkedFontColor = Nullable(new Color(c)))
            s2d.checkedDownFontColor.foreach(c => stt.checkedDownFontColor = Nullable(new Color(c)))
            s2d.checkedOverFontColor.foreach(c => stt.checkedOverFontColor = Nullable(new Color(c)))
            s2d.checkedFocusedFontColor.foreach(c => stt.checkedFocusedFontColor = Nullable(new Color(c)))

            stt.checkedDown = s2d.checkedDown.map(_.asInstanceOf[AnyRef])
            stt.checkedFocused = s2d.checkedFocused.map(_.asInstanceOf[AnyRef])
            stt.checkedOver = s2d.checkedOver.map(_.asInstanceOf[AnyRef])
            stt.disabled = s2d.disabled.map(_.asInstanceOf[AnyRef])
            stt.focused = s2d.focused.map(_.asInstanceOf[AnyRef])
            stt.over = s2d.over.map(_.asInstanceOf[AnyRef])
            stt.checkedOffsetX = s2d.checkedOffsetX
            stt.checkedOffsetY = s2d.checkedOffsetY
            stt.pressedOffsetX = s2d.pressedOffsetX
            stt.pressedOffsetY = s2d.pressedOffsetY
            stt.unpressedOffsetX = s2d.unpressedOffsetX
            stt.unpressedOffsetY = s2d.unpressedOffsetY

            add(entryName, stt, classOf[Styles.TextButtonStyle])
          }
        }
      case _ => ()
    }

  /** For each ImageTextButtonStyle entry, creates a corresponding Styles.ImageTextButtonStyle. */
  private def loadTextraImageTextButtonStyles(typeValue: Json): Unit =
    typeValue match {
      case Json.Obj(entries) =>
        entries.fields.foreach { case (entryName, jsonData) =>
          val s2d      = get(entryName, classOf[ImageTextButton.ImageTextButtonStyle])
          val fontName = getStringField(jsonData, "font", "default-font")
          val fontOpt  = optional(fontName, classOf[Font])
          fontOpt.foreach { font =>
            val stt = new Styles.ImageTextButtonStyle(
              s2d.up.map(_.asInstanceOf[AnyRef]),
              s2d.down.map(_.asInstanceOf[AnyRef]),
              s2d.checked.map(_.asInstanceOf[AnyRef]),
              Nullable(font)
            )
            s2d.fontColor.foreach(c => stt.fontColor = Nullable(new Color(c)))
            s2d.downFontColor.foreach(c => stt.downFontColor = Nullable(new Color(c)))
            s2d.overFontColor.foreach(c => stt.overFontColor = Nullable(new Color(c)))
            s2d.focusedFontColor.foreach(c => stt.focusedFontColor = Nullable(new Color(c)))
            s2d.disabledFontColor.foreach(c => stt.disabledFontColor = Nullable(new Color(c)))

            s2d.checkedFontColor.foreach(c => stt.checkedFontColor = Nullable(new Color(c)))
            s2d.checkedDownFontColor.foreach(c => stt.checkedDownFontColor = Nullable(new Color(c)))
            s2d.checkedOverFontColor.foreach(c => stt.checkedOverFontColor = Nullable(new Color(c)))
            s2d.checkedFocusedFontColor.foreach(c => stt.checkedFocusedFontColor = Nullable(new Color(c)))

            stt.imageUp = s2d.imageUp.map(_.asInstanceOf[AnyRef])
            stt.imageDown = s2d.imageDown.map(_.asInstanceOf[AnyRef])
            stt.imageOver = s2d.imageOver.map(_.asInstanceOf[AnyRef])
            stt.imageDisabled = s2d.imageDisabled.map(_.asInstanceOf[AnyRef])
            stt.imageChecked = s2d.imageChecked.map(_.asInstanceOf[AnyRef])
            stt.imageCheckedDown = s2d.imageCheckedDown.map(_.asInstanceOf[AnyRef])
            stt.imageCheckedOver = s2d.imageCheckedOver.map(_.asInstanceOf[AnyRef])

            stt.checkedDown = s2d.checkedDown.map(_.asInstanceOf[AnyRef])
            stt.checkedFocused = s2d.checkedFocused.map(_.asInstanceOf[AnyRef])
            stt.checkedOver = s2d.checkedOver.map(_.asInstanceOf[AnyRef])
            stt.disabled = s2d.disabled.map(_.asInstanceOf[AnyRef])
            stt.focused = s2d.focused.map(_.asInstanceOf[AnyRef])
            stt.over = s2d.over.map(_.asInstanceOf[AnyRef])
            stt.checkedOffsetX = s2d.checkedOffsetX
            stt.checkedOffsetY = s2d.checkedOffsetY
            stt.pressedOffsetX = s2d.pressedOffsetX
            stt.pressedOffsetY = s2d.pressedOffsetY
            stt.unpressedOffsetX = s2d.unpressedOffsetX
            stt.unpressedOffsetY = s2d.unpressedOffsetY

            add(entryName, stt, classOf[Styles.ImageTextButtonStyle])
          }
        }
      case _ => ()
    }

  /** For each CheckBoxStyle entry, creates a corresponding Styles.CheckBoxStyle. */
  private def loadTextraCheckBoxStyles(typeValue: Json): Unit =
    typeValue match {
      case Json.Obj(entries) =>
        entries.fields.foreach { case (entryName, jsonData) =>
          val s2d      = get(entryName, classOf[CheckBox.CheckBoxStyle])
          val fontName = getStringField(jsonData, "font", "default-font")
          val fontOpt  = optional(fontName, classOf[Font])
          fontOpt.foreach { font =>
            val stt = new Styles.CheckBoxStyle(
              s2d.checkboxOff.map(_.asInstanceOf[AnyRef]),
              s2d.checkboxOn.map(_.asInstanceOf[AnyRef]),
              Nullable(font),
              s2d.fontColor
            )

            s2d.fontColor.foreach(c => stt.fontColor = Nullable(new Color(c)))
            s2d.downFontColor.foreach(c => stt.downFontColor = Nullable(new Color(c)))
            s2d.overFontColor.foreach(c => stt.overFontColor = Nullable(new Color(c)))
            s2d.focusedFontColor.foreach(c => stt.focusedFontColor = Nullable(new Color(c)))
            s2d.disabledFontColor.foreach(c => stt.disabledFontColor = Nullable(new Color(c)))

            s2d.checkedFontColor.foreach(c => stt.checkedFontColor = Nullable(new Color(c)))
            s2d.checkedDownFontColor.foreach(c => stt.checkedDownFontColor = Nullable(new Color(c)))
            s2d.checkedOverFontColor.foreach(c => stt.checkedOverFontColor = Nullable(new Color(c)))
            s2d.checkedFocusedFontColor.foreach(c => stt.checkedFocusedFontColor = Nullable(new Color(c)))

            stt.checkboxOnOver = s2d.checkboxOnOver.map(_.asInstanceOf[AnyRef])
            stt.checkboxOver = s2d.checkboxOver.map(_.asInstanceOf[AnyRef])
            stt.checkboxOnDisabled = s2d.checkboxOnDisabled.map(_.asInstanceOf[AnyRef])
            stt.checkboxOffDisabled = s2d.checkboxOffDisabled.map(_.asInstanceOf[AnyRef])

            stt.checkedDown = s2d.checkedDown.map(_.asInstanceOf[AnyRef])
            stt.checkedFocused = s2d.checkedFocused.map(_.asInstanceOf[AnyRef])
            stt.checkedOver = s2d.checkedOver.map(_.asInstanceOf[AnyRef])
            stt.disabled = s2d.disabled.map(_.asInstanceOf[AnyRef])
            stt.focused = s2d.focused.map(_.asInstanceOf[AnyRef])
            stt.over = s2d.over.map(_.asInstanceOf[AnyRef])
            stt.checkedOffsetX = s2d.checkedOffsetX
            stt.checkedOffsetY = s2d.checkedOffsetY
            stt.pressedOffsetX = s2d.pressedOffsetX
            stt.pressedOffsetY = s2d.pressedOffsetY
            stt.unpressedOffsetX = s2d.unpressedOffsetX
            stt.unpressedOffsetY = s2d.unpressedOffsetY

            stt.down = s2d.down.map(_.asInstanceOf[AnyRef])
            stt.up = s2d.up.map(_.asInstanceOf[AnyRef])
            stt.checked = s2d.checked.map(_.asInstanceOf[AnyRef])

            add(entryName, stt, classOf[Styles.CheckBoxStyle])
          }
        }
      case _ => ()
    }

  /** For each WindowStyle entry, creates a corresponding Styles.WindowStyle. */
  private def loadTextraWindowStyles(typeValue: Json): Unit =
    typeValue match {
      case Json.Obj(entries) =>
        entries.fields.foreach { case (entryName, jsonData) =>
          val s2d      = get(entryName, classOf[Window.WindowStyle])
          val fontName = getStringField(jsonData, "titleFont", "default-font")
          val fontOpt  = optional(fontName, classOf[Font])
          fontOpt.foreach { font =>
            val titleColor = s2d.titleFontColor.getOrElse(Color(1, 1, 1, 1))
            val stt        = new Styles.WindowStyle(font, titleColor, Nullable(s2d.background.asInstanceOf[AnyRef]))
            stt.stageBackground = s2d.stageBackground.map(_.asInstanceOf[AnyRef])
            add(entryName, stt, classOf[Styles.WindowStyle])
          }
        }
      case _ => ()
    }

  /** For each TextTooltipStyle entry, creates a corresponding Styles.TextTooltipStyle. */
  private def loadTextraTextTooltipStyles(typeValue: Json): Unit =
    typeValue match {
      case Json.Obj(entries) =>
        entries.fields.foreach { case (entryName, jsonData) =>
          val s2d            = get(entryName, classOf[TextTooltip.TextTooltipStyle])
          val labelStyleName = getStringField(jsonData, "label", "default")
          val labelStyleOpt  = optional(labelStyleName, classOf[Styles.LabelStyle])
          labelStyleOpt.foreach { labelStyle =>
            val tt = new Styles.TextTooltipStyle(labelStyle, s2d.background.map(_.asInstanceOf[AnyRef]))
            tt.wrapWidth = s2d.wrapWidth
            add(entryName, tt, classOf[Styles.TextTooltipStyle])
          }
        }
      case _ => ()
    }

  /** For each ListStyle entry, creates a corresponding Styles.ListStyle. */
  private def loadTextraListStyles(typeValue: Json): Unit =
    typeValue match {
      case Json.Obj(entries) =>
        entries.fields.foreach { case (entryName, jsonData) =>
          val s2d      = get(entryName, classOf[SgeList.ListStyle])
          val fontName = getStringField(jsonData, "font", "default-font")
          val fontOpt  = optional(fontName, classOf[Font])
          fontOpt.foreach { font =>
            val stt = new Styles.ListStyle(font, s2d.fontColorSelected, s2d.fontColorUnselected, Nullable(s2d.selection.asInstanceOf[AnyRef]))
            stt.background = s2d.background.map(_.asInstanceOf[AnyRef])
            stt.down = s2d.down.map(_.asInstanceOf[AnyRef])
            stt.over = s2d.over.map(_.asInstanceOf[AnyRef])
            add(entryName, stt, classOf[Styles.ListStyle])
          }
        }
      case _ => ()
    }

  /** For each SelectBoxStyle entry, creates a corresponding Styles.SelectBoxStyle. */
  private def loadTextraSelectBoxStyles(typeValue: Json): Unit =
    typeValue match {
      case Json.Obj(entries) =>
        entries.fields.foreach { case (entryName, jsonData) =>
          val s2d      = get(entryName, classOf[SelectBox.SelectBoxStyle])
          val fontName = getStringField(jsonData, "font", "default-font")
          val fontOpt  = optional(fontName, classOf[Font])
          fontOpt.foreach { font =>
            val listStyleName = getStringField(jsonData, "listStyle", "default")
            val lsOpt         = optional(listStyleName, classOf[Styles.ListStyle])

            lsOpt.foreach { ls =>
              val stt = new Styles.SelectBoxStyle(font, s2d.fontColor, s2d.background.map(_.asInstanceOf[AnyRef]), Nullable(s2d.scrollStyle.asInstanceOf[AnyRef]), ls)
              stt.background = s2d.background.map(_.asInstanceOf[AnyRef])
              stt.backgroundDisabled = s2d.backgroundDisabled.map(_.asInstanceOf[AnyRef])
              stt.backgroundOpen = s2d.backgroundOpen.map(_.asInstanceOf[AnyRef])
              stt.backgroundOver = s2d.backgroundOver.map(_.asInstanceOf[AnyRef])
              s2d.disabledFontColor.foreach(c => stt.disabledFontColor = Nullable(new Color(c)))
              s2d.overFontColor.foreach(c => stt.overFontColor = Nullable(new Color(c)))
              add(entryName, stt, classOf[Styles.SelectBoxStyle])
            }
          }
        }
      case _ => ()
    }

  /** For each TextFieldStyle entry, creates a corresponding Styles.TextFieldStyle. */
  private def loadTextraTextFieldStyles(typeValue: Json): Unit =
    typeValue match {
      case Json.Obj(entries) =>
        entries.fields.foreach { case (entryName, jsonData) =>
          val s2d      = get(entryName, classOf[TextField.TextFieldStyle])
          val fontName = getStringField(jsonData, "font", "default-font")
          val fontOpt  = optional(fontName, classOf[Font])
          fontOpt.foreach { font =>
            val stt = new Styles.TextFieldStyle(
              font,
              s2d.fontColor,
              s2d.cursor.map(_.asInstanceOf[AnyRef]),
              s2d.selection.map(_.asInstanceOf[AnyRef]),
              s2d.background.map(_.asInstanceOf[AnyRef])
            )
            s2d.messageFontColor.foreach(c => stt.messageFontColor = Nullable(new Color(c)))
            s2d.focusedFontColor.foreach(c => stt.focusedFontColor = Nullable(new Color(c)))
            s2d.disabledFontColor.foreach(c => stt.disabledFontColor = Nullable(new Color(c)))
            stt.focusedBackground = s2d.focusedBackground.map(_.asInstanceOf[AnyRef])
            stt.disabledBackground = s2d.disabledBackground.map(_.asInstanceOf[AnyRef])
            add(entryName, stt, classOf[Styles.TextFieldStyle])
          }
        }
      case _ => ()
    }

  // ---------------------------------------------------------------------------
  // Distance field resizing
  // ---------------------------------------------------------------------------

  /** Calls Font.resizeDistanceField(float, float) with the given width and height on every Font loaded by this skin. If you are mainly loading Font values via a skin, this can be called instead of
    * manually calling resizeDistanceField on each Font, and should be called in ApplicationListener.resize(int, int) (with width and height matching its parameters). Like Font's
    * resizeDistanceField(), this only has an effect on distance field fonts -- those that use SDF, MSDF, or SDF_OUTLINE for their getDistanceField.
    *
    * @param width
    *   should match the width in ApplicationListener.resize(int, int)
    * @param height
    *   should match the height in ApplicationListener.resize(int, int)
    */
  def resizeDistanceFields(width: Float, height: Float): Unit = {
    val allFonts = getAll(classOf[Font])
    allFonts.foreach { fonts =>
      fonts.values.foreach { font =>
        font.resizeDistanceField(width, height)
      }
    }
  }

  /** Calls Font.resizeDistanceField(float, float) with the given width and height on every Font loaded by this skin. This overload takes a Viewport, which helps inform the calculation to make the
    * edges the correct crispness. This does not change the given Viewport.
    *
    * @param width
    *   should match the width in ApplicationListener.resize(int, int)
    * @param height
    *   should match the height in ApplicationListener.resize(int, int)
    * @param viewport
    *   the viewport used for rendering; passed through to Font for crispness calculation
    */
  def resizeDistanceFields(width: Float, height: Float, viewport: Viewport): Unit = {
    val allFonts = getAll(classOf[Font])
    allFonts.foreach { fonts =>
      fonts.values.foreach { font =>
        font.resizeDistanceField(width, height, viewport)
      }
    }
  }

  // ---------------------------------------------------------------------------
  // JSON field access helpers (local to FWSkin since Skin's are private)
  // ---------------------------------------------------------------------------

  private def getField(json: Json, name: String): Option[Json] = json match {
    case Json.Obj(obj) =>
      var result: Option[Json] = None
      obj.fields.foreach { case (k, v) => if (k == name) result = Some(v) }
      result
    case _ => None
  }

  private def getStringField(json: Json, name: String, default: String): String =
    getField(json, name) match {
      case Some(Json.Str(s)) => s
      case _                 => default
    }

  private def getFloatField(json: Json, name: String, default: Float): Float =
    getField(json, name) match {
      case Some(Json.Num(n)) => n.toDouble.map(_.toFloat).getOrElse(default)
      case _                 => default
    }

  private def getBoolField(json: Json, name: String, default: Boolean): Boolean =
    getField(json, name) match {
      case Some(Json.Bool(b)) => b
      case _                  => default
    }
}
