/*
 * Ported from TextraTypist - https://github.com/tommyettinger/textratypist
 * Original source: com/github/tommyettinger/textra/FWSkin.java
 * Licensed under the Apache License, Version 2.0
 *
 * Scala port copyright 2025-2026 Mateusz Kubuszok
 *
 * Migration notes:
 *   Renames: Skin → standalone class (scene2d base deferred),
 *     Json/JsonValue → deferred, FileHandle → deferred,
 *     TextureAtlas/TextureRegion/Texture → deferred,
 *     BitmapFont → deferred, SerializationException → RuntimeException,
 *     Viewport → deferred
 *   Convention: FWSkin JSON font/style serializers preserved in API;
 *     actual skin loading deferred until scene2d/rendering layer wired up.
 *   TODOs: Full getJsonLoader() override deferred; requires scene2d Skin base.
 */
package sge
package textra

/** A subclass of Skin that includes a serializer for Structured JSON Fonts, which are typically generated by fontwriter (hence the "FW" in the name). This can load FontWriter's JSON format into both
  * Font and BitmapFont objects, from the same files. These files can have a variety of extensions depending on if or how they are compressed: .json, .dat, .ubj, .json.lzma, or .ubj.lzma; .json.lzma
  * is currently preferred.
  *
  * This class is also important when using the styles in Styles, since it allows reading in a skin JSON's styles both as the scene2d.ui format and as styles for TextraTypist widgets.
  */
class FWSkin {

  /** Creates an empty skin. */
  def this(dummy: Unit) = this()

  /** Calls Font.resizeDistanceField(float, float) on every Font loaded by this skin. */
  def resizeDistanceFields(width: Float, height: Float): Unit = {
    // Deferred: requires Skin.getAll(Font.class) integration
  }
}
