/*
 * Ported from colorful-gdx - https://github.com/tommyettinger/colorful-gdx
 * Original authors: Tommy Ettinger
 * Licensed under the Apache License, Version 2.0
 *
 * Scala port copyright 2025-2026 Mateusz Kubuszok
 *
 * Covenant: full-port
 * Covenant-baseline-spec-pass: 0
 * Covenant-baseline-loc: 811
 * Covenant-baseline-methods: ABSINTHE,AIR_FORCE_BLUE,AMAZONITE,ANGEL_WING,APPLE_GREEN,APRICOT,AQUAMARINE,ARMY_GREEN,ARTICHOKE,ASPARAGUS,AVOCADO,BANANA_PUDDING,BEIGE,BLACK,BLACKLIGHT_GLOW,BLUE,BLUEBERRY,BLUE_EYE,BLUE_SMOKE,BLUE_STEEL,BOLOGNA,BOYSENBERRY,BRICK,BRIGHT_RED,BRONZE_SKIN_1,BRONZE_SKIN_2,BRONZE_SKIN_3,BRONZE_SKIN_4,BROWN_VELVET,BUBBLE,BUBBLEGUM_PINK,BUBBLE_GUM,BURNT_YELLOW,CALM_SKY,CARMINE,CEDAR_WOOD,CELADON,CELERY,CHARTREUSE,CHERRY_SYRUP,CHINCHILLA,CHIPPED_GRANITE,CLOUD,COAL_BLACK,COLD_IRON,CORNFLOWER_BLUE,CORN_SILK,COTTON_CANDY,CREAM,CRICKET,CYAN,DARK_GRAY,DARK_PINE,DARK_SKIN_1,DARK_SKIN_2,DARK_SKIN_3,DARK_TEAL,DEEP_JUNGLE,DEEP_PURPLE,DEEP_TEAL,DENIM_BLUE,DESERT_RAIN,DRAB_GREEN,DREARY_BLUE,DRIED_SAGE,DRIFTWOOD,DRY_BRUSH,DRY_PEPPER,DULL_AZURE,DULL_GREEN,DULL_VIOLET,DUN,DUSTY_GRAPE,DUSTY_GREEN,DUSTY_PINK,DUST_BUNNY,EARWAX,EGGPLANT,ELECTRIC_BLUE,EMBERS,EMERALD,EMINENCE,EUCALYPTUS,FADED_BLUE,FAWN,FEATHER_DOWN,FERN_GREEN,FLAMINGO,FLORAL_FOAM,FOREST_GLEN,FROG_GREEN,FRUIT_PUNCH,GARTER_SNAKE,GRAPE_LOLLIPOP,GRAPE_SODA,GRAPHITE,GRAY,GRAY_GREEN,GREEN,GREYHOUND,HAM,HELIOTROPE,HIDDEN_BLUE,HONEYDEW,HOSPITAL_GREEN,HOT_SAUCE,HUNTER_GREEN,INDIGO,INFECTION,IOLITE,IRIS,IRON,IVY_GREEN,JADE,JUICY_GRAPE,KELLY_GREEN,KOA,KYANITE,LAVENDER,LEAD,LIGHT_GRAY,LIGHT_SKIN_1,LIGHT_SKIN_2,LIGHT_SKIN_3,LIGHT_SKIN_4,LIGHT_SKIN_5,LIGHT_SKIN_6,LIGHT_SKIN_7,LIGHT_SKIN_8,LIGHT_SKIN_9,LILAC,LIST,LIZARD_SCALES,LURID_RED,MAGENTA,MAIDENHAIR_FERN,MALACHITE,MARSH,MAUVE,MEDIUM_PLUM,MEDIUM_TEAL,MILD_VIOLET,MINT_GREEN,MOSS_GREEN,MULBERRY,MUMMY_BROWN,MURK,MUSH,NAMED,NAVY_BLUE,NIGHTSHADE,NINJA,OCEAN_BLUE,OCHRE,OLD_ROSE,OLIVE_GREEN,OLIVE_OIL,ORANGE,ORCHID,PASTEL_SKY,PATINA,PEACH,PEAT_BOG,PEA_SOUP,PENCIL_YELLOW,PERIWINKLE,PINE_GREEN,PINK_LEMONADE,PINK_SKIN_1,PINK_SKIN_2,PINK_SKIN_3,PINK_SKIN_4,PINK_TUTU,PINK_VIOLET,PISTACHIO,PLATINUM,PLUM_JUICE,POLISHED_SAPPHIRE,PORK_CHOP,POWDER_BLUE,PRASE,PRUNE,PRUSSIAN_BLUE,PUCE,PURPLE,PURPLE_FREESIA,PUTTY,Palette,RASPBERRY,RAW_MEAT,RED,REDWOOD,REFRESHING_MIST,RIPE_PLUM,RIPPED_DENIM,ROBIN_EGG_BLUE,ROSE,ROSEATE_SPOONBILL,ROUGH_SAPPHIRE,ROYAL_BLUE,ROYAL_VIOLET,SAFFRON,SAGE_GREEN,SALMON,SCRIBE_INK,SEAFOAM,SEAL_BROWN,SEAWATER,SHADOW,SHARP_AZURE,SHINING_SKY,SHRIMP,SIENNA,SILVER,SILVER_GREEN,SILVER_PINK,SLATE_GRAY,SLOW_CREEK,SMOG,SOAP,SOFT_TEAL,SPACE_BLUE,SPEARMINT,SPRING_GREEN,STEAM,STRAW,STRONG_CYAN,STYGIAN_BLUE,SUBTLETY,SUDS,TAN,TARNISH,TAUPE,TAXICAB_YELLOW,TEA_ROSE,THICK_AMETHYST,THIN_AMETHYST,THISTLE,THULIAN_PINK,TRANSPARENT,TROPIC_MIST,TURQUOISE,TWILIGHT_CLOUD,TYRIAN_PURPLE,UMBER,VAPOR,VARISCITE,VARNISH,VIOLET,VIOLET_CUSHIONS,VIRIDIAN,WATERCOLOR_BLACK,WATERCOLOR_GRAY,WET_STONE,WHITE,WISTERIA,WOODLANDS,YELLOW,ZUCCHINI,appendToKnownColors,editKnownColors
 * Covenant-source-reference: com/github/tommyettinger/colorful/oklab/Palette.java
 * Covenant-verified: 2026-04-19
 */
package sge
package colorful
package oklab

import scala.collection.mutable

/** A palette of predefined colors as packed OKLAB floats, the kind [[ColorTools]] works with. You can access colors by their constant name, such as `OCEAN_BLUE`, by the [[NAMED]] map using
  * `NAMED.getOrElse("Ocean Blue", 0f)`, or by index in the list called [[LIST]].
  */
object Palette {

  /** Maps color names to packed float colors. */
  val NAMED: mutable.HashMap[String, Float] = mutable.HashMap.empty[String, Float]

  /** Lists packed float color values, in declaration order. */
  val LIST: mutable.ArrayBuffer[Float] = mutable.ArrayBuffer.empty[Float]

  val TRANSPARENT:       Float = java.lang.Float.intBitsToFloat(0x7f7f00)
  val BLACK:             Float = java.lang.Float.intBitsToFloat(0xfe7f7f00)
  val COAL_BLACK:        Float = java.lang.Float.intBitsToFloat(0xfe7f7f13)
  val SHADOW:            Float = java.lang.Float.intBitsToFloat(0xfe7f7f25)
  val GRAPHITE:          Float = java.lang.Float.intBitsToFloat(0xfe7f7f37)
  val DARK_GRAY:         Float = java.lang.Float.intBitsToFloat(0xfe7f7f49)
  val LEAD:              Float = java.lang.Float.intBitsToFloat(0xfe7f7f5b)
  val IRON:              Float = java.lang.Float.intBitsToFloat(0xfe7f7f6e)
  val GRAY:              Float = java.lang.Float.intBitsToFloat(0xfe7f7f80)
  val CHINCHILLA:        Float = java.lang.Float.intBitsToFloat(0xfe7f7f92)
  val GREYHOUND:         Float = java.lang.Float.intBitsToFloat(0xfe7f7fa4)
  val SILVER:            Float = java.lang.Float.intBitsToFloat(0xfe7f7fb6)
  val LIGHT_GRAY:        Float = java.lang.Float.intBitsToFloat(0xfe7f7fc9)
  val PLATINUM:          Float = java.lang.Float.intBitsToFloat(0xfe7f7fdb)
  val CLOUD:             Float = java.lang.Float.intBitsToFloat(0xfe7f7fed)
  val WHITE:             Float = java.lang.Float.intBitsToFloat(0xfe7f7fff)
  val SEAWATER:          Float = java.lang.Float.intBitsToFloat(0xfe7c736d)
  val HOSPITAL_GREEN:    Float = java.lang.Float.intBitsToFloat(0xfe7b71a8)
  val CYAN:              Float = java.lang.Float.intBitsToFloat(0xfe7a6cdc)
  val BUBBLE:            Float = java.lang.Float.intBitsToFloat(0xfe7d78f1)
  val PERIWINKLE:        Float = java.lang.Float.intBitsToFloat(0xfe6a8392)
  val BLUE:              Float = java.lang.Float.intBitsToFloat(0xfe577b4d)
  val FADED_BLUE:        Float = java.lang.Float.intBitsToFloat(0xfe678254)
  val OCEAN_BLUE:        Float = java.lang.Float.intBitsToFloat(0xfe667c26)
  val STYGIAN_BLUE:      Float = java.lang.Float.intBitsToFloat(0xfe6e7f1c)
  val DEEP_PURPLE:       Float = java.lang.Float.intBitsToFloat(0xfe71954a)
  val TYRIAN_PURPLE:     Float = java.lang.Float.intBitsToFloat(0xfe70967b)
  val MAGENTA:           Float = java.lang.Float.intBitsToFloat(0xfe6aa190)
  val BUBBLEGUM_PINK:    Float = java.lang.Float.intBitsToFloat(0xfe7194b6)
  val PORK_CHOP:         Float = java.lang.Float.intBitsToFloat(0xfe8087d3)
  val RAW_MEAT:          Float = java.lang.Float.intBitsToFloat(0xfe8590aa)
  val RED:               Float = java.lang.Float.intBitsToFloat(0xfe8f9c7f)
  val PUTTY:             Float = java.lang.Float.intBitsToFloat(0xfe87926e)
  val SIENNA:            Float = java.lang.Float.intBitsToFloat(0xfe89913f)
  val SEAL_BROWN:        Float = java.lang.Float.intBitsToFloat(0xfe858b2d)
  val MUMMY_BROWN:       Float = java.lang.Float.intBitsToFloat(0xfe8b8751)
  val FAWN:              Float = java.lang.Float.intBitsToFloat(0xfe8c858e)
  val ORANGE:            Float = java.lang.Float.intBitsToFloat(0xfe928ca4)
  val PEACH:             Float = java.lang.Float.intBitsToFloat(0xfe8b84cd)
  val CREAM:             Float = java.lang.Float.intBitsToFloat(0xfe887cfa)
  val YELLOW:            Float = java.lang.Float.intBitsToFloat(0xfe9876f3)
  val EARWAX:            Float = java.lang.Float.intBitsToFloat(0xfe9179b7)
  val UMBER:             Float = java.lang.Float.intBitsToFloat(0xfe8f7979)
  val IVY_GREEN:         Float = java.lang.Float.intBitsToFloat(0xfe8d6c66)
  val JADE:              Float = java.lang.Float.intBitsToFloat(0xfe8e6a9f)
  val GREEN:             Float = java.lang.Float.intBitsToFloat(0xfe9661ce)
  val CELADON:           Float = java.lang.Float.intBitsToFloat(0xfe8872e7)
  val PUCE:              Float = java.lang.Float.intBitsToFloat(0xfe7d81b4)
  val BEIGE:             Float = java.lang.Float.intBitsToFloat(0xfe8682b0)
  val WET_STONE:         Float = java.lang.Float.intBitsToFloat(0xfe827fa0)
  val SLOW_CREEK:        Float = java.lang.Float.intBitsToFloat(0xfe7e7c8f)
  val SLATE_GRAY:        Float = java.lang.Float.intBitsToFloat(0xfe7d7c7e)
  val LIGHT_SKIN_1:      Float = java.lang.Float.intBitsToFloat(0xfe828171)
  val LIGHT_SKIN_2:      Float = java.lang.Float.intBitsToFloat(0xfe848778)
  val LIGHT_SKIN_3:      Float = java.lang.Float.intBitsToFloat(0xfe84898d)
  val LIGHT_SKIN_4:      Float = java.lang.Float.intBitsToFloat(0xfe86889d)
  val LIGHT_SKIN_5:      Float = java.lang.Float.intBitsToFloat(0xfe8787ad)
  val LIGHT_SKIN_6:      Float = java.lang.Float.intBitsToFloat(0xfe8686ba)
  val LIGHT_SKIN_7:      Float = java.lang.Float.intBitsToFloat(0xfe8685c8)
  val LIGHT_SKIN_8:      Float = java.lang.Float.intBitsToFloat(0xfe8584d3)
  val LIGHT_SKIN_9:      Float = java.lang.Float.intBitsToFloat(0xfe8281e5)
  val DARK_SKIN_1:       Float = java.lang.Float.intBitsToFloat(0xfe818443)
  val DARK_SKIN_2:       Float = java.lang.Float.intBitsToFloat(0xfe838750)
  val DARK_SKIN_3:       Float = java.lang.Float.intBitsToFloat(0xfe828866)
  val PINK_SKIN_1:       Float = java.lang.Float.intBitsToFloat(0xfe828783)
  val PINK_SKIN_2:       Float = java.lang.Float.intBitsToFloat(0xfe82879f)
  val PINK_SKIN_3:       Float = java.lang.Float.intBitsToFloat(0xfe8186bb)
  val PINK_SKIN_4:       Float = java.lang.Float.intBitsToFloat(0xfe7f84dd)
  val BRONZE_SKIN_4:     Float = java.lang.Float.intBitsToFloat(0xfe8481cc)
  val BRONZE_SKIN_3:     Float = java.lang.Float.intBitsToFloat(0xfe8782a5)
  val BRONZE_SKIN_2:     Float = java.lang.Float.intBitsToFloat(0xfe858278)
  val BRONZE_SKIN_1:     Float = java.lang.Float.intBitsToFloat(0xfe86825d)
  val TAUPE:             Float = java.lang.Float.intBitsToFloat(0xfe838130)
  val DRAB_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe857d3f)
  val LIZARD_SCALES:     Float = java.lang.Float.intBitsToFloat(0xfe897c6f)
  val CRICKET:           Float = java.lang.Float.intBitsToFloat(0xfe887c8b)
  val OLIVE_OIL:         Float = java.lang.Float.intBitsToFloat(0xfe8b7b9d)
  val DUN:               Float = java.lang.Float.intBitsToFloat(0xfe897cb0)
  val CORN_SILK:         Float = java.lang.Float.intBitsToFloat(0xfe877cc3)
  val TAN:               Float = java.lang.Float.intBitsToFloat(0xfe867dd6)
  val STRAW:             Float = java.lang.Float.intBitsToFloat(0xfe847dea)
  val HONEYDEW:          Float = java.lang.Float.intBitsToFloat(0xfe8679d8)
  val TARNISH:           Float = java.lang.Float.intBitsToFloat(0xfe8779bc)
  val PEA_SOUP:          Float = java.lang.Float.intBitsToFloat(0xfe8d74ab)
  val MARSH:             Float = java.lang.Float.intBitsToFloat(0xfe877884)
  val ASPARAGUS:         Float = java.lang.Float.intBitsToFloat(0xfe897670)
  val PEAT_BOG:          Float = java.lang.Float.intBitsToFloat(0xfe857b4b)
  val DEEP_JUNGLE:       Float = java.lang.Float.intBitsToFloat(0xfe837c1b)
  val PINE_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe837645)
  val OLIVE_GREEN:       Float = java.lang.Float.intBitsToFloat(0xfe83794e)
  val GRAY_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe827b5d)
  val MAIDENHAIR_FERN:   Float = java.lang.Float.intBitsToFloat(0xfe857564)
  val KELLY_GREEN:       Float = java.lang.Float.intBitsToFloat(0xfe87747e)
  val DUSTY_GREEN:       Float = java.lang.Float.intBitsToFloat(0xfe86759a)
  val GARTER_SNAKE:      Float = java.lang.Float.intBitsToFloat(0xfe8671a8)
  val SILVER_GREEN:      Float = java.lang.Float.intBitsToFloat(0xfe8675b6)
  val PISTACHIO:         Float = java.lang.Float.intBitsToFloat(0xfe8576c7)
  val ANGEL_WING:        Float = java.lang.Float.intBitsToFloat(0xfe7e7cf3)
  val SAGE_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe8277de)
  val DRIED_SAGE:        Float = java.lang.Float.intBitsToFloat(0xfe8277d4)
  val ARTICHOKE:         Float = java.lang.Float.intBitsToFloat(0xfe8377a6)
  val VIRIDIAN:          Float = java.lang.Float.intBitsToFloat(0xfe837770)
  val FLORAL_FOAM:       Float = java.lang.Float.intBitsToFloat(0xfe837257)
  val HUNTER_GREEN:      Float = java.lang.Float.intBitsToFloat(0xfe817b28)
  val DARK_TEAL:         Float = java.lang.Float.intBitsToFloat(0xfe7c7a3b)
  val KYANITE:           Float = java.lang.Float.intBitsToFloat(0xfe7d7767)
  val SPEARMINT:         Float = java.lang.Float.intBitsToFloat(0xfe7d769c)
  val AMAZONITE:         Float = java.lang.Float.intBitsToFloat(0xfe7d78bb)
  val PASTEL_SKY:        Float = java.lang.Float.intBitsToFloat(0xfe7d79d6)
  val AQUAMARINE:        Float = java.lang.Float.intBitsToFloat(0xfe7e7ae7)
  val DUST_BUNNY:        Float = java.lang.Float.intBitsToFloat(0xfe7a7ed0)
  val PATINA:            Float = java.lang.Float.intBitsToFloat(0xfe7a7dc3)
  val CHIPPED_GRANITE:   Float = java.lang.Float.intBitsToFloat(0xfe797eb9)
  val BLUE_SMOKE:        Float = java.lang.Float.intBitsToFloat(0xfe797da7)
  val AIR_FORCE_BLUE:    Float = java.lang.Float.intBitsToFloat(0xfe737a8a)
  val COLD_IRON:         Float = java.lang.Float.intBitsToFloat(0xfe797c70)
  val DREARY_BLUE:       Float = java.lang.Float.intBitsToFloat(0xfe787c54)
  val MURK:              Float = java.lang.Float.intBitsToFloat(0xfe787e19)
  val NINJA:             Float = java.lang.Float.intBitsToFloat(0xfe778122)
  val WATERCOLOR_BLACK:  Float = java.lang.Float.intBitsToFloat(0xfe79813e)
  val IOLITE:            Float = java.lang.Float.intBitsToFloat(0xfe76814e)
  val BOYSENBERRY:       Float = java.lang.Float.intBitsToFloat(0xfe74825e)
  val WATERCOLOR_GRAY:   Float = java.lang.Float.intBitsToFloat(0xfe748276)
  val BLUE_STEEL:        Float = java.lang.Float.intBitsToFloat(0xfe708280)
  val TWILIGHT_CLOUD:    Float = java.lang.Float.intBitsToFloat(0xfe768195)
  val SMOG:              Float = java.lang.Float.intBitsToFloat(0xfe7681b1)
  val TROPIC_MIST:       Float = java.lang.Float.intBitsToFloat(0xfe7a7fdb)
  val FEATHER_DOWN:      Float = java.lang.Float.intBitsToFloat(0xfe7b80e6)
  val MILD_VIOLET:       Float = java.lang.Float.intBitsToFloat(0xfe77859d)
  val VIOLET_CUSHIONS:   Float = java.lang.Float.intBitsToFloat(0xfe6e8b76)
  val DULL_VIOLET:       Float = java.lang.Float.intBitsToFloat(0xfe768665)
  val ROYAL_VIOLET:      Float = java.lang.Float.intBitsToFloat(0xfe75874a)
  val EMINENCE:          Float = java.lang.Float.intBitsToFloat(0xfe7b862d)
  val PRUNE:             Float = java.lang.Float.intBitsToFloat(0xfe7c8439)
  val DUSTY_GRAPE:       Float = java.lang.Float.intBitsToFloat(0xfe788a55)
  val PINK_VIOLET:       Float = java.lang.Float.intBitsToFloat(0xfe788a6e)
  val RIPE_PLUM:         Float = java.lang.Float.intBitsToFloat(0xfe758f7b)
  val MAUVE:             Float = java.lang.Float.intBitsToFloat(0xfe788a89)
  val HAM:               Float = java.lang.Float.intBitsToFloat(0xfe7989c3)
  val COTTON_CANDY:      Float = java.lang.Float.intBitsToFloat(0xfe7d84e8)
  val SILVER_PINK:       Float = java.lang.Float.intBitsToFloat(0xfe7c84d1)
  val TEA_ROSE:          Float = java.lang.Float.intBitsToFloat(0xfe7d85c7)
  val OLD_ROSE:          Float = java.lang.Float.intBitsToFloat(0xfe7d88b3)
  val DUSTY_PINK:        Float = java.lang.Float.intBitsToFloat(0xfe7b89a3)
  val ROSEATE_SPOONBILL: Float = java.lang.Float.intBitsToFloat(0xfe7d8b97)
  val THULIAN_PINK:      Float = java.lang.Float.intBitsToFloat(0xfe7b9182)
  val BROWN_VELVET:      Float = java.lang.Float.intBitsToFloat(0xfe7e8734)
  val NIGHTSHADE:        Float = java.lang.Float.intBitsToFloat(0xfe7e8620)
  val SCRIBE_INK:        Float = java.lang.Float.intBitsToFloat(0xfe7c8817)
  val VARNISH:           Float = java.lang.Float.intBitsToFloat(0xfe848725)
  val CEDAR_WOOD:        Float = java.lang.Float.intBitsToFloat(0xfe888c34)
  val HOT_SAUCE:         Float = java.lang.Float.intBitsToFloat(0xfe8b9454)
  val LURID_RED:         Float = java.lang.Float.intBitsToFloat(0xfe8d9770)
  val BRICK:             Float = java.lang.Float.intBitsToFloat(0xfe889180)
  val BRIGHT_RED:        Float = java.lang.Float.intBitsToFloat(0xfe909788)
  val EMBERS:            Float = java.lang.Float.intBitsToFloat(0xfe8e928f)
  val SALMON:            Float = java.lang.Float.intBitsToFloat(0xfe889499)
  val TAXICAB_YELLOW:    Float = java.lang.Float.intBitsToFloat(0xfe9380c5)
  val APRICOT:           Float = java.lang.Float.intBitsToFloat(0xfe9186ba)
  val BURNT_YELLOW:      Float = java.lang.Float.intBitsToFloat(0xfe9281a6)
  val DRY_PEPPER:        Float = java.lang.Float.intBitsToFloat(0xfe908a8d)
  val REDWOOD:           Float = java.lang.Float.intBitsToFloat(0xfe8e8974)
  val KOA:               Float = java.lang.Float.intBitsToFloat(0xfe8d8964)
  val OCHRE:             Float = java.lang.Float.intBitsToFloat(0xfe88853f)
  val DULL_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe8a7b4d)
  val ARMY_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe8c7a5d)
  val DRIFTWOOD:         Float = java.lang.Float.intBitsToFloat(0xfe867f80)
  val DRY_BRUSH:         Float = java.lang.Float.intBitsToFloat(0xfe917c94)
  val MUSH:              Float = java.lang.Float.intBitsToFloat(0xfe9378a9)
  val BANANA_PUDDING:    Float = java.lang.Float.intBitsToFloat(0xfe907bd2)
  val SAFFRON:           Float = java.lang.Float.intBitsToFloat(0xfe967cd7)
  val PENCIL_YELLOW:     Float = java.lang.Float.intBitsToFloat(0xfe947ae6)
  val CHARTREUSE:        Float = java.lang.Float.intBitsToFloat(0xfe9570e7)
  val ABSINTHE:          Float = java.lang.Float.intBitsToFloat(0xfe936dd2)
  val INFECTION:         Float = java.lang.Float.intBitsToFloat(0xfe946ec2)
  val FROG_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe936dac)
  val AVOCADO:           Float = java.lang.Float.intBitsToFloat(0xfe917092)
  val WOODLANDS:         Float = java.lang.Float.intBitsToFloat(0xfe8c735e)
  val DARK_PINE:         Float = java.lang.Float.intBitsToFloat(0xfe87792e)
  val MOSS_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe89753b)
  val FERN_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe8a704a)
  val FOREST_GLEN:       Float = java.lang.Float.intBitsToFloat(0xfe8f6a79)
  val MALACHITE:         Float = java.lang.Float.intBitsToFloat(0xfe9364ae)
  val APPLE_GREEN:       Float = java.lang.Float.intBitsToFloat(0xfe9463ba)
  val CELERY:            Float = java.lang.Float.intBitsToFloat(0xfe8f6bda)
  val MINT_GREEN:        Float = java.lang.Float.intBitsToFloat(0xfe9067c7)
  val EMERALD:           Float = java.lang.Float.intBitsToFloat(0xfe92669f)
  val PRASE:             Float = java.lang.Float.intBitsToFloat(0xfe8b6a93)
  val EUCALYPTUS:        Float = java.lang.Float.intBitsToFloat(0xfe876f74)
  val ZUCCHINI:          Float = java.lang.Float.intBitsToFloat(0xfe7f7930)
  val SOFT_TEAL:         Float = java.lang.Float.intBitsToFloat(0xfe807081)
  val MEDIUM_TEAL:       Float = java.lang.Float.intBitsToFloat(0xfe836ca4)
  val SPRING_GREEN:      Float = java.lang.Float.intBitsToFloat(0xfe8c67b6)
  val TURQUOISE:         Float = java.lang.Float.intBitsToFloat(0xfe856ac6)
  val SEAFOAM:           Float = java.lang.Float.intBitsToFloat(0xfe8769d5)
  val VARISCITE:         Float = java.lang.Float.intBitsToFloat(0xfe826ede)
  val REFRESHING_MIST:   Float = java.lang.Float.intBitsToFloat(0xfe7976da)
  val SHINING_SKY:       Float = java.lang.Float.intBitsToFloat(0xfe7771ce)
  val STEAM:             Float = java.lang.Float.intBitsToFloat(0xfe7876c7)
  val ROBIN_EGG_BLUE:    Float = java.lang.Float.intBitsToFloat(0xfe7c6dbf)
  val DENIM_BLUE:        Float = java.lang.Float.intBitsToFloat(0xfe70758f)
  val DEEP_TEAL:         Float = java.lang.Float.intBitsToFloat(0xfe7c764e)
  val NAVY_BLUE:         Float = java.lang.Float.intBitsToFloat(0xfe757d2c)
  val BLUEBERRY:         Float = java.lang.Float.intBitsToFloat(0xfe6e7c3b)
  val PRUSSIAN_BLUE:     Float = java.lang.Float.intBitsToFloat(0xfe6c7a4c)
  val DESERT_RAIN:       Float = java.lang.Float.intBitsToFloat(0xfe737a60)
  val ELECTRIC_BLUE:     Float = java.lang.Float.intBitsToFloat(0xfe607b64)
  val HIDDEN_BLUE:       Float = java.lang.Float.intBitsToFloat(0xfe6d7968)
  val DULL_AZURE:        Float = java.lang.Float.intBitsToFloat(0xfe6b7977)
  val RIPPED_DENIM:      Float = java.lang.Float.intBitsToFloat(0xfe777a96)
  val CALM_SKY:          Float = java.lang.Float.intBitsToFloat(0xfe6d789e)
  val VAPOR:             Float = java.lang.Float.intBitsToFloat(0xfe717eb2)
  val POWDER_BLUE:       Float = java.lang.Float.intBitsToFloat(0xfe7376b7)
  val SUDS:              Float = java.lang.Float.intBitsToFloat(0xfe7582c2)
  val STRONG_CYAN:       Float = java.lang.Float.intBitsToFloat(0xfe7172ad)
  val SHARP_AZURE:       Float = java.lang.Float.intBitsToFloat(0xfe667880)
  val BLUE_EYE:          Float = java.lang.Float.intBitsToFloat(0xfe707b7c)
  val SUBTLETY:          Float = java.lang.Float.intBitsToFloat(0xfe698482)
  val ROUGH_SAPPHIRE:    Float = java.lang.Float.intBitsToFloat(0xfe628071)
  val IRIS:              Float = java.lang.Float.intBitsToFloat(0xfe618768)
  val CORNFLOWER_BLUE:   Float = java.lang.Float.intBitsToFloat(0xfe5e815e)
  val POLISHED_SAPPHIRE: Float = java.lang.Float.intBitsToFloat(0xfe5d7c46)
  val ROYAL_BLUE:        Float = java.lang.Float.intBitsToFloat(0xfe5f7c3b)
  val INDIGO:            Float = java.lang.Float.intBitsToFloat(0xfe658132)
  val SPACE_BLUE:        Float = java.lang.Float.intBitsToFloat(0xfe747d23)
  val THICK_AMETHYST:    Float = java.lang.Float.intBitsToFloat(0xfe658a44)
  val JUICY_GRAPE:       Float = java.lang.Float.intBitsToFloat(0xfe618c51)
  val BLACKLIGHT_GLOW:   Float = java.lang.Float.intBitsToFloat(0xfe679066)
  val PURPLE_FREESIA:    Float = java.lang.Float.intBitsToFloat(0xfe64907b)
  val THIN_AMETHYST:     Float = java.lang.Float.intBitsToFloat(0xfe5e9065)
  val ORCHID:            Float = java.lang.Float.intBitsToFloat(0xfe699193)
  val LAVENDER:          Float = java.lang.Float.intBitsToFloat(0xfe6f88a9)
  val LILAC:             Float = java.lang.Float.intBitsToFloat(0xfe7389bd)
  val SOAP:              Float = java.lang.Float.intBitsToFloat(0xfe7784ce)
  val PINK_TUTU:         Float = java.lang.Float.intBitsToFloat(0xfe7987d9)
  val THISTLE:           Float = java.lang.Float.intBitsToFloat(0xfe6e93a8)
  val HELIOTROPE:        Float = java.lang.Float.intBitsToFloat(0xfe6d9ca4)
  val PURPLE:            Float = java.lang.Float.intBitsToFloat(0xfe6b9d84)
  val WISTERIA:          Float = java.lang.Float.intBitsToFloat(0xfe649880)
  val MEDIUM_PLUM:       Float = java.lang.Float.intBitsToFloat(0xfe6c9b71)
  val VIOLET:            Float = java.lang.Float.intBitsToFloat(0xfe68945d)
  val GRAPE_LOLLIPOP:    Float = java.lang.Float.intBitsToFloat(0xfe6f8e3e)
  val MULBERRY:          Float = java.lang.Float.intBitsToFloat(0xfe74903d)
  val GRAPE_SODA:        Float = java.lang.Float.intBitsToFloat(0xfe6f8c2c)
  val EGGPLANT:          Float = java.lang.Float.intBitsToFloat(0xfe738922)
  val CHERRY_SYRUP:      Float = java.lang.Float.intBitsToFloat(0xfe7d8d32)
  val PLUM_JUICE:        Float = java.lang.Float.intBitsToFloat(0xfe75975c)
  val FRUIT_PUNCH:       Float = java.lang.Float.intBitsToFloat(0xfe7b9c6a)
  val BUBBLE_GUM:        Float = java.lang.Float.intBitsToFloat(0xfe779b9b)
  val PINK_LEMONADE:     Float = java.lang.Float.intBitsToFloat(0xfe7897a6)
  val SHRIMP:            Float = java.lang.Float.intBitsToFloat(0xfe7f8cbd)
  val FLAMINGO:          Float = java.lang.Float.intBitsToFloat(0xfe7e9c8d)
  val ROSE:              Float = java.lang.Float.intBitsToFloat(0xfe7e9d7b)
  val CARMINE:           Float = java.lang.Float.intBitsToFloat(0xfe869860)
  val BOLOGNA:           Float = java.lang.Float.intBitsToFloat(0xfe81905a)
  val RASPBERRY:         Float = java.lang.Float.intBitsToFloat(0xfe83944c)

  // Register all colors
  locally {
    NAMED.put("Transparent", java.lang.Float.intBitsToFloat(0x7f7f00))
    LIST += java.lang.Float.intBitsToFloat(0x7f7f00)
    NAMED.put("Black", java.lang.Float.intBitsToFloat(0xfe7f7f00))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7f00)
    NAMED.put("Coal Black", java.lang.Float.intBitsToFloat(0xfe7f7f13))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7f13)
    NAMED.put("Shadow", java.lang.Float.intBitsToFloat(0xfe7f7f25))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7f25)
    NAMED.put("Graphite", java.lang.Float.intBitsToFloat(0xfe7f7f37))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7f37)
    NAMED.put("Dark Gray", java.lang.Float.intBitsToFloat(0xfe7f7f49))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7f49)
    NAMED.put("Lead", java.lang.Float.intBitsToFloat(0xfe7f7f5b))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7f5b)
    NAMED.put("Iron", java.lang.Float.intBitsToFloat(0xfe7f7f6e))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7f6e)
    NAMED.put("Gray", java.lang.Float.intBitsToFloat(0xfe7f7f80))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7f80)
    NAMED.put("Chinchilla", java.lang.Float.intBitsToFloat(0xfe7f7f92))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7f92)
    NAMED.put("Greyhound", java.lang.Float.intBitsToFloat(0xfe7f7fa4))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7fa4)
    NAMED.put("Silver", java.lang.Float.intBitsToFloat(0xfe7f7fb6))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7fb6)
    NAMED.put("Light Gray", java.lang.Float.intBitsToFloat(0xfe7f7fc9))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7fc9)
    NAMED.put("Platinum", java.lang.Float.intBitsToFloat(0xfe7f7fdb))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7fdb)
    NAMED.put("Cloud", java.lang.Float.intBitsToFloat(0xfe7f7fed))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7fed)
    NAMED.put("White", java.lang.Float.intBitsToFloat(0xfe7f7fff))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7fff)
    NAMED.put("Seawater", java.lang.Float.intBitsToFloat(0xfe7c736d))
    LIST += java.lang.Float.intBitsToFloat(0xfe7c736d)
    NAMED.put("Hospital Green", java.lang.Float.intBitsToFloat(0xfe7b71a8))
    LIST += java.lang.Float.intBitsToFloat(0xfe7b71a8)
    NAMED.put("Cyan", java.lang.Float.intBitsToFloat(0xfe7a6cdc))
    LIST += java.lang.Float.intBitsToFloat(0xfe7a6cdc)
    NAMED.put("Bubble", java.lang.Float.intBitsToFloat(0xfe7d78f1))
    LIST += java.lang.Float.intBitsToFloat(0xfe7d78f1)
    NAMED.put("Periwinkle", java.lang.Float.intBitsToFloat(0xfe6a8392))
    LIST += java.lang.Float.intBitsToFloat(0xfe6a8392)
    NAMED.put("Blue", java.lang.Float.intBitsToFloat(0xfe577b4d))
    LIST += java.lang.Float.intBitsToFloat(0xfe577b4d)
    NAMED.put("Faded Blue", java.lang.Float.intBitsToFloat(0xfe678254))
    LIST += java.lang.Float.intBitsToFloat(0xfe678254)
    NAMED.put("Ocean Blue", java.lang.Float.intBitsToFloat(0xfe667c26))
    LIST += java.lang.Float.intBitsToFloat(0xfe667c26)
    NAMED.put("Stygian Blue", java.lang.Float.intBitsToFloat(0xfe6e7f1c))
    LIST += java.lang.Float.intBitsToFloat(0xfe6e7f1c)
    NAMED.put("Deep Purple", java.lang.Float.intBitsToFloat(0xfe71954a))
    LIST += java.lang.Float.intBitsToFloat(0xfe71954a)
    NAMED.put("Tyrian Purple", java.lang.Float.intBitsToFloat(0xfe70967b))
    LIST += java.lang.Float.intBitsToFloat(0xfe70967b)
    NAMED.put("Magenta", java.lang.Float.intBitsToFloat(0xfe6aa190))
    LIST += java.lang.Float.intBitsToFloat(0xfe6aa190)
    NAMED.put("Bubblegum Pink", java.lang.Float.intBitsToFloat(0xfe7194b6))
    LIST += java.lang.Float.intBitsToFloat(0xfe7194b6)
    NAMED.put("Pork Chop", java.lang.Float.intBitsToFloat(0xfe8087d3))
    LIST += java.lang.Float.intBitsToFloat(0xfe8087d3)
    NAMED.put("Raw Meat", java.lang.Float.intBitsToFloat(0xfe8590aa))
    LIST += java.lang.Float.intBitsToFloat(0xfe8590aa)
    NAMED.put("Red", java.lang.Float.intBitsToFloat(0xfe8f9c7f))
    LIST += java.lang.Float.intBitsToFloat(0xfe8f9c7f)
    NAMED.put("Putty", java.lang.Float.intBitsToFloat(0xfe87926e))
    LIST += java.lang.Float.intBitsToFloat(0xfe87926e)
    NAMED.put("Sienna", java.lang.Float.intBitsToFloat(0xfe89913f))
    LIST += java.lang.Float.intBitsToFloat(0xfe89913f)
    NAMED.put("Seal Brown", java.lang.Float.intBitsToFloat(0xfe858b2d))
    LIST += java.lang.Float.intBitsToFloat(0xfe858b2d)
    NAMED.put("Mummy Brown", java.lang.Float.intBitsToFloat(0xfe8b8751))
    LIST += java.lang.Float.intBitsToFloat(0xfe8b8751)
    NAMED.put("Fawn", java.lang.Float.intBitsToFloat(0xfe8c858e))
    LIST += java.lang.Float.intBitsToFloat(0xfe8c858e)
    NAMED.put("Orange", java.lang.Float.intBitsToFloat(0xfe928ca4))
    LIST += java.lang.Float.intBitsToFloat(0xfe928ca4)
    NAMED.put("Peach", java.lang.Float.intBitsToFloat(0xfe8b84cd))
    LIST += java.lang.Float.intBitsToFloat(0xfe8b84cd)
    NAMED.put("Cream", java.lang.Float.intBitsToFloat(0xfe887cfa))
    LIST += java.lang.Float.intBitsToFloat(0xfe887cfa)
    NAMED.put("Yellow", java.lang.Float.intBitsToFloat(0xfe9876f3))
    LIST += java.lang.Float.intBitsToFloat(0xfe9876f3)
    NAMED.put("Earwax", java.lang.Float.intBitsToFloat(0xfe9179b7))
    LIST += java.lang.Float.intBitsToFloat(0xfe9179b7)
    NAMED.put("Umber", java.lang.Float.intBitsToFloat(0xfe8f7979))
    LIST += java.lang.Float.intBitsToFloat(0xfe8f7979)
    NAMED.put("Ivy Green", java.lang.Float.intBitsToFloat(0xfe8d6c66))
    LIST += java.lang.Float.intBitsToFloat(0xfe8d6c66)
    NAMED.put("Jade", java.lang.Float.intBitsToFloat(0xfe8e6a9f))
    LIST += java.lang.Float.intBitsToFloat(0xfe8e6a9f)
    NAMED.put("Green", java.lang.Float.intBitsToFloat(0xfe9661ce))
    LIST += java.lang.Float.intBitsToFloat(0xfe9661ce)
    NAMED.put("Celadon", java.lang.Float.intBitsToFloat(0xfe8872e7))
    LIST += java.lang.Float.intBitsToFloat(0xfe8872e7)
    NAMED.put("Puce", java.lang.Float.intBitsToFloat(0xfe7d81b4))
    LIST += java.lang.Float.intBitsToFloat(0xfe7d81b4)
    NAMED.put("Beige", java.lang.Float.intBitsToFloat(0xfe8682b0))
    LIST += java.lang.Float.intBitsToFloat(0xfe8682b0)
    NAMED.put("Wet Stone", java.lang.Float.intBitsToFloat(0xfe827fa0))
    LIST += java.lang.Float.intBitsToFloat(0xfe827fa0)
    NAMED.put("Slow Creek", java.lang.Float.intBitsToFloat(0xfe7e7c8f))
    LIST += java.lang.Float.intBitsToFloat(0xfe7e7c8f)
    NAMED.put("Slate Gray", java.lang.Float.intBitsToFloat(0xfe7d7c7e))
    LIST += java.lang.Float.intBitsToFloat(0xfe7d7c7e)
    NAMED.put("Light Skin 1", java.lang.Float.intBitsToFloat(0xfe828171))
    LIST += java.lang.Float.intBitsToFloat(0xfe828171)
    NAMED.put("Light Skin 2", java.lang.Float.intBitsToFloat(0xfe848778))
    LIST += java.lang.Float.intBitsToFloat(0xfe848778)
    NAMED.put("Light Skin 3", java.lang.Float.intBitsToFloat(0xfe84898d))
    LIST += java.lang.Float.intBitsToFloat(0xfe84898d)
    NAMED.put("Light Skin 4", java.lang.Float.intBitsToFloat(0xfe86889d))
    LIST += java.lang.Float.intBitsToFloat(0xfe86889d)
    NAMED.put("Light Skin 5", java.lang.Float.intBitsToFloat(0xfe8787ad))
    LIST += java.lang.Float.intBitsToFloat(0xfe8787ad)
    NAMED.put("Light Skin 6", java.lang.Float.intBitsToFloat(0xfe8686ba))
    LIST += java.lang.Float.intBitsToFloat(0xfe8686ba)
    NAMED.put("Light Skin 7", java.lang.Float.intBitsToFloat(0xfe8685c8))
    LIST += java.lang.Float.intBitsToFloat(0xfe8685c8)
    NAMED.put("Light Skin 8", java.lang.Float.intBitsToFloat(0xfe8584d3))
    LIST += java.lang.Float.intBitsToFloat(0xfe8584d3)
    NAMED.put("Light Skin 9", java.lang.Float.intBitsToFloat(0xfe8281e5))
    LIST += java.lang.Float.intBitsToFloat(0xfe8281e5)
    NAMED.put("Dark Skin 1", java.lang.Float.intBitsToFloat(0xfe818443))
    LIST += java.lang.Float.intBitsToFloat(0xfe818443)
    NAMED.put("Dark Skin 2", java.lang.Float.intBitsToFloat(0xfe838750))
    LIST += java.lang.Float.intBitsToFloat(0xfe838750)
    NAMED.put("Dark Skin 3", java.lang.Float.intBitsToFloat(0xfe828866))
    LIST += java.lang.Float.intBitsToFloat(0xfe828866)
    NAMED.put("Pink Skin 1", java.lang.Float.intBitsToFloat(0xfe828783))
    LIST += java.lang.Float.intBitsToFloat(0xfe828783)
    NAMED.put("Pink Skin 2", java.lang.Float.intBitsToFloat(0xfe82879f))
    LIST += java.lang.Float.intBitsToFloat(0xfe82879f)
    NAMED.put("Pink Skin 3", java.lang.Float.intBitsToFloat(0xfe8186bb))
    LIST += java.lang.Float.intBitsToFloat(0xfe8186bb)
    NAMED.put("Pink Skin 4", java.lang.Float.intBitsToFloat(0xfe7f84dd))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f84dd)
    NAMED.put("Bronze Skin 4", java.lang.Float.intBitsToFloat(0xfe8481cc))
    LIST += java.lang.Float.intBitsToFloat(0xfe8481cc)
    NAMED.put("Bronze Skin 3", java.lang.Float.intBitsToFloat(0xfe8782a5))
    LIST += java.lang.Float.intBitsToFloat(0xfe8782a5)
    NAMED.put("Bronze Skin 2", java.lang.Float.intBitsToFloat(0xfe858278))
    LIST += java.lang.Float.intBitsToFloat(0xfe858278)
    NAMED.put("Bronze Skin 1", java.lang.Float.intBitsToFloat(0xfe86825d))
    LIST += java.lang.Float.intBitsToFloat(0xfe86825d)
    NAMED.put("Taupe", java.lang.Float.intBitsToFloat(0xfe838130))
    LIST += java.lang.Float.intBitsToFloat(0xfe838130)
    NAMED.put("Drab Green", java.lang.Float.intBitsToFloat(0xfe857d3f))
    LIST += java.lang.Float.intBitsToFloat(0xfe857d3f)
    NAMED.put("Lizard Scales", java.lang.Float.intBitsToFloat(0xfe897c6f))
    LIST += java.lang.Float.intBitsToFloat(0xfe897c6f)
    NAMED.put("Cricket", java.lang.Float.intBitsToFloat(0xfe887c8b))
    LIST += java.lang.Float.intBitsToFloat(0xfe887c8b)
    NAMED.put("Olive Oil", java.lang.Float.intBitsToFloat(0xfe8b7b9d))
    LIST += java.lang.Float.intBitsToFloat(0xfe8b7b9d)
    NAMED.put("Dun", java.lang.Float.intBitsToFloat(0xfe897cb0))
    LIST += java.lang.Float.intBitsToFloat(0xfe897cb0)
    NAMED.put("Corn Silk", java.lang.Float.intBitsToFloat(0xfe877cc3))
    LIST += java.lang.Float.intBitsToFloat(0xfe877cc3)
    NAMED.put("Tan", java.lang.Float.intBitsToFloat(0xfe867dd6))
    LIST += java.lang.Float.intBitsToFloat(0xfe867dd6)
    NAMED.put("Straw", java.lang.Float.intBitsToFloat(0xfe847dea))
    LIST += java.lang.Float.intBitsToFloat(0xfe847dea)
    NAMED.put("Honeydew", java.lang.Float.intBitsToFloat(0xfe8679d8))
    LIST += java.lang.Float.intBitsToFloat(0xfe8679d8)
    NAMED.put("Tarnish", java.lang.Float.intBitsToFloat(0xfe8779bc))
    LIST += java.lang.Float.intBitsToFloat(0xfe8779bc)
    NAMED.put("Pea Soup", java.lang.Float.intBitsToFloat(0xfe8d74ab))
    LIST += java.lang.Float.intBitsToFloat(0xfe8d74ab)
    NAMED.put("Marsh", java.lang.Float.intBitsToFloat(0xfe877884))
    LIST += java.lang.Float.intBitsToFloat(0xfe877884)
    NAMED.put("Asparagus", java.lang.Float.intBitsToFloat(0xfe897670))
    LIST += java.lang.Float.intBitsToFloat(0xfe897670)
    NAMED.put("Peat Bog", java.lang.Float.intBitsToFloat(0xfe857b4b))
    LIST += java.lang.Float.intBitsToFloat(0xfe857b4b)
    NAMED.put("Deep Jungle", java.lang.Float.intBitsToFloat(0xfe837c1b))
    LIST += java.lang.Float.intBitsToFloat(0xfe837c1b)
    NAMED.put("Pine Green", java.lang.Float.intBitsToFloat(0xfe837645))
    LIST += java.lang.Float.intBitsToFloat(0xfe837645)
    NAMED.put("Olive Green", java.lang.Float.intBitsToFloat(0xfe83794e))
    LIST += java.lang.Float.intBitsToFloat(0xfe83794e)
    NAMED.put("Gray Green", java.lang.Float.intBitsToFloat(0xfe827b5d))
    LIST += java.lang.Float.intBitsToFloat(0xfe827b5d)
    NAMED.put("Maidenhair Fern", java.lang.Float.intBitsToFloat(0xfe857564))
    LIST += java.lang.Float.intBitsToFloat(0xfe857564)
    NAMED.put("Kelly Green", java.lang.Float.intBitsToFloat(0xfe87747e))
    LIST += java.lang.Float.intBitsToFloat(0xfe87747e)
    NAMED.put("Dusty Green", java.lang.Float.intBitsToFloat(0xfe86759a))
    LIST += java.lang.Float.intBitsToFloat(0xfe86759a)
    NAMED.put("Garter Snake", java.lang.Float.intBitsToFloat(0xfe8671a8))
    LIST += java.lang.Float.intBitsToFloat(0xfe8671a8)
    NAMED.put("Silver Green", java.lang.Float.intBitsToFloat(0xfe8675b6))
    LIST += java.lang.Float.intBitsToFloat(0xfe8675b6)
    NAMED.put("Pistachio", java.lang.Float.intBitsToFloat(0xfe8576c7))
    LIST += java.lang.Float.intBitsToFloat(0xfe8576c7)
    NAMED.put("Angel Wing", java.lang.Float.intBitsToFloat(0xfe7e7cf3))
    LIST += java.lang.Float.intBitsToFloat(0xfe7e7cf3)
    NAMED.put("Sage Green", java.lang.Float.intBitsToFloat(0xfe8277de))
    LIST += java.lang.Float.intBitsToFloat(0xfe8277de)
    NAMED.put("Dried Sage", java.lang.Float.intBitsToFloat(0xfe8277d4))
    LIST += java.lang.Float.intBitsToFloat(0xfe8277d4)
    NAMED.put("Artichoke", java.lang.Float.intBitsToFloat(0xfe8377a6))
    LIST += java.lang.Float.intBitsToFloat(0xfe8377a6)
    NAMED.put("Viridian", java.lang.Float.intBitsToFloat(0xfe837770))
    LIST += java.lang.Float.intBitsToFloat(0xfe837770)
    NAMED.put("Floral Foam", java.lang.Float.intBitsToFloat(0xfe837257))
    LIST += java.lang.Float.intBitsToFloat(0xfe837257)
    NAMED.put("Hunter Green", java.lang.Float.intBitsToFloat(0xfe817b28))
    LIST += java.lang.Float.intBitsToFloat(0xfe817b28)
    NAMED.put("Dark Teal", java.lang.Float.intBitsToFloat(0xfe7c7a3b))
    LIST += java.lang.Float.intBitsToFloat(0xfe7c7a3b)
    NAMED.put("Kyanite", java.lang.Float.intBitsToFloat(0xfe7d7767))
    LIST += java.lang.Float.intBitsToFloat(0xfe7d7767)
    NAMED.put("Spearmint", java.lang.Float.intBitsToFloat(0xfe7d769c))
    LIST += java.lang.Float.intBitsToFloat(0xfe7d769c)
    NAMED.put("Amazonite", java.lang.Float.intBitsToFloat(0xfe7d78bb))
    LIST += java.lang.Float.intBitsToFloat(0xfe7d78bb)
    NAMED.put("Pastel Sky", java.lang.Float.intBitsToFloat(0xfe7d79d6))
    LIST += java.lang.Float.intBitsToFloat(0xfe7d79d6)
    NAMED.put("Aquamarine", java.lang.Float.intBitsToFloat(0xfe7e7ae7))
    LIST += java.lang.Float.intBitsToFloat(0xfe7e7ae7)
    NAMED.put("Dust Bunny", java.lang.Float.intBitsToFloat(0xfe7a7ed0))
    LIST += java.lang.Float.intBitsToFloat(0xfe7a7ed0)
    NAMED.put("Patina", java.lang.Float.intBitsToFloat(0xfe7a7dc3))
    LIST += java.lang.Float.intBitsToFloat(0xfe7a7dc3)
    NAMED.put("Chipped Granite", java.lang.Float.intBitsToFloat(0xfe797eb9))
    LIST += java.lang.Float.intBitsToFloat(0xfe797eb9)
    NAMED.put("Blue Smoke", java.lang.Float.intBitsToFloat(0xfe797da7))
    LIST += java.lang.Float.intBitsToFloat(0xfe797da7)
    NAMED.put("Air Force Blue", java.lang.Float.intBitsToFloat(0xfe737a8a))
    LIST += java.lang.Float.intBitsToFloat(0xfe737a8a)
    NAMED.put("Cold Iron", java.lang.Float.intBitsToFloat(0xfe797c70))
    LIST += java.lang.Float.intBitsToFloat(0xfe797c70)
    NAMED.put("Dreary Blue", java.lang.Float.intBitsToFloat(0xfe787c54))
    LIST += java.lang.Float.intBitsToFloat(0xfe787c54)
    NAMED.put("Murk", java.lang.Float.intBitsToFloat(0xfe787e19))
    LIST += java.lang.Float.intBitsToFloat(0xfe787e19)
    NAMED.put("Ninja", java.lang.Float.intBitsToFloat(0xfe778122))
    LIST += java.lang.Float.intBitsToFloat(0xfe778122)
    NAMED.put("Watercolor Black", java.lang.Float.intBitsToFloat(0xfe79813e))
    LIST += java.lang.Float.intBitsToFloat(0xfe79813e)
    NAMED.put("Iolite", java.lang.Float.intBitsToFloat(0xfe76814e))
    LIST += java.lang.Float.intBitsToFloat(0xfe76814e)
    NAMED.put("Boysenberry", java.lang.Float.intBitsToFloat(0xfe74825e))
    LIST += java.lang.Float.intBitsToFloat(0xfe74825e)
    NAMED.put("Watercolor Gray", java.lang.Float.intBitsToFloat(0xfe748276))
    LIST += java.lang.Float.intBitsToFloat(0xfe748276)
    NAMED.put("Blue Steel", java.lang.Float.intBitsToFloat(0xfe708280))
    LIST += java.lang.Float.intBitsToFloat(0xfe708280)
    NAMED.put("Twilight Cloud", java.lang.Float.intBitsToFloat(0xfe768195))
    LIST += java.lang.Float.intBitsToFloat(0xfe768195)
    NAMED.put("Smog", java.lang.Float.intBitsToFloat(0xfe7681b1))
    LIST += java.lang.Float.intBitsToFloat(0xfe7681b1)
    NAMED.put("Tropic Mist", java.lang.Float.intBitsToFloat(0xfe7a7fdb))
    LIST += java.lang.Float.intBitsToFloat(0xfe7a7fdb)
    NAMED.put("Feather Down", java.lang.Float.intBitsToFloat(0xfe7b80e6))
    LIST += java.lang.Float.intBitsToFloat(0xfe7b80e6)
    NAMED.put("Mild Violet", java.lang.Float.intBitsToFloat(0xfe77859d))
    LIST += java.lang.Float.intBitsToFloat(0xfe77859d)
    NAMED.put("Violet Cushions", java.lang.Float.intBitsToFloat(0xfe6e8b76))
    LIST += java.lang.Float.intBitsToFloat(0xfe6e8b76)
    NAMED.put("Dull Violet", java.lang.Float.intBitsToFloat(0xfe768665))
    LIST += java.lang.Float.intBitsToFloat(0xfe768665)
    NAMED.put("Royal Violet", java.lang.Float.intBitsToFloat(0xfe75874a))
    LIST += java.lang.Float.intBitsToFloat(0xfe75874a)
    NAMED.put("Eminence", java.lang.Float.intBitsToFloat(0xfe7b862d))
    LIST += java.lang.Float.intBitsToFloat(0xfe7b862d)
    NAMED.put("Prune", java.lang.Float.intBitsToFloat(0xfe7c8439))
    LIST += java.lang.Float.intBitsToFloat(0xfe7c8439)
    NAMED.put("Dusty Grape", java.lang.Float.intBitsToFloat(0xfe788a55))
    LIST += java.lang.Float.intBitsToFloat(0xfe788a55)
    NAMED.put("Pink Violet", java.lang.Float.intBitsToFloat(0xfe788a6e))
    LIST += java.lang.Float.intBitsToFloat(0xfe788a6e)
    NAMED.put("Ripe Plum", java.lang.Float.intBitsToFloat(0xfe758f7b))
    LIST += java.lang.Float.intBitsToFloat(0xfe758f7b)
    NAMED.put("Mauve", java.lang.Float.intBitsToFloat(0xfe788a89))
    LIST += java.lang.Float.intBitsToFloat(0xfe788a89)
    NAMED.put("Ham", java.lang.Float.intBitsToFloat(0xfe7989c3))
    LIST += java.lang.Float.intBitsToFloat(0xfe7989c3)
    NAMED.put("Cotton Candy", java.lang.Float.intBitsToFloat(0xfe7d84e8))
    LIST += java.lang.Float.intBitsToFloat(0xfe7d84e8)
    NAMED.put("Silver Pink", java.lang.Float.intBitsToFloat(0xfe7c84d1))
    LIST += java.lang.Float.intBitsToFloat(0xfe7c84d1)
    NAMED.put("Tea Rose", java.lang.Float.intBitsToFloat(0xfe7d85c7))
    LIST += java.lang.Float.intBitsToFloat(0xfe7d85c7)
    NAMED.put("Old Rose", java.lang.Float.intBitsToFloat(0xfe7d88b3))
    LIST += java.lang.Float.intBitsToFloat(0xfe7d88b3)
    NAMED.put("Dusty Pink", java.lang.Float.intBitsToFloat(0xfe7b89a3))
    LIST += java.lang.Float.intBitsToFloat(0xfe7b89a3)
    NAMED.put("Roseate Spoonbill", java.lang.Float.intBitsToFloat(0xfe7d8b97))
    LIST += java.lang.Float.intBitsToFloat(0xfe7d8b97)
    NAMED.put("Thulian Pink", java.lang.Float.intBitsToFloat(0xfe7b9182))
    LIST += java.lang.Float.intBitsToFloat(0xfe7b9182)
    NAMED.put("Brown Velvet", java.lang.Float.intBitsToFloat(0xfe7e8734))
    LIST += java.lang.Float.intBitsToFloat(0xfe7e8734)
    NAMED.put("Nightshade", java.lang.Float.intBitsToFloat(0xfe7e8620))
    LIST += java.lang.Float.intBitsToFloat(0xfe7e8620)
    NAMED.put("Scribe Ink", java.lang.Float.intBitsToFloat(0xfe7c8817))
    LIST += java.lang.Float.intBitsToFloat(0xfe7c8817)
    NAMED.put("Varnish", java.lang.Float.intBitsToFloat(0xfe848725))
    LIST += java.lang.Float.intBitsToFloat(0xfe848725)
    NAMED.put("Cedar Wood", java.lang.Float.intBitsToFloat(0xfe888c34))
    LIST += java.lang.Float.intBitsToFloat(0xfe888c34)
    NAMED.put("Hot Sauce", java.lang.Float.intBitsToFloat(0xfe8b9454))
    LIST += java.lang.Float.intBitsToFloat(0xfe8b9454)
    NAMED.put("Lurid Red", java.lang.Float.intBitsToFloat(0xfe8d9770))
    LIST += java.lang.Float.intBitsToFloat(0xfe8d9770)
    NAMED.put("Brick", java.lang.Float.intBitsToFloat(0xfe889180))
    LIST += java.lang.Float.intBitsToFloat(0xfe889180)
    NAMED.put("Bright Red", java.lang.Float.intBitsToFloat(0xfe909788))
    LIST += java.lang.Float.intBitsToFloat(0xfe909788)
    NAMED.put("Embers", java.lang.Float.intBitsToFloat(0xfe8e928f))
    LIST += java.lang.Float.intBitsToFloat(0xfe8e928f)
    NAMED.put("Salmon", java.lang.Float.intBitsToFloat(0xfe889499))
    LIST += java.lang.Float.intBitsToFloat(0xfe889499)
    NAMED.put("Taxicab Yellow", java.lang.Float.intBitsToFloat(0xfe9380c5))
    LIST += java.lang.Float.intBitsToFloat(0xfe9380c5)
    NAMED.put("Apricot", java.lang.Float.intBitsToFloat(0xfe9186ba))
    LIST += java.lang.Float.intBitsToFloat(0xfe9186ba)
    NAMED.put("Burnt Yellow", java.lang.Float.intBitsToFloat(0xfe9281a6))
    LIST += java.lang.Float.intBitsToFloat(0xfe9281a6)
    NAMED.put("Dry Pepper", java.lang.Float.intBitsToFloat(0xfe908a8d))
    LIST += java.lang.Float.intBitsToFloat(0xfe908a8d)
    NAMED.put("Redwood", java.lang.Float.intBitsToFloat(0xfe8e8974))
    LIST += java.lang.Float.intBitsToFloat(0xfe8e8974)
    NAMED.put("Koa", java.lang.Float.intBitsToFloat(0xfe8d8964))
    LIST += java.lang.Float.intBitsToFloat(0xfe8d8964)
    NAMED.put("Ochre", java.lang.Float.intBitsToFloat(0xfe88853f))
    LIST += java.lang.Float.intBitsToFloat(0xfe88853f)
    NAMED.put("Dull Green", java.lang.Float.intBitsToFloat(0xfe8a7b4d))
    LIST += java.lang.Float.intBitsToFloat(0xfe8a7b4d)
    NAMED.put("Army Green", java.lang.Float.intBitsToFloat(0xfe8c7a5d))
    LIST += java.lang.Float.intBitsToFloat(0xfe8c7a5d)
    NAMED.put("Driftwood", java.lang.Float.intBitsToFloat(0xfe867f80))
    LIST += java.lang.Float.intBitsToFloat(0xfe867f80)
    NAMED.put("Dry Brush", java.lang.Float.intBitsToFloat(0xfe917c94))
    LIST += java.lang.Float.intBitsToFloat(0xfe917c94)
    NAMED.put("Mush", java.lang.Float.intBitsToFloat(0xfe9378a9))
    LIST += java.lang.Float.intBitsToFloat(0xfe9378a9)
    NAMED.put("Banana Pudding", java.lang.Float.intBitsToFloat(0xfe907bd2))
    LIST += java.lang.Float.intBitsToFloat(0xfe907bd2)
    NAMED.put("Saffron", java.lang.Float.intBitsToFloat(0xfe967cd7))
    LIST += java.lang.Float.intBitsToFloat(0xfe967cd7)
    NAMED.put("Pencil Yellow", java.lang.Float.intBitsToFloat(0xfe947ae6))
    LIST += java.lang.Float.intBitsToFloat(0xfe947ae6)
    NAMED.put("Chartreuse", java.lang.Float.intBitsToFloat(0xfe9570e7))
    LIST += java.lang.Float.intBitsToFloat(0xfe9570e7)
    NAMED.put("Absinthe", java.lang.Float.intBitsToFloat(0xfe936dd2))
    LIST += java.lang.Float.intBitsToFloat(0xfe936dd2)
    NAMED.put("Infection", java.lang.Float.intBitsToFloat(0xfe946ec2))
    LIST += java.lang.Float.intBitsToFloat(0xfe946ec2)
    NAMED.put("Frog Green", java.lang.Float.intBitsToFloat(0xfe936dac))
    LIST += java.lang.Float.intBitsToFloat(0xfe936dac)
    NAMED.put("Avocado", java.lang.Float.intBitsToFloat(0xfe917092))
    LIST += java.lang.Float.intBitsToFloat(0xfe917092)
    NAMED.put("Woodlands", java.lang.Float.intBitsToFloat(0xfe8c735e))
    LIST += java.lang.Float.intBitsToFloat(0xfe8c735e)
    NAMED.put("Dark Pine", java.lang.Float.intBitsToFloat(0xfe87792e))
    LIST += java.lang.Float.intBitsToFloat(0xfe87792e)
    NAMED.put("Moss Green", java.lang.Float.intBitsToFloat(0xfe89753b))
    LIST += java.lang.Float.intBitsToFloat(0xfe89753b)
    NAMED.put("Fern Green", java.lang.Float.intBitsToFloat(0xfe8a704a))
    LIST += java.lang.Float.intBitsToFloat(0xfe8a704a)
    NAMED.put("Forest Glen", java.lang.Float.intBitsToFloat(0xfe8f6a79))
    LIST += java.lang.Float.intBitsToFloat(0xfe8f6a79)
    NAMED.put("Malachite", java.lang.Float.intBitsToFloat(0xfe9364ae))
    LIST += java.lang.Float.intBitsToFloat(0xfe9364ae)
    NAMED.put("Apple Green", java.lang.Float.intBitsToFloat(0xfe9463ba))
    LIST += java.lang.Float.intBitsToFloat(0xfe9463ba)
    NAMED.put("Celery", java.lang.Float.intBitsToFloat(0xfe8f6bda))
    LIST += java.lang.Float.intBitsToFloat(0xfe8f6bda)
    NAMED.put("Mint Green", java.lang.Float.intBitsToFloat(0xfe9067c7))
    LIST += java.lang.Float.intBitsToFloat(0xfe9067c7)
    NAMED.put("Emerald", java.lang.Float.intBitsToFloat(0xfe92669f))
    LIST += java.lang.Float.intBitsToFloat(0xfe92669f)
    NAMED.put("Prase", java.lang.Float.intBitsToFloat(0xfe8b6a93))
    LIST += java.lang.Float.intBitsToFloat(0xfe8b6a93)
    NAMED.put("Eucalyptus", java.lang.Float.intBitsToFloat(0xfe876f74))
    LIST += java.lang.Float.intBitsToFloat(0xfe876f74)
    NAMED.put("Zucchini", java.lang.Float.intBitsToFloat(0xfe7f7930))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f7930)
    NAMED.put("Soft Teal", java.lang.Float.intBitsToFloat(0xfe807081))
    LIST += java.lang.Float.intBitsToFloat(0xfe807081)
    NAMED.put("Medium Teal", java.lang.Float.intBitsToFloat(0xfe836ca4))
    LIST += java.lang.Float.intBitsToFloat(0xfe836ca4)
    NAMED.put("Spring Green", java.lang.Float.intBitsToFloat(0xfe8c67b6))
    LIST += java.lang.Float.intBitsToFloat(0xfe8c67b6)
    NAMED.put("Turquoise", java.lang.Float.intBitsToFloat(0xfe856ac6))
    LIST += java.lang.Float.intBitsToFloat(0xfe856ac6)
    NAMED.put("Seafoam", java.lang.Float.intBitsToFloat(0xfe8769d5))
    LIST += java.lang.Float.intBitsToFloat(0xfe8769d5)
    NAMED.put("Variscite", java.lang.Float.intBitsToFloat(0xfe826ede))
    LIST += java.lang.Float.intBitsToFloat(0xfe826ede)
    NAMED.put("Refreshing Mist", java.lang.Float.intBitsToFloat(0xfe7976da))
    LIST += java.lang.Float.intBitsToFloat(0xfe7976da)
    NAMED.put("Shining Sky", java.lang.Float.intBitsToFloat(0xfe7771ce))
    LIST += java.lang.Float.intBitsToFloat(0xfe7771ce)
    NAMED.put("Steam", java.lang.Float.intBitsToFloat(0xfe7876c7))
    LIST += java.lang.Float.intBitsToFloat(0xfe7876c7)
    NAMED.put("Robin Egg Blue", java.lang.Float.intBitsToFloat(0xfe7c6dbf))
    LIST += java.lang.Float.intBitsToFloat(0xfe7c6dbf)
    NAMED.put("Denim Blue", java.lang.Float.intBitsToFloat(0xfe70758f))
    LIST += java.lang.Float.intBitsToFloat(0xfe70758f)
    NAMED.put("Deep Teal", java.lang.Float.intBitsToFloat(0xfe7c764e))
    LIST += java.lang.Float.intBitsToFloat(0xfe7c764e)
    NAMED.put("Navy Blue", java.lang.Float.intBitsToFloat(0xfe757d2c))
    LIST += java.lang.Float.intBitsToFloat(0xfe757d2c)
    NAMED.put("Blueberry", java.lang.Float.intBitsToFloat(0xfe6e7c3b))
    LIST += java.lang.Float.intBitsToFloat(0xfe6e7c3b)
    NAMED.put("Prussian Blue", java.lang.Float.intBitsToFloat(0xfe6c7a4c))
    LIST += java.lang.Float.intBitsToFloat(0xfe6c7a4c)
    NAMED.put("Desert Rain", java.lang.Float.intBitsToFloat(0xfe737a60))
    LIST += java.lang.Float.intBitsToFloat(0xfe737a60)
    NAMED.put("Electric Blue", java.lang.Float.intBitsToFloat(0xfe607b64))
    LIST += java.lang.Float.intBitsToFloat(0xfe607b64)
    NAMED.put("Hidden Blue", java.lang.Float.intBitsToFloat(0xfe6d7968))
    LIST += java.lang.Float.intBitsToFloat(0xfe6d7968)
    NAMED.put("Dull Azure", java.lang.Float.intBitsToFloat(0xfe6b7977))
    LIST += java.lang.Float.intBitsToFloat(0xfe6b7977)
    NAMED.put("Ripped Denim", java.lang.Float.intBitsToFloat(0xfe777a96))
    LIST += java.lang.Float.intBitsToFloat(0xfe777a96)
    NAMED.put("Calm Sky", java.lang.Float.intBitsToFloat(0xfe6d789e))
    LIST += java.lang.Float.intBitsToFloat(0xfe6d789e)
    NAMED.put("Vapor", java.lang.Float.intBitsToFloat(0xfe717eb2))
    LIST += java.lang.Float.intBitsToFloat(0xfe717eb2)
    NAMED.put("Powder Blue", java.lang.Float.intBitsToFloat(0xfe7376b7))
    LIST += java.lang.Float.intBitsToFloat(0xfe7376b7)
    NAMED.put("Suds", java.lang.Float.intBitsToFloat(0xfe7582c2))
    LIST += java.lang.Float.intBitsToFloat(0xfe7582c2)
    NAMED.put("Strong Cyan", java.lang.Float.intBitsToFloat(0xfe7172ad))
    LIST += java.lang.Float.intBitsToFloat(0xfe7172ad)
    NAMED.put("Sharp Azure", java.lang.Float.intBitsToFloat(0xfe667880))
    LIST += java.lang.Float.intBitsToFloat(0xfe667880)
    NAMED.put("Blue Eye", java.lang.Float.intBitsToFloat(0xfe707b7c))
    LIST += java.lang.Float.intBitsToFloat(0xfe707b7c)
    NAMED.put("Subtlety", java.lang.Float.intBitsToFloat(0xfe698482))
    LIST += java.lang.Float.intBitsToFloat(0xfe698482)
    NAMED.put("Rough Sapphire", java.lang.Float.intBitsToFloat(0xfe628071))
    LIST += java.lang.Float.intBitsToFloat(0xfe628071)
    NAMED.put("Iris", java.lang.Float.intBitsToFloat(0xfe618768))
    LIST += java.lang.Float.intBitsToFloat(0xfe618768)
    NAMED.put("Cornflower Blue", java.lang.Float.intBitsToFloat(0xfe5e815e))
    LIST += java.lang.Float.intBitsToFloat(0xfe5e815e)
    NAMED.put("Polished Sapphire", java.lang.Float.intBitsToFloat(0xfe5d7c46))
    LIST += java.lang.Float.intBitsToFloat(0xfe5d7c46)
    NAMED.put("Royal Blue", java.lang.Float.intBitsToFloat(0xfe5f7c3b))
    LIST += java.lang.Float.intBitsToFloat(0xfe5f7c3b)
    NAMED.put("Indigo", java.lang.Float.intBitsToFloat(0xfe658132))
    LIST += java.lang.Float.intBitsToFloat(0xfe658132)
    NAMED.put("Space Blue", java.lang.Float.intBitsToFloat(0xfe747d23))
    LIST += java.lang.Float.intBitsToFloat(0xfe747d23)
    NAMED.put("Thick Amethyst", java.lang.Float.intBitsToFloat(0xfe658a44))
    LIST += java.lang.Float.intBitsToFloat(0xfe658a44)
    NAMED.put("Juicy Grape", java.lang.Float.intBitsToFloat(0xfe618c51))
    LIST += java.lang.Float.intBitsToFloat(0xfe618c51)
    NAMED.put("Blacklight Glow", java.lang.Float.intBitsToFloat(0xfe679066))
    LIST += java.lang.Float.intBitsToFloat(0xfe679066)
    NAMED.put("Purple Freesia", java.lang.Float.intBitsToFloat(0xfe64907b))
    LIST += java.lang.Float.intBitsToFloat(0xfe64907b)
    NAMED.put("Thin Amethyst", java.lang.Float.intBitsToFloat(0xfe5e9065))
    LIST += java.lang.Float.intBitsToFloat(0xfe5e9065)
    NAMED.put("Orchid", java.lang.Float.intBitsToFloat(0xfe699193))
    LIST += java.lang.Float.intBitsToFloat(0xfe699193)
    NAMED.put("Lavender", java.lang.Float.intBitsToFloat(0xfe6f88a9))
    LIST += java.lang.Float.intBitsToFloat(0xfe6f88a9)
    NAMED.put("Lilac", java.lang.Float.intBitsToFloat(0xfe7389bd))
    LIST += java.lang.Float.intBitsToFloat(0xfe7389bd)
    NAMED.put("Soap", java.lang.Float.intBitsToFloat(0xfe7784ce))
    LIST += java.lang.Float.intBitsToFloat(0xfe7784ce)
    NAMED.put("Pink Tutu", java.lang.Float.intBitsToFloat(0xfe7987d9))
    LIST += java.lang.Float.intBitsToFloat(0xfe7987d9)
    NAMED.put("Thistle", java.lang.Float.intBitsToFloat(0xfe6e93a8))
    LIST += java.lang.Float.intBitsToFloat(0xfe6e93a8)
    NAMED.put("Heliotrope", java.lang.Float.intBitsToFloat(0xfe6d9ca4))
    LIST += java.lang.Float.intBitsToFloat(0xfe6d9ca4)
    NAMED.put("Purple", java.lang.Float.intBitsToFloat(0xfe6b9d84))
    LIST += java.lang.Float.intBitsToFloat(0xfe6b9d84)
    NAMED.put("Wisteria", java.lang.Float.intBitsToFloat(0xfe649880))
    LIST += java.lang.Float.intBitsToFloat(0xfe649880)
    NAMED.put("Medium Plum", java.lang.Float.intBitsToFloat(0xfe6c9b71))
    LIST += java.lang.Float.intBitsToFloat(0xfe6c9b71)
    NAMED.put("Violet", java.lang.Float.intBitsToFloat(0xfe68945d))
    LIST += java.lang.Float.intBitsToFloat(0xfe68945d)
    NAMED.put("Grape Lollipop", java.lang.Float.intBitsToFloat(0xfe6f8e3e))
    LIST += java.lang.Float.intBitsToFloat(0xfe6f8e3e)
    NAMED.put("Mulberry", java.lang.Float.intBitsToFloat(0xfe74903d))
    LIST += java.lang.Float.intBitsToFloat(0xfe74903d)
    NAMED.put("Grape Soda", java.lang.Float.intBitsToFloat(0xfe6f8c2c))
    LIST += java.lang.Float.intBitsToFloat(0xfe6f8c2c)
    NAMED.put("Eggplant", java.lang.Float.intBitsToFloat(0xfe738922))
    LIST += java.lang.Float.intBitsToFloat(0xfe738922)
    NAMED.put("Cherry Syrup", java.lang.Float.intBitsToFloat(0xfe7d8d32))
    LIST += java.lang.Float.intBitsToFloat(0xfe7d8d32)
    NAMED.put("Plum Juice", java.lang.Float.intBitsToFloat(0xfe75975c))
    LIST += java.lang.Float.intBitsToFloat(0xfe75975c)
    NAMED.put("Fruit Punch", java.lang.Float.intBitsToFloat(0xfe7b9c6a))
    LIST += java.lang.Float.intBitsToFloat(0xfe7b9c6a)
    NAMED.put("Bubble Gum", java.lang.Float.intBitsToFloat(0xfe779b9b))
    LIST += java.lang.Float.intBitsToFloat(0xfe779b9b)
    NAMED.put("Pink Lemonade", java.lang.Float.intBitsToFloat(0xfe7897a6))
    LIST += java.lang.Float.intBitsToFloat(0xfe7897a6)
    NAMED.put("Shrimp", java.lang.Float.intBitsToFloat(0xfe7f8cbd))
    LIST += java.lang.Float.intBitsToFloat(0xfe7f8cbd)
    NAMED.put("Flamingo", java.lang.Float.intBitsToFloat(0xfe7e9c8d))
    LIST += java.lang.Float.intBitsToFloat(0xfe7e9c8d)
    NAMED.put("Rose", java.lang.Float.intBitsToFloat(0xfe7e9d7b))
    LIST += java.lang.Float.intBitsToFloat(0xfe7e9d7b)
    NAMED.put("Carmine", java.lang.Float.intBitsToFloat(0xfe869860))
    LIST += java.lang.Float.intBitsToFloat(0xfe869860)
    NAMED.put("Bologna", java.lang.Float.intBitsToFloat(0xfe81905a))
    LIST += java.lang.Float.intBitsToFloat(0xfe81905a)
    NAMED.put("Raspberry", java.lang.Float.intBitsToFloat(0xfe83944c))
    LIST += java.lang.Float.intBitsToFloat(0xfe83944c)
  }

  /** Converts existing Color entries in [[sge.graphics.Colors]] from RGBA to Oklab format. */
  def editKnownColors(): Unit =
    for (c <- sge.graphics.Colors.colors.values) {
      val f = ColorTools.fromColor(c)
      c.set(ColorTools.channelL(f), ColorTools.channelA(f), ColorTools.channelB(f), c.a)
    }

  /** Appends Oklab-compatible Color instances to the map in [[sge.graphics.Colors]]. */
  def appendToKnownColors(): Unit =
    for ((key, value) <- NAMED) {
      val f = value
      sge.graphics.Colors.put(key, new sge.graphics.Color(ColorTools.channelL(f), ColorTools.channelA(f), ColorTools.channelB(f), ColorTools.alpha(f)))
    }
}
